### ISSUE TITLE
FAQ and How It Works pages now blank on partner sites

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#10]
@cgladue since the update if the dynamic page builders for these pages the FAQ pages and How It Works pages are blank on Xlcub and Foxwoods pages...

**Comment by robgpeak** [comment]
Where you get the above issue solved, please refresh me on how I can add the {Rewards Program Name} or other variable from the db so it would display differently for each partner.

**Comment by cgladue** [comment]
thats correct, because there is no content there for those sites yet, you
need to add it... should the same shop.complinks.co data be copied



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
well, since you have to add the content for every partner, you would just
use the name in text, no need for {}



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Ah, I did not see the Current Partner dropdown menu.  Yes, they should all
have the intial default page be the same content that is on the
shop.complinks.co page, and then we can tweak individually from there.

Honestly I thought initially it was going to be the same page with just
different "variables" in there like {Rewards Program Name}.  I think that
might be easier for administration purposes, but for individuality your way
is definitely better. So let's just do it the way you got it now.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
xclub and foxwoods are now duplicated



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Cool. And upon the creation of a new subdomain, it should mirror whatever is in the shop on at that particular time.
