### ISSUE TITLE
Have users "view" page open in a new tab

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#100]
@cgladue please have the linked account number for the user on the pages ../dashboard/users and ../dashboard/partner/users open in a new tab.

**Comment by cgladue** [comment]
@robgpeak Done

**Comment by robgpeak** [comment]
Nice.  Please do the same thing in ../dashboard/csr/users  I see you did it in partner/users already

**Comment by cgladue** [comment]
done



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Excellent!
