### ISSUE TITLE
Engagement Modal

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#102]
@cgladue How about we try something on test.complinks.co whereby when someone clicks a shop now button, we display a modal with the content that resembles a smaller version of this page... http://www.complinks.co/CLgames/slot.html

We would of course need to maintain a record in the back end for each use who opts out of seeing these modals, and also let them opt back in from their manage account page.

If you could, please set up a test on the main shop now button on the page http://test.complinks.co/stores/index/11 so we can test to make sure that it also retains the referring URL when the person spins the wheel and begins the actual shopping trip.

As we discussed in the past, the bonus someone would receive in points for that particular trip would be random, but predetermined.  it would range from 0% to 50% and we could weight the prizes as I've indicated in the https://app.moqups.com/robg/QSDVx2F07W/edit/page/a191413e0

I know this would take a bit of planning and programming, but maybe we can start in Phases.

Phase 1.  Let's see if we can get the modal to show up when someone clicks on the shop now link, and we can retain the referring URL when the trip starts from the click on the new shop now button that would appear in the modal.

Phase 2. Build the functionality of allow users to opt out of seeing the modal.  Along with opting back in.

Phase 3. Start with a more simple Engagement Modal model with campaigns.  I can create a campaign that says, "Earn an extra 10 points if you make a purchase at {store name} THIS shopping trip".  We would have to tag that specific trip ID to an email and/or push notification trigger which would send the user a message AFTER that trip results in the earning of points.

Phase 4. We work on the spinning roulette wheel and other types of gamifying modals.

Can I use the word modal any more...?  modal, modal, modal.  Name that movie reference...

**Comment by cgladue** [comment]
Is it within the Terms and conditions for CJ, IR, and LS to show an advertisement prior to sending the user to the advertiser ?

**Comment by robgpeak** [comment]
Even if it was I'm not sure that would constitute being an Advertiser. We are only giving them an opportunity to earn more points. But either way I will look into the t's and C's and let you know. See now I dictated this whole thing into my phone and it came out very legible. So what was the movie reference I was referring to ? :-) see I even did the question mark in the :-) verbally.

**Comment by robgpeak** [comment]
Now that I'm thinking about it there is really no difference. Meaning it's just a different shop now button on our site. So for example if someone does a search for GoDaddy and they click on the logo itself and it brings them to the store Page and then they click on the shop now button from there that launches a new shopping trip and takes them to GoDaddy that's one thing but if they click the shop now button see the modal and click on that secondary shop now button it's the same thing. My main concern is to ensure that we can still show the referring URL as that main page instead of the modal page

**Comment by cgladue** [comment]
@robgpeak you around ?

**Comment by robgpeak** [comment]
On a plane heading to Vegas. What's up?
