### ISSUE TITLE
Look for interstitial

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#106]
@ChrisASearles Here is a mock up of the interstitial page we spoke about on the phone.

Is it possible to build the page in such a way that we could easily update in from the back end sort of the way the promotions page is built?  I know of course we would have to have some rigid guidelines as to what is editable, but I am just thinking of down the road when we want to be able to include stuff like... https://app.moqups.com/robg/QSDVx2F07W/edit/page/aad6bd9e3 it would make it much easier.

The complinks logo in the background is also attached to this thread, and the opacity is set to 7%

![uploads/8f1c0b85-072f-4e3f-98b5-76d9675824be/Screen Shot 2018-04-18 at 1.40.21 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8f1c0b85-072f-4e3f-98b5-76d9675824be%2FScreen+Shot+2018-04-18+at+1.40.21+PM.png)

![uploads/c705d584-6e9e-43af-814a-5ef6c70fe415/cropped-CL_ICO_512 white BG.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc705d584-6e9e-43af-814a-5ef6c70fe415%2Fcropped-CL_ICO_512+white+BG.png)

**Comment by robgpeak** [comment]
@ChrisASearles Now that this is live on all subdomains, I would like to make it look pretty.

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
this should be live now.



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
i have restored the last backup and the trips start page is working again,
but not chris's new style...





Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/39163184-53457614-4747-11e8-9414-09af58bc8ffd.png)

**Comment by ChrisASearles** [comment]
@cgladue emailed you back this morning on this, I think it was a timing issue on your script build b/c I had to merge in those resource builds when I made changes this morning. Version that's checked in should be working so let me know if you're still having issues.

**Comment by cgladue** [comment]
ok let me grab it



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@ChrisASearles I really don't want to be a dick, but this is what the page looks like now...

<img width="872" alt="screen shot 2018-04-24 at 6 00 37 pm" src="https://user-images.githubusercontent.com/28393235/39216416-8e5d2466-47e9-11e8-8334-315c6b13d82b.png">

and I would really like it to look like the mock up I did at the top of this thread, with the blue border around the wording, and the sort of spacing between the lines of text that I originally indicated.  Right now it just takes up too much real estate.  We need to tighten it up and make it look more appealing.

Then again, so we are on the same page, the blue line would be replaced by the primary main color based on the subdomain's color scheme of where the trip originated from.  For now we WILL keep the same CompLinks logo as the background, but we might change that in the future based on the partner/subdomain.

**Comment by robgpeak** [comment]
Good news is it's working in chrome for me now.

**Comment by cgladue** [comment]
@robgpeak so i think the issue is just a cache issue then ?

**Comment by robgpeak** [comment]
Chad, When you see the shopping trip interstitial, do you see it with the blue border around the text like my original mock-up at the top of this thread?  Could you take a screen shot of the interstitial you see?

**Comment by cgladue** [comment]
No, this is what it looks like to me...

![image](https://user-images.githubusercontent.com/7914133/39373173-b9027612-4a14-11e8-81fe-9469e68fbd74.png)

**Comment by ChrisASearles** [comment]
Committed a new version of this to more-closely match your design.

**Comment by cgladue** [comment]
@ChrisASearles @robgpeak i pushed this but i stilll am not seeign the blue border that rob wanted ... should it be there ?

**Comment by robgpeak** [comment]
I see it.  Thanks!
