### ISSUE TITLE
WTF is up with CJ and their API moving advertisers to NotJoined!

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#107]
@cgladue It looks like at about 2:25 this morning a SHITLAOD of major advertisers on CJ were changed from joined to notjoined, then at 10:30 am most of them changed back to joined, but still a lot of them didn't  Walgeeens, vistprint, etc.  Please look into this as this is a problem.

**Comment by cgladue** [comment]
@robgpeak i checked the API and ALL advertisers are returning 0 links ...

**Comment by cgladue** [comment]
@robgpeak links are coming through again

**Comment by cgladue** [comment]
API seems to be back to normal.
