### ISSUE TITLE
Advertisers that are marked as NotJoined are still showing up in Featured

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#108]
@cgladue So as #107 indicated there are some issues with some advertisers in CJ that are being marked as Notjoined, when in reality they there has been no relationship change in the cj back end, so I am not sure why they are being marked as notjoined all of a sudden, so please check the API from them.

In the meantime, if an advertiser is in the featured category and then becomes notjoined, they are still showing up on the home page.  Have a look at walgreens and vistaprint

**Comment by cgladue** [comment]
@robgpeak the call to getfeaturedadvertisers did not specify only active = true advertisers, this has been corrected.
