### ISSUE TITLE
moving user accounts to a different sub domain

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#109]
As you can see from #101 there are a couple of other people who have seemingly signed up as xclub members, but have come through shop.complinks.co @morganpeak please go through this list  https://shop.complinks.co/dashboard/users and send emails to the members that are showing the partner "CompLinks" which should obviously be xclub and tell them the same thing you told the last woman.  The only thing is, we will have to wait for Chad to allow those account access to xclub...

@cgladue Maybe we can build a mechanism that would allow Morgan to change the sub domain of an account holder?

**Comment by morganpeak** [comment]
@cgladue let me know when I can start emailing these customers

**Comment by cgladue** [comment]
i assume its  just these two ?


100143 | Regina | Frost | Reginafrost3@gmail.com | CompLinks | 100 | 0 | 100 | 0 | 04/17/2018 | Active
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
100139 | Patti | Gasperi | patti232@aol.com | CompLinks | 0 | 0 | 0 | 0 | 04/17/2018 | Active

**Comment by robgpeak** [comment]
Yes, at the moment it is just those two.  After you do make the change please inform Morgan and give her the email addresses of the accounts that you changed to xclub so she can see them.

**Comment by cgladue** [comment]
@robgpeak @morganpeak 

Now on the user view page, the partner field is a dropdown, you can move the user between partners using this dropdown

![image](https://user-images.githubusercontent.com/7914133/39025353-732119ce-4414-11e8-881d-f1400059e6d9.png)

**Comment by robgpeak** [comment]
Very nice. Please do me a favor and eliminate this functionality from partner and csr login ins.  They should NOT be able to change someone's Partner Name.  It should be greyed out.

**Comment by cgladue** [comment]
should be that way now

**Comment by robgpeak** [comment]
That works.  They are greyed out for both partners and csr, but now they are not popping open in a new tab:)

**Comment by robgpeak** [comment]
nevermind.  It's only if you try to open another one from the newly spawned tab.  It's fine

**Comment by cgladue** [comment]
i think the way that its setup, the page opens in a new tab called
"_blank"  if you then click on a link in that new tab that should open a
tab in _blank it knows that the current tab is _blank and just uses the
current tab, my guess is you have two tabs open the original window and the
tab that origionally opened a new tab in.



Chad Gladue
*DevNull Technology, LLC*
