### ISSUE TITLE
Interstitial for unauthenticated users

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#110]
@cgladue @ChrisASearles 

In reference to #106 if someone is unauthenticated we would like to present them with a page that looks like this...(below) so the idea is to include the login/register button to make it obvious and friendly that they are on their way to earning points but they have to login or sign up in order to do so.

We need to remember that these customers are not going to be as computer savvy and we need to make it as obvious as possible what is going on when they click shop now and reinforcing why. I know this seems obvious to us but we need to develop for computer newbies.

![screen shot 2018-04-19 at 7 36 42 pm](https://user-images.githubusercontent.com/28446563/39023669-12eb3cba-440a-11e8-81b8-157d8b9a6ece.png)

**Comment by ChrisASearles** [comment]
Hey @cgladue can you set up the redirect for this with whatever data I'm going to need coming down in a model object and then I'll get into the design?

**Comment by cgladue** [comment]
@ChrisASearles @robgpeak 

problem is this page would be used for even non-shopping related unauthenticated users (like dashboard users who arent logged in) so there may be times where there is no advertiser or url to display ... and the way ASP works is it handles all the unauthenticated redirecting and stuff on its own, not sure how i will know ... let me do some research

**Comment by cgladue** [comment]
```
public class CustomAuthorize: AuthorizeAttribute
{
    protected override void HandleUnauthorizedRequest(AuthorizationContext filterContext)
    {
       filterContext.Result = new HttpUnauthorizedResult(); // Try this but i'm not sure
    }
}
```

**Comment by robgpeak** [comment]
The only thing that showed up when I clicked in a shop now button as I was unauthenticated was the login screen.  So you know I just tried it from my phone.

Also, it looks like the issue #22 reverted back to the original wording.  The copy in the call out box on the home page hero image for an unauthenticated visitor... please change the last line to read, "When You Purchase Everyday Items From Online Retailers"
