### ISSUE TITLE
Limit the csr points awarding ability to 200 points maximum per user account.

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#113]

**Comment by cgladue** [comment]
200 maximum per transaction or total lifetime for the user ?

**Comment by robgpeak** [comment]
For the lifetime of the account

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
is that 200 points per CSR or 200 points across all CSRs ?

**Comment by robgpeak** [comment]
Per csr
