### ISSUE TITLE
Integrate into Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#114]
@cgladue  please look into what it would take to integrate into Intercom.  First name, last name, shopping trips, last trip, pending point balance, available, email, etc.

@morganpeak  and I have been using it for most of the day, and I can honestly say it is by far and away the best, most well thought out piece of software I have ever used, EVER!  The UI/UX is incredible.  I just downloaded the app on my phone, and it too is flawlessly designed and it works GREAT!  Very intuitive. 

They do have push notifications, but only for native apps.  Having said that, I used one signal today to send out a push notification to 37 people, and not one person clicked.  That won't happen with intercom, people WILL engage with this.  If there are on the site, and they see that little red "1" next to text bubble at the bottom of the screen, they will click it. Web push notifications disappear too quick never to be seen again.

I think this will become the ultimate user engagement tool.  It will take the place of groove and onesignal (see image below:) and I am pretty sure this will be the last integration we need to do... until next time...lol  Seriously though, this product is amazing, and the only thing better would be if we built it on our own.

So before rolling it out on xclub, I want to see what the integration points and tags do in shop this way I can set it up properly so when we do turn it on for xclub it is working flawlessly.  My goal is to have it live on xclub by next Thursday the latest.

![uploads/6b308b5d-21bc-48bc-836c-b8d7bcd752ac/Screen Shot 2018-04-20 at 12.38.20 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6b308b5d-21bc-48bc-836c-b8d7bcd752ac%2FScreen+Shot+2018-04-20+at+12.38.20+AM.png)

**Comment by robgpeak** [comment]
@cgladue Did you already add something to intercom, because it is showing me details of users who visit shop.complinks.co even if they do not start a conversation.  I see your email address and account number, as well as mine, Morgan's and Addison's.  Then I just tried with my wife's account and the same thing happened.  I was able to see her email and complinks account number.

**Comment by robgpeak** [comment]
![uploads/82544d72-44af-42e4-a310-cbe979a14639/Screen Shot 2018-04-20 at 10.33.37 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F82544d72-44af-42e4-a310-cbe979a14639%2FScreen+Shot+2018-04-20+at+10.33.37+AM.png)

**Comment by cgladue** [comment]
I did add email, name, and acct# yes

**Comment by robgpeak** [comment]
ah, ok, it scared me for a minute:)  Still testing the messaging to make sure we can handle all of it for all subdomains through one interface before turning it live on xclub.

One thing I did notice is it had a feature to manually unsubscribe someone from the email list, and I am not sure how we would do that if we were to use this for email instead of mailchimp...

**Comment by robgpeak** [comment]
@cgladue Please have a look to see if it's possible to customize the support Link in our head and shoulders menu to Launch intercom messenger the same way their little widget modal does...  

Not sure if this article helps https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customize-the-intercom-messenger-technical

**Comment by cgladue** [comment]
so you would like the "Support" option to do the same thing as if they clicked the icon in the bottom right ?

**Comment by robgpeak** [comment]
Yes Please

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@ChrisASearles i dont know how to do this in angular, but the support link in the head&shoulders menu should do something similar to the following:

document.querySelectorAll(".intercom-avatar")[0].click();

it should replicate as if a user clicked the icon for Intercom.

**Comment by cgladue** [comment]
@robgpeak @morganpeak 

the following user details hould be available in intercom from this point onward now:

```
window.intercomSettings = {
                    app_id: APP_ID,
                    name: current_user_name,
                    email: current_user_email,
                    user_id: current_user_id
                    lastTrip: '@(ViewBag.user?.lastTrip)',
                    totalTrips: '@(ViewBag.user?.totalTrips)',
                    PointBalance: @ViewBag.user?.PointBalance,
                    PendingPoints: @ViewBag.user?.PendingPoints
                };
```

**Comment by robgpeak** [comment]
cool, but I am not sure how to make it visible in Intercom.  I am assuming it would be from the page https://app.intercom.io/a/apps/d8m2yyar/settings/people-data but I am not sure.  The email address and account number show up automatically because they seem like pre-defined fields from with Intercom, but I am not sure on these other fields.  @cgladue please see if you can figure it out.

**Comment by robgpeak** [comment]
@ChrisASearles The comment that Chad made three days ago, "... i dont know how to do this in angular, but the support link in the head&shoulders menu should do something similar to the following:..." This needs to be a **high priority**, as I am planning on launching the Intercom solution and removing the Groove integration as soon as you get it done. #

**Comment by ChrisASearles** [comment]
@cgladue I started working on this but I feel like I'm missing something. I fixed a couple bugs in this section:
```javascript
window.intercomSettings = {
                    app_id: APP_ID,
                    name: current_user_name,
                    email: current_user_email,
                    user_id: current_user_id,
                    lastTrip: '@(ViewBag.user?.lastTrip)',
                    totalTrips: '@(ViewBag.user?.totalTrips)',
                    PointBalance: @(ViewBag.user?.PointBalance),
                    PendingPoints: @(ViewBag.user?.PendingPoints)
                };
```
to clean up some JS errors I was getting but nothing from Intercom is loading anywhere so I can't really test anything. It sounds like you guys had some discussions surrounding this but it's the first I'm hearing or seeing anything about it so it's a little bit of a black box for me. Just let me know what I'm not seeing or if there's something commented out somewhere or whatever and I can try to finalize what I was doing based on the info you sent previously.

**Comment by robgpeak** [comment]
@cgladue In Intercom section above

`window.intercomSettings = {
                    app_id: APP_ID,
                    name: current_user_name,
                    email: current_user_email,
                    user_id: current_user_id,
                    lastTrip: '@(ViewBag.user?.lastTrip)',
                    totalTrips: '@(ViewBag.user?.totalTrips)',
                    PointBalance: @(ViewBag.user?.PointBalance),
                    PendingPoints: @(ViewBag.user?.PendingPoints)
                };`

could you please add "PartnerName" so I can use it as a separator in Intercom

**Comment by robgpeak** [comment]
Also @cgladue Chris' comment the other day " i dont know how to do this in angular, but the support link in the head&shoulders menu should do something similar to the following:

`document.querySelectorAll(".intercom-avatar")[0].click();`

it should replicate as if a user clicked the icon for Intercom.

Will this work?  I would like to test it on Shop before rolling Intercom out on xclub.

**Comment by cgladue** [comment]
@robgpeak @ChrisASearles

**Comment by robgpeak** [comment]
@cgladue you closed this issue, but I am not sure it's done.  Chris would still need to make it work...  

And I also asked "could you please add "PartnerName" so I can use it as a separator in Intercom window settings..."  Is that possible?

**Comment by cgladue** [comment]
yea totally didnt mean to close it ...  PartnerName is already added.

**Comment by cgladue** [comment]
@ChrisASearles why dosnt any of this load on your local machine ?  it loads fine on mine

**Comment by ChrisASearles** [comment]
I have no idea, that's what I was asking in my comment earlier this week. I see the Intercom widget on the production site but locally I get a 403 error on a post to: https://api-iam.intercom.io/messenger/web/ping

**Comment by cgladue** [comment]
@ChrisASearles hmm, i guess its loading in an iframe, and therefore i the widget isnt in the DOM untill the user clicks on it the first time so this may not work as i tested it every time .. it might not be possible to make this work reliably...

**Comment by robgpeak** [comment]
I did not read his answer but I hope this helps...

My question to Intercom... "Is it possible to have the message window be activated on a users screen if they click a different link other than the Intercom widget at the bottom right of the screen?

Absolutely! You can have the messenger open from any link by setting up a custom launcher. It'd work like this:
https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customize-the-intercom-messenger-technical

You can also use the Javascript API to have it open with pre-populated content or to a new message specifically instead just the message list. There's more on that in our Javascript API docs here.

https://developers.intercom.com/docs/intercom-javascript-articles

**Comment by cgladue** [comment]
ok i think i may be able to modify chris's code to do this let me give it a
try



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
actually, this says that if you use a custom launcher then the default one will not show if i read it right ... so then chris would need to duplicate the functionality of the bottom right icon ...

**Comment by robgpeak** [comment]
- If you use a custom launcher and also want to use the 'badge' delivery
   option, we recommend that you use the onUnreadCountChangemethod in
our JavaScript
   API
   <https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/the-intercom-javascript-api>
    to show a badge on your custom launcher. If you use a custom launcher
   without a badge, you shouldn't use the badge delivery option.

**Comment by robgpeak** [comment]
In theory I was looking to replicate what we had with Groove with the widget and the "Support" link in the user's menu when they are logged in.  So you're right, the badge let's the user know there is a message waiting for them, but the support link is just another means to open that same Intercom messenger modal.

**Comment by robgpeak** [comment]
@ChrisASearles please look at my comments and the links I posted last week in this thread for what is hopefully the way to accomplish what we are looking for.  Parx is doing a full launch today, and we really need this in place ASAP in order to effectively handle customer inquiries.

**Comment by robgpeak** [comment]
@cgladue Today being May 1, I need Intercom live on xlcub today.  I just called Chris and he said it would take some work and time to dig through the code to get the head and shoulders support link and the support link that shows up on the left hand nav when someone is in their user dashboard to link to the Intercom modal, so for now I just assume remove (comment out), the "Support" listing from both the head and shoulders and the left hand nav and remove the Groove widget and just activate the Intercom widget like it is currently showing up on shop.

Having said that, I would still like to speak with you about #127 as it is related to this issue as well.  It should only take a 4 minute phone call to make sure we are on the same page with the desired results.

**Comment by cgladue** [comment]
this would mean that groove is going away then right ?

**Comment by cgladue** [comment]
@robgpeak intercom is now on all subdomains.

**Comment by robgpeak** [comment]
Yes, groove is going away for end users, and we are going to use Intercom.
We will still use groove for info@complinks.co

Is there a way you can comment out the links to "Support" in both the head
and shoulders menu, and in the users menu when they are in their dashboard
area?

**Comment by cgladue** [comment]
Yes

**Comment by cgladue** [comment]
@robgpeak all set

**Comment by robgpeak** [comment]
It's gone from The Head and Shoulders menu but it's still in the other menu. It needs to be comment it out from there as well.
![screenshot_2018-05-02-09-13-45](https://user-images.githubusercontent.com/28393235/39525209-596447b6-4de9-11e8-92cc-f03b95d012d2.png)

**Comment by robgpeak** [comment]
Still there an incognito for me.

![20180502_115520](https://user-images.githubusercontent.com/28393235/39534594-e993b248-4dff-11e8-8336-22c9a9c87af4.jpg)

**Comment by robgpeak** [comment]
Not sure why it did not work the first time, but it's gone now.
