### ISSUE TITLE
Error saving user info

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#118]
@cgladue When I go to edit user #100195 and change her from CompLinks to Xclub I get an error message when I click Save. It takes me to this link: https://shop.complinks.co/InternalError?aspxerrorpath=/dashboard/users/saveUser

I have not been having this issue when saving other users after this change.

**Comment by morganpeak** [comment]
Okay gotcha. Is there a way to get rid of the other account? Should we do that if possible?

**Comment by cgladue** [comment]
Yea, i can use the nuclear option if thats what you want, i dont really
want to build that into the frontend, but if it shouldnt be there then i
can do that



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@cgladue you are correct, that should only be a situation that you handle manually on the back end.  So in this instance, do get rid of the other account to avoid confusion.

**Comment by robgpeak** [comment]
@cgladue The strange thing is that she opened account 100123 on the 17th through xclub (seemingly.  Meaning I don't think it was one that Morgan manually changed from CompLinks to xclub), but then registered again on the 21st through CompLinks.  So we need to get rid of one, but which one...?

<img width="1163" alt="screen shot 2018-04-24 at 10 25 25 am" src="https://user-images.githubusercontent.com/28393235/39193584-e81c7960-47a9-11e8-901d-dae05328c677.png">

**Comment by cgladue** [comment]
i would say keep the xclub, and the points would transfer over to the other
account.  is that ok ?




Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
Yep, its done now.
