### ISSUE TITLE
Column visibility on all users on mobile

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#119]
@cgladue I was in all users on my phone, and I wanted to see the column "Partner", but even if I have it as the only column visible from the dropdown menu, nothing shows up...  Please see if you can replicate it and fix it.

![screenshot_2018-04-23-09-11-00](https://user-images.githubusercontent.com/28393235/39128855-e7dfb382-46d6-11e8-8dd3-0ae6a16fa59d.png)

**Comment by cgladue** [comment]
Yea i set it as available on desktop or larger only, i will change that so
its visible on mobile too.



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
Partner is available on mobile and up now.

**Comment by robgpeak** [comment]
cool
