### ISSUE TITLE
Include CSV link on partnerdashboard pages

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#12]
@cgladue Like you have the CSV link on the ./partnerdashboard/redemptions, it needs to be on the /users and /users/purchases pages.

**Comment by cgladue** [comment]
Should be set now, changed it to Excel instead of CSV, its easier

**Comment by robgpeak** [comment]
@cgladue this might be two separate issues, but:

1. The excel data that I download from the page https://xclub.complinks.co/partnerdashboard/redemptions was empty.  It showed my account number in one column, but nothing else.

2. The page https://xclub.complinks.co/partnerdashboard/users is not showing any data at all, so I can't tell if the excel button would even show up.  There should be data in that section.

**Comment by cgladue** [comment]
Fixed both

**Comment by robgpeak** [comment]
I see the Excel link in there now, but the "Name" and "Email Address" columns are still empty...

<img width="943" alt="screen shot 2018-02-21 at 11 55 55 am" src="https://user-images.githubusercontent.com/28393235/36493772-63afda90-16fe-11e8-9456-23f8fe096246.png">

**Comment by cgladue** [comment]
try Shift F5 to force a reload, because it shows all the data correctly when i export it...

![image](https://user-images.githubusercontent.com/7914133/36494078-1ba6e562-16ff-11e8-9460-593e7805aacf.png)

**Comment by robgpeak** [comment]
Actually, when I open it in Numbers, it comes up blank like I showed, but when I do it in Excel, it shows fine.  strange.  How had would it be to have CSV as a download option in there?

**Comment by cgladue** [comment]
Not hard, all set i added CSV as an option.

**Comment by robgpeak** [comment]
Sweet!

**Comment by robgpeak** [comment]
Shit, One thing I just realized, the "Name" column should be broken into two columns "First Name" "Last Name", just like it is in the admin dashboard of users...

**Comment by cgladue** [comment]
really, you like it in seperate columns ?   seems so inconvienient in reality to have it that way

**Comment by robgpeak** [comment]
I did not create the "database management 101" rules, but I've lived by them for the last 25+ years.  First and last name are ALWAYS separate fields.  Imagine they have 10,000 customers in their db and they want to do a query for everyone named "Jane".

**Comment by cgladue** [comment]
i live by them every day, and thats what ETL is for they can split it based on the comma if they wanted to but hey thats what you want your the boss, ill split it out on the table

**Comment by robgpeak** [comment]
Thank you sir:)  If nothing else, it is consistent with the way the data is displayed in our User screen in the admin dashboard

**Comment by cgladue** [comment]
yea, admin area will be changing to look like the partner area too, so ill
keep that in mind when that happens.



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
All Set

**Comment by robgpeak** [comment]
👍
