### ISSUE TITLE
Typo when updating password

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#120]
@cgladue In making some how-to videos for people I noticed there are two typos in the prompt that comes up when you type your password in incorrectly. The words "you entered" are written twice and it also says "Enter _You_ Password" when it should say "Enter _Your_ Password" Small thing but I figured it should be changed. See below.

![screen shot 2018-04-24 at 3 49 25 pm](https://user-images.githubusercontent.com/28446563/39210638-4db24552-47d7-11e8-8eb8-946a83290709.png)

**Comment by cgladue** [comment]
this has been corrected, thank you for finding it ;)

**Comment by robgpeak** [comment]
Morgan, after you are satisfied that the error has been corrected, please come into git hub and mark the issue as closed.
