### ISSUE TITLE
Making support.complinks.co secure (SSL)

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#122]
@cgladue Could you please read section 3 on this page https://developers.intercom.com/docs/set-up-your-custom-domain about making this page support.complinks.co secure.  I set up the CNAME on Cloudflare, but I don't want to screw anything up with the SSL on the lie sites, so I wanted you and the professional tiny mice to handle it.

**Comment by cgladue** [comment]
i talked to the mice and they appreciate the confidence you have in them.  They set the Page to be HTTPS required in cloudflare and i think it looks good now.

**Comment by robgpeak** [comment]
I thank both you and your furry little cheese eaters.
