### ISSUE TITLE
Moving a user to different subdomain

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#123]
@morganpeak Let's leave this thread open, and I've assigned both you and I so hopefully Chris and Chad don't get continually notified  on this issue (if you guys do, please mute it).

Since you are not looking at the back end dashboad as often as I am, I will post here when there is someone in the back end that came into the wrong Partner and needs to be changed and notified.

Please change https://shop.complinks.co/dashboard/users/view/100240 to xclub, notify them, and make a comment in their comments field that you've changed them. Then you can just reply to the email that you will receive from github on this issue that it's been done, and it will update this thread.

**Comment by morganpeak** [comment]
@robgpeak  User 100240 done

**Comment by robgpeak** [comment]
@morganpeak Please move these three players to xclub, but here is a way to double check that they are from the Parx Casino Pennsylvania area... https://screencast.com/t/SjWOLIfA

<img width="764" alt="screen shot 2018-05-07 at 10 58 38 am" src="https://user-images.githubusercontent.com/28393235/39708620-a67f6e22-51e5-11e8-87e2-fc6dad9b2af1.png">

**Comment by morganpeak** [comment]
@robgpeak These three users have been taken care of. Question though, in Intercom it still says their company that they are associated with is CompLinks, does that eventually pull over to be Xclub when it next updates?

**Comment by cgladue** [comment]
hmm, that IS a good question... the next time they login i will be sending the current partner as the company so as long as intercom will overwrite the existing company with that then should be fine.
