### ISSUE TITLE
Some Partner Name tags not coming across to Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#124]
@cgladue Please have a look and see if you can help troubleshoot it https://screencast.com/t/tAvoZZ5hbx

**Comment by cgladue** [comment]
The reason is no one else has visited the website and logged in since i added partner name... the way it works is the users have to visit the site for these tags to update.

**Comment by robgpeak** [comment]
Ah, OK.  Gotcha
