### ISSUE TITLE
Someone credited the email optin bonus twice at the very same time

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#125]
https://shop.complinks.co/dashboard/users/view/100247 look in points history.  You can leave it there in this case of course, but let's see if it is a bug that we can fix.

**Comment by cgladue** [comment]
i bet they did something like queue up two tabs and press enter at exactly the same time .. or double clicked the link at the same time.... are you able to try either of those ?

**Comment by robgpeak** [comment]
Again bigger fish to fry. If we see it happening more than once in a blue moon will look into it...
