### ISSUE TITLE
Changing PartnerName to "Companies" in Intercom API

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#126]
@cgladue I hate to do this to you, but as I was looking through some more of the features of Intercom I think we are better off using their "Companies" feature to help us better segment users from multiple casino partners in the future.

The Partner Name attribute does come over fine, and I can segment by it, but again it does not allow for some of the cool extra features we would have if we used "PartnerName" as what Intercom calls "Companies"

If you have a look at https://docs.intercom.com/intercom-s-key-features-explained/tracking-user-data/the-people-and-company-list-explained and watch the video (but fast forward to 2:35) and just watch the last 60 seconds or so.

Then on the page below, you'll see the code for the window.intercomSettings = you'll need to add the company name (again, it would be the same as the Partner Name), and a unique code for the company. 

https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/group-your-users-by-company

Even after this works we can leave partner name in place as you currently have it just so we have it in the details attributes section anyway in case we want to use it as a merge field in end user communications...  i.e. "Hi {first_name} we see you are a member of {Partner_Name}..."

As per the instruction on the second link above, I have already enabled the Companies features in the general settings of Intercom.

**Comment by cgladue** [comment]
@robgpeak should be added now...
