### ISSUE TITLE
Integrate Unsubscribes between Intercom and Mailchimp 

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#127]
@cgladue please call me to discuss this before doing anything...  https://docs.intercom.com/faqs-and-troubleshooting/unsubscribing-users/how-can-i-sync-unsubscribed-users-with-mailchimp

**Comment by robgpeak** [comment]
Just thinking out loud here. In advance of turning Intercom on for Xclub, we might want to consider importing the existing xclub users...  https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/import-your-user-data-into-intercom

It is still part of the same issue.

**Comment by cgladue** [comment]
@robgpeak is this still valid since you removed the double opt in ?

**Comment by robgpeak** [comment]
I tried to remove the double opt in from mail chimp, but it is still sending the email subscription confirmation email, so I am not sure of the right solution.  I started another thread on this subject #176
