### ISSUE TITLE
Deactivated users not showing up in Relationship Changed

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#128]
@cgladue The image below shows advertisers from CJ that were deactivated but they do not show up in the relationship changed section as "not joined" as I thought they would.

![screen shot 2018-05-01 at 7 28 42 pm](https://user-images.githubusercontent.com/28446563/39498437-0ce7cb7e-4d76-11e8-9c30-5f857dc44479.png)

**Comment by morganpeak** [comment]
Hmm, something must be up then because I searched for a couple of them on CJ and they’re not even showing up anymore as advertisers which happens when they’re deactivated. So I’m getting the emails that they’re deactivated which true for most of them because they’re no longer on CJ

**Comment by morganpeak** [comment]
Disregard my last message I checked again and they came through on relationship changed

**Comment by cgladue** [comment]
so it must be that the API lags behind the actual website... hmm



Chad Gladue
*DevNull Technology, LLC*

**Comment by morganpeak** [comment]
yea that's what it's seeming like
