### ISSUE TITLE
Advertisers in MailChimp

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#13]
@cgladue I wanted to move this one over from the other github thread, as it is important for the testing and launch with Parx.  Please have a look at https://screencast.com/t/gNwGai9MgR and give it some thought as to a good way to handle it.

If we have to use static image in the email (meaning not calling to them from a URL), that's fine, just want to make sure the tracking will work.

**Comment by robgpeak** [comment]
@cgladue I wanted to see about getting a better understanding of how the "Campaigns" would work tracking wise from the emails that we send out for example.  I put together a crude screencast to show you how I was thinking about using it, but I am not sure if I am thinking about it properly.

https://screencast.com/t/Df0GzfofVB

**Comment by cgladue** [comment]
this was completed in your other request to do campaigns at the store level ... but you did mention that the user would have to click shop now button again, is it your desire to not have them click that button and take them to the advertiser automatically, after awarding the points and starting the trip ?

**Comment by robgpeak** [comment]
For the 50 points, they only have to click from the email to our site, they don't have to actually start a shopping trip.  As people start clicking through to our site, we should be able to track whether or not they actually start a shopping trip so we can gauge the effectiveness of the campaigns, but that would be a separate github issue.  So this issue can be considered closed.
