### ISSUE TITLE
Issue with not all Featured Stores showing up on the home page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#130]
@cgladue please have a look and see if you can tell what is happening.  I changed the order, moved some advertisers around in the order list, but it is not showing up on the live site(s) shop or xclub

**Comment by robgpeak** [comment]
hmm, I thought there were at least 12 in there.  Can there be?  I think it would be better balanced.

Also, maybe we can create another link at the bottom that says "See More Featured Stores" and it would expand that area and load more stores???  If that is something that can be done, please create and issue for it.  Thanks.

**Comment by robgpeak** [comment]
Yes please.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
all set, 12 now.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Thanks
