### ISSUE TITLE
API feed of items purchased from Impact Radius

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#131]
@cgladue did we ever get this sorted?

Here was the email I received from their support department...

Hi Rob,

Which call you decide to use would be up to your organization's needs. If you need information that is only available through the Action Updates then I would suggest using that. 

If an order is modified or reversed, the new sale amount would be recorded within the DeltaAmount section and there is no section for original sale amount. The state will also change, along with any other items that are modified. Additionally, once an action has been modified the changes should also be applied to the regular Action call, as those are now the correct details. 

However, you can also call a specific report (like the Advanced Action Listing) through the API and you can alter the report to include order SKU info, as well as original sale amount. I've included the API call for this report below for reference:
https://IRpheWJsW4ov406688Y2yse2g6i5P5gdh1:WVMTuzw%7EyHHgb3EChNCcXfFVKYEK%7E2Uh@api.impactradius.com/Mediapartners/IRpheWJsW4ov406688Y2yse2g6i5P5gdh1/Reports/mp_action_listing_sku?compareEnabled=false&timeRange=CUSTOM&START_DATE=2018-04-16&END_DATE=2018-04-20&SUPERSTATUS_MS=APPROVED&SUPERSTATUS_MS=NA&SUPERSTATUS_MS=PENDING&PUB_CAMPAIGN=0&MP_CATEGORY_LIST2=&MODIFIED_Y_N=0&PUB_ACTION_TRACKER=0&MP_ACTION_TYPE=0&ADV_PROMOCODE=&REFERRAL_TYPE=0&ACTION_ID=&SHOW_SKU=1&SHOW_ORIGINAL_SALEAMOUNT=1

Best,
Crystal

--

Hi Crystal,

My programmer ask me to ask you the following...

"Can you ask them if we could use the ActionUpdates API Exclusively or should we use the getActions API and use the ActionUpdates call seperatly to just get SKU and other info...

Also for the actionUpdates API call, the data that is returned, will the data ever change, or will all changes be additional records in the response ? like if they buy something for $10 then return part of the order, will we see the $10 original sale, then a second record for the -$5 or would we see one record showing $5 ?

Thanks again,

Rob

**Comment by cgladue** [comment]
i think the issue is sufficiently resolved for now ... all purchases will just have to come in through a "batch" instead of a realtime reporting since we dont know who has realtime enabled or not without you guys maintaining that field daily for all advertisers...  batch seems to be doing fine at the moment.
