### ISSUE TITLE
pending bonus/award campaigns

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#132]
@cgladue To be able to bonus/award a user with points for a certain action that happens in addition to them activating the campaign by clicking on a specific link.

For example: "Get 50 points for free when you earn points from a shopping trip to ABC store (or any store...?) by xx/xxxx date."

**Comment by cgladue** [comment]
@robgpeak take a look, give it a test and let me know if it is what you wanted, as we discussed.

**Comment by robgpeak** [comment]
@cgladue as a follow up (refresher) on this, if we were to send out an email like this (below), would the campaign that I set up (directly below) work?
<img width="975" alt="screen shot 2018-06-08 at 10 14 05 am" src="https://user-images.githubusercontent.com/28393235/41162739-bbc2b4fa-6b04-11e8-9b64-5985ba0f27cd.png">


--

Hi Chad,

I see you registered with Rewards Everywhere and that's great, but you have not started a shopping trip yet.  This is the way you will earn Rewards Everywhere points that you can exchange for Comp Dollars.

If you start a shopping trip this weekend before Sunday (June 10th) at midnight, I will give you an extra 50 points for free.  To activate this award, simply [click here](https://xclub.complinks.co/campaign/clicktrack/8680b4af1f0644d28f7761dfd0d0e790). 

Enjoy & Happy Shopping,

Morgan G.
Customer Care Lead Agent
CompLinks
xclub@complinks.co

PS. Not sure how to start a shopping trip [click here](https://support.complinks.co/how-to-video-collection/how-to-view-store-deals-and-start-a-shopping-trip) to see an example.

**Comment by cgladue** [comment]
this would activate the 50 extra points, but it would not give them to the
customer unless they earned a comission... the email says "start a trip" so
technically that just means click a link to an advertiser, perhaps
something like "start a trip and complete a purchase" or something ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
How do I see how many people activated a particular campaign?

**Comment by cgladue** [comment]
hmm, i guess didnt think of that, i just looked and there are 30 people who activate so far

**Comment by cgladue** [comment]
if you want to open this or a new item and i can add a tab for campaigns ?

**Comment by cgladue** [comment]
1 person already got the bonus amount ... 
![image](https://user-images.githubusercontent.com/7914133/41440813-0a396e0a-6ffe-11e8-94fe-88b713007a57.png)

**Comment by robgpeak** [comment]
So if you can tell who activated one and you received one, let's add two additional columns to https://shop.complinks.co/dashboard/campaign "Number of Bonuses Activated" and "Number of Bonuses Received"

I do also like the idea of seeing a campaigns tab for each person.

Lastly, what would happen if she returned the item?  Any way to claw it back?  Not that we would in this particular case because it is a one off, and we are NOT anticipating giving a bonus every time, but again, of we begin to implement the spinning wheel for the % increase in points for a particular shopping trip, we need to somehow tie the bonus to the specific trip, and if that trip results in a return, we need to remove the bonus points earned otherwise people will catch on and abuse the system.

That is at least another good reason to have the campaign tab in the person's user screen in the back end, so we can connect the dots to just such an instance.

**Comment by cgladue** [comment]
yea the bonus is tagged with the trip that triggered it, so in theory if
that goes to 0 then we could zero out the bonus as well.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
cool.  let's just keep an eye out for it.
