### ISSUE TITLE
Automatically updating Program URLs in LS

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#133]
@cgladue I know we were close to solving this I thought, and I wanted to create an issue so you had it for reference...

Thank you for your email. 

I understand that you want to get the Website URL of the Advertiser through API as it will be helpful for you in using it on your websites. I would request you to please go through the below information. 

Please be informed that you can get the URL along with other information of Advertiser by using the below link:

http://reportws.linksynergy.com/downloadreport.php?token=[Security Token]&reportid=13

In the above URL, you just have to replace [Security Token] with the Security token of the your account. Please follow the below mentioned steps to get the token:

Login to your dashboard.
Go to Links > Webservices.
Scroll down to Security token and copy the token and paste it in the above link.

Please find the below example: (please note the token provided below is from our publisher test account it is just for your reference)

http://reportws.linksynergy.com/downloadreport.php?token=026f0aa2753b36229b2dc0c0b3f150fcd48a697747762ea4a26da7815c96e3a9&reportid=13

I hope this helps to explain. Please let me know if something remains unclear to you. Thank you for contacting Rakuten Affiliate Network.

Regards,

Pooja Pal
Rakuten Affiliate Network Support.

**Comment by cgladue** [comment]
ok this is done, however the "report" that they deliver is really shitty, there are line breaks in the middle of lines and all sorts of data issues so i have to manually clean them up before loading ... attached is the file i loaded and it updated 96 advertisers program_url fields.

[reportdownload (1).zip](https://github.com/robgpeak/CompLinks-xclub/files/1981981/reportdownload.1.zip)

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/39732896-ead3f270-523d-11e8-8d37-efdbceb49e79.png)

**Comment by robgpeak** [comment]
Ok.  And the advertiser's it did NOT update, does that mean they already
had URLs in that field, or will they still be blank?

**Comment by cgladue** [comment]
either the program URL was blank in the file, or the program URL was
already the same in the database



Chad Gladue
*DevNull Technology, LLC*
