### ISSUE TITLE
Barcode scanner

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#134]
@cgladue In addition to the web extension, I think another valuable feature that will help people use CompLinks to shop more would be the barcode scanner.  I have been doing a bit of research, and it seems like it is now available within web apps.

There are a couple of apps that do it:
https://www.scandit.com/scandit-launches-barcode-scanner-sdk-for-web-brings-scanning-to-the-browser/

https://www.dynamsoft.com/Products/barcode-recognition-javascript.aspx

https://github.com/zxing/zxing

The other component is to have the scanned barcode be converted into a sku that we could look up, and then compare to skus that our participating online advertisers sell...  Wait for it...  https://screencast.com/t/N9EyZqkzCcg8

Please look into it and let me know your thoughts...

**Comment by robgpeak** [comment]
This site too...  I did a follow up search to make sure it would work on ios...  http://www.pic2shop.com/developers.html

**Comment by cgladue** [comment]
Interesting ... 

But SKU is only unique for each advertiser, the same UPC could be different skus for multiple advertisers ... is there somewhere in LS and CJ/IR that lists UPC and SKU on the same line ?

**Comment by robgpeak** [comment]
Not sure.  Yeah I think I was confusing the terms UPC and SKU. But I think
if they have multiple vendors that sell the same product it will compare
them side by side. I've seen that in the retail benefits app when I took a
picture of a certain UPC code

**Comment by cgladue** [comment]
there has to be a way ...

**Comment by robgpeak** [comment]
For sure there has to be a way.  It would be great if it worked on mobile,
tablet and desktop.  Does it look really complicated?

**Comment by robgpeak** [comment]
In looking at something like this https://github.com/VisionSmarts/pic2shop-client where the code is posted up there, does that mean you can install it on test.complinks.co and play around with it?

**Comment by robgpeak** [comment]
Nevermind, I just read this in their Readme file...  This is not a barcode scanner. This code demonstrates how to call pic2shop from another app and how to retrieve the result.

**Comment by robgpeak** [comment]
@cgladue I put together a scope document for this project.  Please have a look. https://docs.google.com/document/d/1he10VM6kwJdTXvRVNM59FmWx_NFJoGfPE43KUHQrCDM/edit?usp=sharing

**Comment by cgladue** [comment]
I Looked through the Linkshare one and int he merchandiser file they only
give us SKU and no UPC... so im still not sure how we are expected to
lookup the product by SKU if all we have is the UPC ?  i havent found any
SKU to UPC mapping out there, since every advertiser can map them to
different SKUs



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
According to this document, there is a list of advertisers (and they are the top 200 major ones in the US) that have UPC codes in the Merchandiser file...  https://pubhelp.rakutenmarketing.com/hc/en-us/articles/201704547-Advertisers-Who-Include-UPC-in-Merchandiser?flash_digest=b36bf2ce1809f792c37ad07f562c8ac2914daf5d

**Comment by cgladue** [comment]
hmm, interesting, ok i will have to generate the Merchandiser file because
in the page that describes what the merchandiser file is they list the
fields and UPC was not on the list



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
There is a table at the bottom of this page that shows the feed/file would contain UPC codes.

https://pubhelp.rakutenmarketing.com/hc/en-us/articles/210970606-Merchandiser-Query-API-Overview

**Comment by robgpeak** [comment]
Again, this is only going to work if we can map a sku to a UPC.  I think the UPC will be the only thing people will scan.

**Comment by cgladue** [comment]
that is correct, and there are UPS in there, but not every advertiser enters a UPC for every one of their products ...
