### ISSUE TITLE
The featured deals on the home page look messed up

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#136]
@ChrisASearles  Not sure what happened, but this is messed up and needs to be fixed ASAP.

<img width="1209" alt="screen shot 2018-05-08 at 1 52 46 pm" src="https://user-images.githubusercontent.com/28393235/39773916-ea576b96-52e8-11e8-8678-3a2288ccb791.png">

**Comment by robgpeak** [comment]
Even when it is full size, something is askew... 
<img width="977" alt="screen shot 2018-05-08 at 1 55 50 pm" src="https://user-images.githubusercontent.com/28393235/39774003-a6ce334e-52c7-11e8-94b5-01506c3d7dcb.png">

**Comment by ChrisASearles** [comment]
@cgladue It looks like the deal text is being saved into the linkCodeHTML field somehow. That's where this is coming from and a cursory look at LinkDAL.getFeaturedDeals looks like it's loading from the correct field out of the Link class.

**Comment by robgpeak** [comment]
@cgladue We need to get this fix ASAP, it looks like shit.

**Comment by robgpeak** [comment]
Just have to get the text out of the image area.

**Comment by cgladue** [comment]
@robgpeak @ChrisASearles 

im not sure what i have to do with this, its been fine all along and nothing changed except whatever you did for home depot and the tracking pixel ...

**Comment by robgpeak** [comment]
Guys let's get this fixed today please

**Comment by cgladue** [comment]
i got this ...

the problem is chris was using the entire contennts of the linkCodeHTML not just the image element ... the code below extracts just the IMG from the HTML and inserts just that pixel for tracking purposes, we dont need the <a> part ...

```
string trackingPixel = "";
    if (!String.IsNullOrEmpty(Model.linkCodeHTML))
    {
        var htmldoc = new HtmlAgilityPack.HtmlDocument();
        htmldoc.LoadHtml(Model.linkCodeHTML);

        trackingPixel = htmldoc.DocumentNode.Descendants().Where(x => x.Name == "img").FirstOrDefault()?.OuterHtml;
    }
```

**Comment by cgladue** [comment]
@robgpeak @ChrisASearles this should be done now...

**Comment by robgpeak** [comment]
OK thanks

**Comment by cgladue** [comment]
@robgpeak also, can you ask home depot to take a look again and (hopefully) enable our comission %

**Comment by robgpeak** [comment]
​will do
