### ISSUE TITLE
Check the IR API

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#137]
@cgladue I noticed something about this Dick's Sporting Goods purchase that I made several weeks ago keeps showing up at the top of the list as a new transaction for a new date. Meaning it looks like it's today's date at 3:44 but I made the original purchase about 10 days ago.​  For some reason the API must keep calling for it.  

Maybe it is just becasue it is a 0 points transaction...  I had another IR transaction from Target on my xclub account where I earned points and it does not keep coming to the top of the list...
<img width="949" alt="screen shot 2018-05-08 at 4 08 15 pm" src="https://user-images.githubusercontent.com/28393235/39780710-23f0da12-52db-11e8-84f7-fd35037b17e8.png">

**Comment by cgladue** [comment]
This was an order you cancelled or returned correct ?

**Comment by cgladue** [comment]
yea, i think you did, it shows as "REVERSED" status so thats why i thought
you returned the item.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
but why does it keep "updating" and show the new current date?

**Comment by cgladue** [comment]
i was updating the balance record every time it checked the API, i removed that and only update when neccessary now... next time i have changes to push to the ComlinksEngine it will take effect.

**Comment by robgpeak** [comment]
Have you pushed the ComlinksEngine since this post you made three days ago?  Just wondering because I saw the same Dicks sporting goods transaction again in my points history from today at 4:14pm
