### ISSUE TITLE
replacing some back end icons

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#140]
@cgladue I am planning on showing caesars the back end functionality when I am making the presentation next week, and I wanted to see if you can replace the current menu icons in the back end for two new ones, just so they are all different.

For Activity Stream, please use https://material.io/tools/icons/?search=activity&icon=local_activity&style=baseline

For Properties, please use https://material.io/tools/icons/?search=ho&icon=home&style=baseline

For Point Transfers, please use https://material.io/tools/icons/?search=arro&icon=compare_arrows&style=baseline

**Comment by cgladue** [comment]
ok, and just an FYI you dont have to only choose from material.io icons, i
actually like the fontawesome icons better personally...
https://fontawesome.com/

if you saw something you liked there better can use those too



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
OK.  The ones I pick for now will work, and in the future I will look at the other site.

**Comment by cgladue** [comment]
@robgpeak published
