### ISSUE TITLE
Showing links to the browser extensions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#141]
Initially we are going to only have the extension for Chrome, but these instructions will be for ALL browser extensions.

1. We need to be able to first check the browser that someone is using and if it is Chrome they would see the modal that shows the Chrome browser extension information. If they are using Safari they would see the modal that includes the Safari extension button. If they're using Firefox they would see the modal that includes the Firefox extension button.

2. The border and button in the modal would have the same color scheme as the subdomain on which the modal is being viewed.

2a. We would need to check every authenticated user's cookies each time they come to the site to see if they have the browser extension installed.  If they DO, then we do not show the modal.  If they do not have it installed, then they would see the modal.  This would be the same for each different browser that same authenticated user might be using.

3. The copy for the modal top section is: "Install the **Rewards Everywhere Shopping Assistant** and never miss a points earning opportunity."

4. The copy for the modal top section is: 
**How it works…** 
Whenever you visit the site of a participating store, you will receive a
notification to activate a shopping trip which will allow you to get the
**best deals** from that store, and earn **more points**.

images:
![extension_notification](https://user-images.githubusercontent.com/28393235/39893933-5bcdbbbe-5473-11e8-853f-88fe7e769d56.png)
![internet-chrome-icon](https://user-images.githubusercontent.com/28393235/39893943-63c95364-5473-11e8-9f1d-ddb7a27db68a.png)
![safari-icon](https://user-images.githubusercontent.com/28393235/39894114-dd9309a6-5473-11e8-8e95-11e72391a2bc.png)
![firefox-icon](https://user-images.githubusercontent.com/28393235/39894127-e307e37a-5473-11e8-8810-4498f1178875.png)

5. Additionally, I would like a page on the site that is called /shopping-assistant that looks like this... (below) which I would be able to edit in the back end similarly to the promotions page.

<img width="606" alt="screen shot 2018-05-10 at 5 32 27 pm" src="https://user-images.githubusercontent.com/28393235/39895460-53eaac40-5478-11e8-907b-0c36cec8dd61.png">

**Comment by ChrisASearles** [comment]
@cgladue can you send me the links to all the extensions when you get a chance?

**Comment by robgpeak** [comment]
https://chrome.google.com/webstore/detail/rewards-everywhere-shoppi/biikhgpldoekknfibpcegkkhbbjkchnh?hl=en-US

Keep in mind that at the moment this is NOT live on the Chrome web app store EXCEPT if someone has this link.  It is still being tested by the advertiser networks.

**Comment by ChrisASearles** [comment]
What about the other two?

**Comment by robgpeak** [comment]
They are not built yet.  We are waiting for the compliance department from the affiliate networks to approve the chrome version before building the other browser's versions.

**Comment by ChrisASearles** [comment]
Ok, I dropped this to the backlog, let me know when we can get into it.

**Comment by robgpeak** [comment]
Chris, we just received approval for the Chrome version of the web extension, so I would like to see the mock-up you have to the layout and look of that page as soon as you can.  You can put it live on the site, (the page itself), but not the link to it in the navigation until we do some internal testing with the page and extension...

**Comment by robgpeak** [comment]
@ChrisASearles please see my message from Friday.

**Comment by ChrisASearles** [comment]
Hey @robgpeak I created the page but I'm just re-reading this and realized you said you need this to be editable by you on the backend which pulls me out of the loop at least until you and @cgladue define how structured you want the data to be when stored in the DB and the back-end (or at least the data model) has been completed to be able to pass to me on the front-end.

**Comment by robgpeak** [comment]
When I said I would _like_ it to be editable, I meant, if you could build it in such a way that makes it like the Promotions page or the How it Works page, where is has the same sort of structure with image area on the left, copy area on the right in the tops section, then image on the right and copy on the left in the next section that would be great.  So in essence, it would be a replica of the promotions and how it works pages.

This way we can start with Chrome, and then as the other browser extensions come online, we can add in their sections...

**Comment by robgpeak** [comment]
@ChrisASearles What does the page look like that you created?

**Comment by ChrisASearles** [comment]
Right now it's just a blank content section. If it's going to be editable then the content needs to come from the database so there's not much I can do until there's content being sent to the page (or at least a well-defined data structure I can use to mock something up accordingly). Based on how you and @cgladue decide to define the data store, that would determine what I need to do on the front-end to achieve the layout you're looking for.

**Comment by robgpeak** [comment]
So if you already created a page, can you fill the content in with the information in the mock up that I did with the imagery and verbiage so we have something to work with...

**Comment by robgpeak** [comment]
@ChrisASearles The intent right now is to get people to install the browser extension, so what I would like you to do is figure out how to get the most number of people to install the web extension.  I would think it would be through a combination maybe an overlay and a page explaining the benefits and exactly how to do it.  Please use your creativity to make it attractive and captivating like ebates does.

**Comment by ChrisASearles** [comment]
@robgpeak Just committed a version of this page with a dummied in video. Will work on the modal next.

**Comment by robgpeak** [comment]
@cgladue When will I be able to see this page that Chris committed?

**Comment by cgladue** [comment]
When did he commit it ?    It’s not there already?  If not then will have to be tonight.  I’m in Boston for a conference.

**Comment by robgpeak** [comment]
He wrote in github 22 hours ago, "@robgpeak Just committed a version of this page with a dummied in video. Will work on the modal next."

**Comment by robgpeak** [comment]
Oh, sorry, I see it now... Nevermind Chad

**Comment by ChrisASearles** [comment]
@robgpeak my fault, realize I never sent you the URL. There are two images missing on the page, they were included in my commit but it looks like I hadn't saved the project file before I pushed it up for Chad. I fixed that this morning so they should get up there as soon as the site gets updated next.

**Comment by robgpeak** [comment]
@ChrisASearles please make some slight copy changes to this page, and embed this video...

1. ​Change ​the headline of the page to read, "Never miss an opportunity to earn points again"  No period at the end.​

2. Change "Click on the icon above to install our Chrome browser extension." to "Click here to ​add the Shopping Assistant ​to​ your Chrome web browser." and make the full line of text AND the icon above clickable.

3.  ​Change the word "little" ​in the bottom paragraph​ to "popup"​.

4.​ Please use this code to embed the video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/WydzYxl4U5E?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>​

As for making the whole page editable in the back end like the promotions and how it works pages, is that possible?

**Comment by cgladue** [comment]
What elements would you like me to make available to rob Chris ?   Like a title header and body section or anything special that you need me to capture from him ?  The how it works sections are basically just a couple sections and rob edits those.  I assume something similar?

**Comment by robgpeak** [comment]
@cgladue I would assume it would be just like those other pages where it's only the body sections that I can edit.  Just like on Promotions and How It Works...

**Comment by robgpeak** [comment]
@ChrisASearles I know you have other issue you're working on right now, but could you please make some slight copy changes to this page, and embed this video...  It should only take 15 minutes...

1. ​Change ​the headline of the page to read, "Never miss an opportunity to earn points again" No period at the end.​

2. Change "Click on the icon above to install our Chrome browser extension." to "Click here to ​add the Shopping Assistant ​to​ your Chrome web browser." and make the full line of text AND the icon above clickable.

3. ​Change the word "little" ​in the bottom paragraph​ to "popup"​.

4.​ Please use this code to embed the video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/WydzYxl4U5E?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>​

**Comment by cgladue** [comment]
it was last night i emailed just to be clear ;)



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Gotcha.

**Comment by ChrisASearles** [comment]
@robgpeak This has been committed, I'm going to reassign this ticket back to you and @cgladue to figure out what and how you want to be able to edit this content on the back end.
