### ISSUE TITLE
Changes to the "Quick  Links" in the footer

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#142]
@cgladue currently the "Featured Stores" link in the Quick Links section of the footer links to a page that is non existent.  Please remove it all together.  Eventually it will be replaced with the link to the "All Stores" page mentioned in #139 

For now, please also comment out the "Referrals" link as that page is not built yet.

Eventually we will have a link to the Shopping Assistant page there as well ( #141 )

**Comment by cgladue** [comment]
@robgpeak published
