### ISSUE TITLE
Importing user data into Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#144]
@cgladue please import the user data and all the attributes from the users who signed up for xclub before we had the Intercom widget installed on the xclub subdomain.  This way we can have a full view of ALL the users.

https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/import-your-user-data-into-intercom

We want to make sure there are no duplicates, but we also don't want to leave anyone out.

**Comment by cgladue** [comment]
i tried to do this tonight, but there was no option for me to choose the "Company" for the users i was importing... is that something you can set manually ?

**Comment by robgpeak** [comment]
Does something on this page help? https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/group-your-users-by-company

**Comment by cgladue** [comment]
no that shows how to remove users from a company or add them when they
visit your site, i need to either add existing users that are in intercom
to a company or import users directly into a company



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I wrote to Intercom and this is what they said:

Hi there!
Austin here from the Support Engineer team. 👋
There are various ways you can import users into Intercom, but at the moment, the only way you can bulk import users with their company data is with our REST API. You can use it to create users and include their company data like so:
<img width="551" alt="screen shot 2018-05-12 at 1 26 21 pm" src="https://user-images.githubusercontent.com/28393235/39959980-1d912efa-55e8-11e8-8fb6-dbeb7a138d41.png">


Let me know if you have any other questions about this — I'm happy to help!

**Comment by cgladue** [comment]
ugh, wtf



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I have no idea.  It's all Greek to me.

**Comment by cgladue** [comment]
no, if the API is the only way ill have to write something



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@cgladue In order to keep all the correspondence we have with the end users in one place, we would really need to have all the user data in one place, and the users who signed up before we had Intercom enabled are not in there.  So for example, I would like to send an email through Intercom today to the woman (Cynthia Boyden) who earned a voucher for reaching more than 400 points last month, but she is not showing up in Intercom along with her points total.

Is there anyway you can get all those users imported into the Xclub company in Intercom for me?

**Comment by cgladue** [comment]
Ok yea it can be done. I’ll get right on it

**Comment by robgpeak** [comment]
Thanks.

Rob

**Sent from my phone

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/40880417-67af88f0-667e-11e8-81c0-00ec62ceef81.png)

need access to Extended functions, they claim could take up to 5 days to approve my request .. so waiting onethem currently.

**Comment by cgladue** [comment]
@robgpeak can you take a look now and see how it looks ?

**Comment by robgpeak** [comment]
Please do me a favor and have look at the points for this person in both our back end and in Intercom and see if you can make heads or tails of it.  https://shop.complinks.co/dashboard/users/view/100203 and https://app.intercom.io/a/apps/d8m2yyar/users/segments/all-users?searchActive=true&searchTerm=cynthia%20boyden and see if you can see the discrepancy? 

I see pending points and available points in our back end of 448, and 175 respectively, but in Intercom I only see 335 and 150 respectively.  Looks like 113 points-ish is missing, and there is one transaction, the forever 21 that is that amount...?

**Comment by robgpeak** [comment]
Same thing with user https://shop.complinks.co/dashboard/users/view/100267 who shows pending points in our back end, bot not showing up in https://app.intercom.io/a/apps/d8m2yyar/users/segments/all-users?searchActive=true&searchTerm=maureen

**Comment by cgladue** [comment]
remember, the values dont get updated till they go back to the website
again...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I did not remember that, and why would that be the case?  Meanibg, why is
it not pulling the actual number...  Is there a way to make it do that?

So if I was to send an email through Intercom saying by something like, Hi
{first name} you have earned  {pending points} so for this month, only x
more to reach reward y... That would not be accurate if it was reading the
number showing up in Intercom, and that would be a problem.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
take a look now ? i manually did a mass update of all users in xclub.

**Comment by cgladue** [comment]
rob i have integrated intercom into the system to automatically update intercom when the following happens:

Point adjustment happens
Comission is earned
redemption occurs

i think this should cover all the places the point balance can change so intercom should stay up-to-date going forward.

**Comment by robgpeak** [comment]
Sounds good
