### ISSUE TITLE
For some reason the Harry and David logo is not showing up on the home page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#145]
@cgladue I just put it in with a featured deal, and the logo is not showing up for some reason.  Actually, it must have something to do with it being an IR logo because I just tried to feature a deal from Target and it too is not showing the logo in the featured deal section, yet the same logo IS showing in the featured store section on the same home page.

Please let me know when you have looked at it and ascertained the problem so I can take them both down because they look bad at the moment...

**Comment by cgladue** [comment]
@robgpeak had to do with Impact storing the logos differently then the others and the URL being interpreted wrong, i fixed it.

**Comment by robgpeak** [comment]
Cool
