### ISSUE TITLE
No links for newly joined Impact Radius Advertisers

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#146]
@cgladue it seems like the links aren't pulling through for the Impact Radius advertisers that changed to "joined" for us recently.

some examples:
casetify - no links
eyebuydirect- no links
belkin- no links
6 pack fitness- no links

**Comment by cgladue** [comment]
Recently meaning over 1 day ago ?

**Comment by morganpeak** [comment]
Yea some of them joined 2 or 3 days ago

**Comment by morganpeak** [comment]
Okay I’ll check to see that it’s working
