### ISSUE TITLE
Adding advertisers paying flat commissions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#147]
@cgladue we wanted to see about adding the ability to list advertisers who are paying a flat fee commission.  Please give it some thought and let us know. @morganpeak

**Comment by cgladue** [comment]
do you know any off the top of your head ?

**Comment by robgpeak** [comment]
So instead of "Earn x points/$1 spent" for the existing commission based advertisers, it would read, "Earn x points"

For examples, in CJ, there is:
2166096 - Bistro MD who is paying $45 per sale
2690199 - Blooms Today Flowers & Gifts paying $5 per sale

In LS:
42582 - Shaw Academy paying $7 flat fee
42135 - Lookupfare pays between $8 and $16 depending on the item purchased.

In IR:
5613 - Cloud Phone paying $60 per sale
2092 - Target in addition to paying a percentage of sales at the store, they pay $8 for a credit or debit card application that is approved.

**Comment by cgladue** [comment]
It’s a one time commission right?  How will you convey that to the user ?

**Comment by robgpeak** [comment]
Yes one time, and we will convey in the Conditions section of the stores
page.
