### ISSUE TITLE
Site security SSL

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#149]
@cgladue Please have a look at

<img width="343" alt="screen shot 2018-05-22 at 5 51 39 pm" src="https://user-images.githubusercontent.com/28393235/40392281-0b94d7e8-5de9-11e8-8ad1-58c342aebabb.png">

and then see if we can fix it and have a solid green lock showing the site is "secure" all the time.

https://support.google.com/chrome/answer/95617?visit_id=1-636626226751978357-1904821776&p=ui_security_indicator&rd=1

The same thing happens on Firefox
<img width="430" alt="screen shot 2018-05-22 at 5 50 25 pm" src="https://user-images.githubusercontent.com/28393235/40392326-3ad2d9ce-5de9-11e8-98b8-933180ddf01d.png">

and this is their article on how to check into it and fix it.

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

**Comment by cgladue** [comment]
probbally something loading a file from non-https thats breaking the green
lock.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Is there a way to see with inspector or something...?

**Comment by cgladue** [comment]
yea it will tell you using dev tools



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I was just asking if it was something you could see personally. Meaning you
yourself to determine if there is something we can fix

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/40396627-0e842e78-5dfc-11e8-843e-36b66e28c10d.png)

its the tracking pixels, they are not on https... let me see if they are even available on https and if so ill have to do some switcharoo

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/40396870-60cc9f70-5dfd-11e8-9cfd-c03841967f8f.png)

ok should be all set now, take a look

**Comment by robgpeak** [comment]
Awesome-sauce.  Thanks
