### ISSUE TITLE
trouble removing (Excluding) advertiser

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#150]
I tried to remove Caesar's from foxwoods.complinks.co but it is not working.  I even tried from incognito window.

<img width="847" alt="screen shot 2018-05-23 at 7 07 34 am" src="https://user-images.githubusercontent.com/28393235/40421114-b274448a-5e58-11e8-982c-05e4988b8887.png">

<img width="875" alt="screen shot 2018-05-23 at 7 10 34 am" src="https://user-images.githubusercontent.com/28393235/40421123-b9fb7f7a-5e58-11e8-83b1-90058f0e14da.png">

**Comment by cgladue** [comment]
I’ll get this working by the time of your presentation.

**Comment by robgpeak** [comment]
Just so you know it is not isolated to Foxwoods.  I have excluded Caesars from Xlcub, but it is still showing up.  If you can't resolve it by 11:30, don't sweat it, I will just make Caesars inactive for the time being.

**Comment by cgladue** [comment]
where are you seeing caesers entertainment ?  its not showing up for me




Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
got it, all fixed... it was pulling all advertisers by category even if
they were excluded but the search box and the featured advertisers was
working fine.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
👍
