### ISSUE TITLE
Error in inspect mode

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#151]
@cgladue Please have a look at this error and see if you can fix it.

<img width="1263" alt="screen shot 2018-05-30 at 8 34 34 am" src="https://user-images.githubusercontent.com/28393235/40720363-7595135a-63e4-11e8-9d64-05756873be82.png">

**Comment by cgladue** [comment]
think this is an error in onesignal's code and not much i can do ill confirm tho

**Comment by robgpeak** [comment]
So in addition to checking specifically for the issue with Intercom can you look though inspector and see if there are any other issues/errors in the code that you might be able to fix.

In essence, we should always be looking to improve the speed and performance of the site

**Comment by cgladue** [comment]
actually, error seems to not be there now...
![image](https://user-images.githubusercontent.com/7914133/41820971-f2c2f78a-77a7-11e8-889a-d186f62af8c5.png)
