### ISSUE TITLE
Functionality and look of "All Stores" page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#153]
@ChrisASearles I know you're not done with #139, and I also know some of these things below are already on your radar, but I wanted to create a separate issue for the functionality and look of the page just to keep it separate from 139.  There are a few things to consider.

1. Please have the bookmark to the individual letters stop at the actual letter.  Meaning, as it is now, if I click on a letter at the top, it goes to the first listing of that letter, but I can't see the actual letter any more.

2. Number 1 is important because when the bookmark stops on that letter, there needs to be a ^Top link to get back to the top of the page.

3. In the listings themselves, we of course need the "Earn x points/$1 spent" for each store.

4. I would like to see some sort of divider between each listing.  It should be consistent with our overall look and feel for continuity sake.

**Comment by ChrisASearles** [comment]
This is all being tracked under #139
