### ISSUE TITLE
GDPR notice

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#156]
@ChrisASearles  please put a GDPR notice on our sites.  https://termsfeed.com/blog/gdpr-notice/ I know we do not target European users but none-the-less better safe than sorry.

**Comment by ChrisASearles** [comment]
@robgpeak can you approve / edit the following text for me. I'm obviously not an attorney so I would make sure your attorney reviews this, especially how it relates to your privacy policy:

"This site uses cookies and other tracking technology to provide the core services of our product and measure the effectiveness of our products. These include things like tracking the points you earn from our partners and linking them to your CompLinks account as well as tracking anonymous, aggregate site usage data like the number of visits to each page in a month, etc. For more information about the way we collect and use data, please review our privacy policy."

**Comment by robgpeak** [comment]
will do.

**Comment by robgpeak** [comment]
Legal is fine with it, but there's just a couple of small changes.  "This site uses cookies and other tracking technology to provide the core services of our product and measure the effectiveness of our products. These include things like tracking the points you earn from the advertisers on our site and linking them to your Rewards Everywhere account as well as tracking anonymous, aggregate site usage data like the number of visits to each page in a month, etc.  For more information about the way we collect and use data, please review our privacy policy."

**Comment by ChrisASearles** [comment]
Just committed this. Will show up until they hit the continue button then go away for up to a year.

**Comment by robgpeak** [comment]
How do I see this in action?

**Comment by cgladue** [comment]
i published it

**Comment by robgpeak** [comment]
@ChrisASearles after clicking the accept "continue" button on the notification in my phone, I was unable to scroll anywhere else in the page.  Please try it in your phone and let me know if you see that same thing.  If so, please fix it.  If not, maybe it was just a fluke

**Comment by ChrisASearles** [comment]
@robgpeak looks like we can isolate this only to chrome on android, looking into a fix now ...
