### ISSUE TITLE
Force capitalization of first and last name

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#157]
@cgladue Is there a way to programmatically force (or automatically augment) the capitalization of a person's first and last name when they enter it?  Or at least change it after they submit it.

We just sent out an email, and I see some of them are showing up with uncapitalized first names, and it looks pretty bad.

**Comment by cgladue** [comment]
@robgpeak should be working now.

**Comment by robgpeak** [comment]
I'm not sure it's working.  Account 100849 signed up after you fixed it, and her first mean is not capitalized.

Also, can it force the capitalization of all the previous user who have already registered?

Lastly, and this might be a separate issue but user 100843 has no first name listed.  How can that be?
