### ISSUE TITLE
API may not be updating

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#159]
@cgladue In the Relationship Changed tab, the last day new info was pulled into there seems to be 6/8. I have been getting emails from advertisers saying that they have approved our program or have been reactivated/deactivated but it doesn't seem to be up to date or pulling through and showing joined/notjoined

**Comment by cgladue** [comment]
i had temporarily stopped that process while i was testing out the product feed, it has been started as of a day or so ago and all that should be up to date again if you can check ?

**Comment by morganpeak** [comment]
Yup its up again now, thank you!
