### ISSUE TITLE
Mobile view of ./myewards page is different from desktop

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#16]
@cgladue Here is an issue that has been around for a LONG time.  And it indicates to me that there is some sort of disconnect between the desktop version and the mobile version of the site that is also causing the logging out issue.

I just put in a transfer request of points from my desktop, and it worked fine, but when I happened to go to my mobile version of the same page, I am still seeing the display of (The number of points that would be remaining after the transfer) on the left hand side, instead of the (number of points I would like to transfer on the left [as it should be, and is on the desktop version of the page])

![uploads/02d474cf-0f2c-42fc-b6c1-76baf7fcd8b1/Screenshot_2018-02-22-12-22-58.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F02d474cf-0f2c-42fc-b6c1-76baf7fcd8b1%2FScreenshot_2018-02-22-12-22-58.png)

and 

![uploads/9bfad60c-0d33-4f79-ae8b-ee5b4472a642/Screen Shot 2018-02-22 at 12.35.04 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9bfad60c-0d33-4f79-ae8b-ee5b4472a642%2FScreen+Shot+2018-02-22+at+12.35.04+PM.png)

**Comment by cgladue** [comment]
this is something chris and company messed up a while ago and never fixed, ill do my best to see what the heck they did

**Comment by cgladue** [comment]
i got it, fixed.. but it wouldnt have any affect on the login of the site unfortunatly ...
![image](https://user-images.githubusercontent.com/7914133/36574742-1e207b66-1815-11e8-984f-eb82a4d13001.png)

**Comment by robgpeak** [comment]
👍
