### ISSUE TITLE
Need new message for Activated bonus campaign

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#160]
@cgladue When I activate a campaign to earn a "Bonus" for completing a shopping trip the original message is fine, but if I go back to that same page with the campaign code I see "error You have already recieved the award for this campaign."

(which by the way received is spelled wrong)

But instead it should read in yellow with the yield sign exclamation point, "You have already activated the award for this campaign."

**Comment by robgpeak** [comment]
@cgladue I never heard back from you on this one, and I was about to send out another email for a new campaign this weekend.

<img width="863" alt="screen shot 2018-06-22 at 12 53 28 pm" src="https://user-images.githubusercontent.com/28393235/41788945-79eed1e0-761b-11e8-955c-af854e7195f2.png">

**Comment by cgladue** [comment]
@robgpeak i have the fix in, but cannot publish the site untill @ChrisASearles sends me the missing file from his shoppingassistant work.

**Comment by ChrisASearles** [comment]
@cgladue that file is not being used yet so for now you can just exclude it from the project. that was Derek sharing his updates with me for me to finalize a few things. he's going to get it added to the repo but for now you can just exclude from project.

**Comment by robgpeak** [comment]
Cool
