### ISSUE TITLE
Automatic commission percentage adjustments in IR

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#162]
@cgladue In impact radius Houzz just changed our commission from 2% to 3%, but it is not updating in the back end.  Also, Cabela's just accepted us into their affiliate program, but the percentage in our back end still show 0? This may have to do with the other issue I brought up about the API but wanted to bring it to your attention either day

**Comment by cgladue** [comment]
has it been over 24 hours since these updates occured ?  we only poll the
API once every 24 hours for updates of these types



Chad Gladue
*DevNull Technology, LLC*

**Comment by morganpeak** [comment]
At this point, not yet so I will keep an eye on it and keep you posted. Sorry!

**Comment by robgpeak** [comment]
@cgladue Houzz updated our commission to 3% on the 13th but still it's not showing up in our back end yet.
<img width="856" alt="screen shot 2018-06-18 at 3 42 38 pm" src="https://user-images.githubusercontent.com/28393235/41558271-44977336-730e-11e8-949b-364a7f9c9e99.png">

**Comment by cgladue** [comment]
Just looked and there is nothing available to get the commission rate
through the API at the time i implemented it ... i will check their
documentation again just to confirm...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Anything on this Chad?  Can we (should we) change it manually in the back end?  Will it stay that way if we do?

**Comment by cgladue** [comment]
it will stay that way yes because there is nothing in the code to adjust it
currently.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I just updated it manually to 3% in our back end, and submitted a ticket to
IR to see if they have that information in a feed.
