### ISSUE TITLE
Quick fix for changing "Featured Deals" display order

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#163]
@cgladue If you go to the home page now and see the Featured Deals, you can see I just added the 1800baskets as a "featured link" for a Father's day special, but it shows up at the very bottom.  I would like it to show up at the top of the list and move all the other ones down.

**Comment by cgladue** [comment]
uhh what if i sorted by last modified date, then when you featured something it would be the latest one first ?

**Comment by robgpeak** [comment]
exactly.  Can you do that?

**Comment by cgladue** [comment]
@robgpeak Yep, done

**Comment by robgpeak** [comment]
So what order does it really sort in?  I just changed a Taylor Made link to be Featured, and it showed up in the Featured Deals section of the home page, but not at the top, it's somewhere in the middle of the pack.  I would think it would be based on when I featured the link, no?

Also, will they disappear when they expire?

**Comment by cgladue** [comment]
it will disappear when you defeature it or the link expires yea

i just made a change, when featuring a link it didnt change the modified
date, so try to defeature then feature that link again and should be at the
top...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
👍
