### ISSUE TITLE
Quick fix on https://shop.complinks.co/trips page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#165]
@cgladue Two things:

1. There is a little dropdown menu on the page:
<img width="325" alt="screen shot 2018-06-14 at 6 30 28 pm" src="https://user-images.githubusercontent.com/28393235/41441511-f12aaed0-7000-11e8-89c6-be2778f3863f.png">

but the month selection feature does not work.  If it is easy to have the month section feature work, that would be great, otherwise remove it for now.  At the moment we do not have enough users over enough months making that many trips, but eventually we will...

2. Pleas remove "Pending" from all the cells in both the Order total and Points awards columns so it resembles the look of the Most Recent Shopping Trips on the user's Dashboard.

**Comment by cgladue** [comment]
yea i dont think chris ever implemented this ...



Chad Gladue
*DevNull Technology, LLC*
