### ISSUE TITLE
Cabela's Ads are showing up twice each

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#166]
@cgladue There are only three active ads in the back end, but they are showing up as duplicates https://shop.complinks.co/stores/index/12347

**Comment by cgladue** [comment]
@ChrisASearles looks like the img is showing twice, but the link is only once for these ... not sure whats up.

**Comment by ChrisASearles** [comment]
Hey @cgladue it looks like you made some changes for the tracking pixel. That code is what's loading the second image for these ads so I'm going to reassign back to you.

**Comment by cgladue** [comment]
I disnt make any changes.  What changes did i make ?

**Comment by ChrisASearles** [comment]
I don't remember writing this, was pretty sure it was yours:

```C#
@{
    string trackingPixel = "";
    if (!String.IsNullOrEmpty(Model.linkCodeHTML))
    {
        var htmldoc = new HtmlAgilityPack.HtmlDocument();
        htmldoc.LoadHtml(Model.linkCodeHTML);

        trackingPixel = htmldoc.DocumentNode.Descendants().Where(x => x.Name == "img").FirstOrDefault()?.OuterHtml;
    }
}

...

@if (!string.IsNullOrWhiteSpace(trackingPixel))
{
    @Html.Raw(trackingPixel.Replace("http://", "https://"))
}
```

**Comment by cgladue** [comment]
That part is, because he part you had done didnt extract the img out   Ill take a look again but i hope theres not more then just a single pixel in that field.

**Comment by cgladue** [comment]
@ChrisASearles ok, i think it was for links they stick the tracking pixel image in that field, but for ads they stick the ad image in that field too, with no tracking pixel, so for the MedSquareAd partial, i just commented out the tracking pixel code... looks to be fixed. @robgpeak

**Comment by robgpeak** [comment]
Cool.  Working now
