### ISSUE TITLE
Need links to Shopping Assistant page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#167]
@ChrisASearles please put a link in the footer interested the Quick Links section below how it works to the shopping assistant page.  We need another link in the main navigation across the top to the right of FAQ that says Shopping Assistant.  That one would also appear in the hamburger menu.

Lastly we need some sort of modal that pops up to Authenticated users who have Not installed the shopping assistant yet.  Meaning, once they have it installed, they would NOT see the pop-up any more.

**Comment by ChrisASearles** [comment]
@cgladue did you build the extension? I believe we're going to have to make a small change there to be able to hide/show the modal based on whether or not it's been installed.

**Comment by cgladue** [comment]
no sir i did not, @robgpeak

**Comment by cgladue** [comment]
@ChrisASearles i pulled down the latest changes and tried to run the app, but _ShoppingAssistant.cshtml is missing so it failes to run.
