### ISSUE TITLE
Adjustments to the Advertiser View Details section on dashboard/partner/  Dashboard page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#169]
@cgladue These might be separate issue, but I will list them here.  If something needs to be pulled out as a new issue for Chris to handle, please do that and @ me on the thread as well.

1. Change the name of the column "Count" to Trip Count"

2. Add the ability to see the data for a specific month. So it would show the current month by default, but then it would allow the user to select a date range.

2. I would like to see numbers as the cumulative total of all shopping trips for the time period selected.  Right now it is showing each advertiser by each day and that is not very useful.

**Comment by cgladue** [comment]
@robgpeak  #1 done

**Comment by cgladue** [comment]
So it would show day by day from the start and end dates selected all trips for that date, is that what you mean ?

**Comment by cgladue** [comment]
```
{
        "etransaction_id": "A4A3AB457882B9DBAEBCDB95D966C47A",
        "advertiser_id": 41258,
        "sid": 3371414,
        "order_id": "32513854",
        "offer_id": "425060",
        "sku_number": "*not-available*",
        "sale_amount": 17.99,
        "quantity": 1,
        "commissions": 1.6191,
        "process_date": "Mon Jun 18 2018 13:40:23 GMT+0000 (UTC)",
        "transaction_date": "Mon Jun 04 2018 00:00:00 GMT+0000 (UTC)",
        "transaction_type": "batch",
        "product_name": "",
        "u1": "3371414",
        "currency": "USD",
        "is_event": "N"
    }
```

did you do anything different with this trip then usual ?  the trip ID came across as 3371414 which is no identifier that i can find on our end.. wonder if stickeryou.com messed up the reporting

**Comment by robgpeak** [comment]
This is the wrong issue thread for your last post.  3371414 is our Site ID within the Link Share network...
<img width="402" alt="screen shot 2018-06-18 at 9 59 41 pm" src="https://user-images.githubusercontent.com/28393235/41571770-ccbfe08e-7342-11e8-90e9-9f7c5a1a742f.png">

**Comment by cgladue** [comment]
yea thanks, i deleted and reposted it

**Comment by robgpeak** [comment]
Back to this post, "Count" to Trip Count" is not showing up for me yet and I just tried an incognito window.

As for the other things, please watch https://screencast.com/t/b6D76VnrLdLi

**Comment by cgladue** [comment]
ok, instead of the dropdown that has every month listed can it just be a start and end date selection ?

**Comment by robgpeak** [comment]
Sure.  So in the top two sections (the current ones that are there), you can leave it as it is now, but in the third section below that I described in the screencast, it would have the date selectors.

**Comment by cgladue** [comment]
Yea. Ok

**Comment by cgladue** [comment]
No i didnt get it all done yet.

**Comment by cgladue** [comment]
@ChrisASearles i pulled down the latest changes and tried to run the app, but _ShoppingAssistant.cshtml is missing so it failes to run.

**Comment by cgladue** [comment]
@robgpeak how about that ?

**Comment by cgladue** [comment]
@robgpeak ok, how about now ?

**Comment by robgpeak** [comment]
👍

**Comment by robgpeak** [comment]
yeah, sorry about that.  Should have closed it.
