### ISSUE TITLE
Chance some verbiage on the home page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#17]
@cgladue Just got off the phone with Parx, and basically, anywhere on the site where it reads something like, "...Exchange (or transfer) your points for free hotel stays, food discounts and more..." that would like to to be "Exchange (or transfer your points for Parx Casino® Comp Dollars..."

So thinking out loud, if we are going to change something on the home page, I know at the moment, that is going to be globally throughout all the sites.  In that instance, we have two options.

1. Change the verbiage on the home page in the "Redeem" box to "Exchange your points for {Rewards Program Name}.  In this case, it would mean all the subdomains would follow suit, and xclub.complinks.co would them read, "Exchange your points for Parx Casino® Comp Dollars."
 And foxwoods.complinks.co would them read, "Exchange your points for Foxwoods Rewards."

2. We make individual home pages for all the properties which are then independently editable like the FAQ and How it works pages.

I think option 1 is the easiest for now.

**Comment by cgladue** [comment]
#1 - Done

**Comment by robgpeak** [comment]
Great.
