### ISSUE TITLE
remove all password restrictions!

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#170]
@cgladue @ChrisASearles We MUST remove password restrictions ALL TOGETHER.  and ASAP.

**Comment by cgladue** [comment]
its ALWAYS required 8 digits since day #1.  i dont see any requirements for numbers or symbols, i have reduced the minimum number to 1, altho i dont think thats a great idea, is that your desire ?

**Comment by robgpeak** [comment]
How about a minimum of 3 characters?  We are not housing any financial
data...

Thanks,

Rob

**Sent from my phone

**Comment by ChrisASearles** [comment]
@robgpeak I have to side with @cgladue on this one. some sense of basic password requirements is just good policy, and instills some level of trust in the organization on behalf of your users. personally, if I visit a site that doesn't enforce the most basic of password and data security policies, i never go back. if there's an issue with how we're reporting failed requirements to the user when they register or try to change their password then I'd recommend that's the problem to solve, not making the system less secure.

**Comment by robgpeak** [comment]
Guys, we can implement 256 character minimum for all I care, my issue/gripe/beef is the messaging or lack there of when someone does not enter enough letters, there is no notification that they did something wrong, it would only redirect back to signup page that is embedded in the page without any notification that something was wrong.  It happened three times yesterday.

We are NOT dealing with the brightest bulb in the box with this demographic.

If we tell them in advance that the password must be "(minimum of 8 characters required)", that would be fine.   Then if they do not put enough characters, we make a nice UI/UX to tell them.

<img width="411" alt="screen shot 2018-06-18 at 3 36 02 pm" src="https://user-images.githubusercontent.com/28393235/41557906-3116b62e-730d-11e8-8652-09324c5fa4a7.png">

**Comment by ChrisASearles** [comment]
Much better version of this has been committed.

**Comment by robgpeak** [comment]
Me likey much better versions :)
