### ISSUE TITLE
No data showing on https://shop.complinks.co/dashboard/admin/profitability

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#172]
@cgladue It seems like when I am looking at "All Partners" it is coming back with all $0's, but if I look at each individual partner, I see data.  This is happening from incognito, and I even logged in through FF for the very first time into my (account number 1), and it's the same thing there?

**Comment by cgladue** [comment]
ok im looking, strange what would of changed ...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Strange that it did not track it.  This is sort of like the orphan trips we spoke about a long time ago.  That was actually me (Account number 1) on this trip...


6/4/2018 9:55:02 PM | stickeryou.com |   |   | Trip ID 2233
-- | -- | -- | -- | --

So how would Morgan or a CS rep move that transaction to my account?

**Comment by cgladue** [comment]
what network is stickeryou in ?  ill have to give morgan or whooever a
button to update the user ID the trip belongs to, that comission was not
earned on trip ID 2233 tho




Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
LS

**Comment by cgladue** [comment]
{
        "etransaction_id": "A4A3AB457882B9DBAEBCDB95D966C47A",
        "advertiser_id": 41258,
        "sid": 3371414,
        "order_id": "32513854",
        "offer_id": "425060",
        "sku_number": "*not-available*",
        "sale_amount": 17.99,
        "quantity": 1,
        "commissions": 1.6191,
        "process_date": "Mon Jun 18 2018 13:40:23 GMT+0000 (UTC)",
        "transaction_date": "Mon Jun 04 2018 00:00:00 GMT+0000 (UTC)",
        "transaction_type": "batch",
        "product_name": "",
        "u1": "3371414",
        "currency": "USD",
        "is_event": "N"
    }
did you do anything different with this trip then usual ? the trip ID came across as 3371414 which is no identifier that i can find on our end.. wonder if stickeryou.com messed up the reporting

**Comment by robgpeak** [comment]
This was the email I received after the order...  What trip are you showing the order placed under?

Dear Rob Gallo,

Thank you for shopping at StickerYou.com! We are pleased to confirm your order received has been received on 6/4/2018 10:20:33 PM.

Please see below the details of your order # 32513854.

**Comment by cgladue** [comment]
they just reported it today... two weeks after the sale...

**Comment by cgladue** [comment]
saw your other post... i think its an error in stickeryou's reporting ...

**Comment by robgpeak** [comment]
I wouldn't doubt it.
