### ISSUE TITLE
Data table warning error

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#174]
@cgladue I am just going through the back end while I am logged in as a Partner Admin so I can see what Marc will see during our 1:00 call screen sharing session today, and I saw this error message when I click on the campaigns tab of an individual user.

<img width="1041" alt="screen shot 2018-06-21 at 11 34 33 am" src="https://user-images.githubusercontent.com/28393235/41729362-03bdfd7c-7547-11e8-8222-d0e7f4bcdc29.png">

**Comment by robgpeak** [comment]
Just so you known this only happens when I am logged in as Partner Admin.  It seems to work fine when I am logged in as Super Admin.

**Comment by cgladue** [comment]
i assume its because i restricted the campaign list to CS and Super admin only ... should this tab not show for Partners ?

**Comment by cgladue** [comment]
or are you OK with partners seeing that data

**Comment by robgpeak** [comment]
Yeah, I think the partners can see it.  Should not be an issue.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
try it when you get a chance

**Comment by robgpeak** [comment]
working
