### ISSUE TITLE
Shop.complink.co is bring up xclub site

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#175]
Please fix this ASAP

<img width="625" alt="screen shot 2018-06-21 at 8 27 26 pm" src="https://user-images.githubusercontent.com/28393235/41751840-77b72268-7591-11e8-9fca-f1655946306c.png">

**Comment by robgpeak** [comment]
@cgladue Actually all the subdomains are doing it...

<img width="604" alt="screen shot 2018-06-21 at 8 30 47 pm" src="https://user-images.githubusercontent.com/28393235/41751912-e3ff1cb4-7591-11e8-9e47-762d13efbf2d.png">

**Comment by cgladue** [comment]
its fixed as of 5 minutes ago or so ... i have no idea how a debug build got deployed, i deployed like i always do ...

**Comment by robgpeak** [comment]
Strange.
