### ISSUE TITLE
Trouble removing the double opt-in feature at Mailchimp

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#176]
@cgladue This NOT mission critical, but I need your help trying to understand how the email capture from our form, and then the syncing with Mailchimp works.  For some reason I have unchecked the double opt-in option on all the lists, but it is still sending the subscribe confirmation email, and I don't know why?
Supposedly they are single opt-in by default https://blog.mailchimp.com/why-single-opt-in-and-an-update-for-our-eu-customers/ but again, I think it might be a setting on our side that is not really using one of their forms, but we are just telling them, "Hey here's a new email address, and for whatever reason, it is not taking that as a subscribe...

<img width="405" alt="screen shot 2018-06-22 at 4 33 58 pm" src="https://user-images.githubusercontent.com/28393235/41798198-c6cf71f8-763a-11e8-9c15-5c944cc7e92f.png">

**Comment by cgladue** [comment]
When is it sending the email?   When they register ?  And when they check the box ?  If its both times it could be when we update their profile?  That email comes from mailchimp directly.  So im confused too.  Ill take a look

**Comment by robgpeak** [comment]
Well look what I found... https://screencast.com/t/uvEBwYBwqh0y

Immediately when they register on our site they are getting the confirmation subscription email, and I would rather them get the welcome email instead.  Also, if they never click subscribe, their email address never shows up in mailchimp.  Or at least not in a format that we can send them a reminder...  Anyway, you'll see what I mean in the screencast

**Comment by cgladue** [comment]
i dont know, it looks like the way that is acting is as designed for mailchimp: https://mailchimp.com/help/about-your-contacts/ it seems like from all the articles i am reading that mailchimp will not market to them without them subscribing.  and if you cant market to them there is no reason for them to be visible in the list ...   :( intercom still cannot send emails ?

**Comment by robgpeak** [comment]
They are still having some issues with a couple of email providers on
delivery...

Thanks,

Rob

**Sent from my phone
