### ISSUE TITLE
Trouble uploading a new advertiser logo

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#177]
@cgladue please have a look at why this would be happening.  Adding @morganpeak so she is in the know.  The logo we want up there is at the bottom of this thread.

<img width="645" alt="screen shot 2018-06-26 at 7 35 20 pm" src="https://user-images.githubusercontent.com/28393235/41944851-0f787568-7978-11e8-8a29-706051d35aef.png">

![cherylscookies](https://user-images.githubusercontent.com/28393235/41944874-2b777368-7978-11e8-9d39-3b1f36fbb6ef.jpg)

**Comment by robgpeak** [comment]
@cgladue any feedback in this?

**Comment by cgladue** [comment]
its because Impact Radius supplies the images we dont upload them usually, so its a one off case where there was an upload for an IR advertiser, why did you upload the image ? the IR image didnt show ?

**Comment by cgladue** [comment]
the image that came across the API works, any reason to upload a new image ?

https://member.impactradius.com/display-logo-via-campaign/5365.gif

**Comment by robgpeak** [comment]
The affilaite manager told me the image we were using was old.  The new
logo on is up on the IR site, and I pulled it down and uploaded it. You can
find it here...
https://app.impact.com/secure/mediapartner/ads/searchAdsDirectoryMP.ihtml?ecid=bV3NJhw0cQKccWrUjdsoZ2lCcjCexl3j

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
heh, nice of them to have the advertiser update their images ... im working a workaround now... ready in a few mins

**Comment by cgladue** [comment]
@robgpeak updated  @morganpeak nothing for you guys to do differently, i am handling it on my side.
