### ISSUE TITLE
Relationship change in IR not working as expected

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#178]
@cgladue I just looked and saw:
<img width="1002" alt="screen shot 2018-07-02 at 9 44 43 am" src="https://user-images.githubusercontent.com/28393235/42167622-9416532c-7ddc-11e8-9af1-d1fee898921d.png">

which is good in the sense that it automatically picked up that the relationship changed.  Then I saw this:
<img width="999" alt="screen shot 2018-07-02 at 9 44 54 am" src="https://user-images.githubusercontent.com/28393235/42167674-b48daaec-7ddc-11e8-8269-1d317ba393bd.png">

which shows it has moved to notjoined.  Again that's good, but then I saw it still live on the front end:
<img width="883" alt="screen shot 2018-07-02 at 9 45 14 am" src="https://user-images.githubusercontent.com/28393235/42167705-d01c33dc-7ddc-11e8-890c-4c0461c77046.png">

**Comment by cgladue** [comment]
hmmm, ok i think the criteria for appearing on the site is Status = active, i assume it should be status = active AND relationship = "joined" right ?  if either of those are not true then it would be removed from the site ?

**Comment by robgpeak** [comment]
Yeah I suppose that would stand to reason.

**Comment by cgladue** [comment]
unless you would prefer it to automaticaly set the status to inactive when the relationship goes from joined to notjoined ?

**Comment by robgpeak** [comment]
let me think about the reasoning. Originally it was
​ that an advertiser could have been​
notjoined and active just to show
​ them​
in a demo of who we had as advertisers potentially.
​N​
ow that we are live if we are notjoined with an
​a
dvertiser they should not show up.
​  Would there be a need to have an advertiser who is not joined to still
show up on the site?  Maybe for demonstration purposes on a particular
subdomain (like shop).

So yes, let's automatically set a notjoined to inactive, but then in an
instance described above, if the need arises I can set it to active and
also to the excluded advertisers list in the live subdomains.​

**Comment by cgladue** [comment]
ok

**Comment by cgladue** [comment]
@robgpeak can you check this out on test.complinks.co and make sure its working as you expect then i will deploy to live site.

**Comment by robgpeak** [comment]
I'm not exactly sure what I am looking for on test.complinks.co?  I just looked in the activity feed for a relationship change from joined to notjoined, but there weren't any in there.

**Comment by cgladue** [comment]
it was the advertisers that were actie but not joined, like discount tire
direct ...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
so seemingly it is working as desired.  I just filtered by Active, and then sorted by status, and the 4 Notjoined are NOT showing up on the front end of test.complinks.co, and that is the desired result.

Nice!

<img width="1043" alt="screen shot 2018-07-16 at 9 52 48 pm" src="https://user-images.githubusercontent.com/28393235/42792303-a08cf068-8942-11e8-8924-cf0e3eeed964.png">
