### ISSUE TITLE
Add "Current Partner" dropdown functionality to https://shop.complinks.co/dashboard/partner/ page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#179]
@cgladue when I look at the page https://shop.complinks.co/dashboard/partner/ I would like to see the "Current Partner" dropdown menu (logged in as Super Admin of course), whereby I can see "All" subdomains collectively, and then be able to choose individual sub domains to see just their stats.

**Comment by cgladue** [comment]
@robgpeak can you take a look logged in as a partner and also as super admin and make sure it behaves as you want ?

**Comment by robgpeak** [comment]
exactly as expected.  Thanks.
