### ISSUE TITLE
Allowing subdomains to display or not display certain advertisers

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#18]
Something else to consider, but what happens when a particular casino wants to display (or not display) and particular advertiser?  We will need a way to have advertisers, true or false (in the Active) column of the advertisers list, but specific to individual casinos and their needs/preferences.  I put this in as a separate issue now so you can think about it.

I would think that in the "Action" dropdown for each partner on the https://shop.complinks.co/admindashboard/partners page, there would be an option for "View Advertisers" and in there it would be the full list of "Joined", but then we can change the "Active" to True or False for each individual sub-domain.

They would of course all initially default to the Active True for all the subdomains, AND if any new ones are added to shop.complinks.co and become Active True, they would also automatically be included on all the other subdomains (as it happens now), but again, can be controlled independently by us manually after the fact.

**Comment by cgladue** [comment]
This would be controlled in the backend of Retail Benefits it sounds like, so if they gave us a special Token to be able to do it via interface, but i think it can be closed now with that in mind.
