### ISSUE TITLE
Seeing different transaction dates on seemingly the same transactions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#180]
@cgladue Look at these two pages, they seem to be referencing the same transactions, but they are showing two different sets of dates?
<img width="1087" alt="screen shot 2018-07-02 at 2 10 59 pm" src="https://user-images.githubusercontent.com/28393235/42179395-d29b6bda-7e01-11e8-98c1-b2de5e264068.png">
<img width="1033" alt="screen shot 2018-07-02 at 2 11 25 pm" src="https://user-images.githubusercontent.com/28393235/42179408-dd575804-7e01-11e8-9c91-120b38a1c1a2.png">

**Comment by cgladue** [comment]
the one under /purchases is probbally the date of the actual purchase, the one on profitability is the date of it being reported to us

**Comment by robgpeak** [comment]
ok
