### ISSUE TITLE
Creating a new Account Status

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#181]
@cgladue Please see if you can create a new Account Status:
<img width="549" alt="screen shot 2018-07-02 at 2 20 25 pm" src="https://user-images.githubusercontent.com/28393235/42179679-d76df23a-7e02-11e8-9676-cb1690139fcf.png">

on someone's profile page that we can mark as Test Account whereby none their statistics appear in any reports.

I am in the midst of producing the reports manually for Parx for the last two months, and each time I need to put a report together, I am having to manually remove all the accounts and the transactions of my account, yours, Morgan's, Chris' Derek's etc. and I am trying to think of an elegant way to do it.  

My thought was if we can change the status of all the accounts we know as test accounts and then not include that data in the reports that we generate, this would be then showing the true numbers of New Customers, and real shopping trips from their customers.  Do you think that would work or would it cause some other issues you might know of?

**Comment by cgladue** [comment]
@robgpeak 

![image](https://user-images.githubusercontent.com/7914133/42299518-9c35cf98-7fd9-11e8-98ca-e7904fcc0b91.png)

Check it out.

**Comment by robgpeak** [comment]
👍
