### ISSUE TITLE
Adding date selectors and standardizing the naming convention of the reports

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#182]
@cgladue As I mentioned, I was just producing the reports for Parx for the last three months.  Even though they can log into retrieve the data, and I spoke to them on the phone about it, they still asked if I could produce the reports and send them to them each month.  I know other operators are going to want the same thing.

That said I want to see if you can do a couple of things for me.   

1. The first one is #181 

2. The same way you added the date selector to the "Advertiser View Totals", please add the same functionality to https://xclub.complinks.co/dashboard/partner/users so I can select the date range, and then when I choose to download the CSV, it will just include the results within that date range.

3. The same as above for https://xclub.complinks.co/dashboard/partner/purchases

4. Same for https://xclub.complinks.co/dashboard/partner/transfers  (I know there is no real data in there yet, but there will be eventually.)

5. Lastly the naming convention of the csv reports that are generated.  Can they be:
"Rewards_Everywhere_Enrolled_Users_060118_063018.csv" (where the numbers are the start and end dates of the data selected.  If it has to be 06012018_06302018 that's fine too, but I prefer mmddyy.)
"Rewards_Everywhere_User_Purchase_Data_060118_063018.csv"
"Rewards_Everywhere_User_Redemptions_060118_063018.csv"
"Rewards_Everywhere_Reconciliation_Report_060118_063018.csv" 
"Rewards_Everywhere_Advertiser_View_Totals_060118_063018.csv"

These last two already have the date selector on them https://xclub.complinks.co/dashboard/partner/reconcile and https://xclub.complinks.co/dashboard/partner/ respectively so that's why they were not in the list of pages that need the date selector added.

**Comment by cgladue** [comment]
so on "Enrolled Users" you want the date range selector to narrow down the list to a range of when they signed up ?

**Comment by cgladue** [comment]
#1 Complete

**Comment by cgladue** [comment]
Item 2 Complete

**Comment by cgladue** [comment]
Item 3 Complete

**Comment by robgpeak** [comment]
Awesome!
