### ISSUE TITLE
Setting up links to Amazon

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#183]
@cgladue We signed up for an account with Amazon as an affiliate again, and in order to first even qualify as an affiliate, we have to send at least three sales to them through our affiliate link.

Here is the affiliate link, `https://www.amazon.com/gp/css/homepage.html/ref=as_li_ss_tl?ie=UTF8&linkCode=ll2&tag=complinks0a-20&linkId=27fbd58a379f6816b251ed2d4ec934ec`

I was thinking about sending out a message to some of our users to see if we can get a couple of people to make purchases, but I don't know how we can track individual shopping trips from unique users in our system.

I thought I recall you saying you had an associates account with Amazon so you were able to see their back end system...?  If not, you can log into the CompLinks account I just set up at email: robg@complinks.co and I will send you a text in 5 minutes with the password so you can poke around and see what you can do.

**Comment by cgladue** [comment]
Is there a contact at amazon to talk to about adding a unique user tracking variable to that affiliate URL ?  and are they OK with our business model ?

**Comment by robgpeak** [comment]
I spoke with a customer service rep this morning on the phone, but I am not sure if they have a technical support call in number.  I will look.  As for our business model, she said we will have to "make our case" to them via email, but we can't even do that until we drive at least three sale. (So I am sure they can then say, "Oh sorry we don't want any more incentive sites"  LOL.

I will try to convince them to allow us to do what ebates is doing.  I will send you the text with the pw shortly.

**Comment by robgpeak** [comment]
Actually, they seem to be having a problem logging into the associates page at the moment

<img width="921" alt="screen shot 2018-07-16 at 5 06 21 pm" src="https://user-images.githubusercontent.com/28393235/42783508-4b227436-891a-11e8-8e37-18fff9af7795.png">

**Comment by cgladue** [comment]
probbally related to prime day



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
seems like the typical use of their affiliate links are for a single affiliate to refer people and get a percentage, not to then divide up that comission to a 3rd party... i have been looking and i see amazon lets you create 100 links and you can request more, but that would only work for the first 100 users lol so thats not something thats viable... i wil continue to google this tonight but i dont see anything about passing the trip ID or the user account number or any custom data to amazon and then get that back in a report like the other networks do ...

**Comment by cgladue** [comment]
@robgpeak i emailed amazon about this, i dont see any way to add this into our program currently as i undersand it.

**Comment by robgpeak** [comment]
Yeah, unfortunately we are going to have to throw in the towel on this for now.
