### ISSUE TITLE
Advertiser page not loading on back end

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#185]
@cgladue I keep getting the below error when i try to access the advertiser page on the backend
![screen shot 2018-07-27 at 7 45 33 am](https://user-images.githubusercontent.com/28446563/43319047-4c44a00a-9171-11e8-8095-8a06689cc3cc.png)

**Comment by cgladue** [comment]
checking into this

**Comment by cgladue** [comment]
@morganpeak should be good now.
