### ISSUE TITLE
Can't get to the all stores page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#187]
@ChrisASearles and @cgladue  I am trying to get to the all stores page but it does not show up.  Please resolve ASAP.

**Comment by ChrisASearles** [comment]
@cgladue did any of those routes change? looks like it's reading the QS param I was using to send the sort order as a store ID on the detail route.

**Comment by cgladue** [comment]
I did add a route for /stores/{id}. What path are you using ?   The same structure ?

**Comment by ChrisASearles** [comment]
That route was /stores/all

**Comment by cgladue** [comment]
this has been resolved.



Chad Gladue
*DevNull Technology, LLC*
