### ISSUE TITLE
adding a link in the footer

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#188]
@cgladue I wanted to see if you could add a link to https://complinks.co if someone click on the image "powered by CompLinks" in the footer of the site.

While you're in the footer, can you also please add a link to "Promotions" between How It Works and Shopping Assistant.

<img width="618" alt="screen shot 2018-08-20 at 3 14 33 pm" src="https://user-images.githubusercontent.com/28393235/44361428-cf4adf00-a48b-11e8-9432-f5b5b0992826.png">

**Comment by cgladue** [comment]
sure

Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Hi Chad, what is the status on this?

**Comment by cgladue** [comment]
@robgpeak sorry i thought i published the changes guess i did not, take a look
