### ISSUE TITLE
Link to start a trip from an email

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#189]
When sending users emails promoting a deal that a certain store is having, I want to be able to say “Click *here* to activate a trip at Walmart.com” for example but whenever I input the link from the Shop Now button for that site from Xclub.complinks.co it just takes me to the index page on our site for that brand and doesn’t start a trip for that customer on Walmart. How can I fix this or make this happen?

**Comment by cgladue** [comment]
ok so you want a link that, when clicked, takes the user to the trip start page and automatically starts the trip at the specific store ?  is that correct ?

**Comment by robgpeak** [comment]
@cgladue is this something that will take a long time to do? If so that's okay, we just needed to know because we want to send out an email ASAP, and at the very least we will send them the link to the store and tell them to click the shop now button.

**Comment by cgladue** [comment]
@robgpeak no it wont take a long time working on it now

**Comment by robgpeak** [comment]
Do you behave an ETA Chad?

**Comment by cgladue** [comment]
tonight

**Comment by robgpeak** [comment]
Ok

**Comment by cgladue** [comment]
ok here you go @morganpeak @robgpeak 

how is this:  so the URL would be this:    https://xclub.complinks.co/stores/shopnow/7105

the number is the advertiser ID you can click intot he store page for that advertiser and see the number in the address bar and just replace it in the link above

**Comment by robgpeak** [comment]
Thanks Chad
