### ISSUE TITLE
not recording the time on a transaction

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#190]
@cgladue I just credited someone account with points, and the time was not recorded...
<img width="431" alt="screen shot 2018-08-30 at 7 27 30 pm" src="https://user-images.githubusercontent.com/28393235/44884713-eb6c2e80-ac8a-11e8-816d-a6ba97ef3812.png">

**Comment by cgladue** [comment]
@robgpeak on it

**Comment by cgladue** [comment]
@robgpeak did you mean to award them 25 points twice ?

**Comment by robgpeak** [comment]
Yeah, it was supposed to be 50... I made a mistake so did it twice.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak ohh, i see why ...

because it lets you choose the date for the transaction, but you dont enter the time in the box, would you prefer to have it ask for the date and time ?  if you choose any day other then today the time portion would be confusing ...

**Comment by robgpeak** [comment]
Just let the date and the time be automatic based on when someone actually
clicks save.  No need to select anything.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
so youll never want to post an adjustment for a particular date, it will
always show up for the current date and time and you will no longer be able
to back-date the adjustment.. thats Ok ?


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
While there could be a need for that, I can't see it at the moment.
Meanibg, even if I was credits by someone now (making an adjustment) to
make up for a past transaction, I would still want the date and time to
show the time that the adjust was actually made.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak ok, it should work as you asked now...

**Comment by robgpeak** [comment]
👍
