### ISSUE TITLE
How does the reconciliation report work

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#191]
@cgladue how does the https://xclub.complinks.co/dashboard/partner/reconcile work.  If you plug in last month's start and end dates, there is one transaction where we owe Parx $10, but how to I change the amount paid field?

**Comment by cgladue** [comment]
The partner Reconcilliation report dosnt have a place to enter a payment, you would use the accounting reconcilliation report here: https://xclub.complinks.co/dashboard/accounting/reconcile

then click "New Payment" enter the date of the payment, the partner the payment is to, the amount and save 

![image](https://user-images.githubusercontent.com/7914133/45102972-d5cc8e00-b0fc-11e8-942d-f07d02a5a93e.png)


![image](https://user-images.githubusercontent.com/7914133/45102989-de24c900-b0fc-11e8-8563-4dac0fb14c28.png)

**Comment by robgpeak** [comment]
Can I save a date in the  past?  I just tried but received an error message.  I was going to save it on the xclub reconciliation report for 8/31/18 so it all showed up in the report for last month...

<img width="1082" alt="screen shot 2018-09-05 at 11 56 53 am" src="https://user-images.githubusercontent.com/28393235/45105681-c8b29d80-b102-11e8-9aed-c4ab395bd25b.png">
