### ISSUE TITLE
Adding Canada as a separate group of affiliates

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#192]
@cgladue A company in Montreal, Playground Poker, inquired about having Rewards Everywhere for their property, but it will take some rejiggering to accommodate them and I wanted to talk with you about it first.  Meaning, for some of the advertiser's we would have to use different domains to send the traffic to like their .ca addresses.

Anyway, I just think it would be worth a conversation before I speak with them this afternoon.  Do you have some time this morning to talk?

**Comment by cgladue** [comment]
i will be to work around 10:30 i can call around then ?

**Comment by robgpeak** [comment]
Ok

**Comment by robgpeak** [comment]
I think it might have to be a completely different build from what we currently have.  I was just looking at ebates.ca, and everything is different.  Let me email cj linkshare and IR and see if we could do it easily.  If not, we may have to pass and tell playground we can't do it at the moment.

**Comment by cgladue** [comment]
we could just duplicate the code on the site, and the Database schema and maintain them as seperate databases ... if thats all it is that shoudnt be too bad... as a first thought

**Comment by robgpeak** [comment]
I am on hold with CJ now.  I wanted to see if we could manage it under the same account, but just a different "profile" or something like that.
