### ISSUE TITLE
missing transaction

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#194]
Hi @cgladue please have a look into a purchase that was made by Barbara Manzo on 9/10/18 from Vistapirnt with the order number 5JB5H-Z4A96-0E0.  It is not showing up and before I reach out to Vistprint, I just wanted to check with you first.
[Vistaprint.pdf](https://github.com/robgpeak/CompLinks-xclub/files/2394738/Vistaprint.pdf)

**Comment by robgpeak** [comment]
Anything in this Chad?  Speaking of which, I remember discussing an orphan transaction section in the back end.  I know this might not be the same issue, but I was just curious if you ever built something for that?

**Comment by robgpeak** [comment]
@cgladue Anything on this thread?

**Comment by cgladue** [comment]
i see a comission on that date for that advertiser ... Trip #2870



```
<commission>
            <action-status>new</action-status>
            <action-type>advanced sale</action-type>
            <aid>11636757</aid>
            <commission-id>2349611848</commission-id>
            <country>US</country>
            <event-date>2018-09-10T17:26:46-0700</event-date>
            <locking-date>2018-11-09</locking-date>
            <order-id>544PH-Z4A25-3C1</order-id>
            <original>true</original>
            <original-action-id>2041172664</original-action-id>
            <posting-date>2018-09-10T18:30:11-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>387606</action-tracker-id>
            <action-tracker-name>Item Sale (2016) </action-tracker-name>
            <cid>769194</cid>
            <advertiser-name>Vistaprint, USA</advertiser-name>
            <commission-amount>2.30</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>2870</sid>
            <sale-amount>38.39</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
```

i think i may have fudged it up when i was fixing the orphaned comission from before ... i had a feeling that i pasted on the wrong row, but it didnt look wrong so i thougtht it was just me ... but it must have been her that i overwrote .. shes back the sale should be there now for her correctly, sorry :'(

**Comment by robgpeak** [comment]
Actually, that was my order order on the same day coincidentally for business cards.  Her's was a different order number which you can see in the pdf in the original post on this thread.  I've sent an inquiry to Vistaprint through CJ, but I just wanted to see if it might have been something you saw on your side.

So just so you know, it was nothing you fudged up on your side.

**Comment by cgladue** [comment]
ok, i changed it back to you ... thats the only transaction from vistaprint that i see, so the problem does not appear to be on our side.

**Comment by cgladue** [comment]
sometimes the order numbers dont match so i assumed that is what it was this time.. so weird that the two of you had orders the same day  lol figures
