### ISSUE TITLE
points issued fields are blank

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#195]
@cgladue for some reason the points issued fields are blank on the page. https://shop.complinks.co/dashboard/admin/profitability

**Comment by robgpeak** [comment]
@cgladue I did not hear back from you on this.  Is this normal?

**Comment by cgladue** [comment]
i see values in that field .. looks like only a single purchase from home depot ?  

![image](https://user-images.githubusercontent.com/7914133/46051343-eb831100-c106-11e8-9b64-4de9ccbe79bc.png)

**Comment by robgpeak** [comment]
please change the partner to All Partners and see

**Comment by cgladue** [comment]
ok i see it... i have corrected it, should be good from now on.

**Comment by robgpeak** [comment]
Cool
