### ISSUE TITLE
rounding to two decimal places

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#196]
@cgladue could you please have all insistences in the back end that show more than two decimal places round to the nearest decimal in the hundredths column.  As I look to show the back end to some people at G2E, it just looks a little strange.
<img width="1015" alt="screen shot 2018-09-25 at 7 13 34 pm" src="https://user-images.githubusercontent.com/28393235/46048448-67755d00-c0f7-11e8-8f51-0150bb683ee9.png">

**Comment by cgladue** [comment]
Are we looking at the same page ?   i dont see any that are not 2 digits ?  
![image](https://user-images.githubusercontent.com/7914133/46051439-80860a00-c107-11e8-98c8-c163a38100f5.png)

**Comment by robgpeak** [comment]
I am on https://shop.complinks.co/dashboard/users sorted from highest to lowest of points earned.

**Comment by cgladue** [comment]
ok got it

**Comment by cgladue** [comment]
i think i went through and changed these where ever they may appear.

**Comment by robgpeak** [comment]
Looks better, but is there an easy way to NOT show any decimal points at all unless it is needed.  Meanibg, if someone has 100 points or 0 points, it would just show 100 or 0.  Not 100.00 or 0.00.

**Comment by cgladue** [comment]
no, because its either an integer or a decimal .. cant mix the two

**Comment by robgpeak** [comment]
It used to say 100 points for some, and other people might have had a
number that included decimals...?

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea they used to be strings (text) ... after i sent the last message i thought of a way it might work, take a look now.

**Comment by cgladue** [comment]
you may need to SHIFT-RELOAD to force the new javascript to be downloaded

**Comment by robgpeak** [comment]
Very cool.  Thanks.
