### ISSUE TITLE
Points Earned in enrolled users data is missing

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#198]
@cgladue when I went to the URL https://xclub.complinks.co/dashboard/partner/users to get the new players that enrolled for xclub last month, I was met by this image...
<img width="818" alt="screen shot 2018-10-03 at 1 22 40 pm" src="https://user-images.githubusercontent.com/28393235/46427851-6ef8bf80-c710-11e8-927c-4451a350c1d9.png">

Then when I compared the results of the data I received in the csv, it was different from the previous months...

Previously it showed...
![screen shot 2018-10-03 at 1 26 43 pm](https://user-images.githubusercontent.com/28393235/46427916-9780b980-c710-11e8-90b3-d0a2ab8c0551.png)

Now it shows...
![screen shot 2018-10-03 at 1 28 03 pm](https://user-images.githubusercontent.com/28393235/46427954-b7b07880-c710-11e8-93c6-9d3148c0a79d.png)

**Comment by cgladue** [comment]
hmm, ok looks like its off by 1 column for some reason hold on...

**Comment by robgpeak** [comment]
strange.  I disabled it and it worked fine.  No error message and the download of the csv worked where I was able to see the data.  Then I re-enabled the extension and it still worked fine.  Meaning i did not get the error message, and I downloaded the csv with no issues
