### ISSUE TITLE
Large amount of "notjoined" in relationship changed tab

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#199]
@cgladue I went to go update the relationship changed section by activating and deactivating advertisers whose relationships have changed but in the last day there has been over 150 going from joined to not joined. Is there maybe something else going on in the back end that is causing them to be pulled this way all of the sudden?

**Comment by cgladue** [comment]
If you look in cj or ls are they nothoined there also?  Or dothey match up?

**Comment by morganpeak** [comment]
Now it looks like they all reverted back and went to joined again. There must be a glitch in their system because I remember this happening before

**Comment by cgladue** [comment]
i would assume so, because it seems that it is cming in the API that way
