### ISSUE TITLE
Replace “$” with "$1" globally

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#20]
Put the number “$1” in pace of the "$" by itself in all the shopping boxes.  (They are trying to say their people are stupid... Actually, they are not trying to say it, they are really saying it.  Every other program in the world says "Earn x points/$", but again, they would like it to read "Earn x points/$1 spent")

**Comment by cgladue** [comment]
god it looks like ass that way :(



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
It's not visible yet, but I don't doubt it...

**Comment by cgladue** [comment]
i mean it will look like ass :P  i dont even like seeing it when you type it once let alone seeing it 30 times on a page .. ill change after i got get groceries

**Comment by cgladue** [comment]
Done

**Comment by robgpeak** [comment]
It does look terrible, but it's what the customer wants...
