### ISSUE TITLE
Ticketmaster missing links

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#201]
Ticketmaster was marked as joined a few days ago from impact radius but the links still haven’t come in @cgladue

**Comment by robgpeak** [comment]
@cgladue nothing on this yet Chad?

**Comment by cgladue** [comment]
no, i restarted the service that pulls in links and it didnt pull them in,
so not sure what is happening there, i need to debug and can only do that
at home on my pc, so ill let you know tonight.


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Ok

**Comment by cgladue** [comment]
@robgpeak @morganpeak i have confirmed that there are no ads (links) in the API data sent to us from impact radius.  i went to the dashboard and tried to "View All Ads" and when i do that for ticketmaster i get a system error... but if i do it for any other advertiser then it works fine, the two might be related.

**Comment by cgladue** [comment]
and by dashboard i mean the Impact radius dashboard ... it says error logged and that they would investigate, but not sure if you know of a contact over there to follow-up with also?

**Comment by robgpeak** [comment]
@morganpeak please see if you can put the links in manually, and also follow up with impact radius support.

**Comment by morganpeak** [comment]
Okay will do

**Comment by robgpeak** [comment]
@cgladue Looking in the back end, Ticketmaster is marked as joined and active, but it is not showing up on the front end in either the search, or miscellaneous or Sports & Outdoor categories?

**Comment by robgpeak** [comment]
but I put the main Advertisement Link in there. That should be enough.
There's plenty of other advertisers who don't have any links other than the
main Advertiser link

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok, yea if you did that then it should let me see

**Comment by cgladue** [comment]
@robgpeak @morganpeak ok it should be visible now, the issue was there was 0 links, the site dosnt show advertisers with 0 links, so now it will show them if there are links OR there is something in the main link field

**Comment by morganpeak** [comment]
Thank you chad!
