### ISSUE TITLE
attributing Trip Points Bonus (%) campaign to total trip

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#202]
@cgladue On account 100086 shopping trip ID# 3349 10/31/18 to walmart I made two purchases, and it seemingly only gave me the bonus for one of the items and not all of the items I purchased from that trip.  Please see if you can look into that and find a solution to cover the whole trip.

**Comment by cgladue** [comment]
hmm, ok i think i know why it did that, and should be able to rectify

**Comment by robgpeak** [comment]
@cgladue any progress on rectifying this and #203?  I am eager to get your feedback on #204, as I think that will be a good economic driver, and also help in the pitching of the platform to new prospective casino customers.

**Comment by cgladue** [comment]
trying to think of an elegant way to handle any number of line items for a
single order for the bonus, now it only bonus's the first item it finds
then marks the bonus as awarded and moves on, have to record some way to
make sure not to award the bonus every 60 minutes when it re-runs the
process over and over again.

Perhaps i will take a break from that and look at the survey to clear my
mind


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
So there is no way to tie the bonus to a shopping trip ID itself, this way,
any of the points that are awarded as a result of the bonus for a shopping
ID would be augmented if the amount for that ID changes in the future, as
it did in this case...?

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea thats an option, ill have to think about the best way to do it... but i
think its possible, spnding the whole day working on this


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Maybe you should clear your mind by looking at the survey thing instead.
For now we can always make the adjustment manual if the % bonus only
credits the first item purchased from a shopping trip.

The surveys should hopefully generate more revenue.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak i think this has been corrected now...
