### ISSUE TITLE
improving the look and functionality of data tables in mobile 

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#206]
@cgladue When you look at **any and all** of the data tables of points, transactions and such in the my account section on your phone, the data shows up in separate boxes for each record, and it looks pretty bad.

If you look at the **Table Pagination** section at the bottom right of this page http://keenthemes.com/preview/metronic/theme/admin_1/table_bootstrap.html on your phone, you can see the individual rows of the records in the table, and you can scroll left and right to see all the columns. This is what I would like to emulate.

I am making a video of the UI/UX on mobile for Draft Kings and Fan Duel, and this really needs to look better than it does.  Is this something you could do in short order?

**Comment by cgladue** [comment]
um no the whole functinality is to not scroll left and right (that really
is bad Functionality.. its better to hide the columns and slim down the
elements when screen sizes change) if this has to be done it would mean
choosing a whole new data grid for all pages.


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Please have a look at https://youtu.be/Bf3QmMW1HKo

**Comment by cgladue** [comment]
you kill me with the amount of emphasis you put on mobile for enterprise
customers, i would bet its a edge case  ;)

maybe for end users i would agree with you, but i dont think any or few
enterprises use mobile devices to view this stuff, but the formatting on
the longer strings is a little messed up i will agree, it could be cleaned
up a little.

ill review this more after dinner


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
It wasn't really thought of from an Enterprise solution but more of aesthetics solution and a better UI/ux for actual end user customers.  That said, it also shows the enterprise customers that we carefully manage the UI/UX.  It just looks better. Thanks.
