### ISSUE TITLE
adding editable call out text

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#207]
@cgladue How hard would it be to have the call out text on the overlay of the home page hero image be editable in the back end?  So line 1 would be (currently) "Earn", line 2 would be "Casino Comps", etc.

Please have a look at this mock up and let me know.
![callout text](https://user-images.githubusercontent.com/28393235/48641145-cee8b400-e9a6-11e8-9247-c28c94ae073e.png)

**Comment by cgladue** [comment]
this shouldnt be too hard, i will do this after the other two monkey
wrenches you threw in the gears ;)


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
👍
