### ISSUE TITLE
Bonus "Game"

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#208]
make the game "functional" (but not production ready)

**Comment by cgladue** [comment]
@robgpeak  the game will now randomly choose between 4 prizes (5% bonus, 200 points, 15% bonus or 10 points) and add a comission Bonus record which when a comission is earned should credit that bonus tot he users point balance.

**Comment by robgpeak** [comment]
Coolio...

![screenshot_2018-12-10-18-54-33](https://user-images.githubusercontent.com/28393235/49769195-414e6a80-fcad-11e8-8a14-e1bb641fedeb.png)
