### ISSUE TITLE
Advertiser views not adding up

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#209]
@cgladue I am not sure what is happening with Walgreens (in particular) but we had a woman Julianna McKeever say that she has made trips to walgreens, made purchases, but has not been credited...

In looking at some trips on our side and reports on CJ some things are just not adding up.

CJ since 11/1/2018
<img width="1201" alt="screen shot 2018-12-13 at 5 06 08 pm" src="https://user-images.githubusercontent.com/28393235/49970753-59ff9000-fefa-11e8-8c9a-ad8850e21884.png">

-

Our data overall showing only two trips during that same time period (xclub) there were none showing for shop, yet I personally took two trips and made purchases...

<img width="866" alt="screen shot 2018-12-13 at 5 07 55 pm" src="https://user-images.githubusercontent.com/28393235/49970796-74396e00-fefa-11e8-90c8-b6c122c588c6.png">

--

Here is Julianna's trips for that same time period showing 5 different trips

<img width="904" alt="screen shot 2018-12-13 at 5 09 05 pm" src="https://user-images.githubusercontent.com/28393235/49971028-13f6fc00-fefb-11e8-8b4e-c8bd2ff6b121.png">

**Comment by cgladue** [comment]
ok i think i know what it is ....

originally the partner dashboard only showed the last 30 days (rolling) of data ... then you wanted a Advertiser view detail option at the very bottom and i added it but didnt restrict you from chooseing a starting date before the rolling 30 days ... its still using the same 30 days of data .. so what would you prefer i do to fix that issue ?  restrict the starting datepicker to only let you choose a date int he last 30 days ? or remove the 30 day restriction and let them run it for any date range ? (more work but doable)

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/50350010-a0ad4580-050b-11e9-891d-0d57785f8813.png)

**Comment by robgpeak** [comment]
What ever is easier and has the numbers add up correctly.
