### ISSUE TITLE
campaign activated and awarded

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#210]
@cgladue I wanted to see if we could change the campaign viewing functionality a bit.

First I wanted to see if we could add a column (field) in the campaign data table that shows "Total Activated" (put it just before Total Awarded.)

The idea is to see who has Activated a campaign.  This would mean they have clicked on the link that activates the campaign, but it might not have been awarded yet.

The other thing is, I would like to make the numbers in the cells clickable and would basically link  to a filtered list of those specific users who either activated the campaign, or have been awarded the campaign (depending on which column data was clicked on) and the list of those people should be  in the same format as  https://shop.complinks.co/dashboard/users
![total activated campaigns](https://user-images.githubusercontent.com/28393235/50694753-be4cd580-1008-11e9-8d60-53d955de364e.jpg)

**Comment by cgladue** [comment]
ok, i will work on this this weekend.


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Thanks.  As sort of a follow up on the same subject, I am thinking about sending the following message to users... (below) and I wanted to make sure I am setting up the campaign correctly and it would work as intended.  Meaning, it would give someone a 50% bonus on every shopping trip for the month...

Would this be correct?
<img width="945" alt="screen shot 2019-01-04 at 10 27 31 am" src="https://user-images.githubusercontent.com/28393235/50695718-7e3b2200-100b-11e9-8cd6-94c8a50e8d39.png">


-- email message--

Hi ​​,

As you know, our primary focus is to help you get the very most from your Xclub comp program by rewarding you for shopping online.  

To get 2019 off to a flying start, we have an exclusive offer for you.

Receive a 50% bonus on ALL the points you earn in January 2019.

You MUST click this link to activate this offer.
​
Happy New Year & Happy Shopping,

Morgan H.
CompLinks
xclub@complinks.co

PS. As an example, this means if you earn 1,000 points for the month, you'll receive an additional 500 points for free!

**Comment by cgladue** [comment]
i believe yes that is correct let me check to make sure


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
yes this will work the way its setup, i just have to make a small
adjustment to the service that awards the bonus on the backend its a
minot=r change and i already changed it just need to copy the code to the
server, would prefer to do in person tonight if you can wait till then ?


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
sure

>

**Comment by cgladue** [comment]
@robgpeak ok i think this should be ok to go now.

**Comment by robgpeak** [comment]
Meaning it's good to go in the sense of the bonuses working right?  Because I don't see the column of total activated...

**Comment by cgladue** [comment]
yea just the working of using the bonus more then once


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Ok

**Comment by cgladue** [comment]
@robgpeak the column has been added, wil make clickable next...

**Comment by cgladue** [comment]
@robgpeak ok should be clickable now...

**Comment by robgpeak** [comment]
Nice!  Thanks.
