### ISSUE TITLE
end user to see campaigns that have been activated and awarded

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#211]
@cgladue Since you are working on #210 this weekend, pelase give some thought as to how we can show the end user the campaigns that they have activated as well as the ones their been awarded.

Maybe it can be another menu item in these two menus, and put "Campaigns" between Rewards and Shopping Trips...

<img width="383" alt="screen shot 2019-01-04 at 11 17 07 am" src="https://user-images.githubusercontent.com/28393235/50698264-6f0ba280-1012-11e9-8903-987be618f3e4.png">
<img width="327" alt="screen shot 2019-01-04 at 11 16 57 am" src="https://user-images.githubusercontent.com/28393235/50698271-73d05680-1012-11e9-85c6-af86765db3f0.png">

**Comment by cgladue** [comment]
think its doable, working on it now, need a couple days.

**Comment by robgpeak** [comment]
@cgladue You put the "ready" label on this, and to be honest, I never really checked it and I closed the issue.  Is this working?  Can a user see the campaigns the've activated?  Even if they have not earned anything in the campaign, it would show that it's been activated...

**Comment by robgpeak** [comment]
@cgladue I wanted to put you bask on your radar.  The main reasoning is so the users can easily see / verify that they have "Activated" a campaign, and can see how much they stand to receive by completing the triggering event.

**Comment by cgladue** [comment]
@robgpeak hmm i dont think it was done when you closed it i forgot all about it .. i will look at it again and it may need @ChrisASearles to be involved too

**Comment by robgpeak** [comment]
Even if you can do it where the data shows up in someone's points history
section for now just to see it working programmatically, that would be
cool.
