### ISSUE TITLE
pending points transfer to xclub

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#212]
@cgladue @morganpeak Chad, please have a look at "pending" transactions from rewards everywhere points to Xclub.  https://shop.complinks.co/dashboard/users/view?id=100599 says they have been pending for a while, and she look correct.

While you're in there, please ensure no other accounts are doing the same thing.

**Comment by cgladue** [comment]
this is most likely something on Parx's side i will reach out to them,..


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@cgladue I take it you never heard back from Parx?

**Comment by cgladue** [comment]
@robgpeak i finally trackeddown the error and i am getting back an "Invalid Account" error from parx, so something happened to that guys account  he has 2 pending withdraws...account 100599

**Comment by cgladue** [comment]
@robgpeak someone should reach out to him have him unlink the account and re-link his new account again, maybe the account is deleted or frozen or something like that

**Comment by robgpeak** [comment]
Can you tell if it is happening in anyone else's account?

@morganpeak please read Chad's remedy and have her relink her account.

**Comment by morganpeak** [comment]
@robgpeak will do

**Comment by robgpeak** [comment]
Any update in this Chad?

**Comment by robgpeak** [comment]
Did she need to relink her Xclub account or get a completely new one?

**Comment by cgladue** [comment]
depends the status of the account, usually a patron cannot simply "get a new one".  a casino will not issue multiple accounts to the same patron.  If she tries to relink the account and it fails then she would need to see the casino to see whats up with it, if it links fine now then i can try to re-withdraw her points

**Comment by robgpeak** [comment]
@cgladue She said she unlinked, and relinked the account without the leading zeros, and Parx says the account number is correct.  Please see if you can push those transfers through.

**Comment by cgladue** [comment]
@robgpeak yep looks like it went through
