### ISSUE TITLE
Are transactions coming through?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#213]
@cgladue I have personally made several transactions (purchases) over the last week that are not showing up.  And it looks like noting has posted on https://shop.complinks.co/dashboard/admin/profitability in 6 days...

**Comment by cgladue** [comment]
ugh, you are right i thougt i had fixed that issue its started again and it
will post those comissions now .. and ill go back and see why it stopped
running ... it had been running without issue for weeks


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
it stopped at noon on the 18th, so 3.5 days


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
It looks like I was credited the 50%january bonus twice for the same transaction.
![screenshot_2019-01-22-09-48-08](https://user-images.githubusercontent.com/28393235/51543203-0a7e7f00-1e2b-11e9-98c9-c67784bc40fe.png)

**Comment by cgladue** [comment]
ok i am looking into it

**Comment by cgladue** [comment]
Can you call me rob

**Comment by robgpeak** [comment]
I guess I should not have closed this.  I still see the two different 50% bonuses in my account and you're still looking into it.

**Comment by cgladue** [comment]
yes i am still working through the cause


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@robgpeak 
Found a bug where i was adding back in the points you redeemed to your lifetime points earned making it higher then really was, i fixed that

**Comment by cgladue** [comment]
@robgpeak 
found a bug where if the user activated multiple times they would get the bonus for each activation, you had 2 activations so thats why you got it twice, i added code to only activate once and removed your extra bonus

**Comment by robgpeak** [comment]
@cgladue , can you please check to make sure all the transactions are coming through. It seem light with only three transactions so far for the month.

**Comment by cgladue** [comment]
the service is running ... and i look at the API data and its accurate...


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@robgpeak i went through CJ, IR, and LS and all the data in the APIs is recorded in the Database, seems that it really is just a light month so far ...

**Comment by robgpeak** [comment]
🤐
