### ISSUE TITLE
Available points and Lifetime points needs adjustment

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#215]
@cgladue I was just looking at my dashboard https://xclub.complinks.co/account/dashboard and I see my Available points and Lifetime points are the same value, but I had made a 1000 point transfer a long time ago.  Shouldn't that mean my Lifetime points would be 15,472.88 and my Available should be 14,472.88?

**Comment by robgpeak** [comment]
You fixed this correct @cgladue ?  Can I close the issue?

**Comment by cgladue** [comment]
@robgpeak if you are looking at your dashboard and it looks good now then yea, i believe it should be correct at this point
