### ISSUE TITLE
adding coupons

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#216]
@cgladue There seems to be an issue with the last click in adding a coupon code during checkout with CJ merchants, in particular Walgreen's.  As a result we need to add a "coupon feed" to the store's index page of our site.  I think you might be able to find information on doing so here. https://cjcommunity.force.com/s/article/Promotional-Link-Feed-4776821

Here is the email I just send to a customer based on the phone call I just had with a CJ rep.

OK, I just got off the phone with the Walgreen's people who manage the commissions from the sales (which ultimately turn into Rewards Everywhere points).

So the way it works is the commission is paid based on the last click.  Meaning, which ever publisher, (in this case us at CompLinks), is responsible for the very last click before the order is placed is who gets the credit for the commission and subsequent point issuance.

What this means is CompLinks needs to be your last click before checking out at Walgreen's.  For example, if you open up a retailmenot, ebates or honey tab (or even use their browser plug in to get a coupon before checking out on CompLinks, they consider that the last click, and thus we don't get the credit, and therefore cannot credit you.

Now we are in the process of getting ALL the available coupons up and available on our site so you don't need to leave our site and you can still get the $2.00 off for this, and the $1.00 off for that when they are available.  But in the mean time, if there is an item that you want which you know has a coupon and you get the coupon from another site, get the coupon code first, THEN click on the Shop Now button on xclub.complinks.co so you can have your cake and eat it too 😊

Thanks,

Rob

--

As far as the graphic look and UI/UX of finding coupon codes on our site, let's see what you can do programmatically on shop.complinks.co and then we can make it look pretty and act properly based on the user's experience.

**Comment by robgpeak** [comment]
The rep from cj sent me this...  Hi Rob,

Walgreens coupons through CJ are whatever they are running promotionally, often they are product or manufacturer specific. You can read about picking up these links here: https://cjcommunity.force.com/s/article/Grabbing-Links-4776636

**Comment by cgladue** [comment]
might need a call later on tonight to explain this more...

the links you give me from CJ never work, all of them just take me to the
dashboard.


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Any time you want to call let me know.

With the CJ links you need to be logged into Commission Junction

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea even when logged in it still takes me to the dashboard and not to any
article


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Are you trying from your phone or computer.  If I try from my computer it
comes up with the correct page, but if I go through my phone it brings me
to the dashboard.  Strange.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
using my PC


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Very strange.  Try this.  At the top right of the dashboard, click the "?" to go to the support center.  Then come back and click on the link in this thread and see what happens.

**Comment by robgpeak** [comment]
Any luck with that last suggestion?

**Comment by cgladue** [comment]
no still nothing, it does to the dashboard every time .. is there a title or something i can search for

**Comment by robgpeak** [comment]
So if you are in the support center, enter, "Grabbing-Links-4776636
<https://cjcommunity.force.com/s/article/Grabbing-Links-4776636>" in the
search bar.

Thanks,

Rob

**Comment by robgpeak** [comment]
@cgladue Did that work?

**Comment by cgladue** [comment]
@robgpeak it did, but that is instructions on doing it manually ... and we do this already programatically in the API i have to talk with you tonight ill call you on the way home ... i still dont understand what the problem is, other then users use a coupon at checkout from another vendor and that take the last click away from us ... but thats the same thing that ebates expieriences too if i used retailmenot or something to get a code ... i believe we already have all coupon codes saved and displayed on the site under links the users would just need to make sure they used that instead of the main store link or the extension would need to display then to the user at checkout so they could re-start a trip using the coupon code link .. but we can discuss tonight
