### ISSUE TITLE
double entry in reconciliation report

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#217]
@cgladue please have a look at the attached reconciliation  report from last month.  It looks like your and Julianna's were processed twice?
[Rewards_Everywhere_Reconciliation_Report_01012019_01312019.xlsx](https://github.com/robgpeak/CompLinks-xclub/files/2841711/Rewards_Everywhere_Reconciliation_Report_01012019_01312019.xlsx)

**Comment by cgladue** [comment]
@robgpeak this was an artifact of the testing of resending transfers (which we didnt do before) .. i believe there may have been one occurance of double transmitting the point withdraw before i got it correct.  but this should not happen again.
