### ISSUE TITLE
points syncing with Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#218]
@cgladue Please have a look at this customer William Dunn 
<img width="750" alt="screen shot 2019-02-07 at 12 34 36 pm" src="https://user-images.githubusercontent.com/28393235/52430922-29d90580-2ad5-11e9-99d4-b793b3c9a780.png">

https://xclub.complinks.co/dashboard/users/view/100997

and all of his points are "Available" in our back end, but when I look at Intercom, it's showing something different.  It may have happened just as you made the changes to sync that data???

<img width="770" alt="screen shot 2019-02-07 at 12 34 19 pm" src="https://user-images.githubusercontent.com/28393235/52430896-1d54ad00-2ad5-11e9-93ad-20c1c9d00b20.png">

https://app.intercom.io/a/apps/d8m2yyar/users/5b982b56a411f47986b59ecb/all-conversations

**Comment by cgladue** [comment]
ok ill check any event that can affect the balance and make sure its
updateing intercom

there must be a special circumstance that doesnt trigger an update to
intercom.


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Here's another person around the same time frame.

https://xclub.complinks.co/dashboard/users/view/101173
<img width="790" alt="screen shot 2019-02-07 at 12 40 36 pm" src="https://user-images.githubusercontent.com/28393235/52431191-bdaad180-2ad5-11e9-9e90-cb4811c4ec46.png">


https://app.intercom.io/a/apps/d8m2yyar/users/5be5e8eb3e2991402075454a/all-conversations

<img width="506" alt="screen shot 2019-02-07 at 12 40 49 pm" src="https://user-images.githubusercontent.com/28393235/52431216-ca2f2a00-2ad5-11e9-8ba8-b1fb83fceaed.png">

**Comment by cgladue** [comment]
ok, after i find out what caused them to be out of sync i can go through all customers and resync them

**Comment by cgladue** [comment]
it could be the campaign and bonus stuff doing it...

**Comment by cgladue** [comment]
@robgpeak i think it was related toa ll the bonusing you did, it never updated Intercom when it awarded the bonus points, i have gone through and added it to those cases and i created a URL you can visit to trigger a complete user re-sync the url is:      http://shop.complinks.co/home/updateIntercom that should go through the user database and resend the attributes for all users...   its running now.

**Comment by cgladue** [comment]
Should be all set now i resynced all users,  if you ever have a particular user issue again you can use this URL:  do small chunks because cloudflare will display a 524 error if the page stils waiting too long, so a coupole hundred at a time:  https://xclub.complinks.co/home/updateIntercom?partnerid=12&start=100001&end=100200  start and end are account number ranges

**Comment by robgpeak** [comment]
Ok great.  Thanks
