### ISSUE TITLE
icons in the back end dashboard disappeared 

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#219]
@cgladue Seems like all the icons in the menu disappeared...

<img width="549" alt="screen shot 2019-02-18 at 4 06 28 pm" src="https://user-images.githubusercontent.com/28393235/52976395-5cb5b000-3397-11e9-9dca-4388725d26cb.png">

**Comment by cgladue** [comment]
@robgpeak not sure what happened, but all set now
