### ISSUE TITLE
Change some wording on the home page Hero Image Call Out text area

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#22]
@cgladue On the unauthenticated hero image on the home page, there is the text that reads, "Earn Rewards
Everywhere
365Days A Year
When You Purchase Everyday Items From Our Merchant Partners"

Please change the last line to read, "When You Purchase Everyday Items From Online Retailers"

Reading the T&C's more closely with CJ and LS, we cannot really imply a "partnership" with the advertisers.

This would be global throughout all the subdomains.

**Comment by robgpeak** [comment]
@cgladue Please see if you can fix this one sooner rather than later

**Comment by cgladue** [comment]
All Set
