### ISSUE TITLE
creating a new subdomain

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#220]
@cgladue I wanted to see if you could create a new subdomain in cloudflare called "your-charity" and then add a new property called your-charity.complinks.co  Please let me know as soon as it's done.  I just happened to reach out to Susan G. Komen (one of the largest breast cancer charities in the US) yesterday, and they want to see a demo tomorrow, but I did not want to change all of "shop.complinks.co" to be non-casino looking.

**Comment by cgladue** [comment]
@robgpeak im not sure why the site isnt loading, i am getting an AngularJS error which is what chris and his guys insisted on using so i dont know how to troubleshoot that part of it ... from my end all the stuff is setup :(

**Comment by cgladue** [comment]
@ChrisASearles this is the error from adding a new subdomain ...  

![image](https://user-images.githubusercontent.com/7914133/53288191-be896780-3753-11e9-92a3-15e44f2d7e3c.png)

**Comment by cgladue** [comment]
@robgpeak @ChrisASearles 

on a hunch, i removed the "-" in the subdomain name and now everything works ... @ChrisASearles definatly a bug that should be fixed.

**Comment by cgladue** [comment]
@robgpeak https://yourcharity.complinks.co/ is working and ready for you to update

**Comment by robgpeak** [comment]
Thanks
