### ISSUE TITLE
changing the word 'points' to '% cash back'

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#221]
@cgladue I forgot if there was a way to change (globally) with word 'points' with '% cash back' in the property settings? 
<img width="1029" alt="screen shot 2019-02-25 at 5 42 34 pm" src="https://user-images.githubusercontent.com/28393235/53373885-c2201880-3924-11e9-9fdf-0c0b36b3f0e6.png">

**Comment by cgladue** [comment]
No not on the store page like where it would say 4 points/dollar ?  the only thing that's controllable would be the rewards that the property offers, you can make it say anything there...

**Comment by robgpeak** [comment]
Well we would have to figure out a way to make it where we could make is say '4% cash back/dollar' for the charity type of partner.  If you look at https://yourcharity.complinks.co/how-it-works you can see what I started reworking to get the idea.

**Comment by robgpeak** [comment]
Any thoughts on this @cgladue ?

**Comment by cgladue** [comment]
yea working on a way to do this

**Comment by cgladue** [comment]
So you want it to say "X% cash back/$1 spent" right ?

**Comment by robgpeak** [comment]
Yes

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak ok look for an update coming today that will do this.

**Comment by cgladue** [comment]
@robgpeak this should be complete ...

**Comment by robgpeak** [comment]
any way to make cash back two separate words?

**Comment by cgladue** [comment]
done


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
The word "Earn" is missing from the boxes at the bottom of the home page, and also from the deals and promotions section on the store under pages.
![Screenshot_2019-03-12-21-27-03](https://user-images.githubusercontent.com/28393235/54247067-e592b800-450d-11e9-9aa9-b97f55c6498f.png)

**Comment by cgladue** [comment]
frig, knew it wasnt going to be that easy LOL

**Comment by cgladue** [comment]
@robgpeak i really dont think it ever had "Earn" in those boxes at the bottom ... i added it but then the top had the word Earn twice ... which tells me it wasnt that way before..

**Comment by robgpeak** [comment]
huh.  strange I never noticed it before.  Ok Thanks
