### ISSUE TITLE
Missing the "claim this bonus" on wheel game

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#223]
@cgladue on the wheel game, there is no call to action to claim the bonus and start the trip...

<img width="611" alt="screen shot 2019-03-04 at 12 55 57 pm" src="https://user-images.githubusercontent.com/28393235/53752626-11160280-3e7d-11e9-92bb-ef558d8a5633.png">

**Comment by cgladue** [comment]
Was it there in the HTML file that was downloaded from 357am or whatever ?


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Not sure, I'll ask.

Thanks,

Rob

**Sent from my phone
