### ISSUE TITLE
subdomains not refreshing

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#225]
@cgladue In the past, if I went to any of the sub domains and made a change in the back end on the Property list edit screen, (change a logo, or color or bit of text), as soon as I went to the live site and did a refresh of the page, the change USED to show up.  It does not do that anymore.  The only way I can see my change is through incognito.  Is there way way to fix that?

**Comment by cgladue** [comment]
you could login to Cloudflare and purge the cache ... thats what is holding
onto the changes i am pretty sure.


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
ok
