### ISSUE TITLE
Orphan transactions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#226]
@cgladue Both of these transactions https://shop.complinks.co/dashboard/users/view/100105?tab=tab-purchases should be credited to my account # 100086

**Comment by robgpeak** [comment]
Don't know if you are working on this and that is why the stats for all the properties for this month are empty https://shop.complinks.co/dashboard/admin/profitability but I figured I would check with you first before creating another issue.

**Comment by cgladue** [comment]
@robgpeak stats should be showing correctly now, and ill associate those purchases in a minute

**Comment by cgladue** [comment]
@robgpeak i only see one there now and its from 2018, is that the one you are referring to ?

**Comment by robgpeak** [comment]
There was two in there, but it now moved to account 0.  Meaning, if you look at the most recent transaction in https://shop.complinks.co/dashboard/admin/profitability that is the one I was speaking of.  That was a purchase made by me on 100086

**Comment by cgladue** [comment]
@robgpeak ok i moved the ticket master one to 100086 .. was the one from 2018 yours too for that account ?

**Comment by robgpeak** [comment]
Yes

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak all set

**Comment by robgpeak** [comment]
@cgladue I marked this one closed because you mentioned it was all set, but I never looked to check, and when I just did now, the transaction for tickemtaster is not showing up in 100086?  It is still showing account 0, and when I look in the purchases for 100086 it's not there either.


<img width="1095" alt="Screen Shot 2019-03-14 at 10 36 01 AM" src="https://user-images.githubusercontent.com/28393235/54365596-846e0000-4645-11e9-80c0-060497e7f7b0.png">

**Comment by cgladue** [comment]
hmmm, i wonder if it got switched back ...

i swear i changed it hmmm


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@cgladue This ticketmaster transaction is still showing in the profitability reports as being credited to account "0" but it should be to 100086 so when I runs the reports at the end of the month, it shows up properly.

<img width="1115" alt="Screen Shot 2019-03-25 at 9 21 03 AM" src="https://user-images.githubusercontent.com/28393235/54923001-b3a32d80-4edf-11e9-8165-473ebb48860d.png">

**Comment by cgladue** [comment]
@robgpeak yea ive set it to your account twice now and it keeps getting recreated back to the unknown account (account 0) i am looking why it changes after i assign it ...
