### ISSUE TITLE
Integration schematic

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#227]
@cgladue Hey Chad,

I just had a call with 888 (online gaming and sports betting in regulated markets in the US), about integrating CompLink into their offering, and they asked me if we have a schematic of how the integration would look.  Do you have something like that which would explain in a visual format what it would look like and do?

**Comment by cgladue** [comment]
sure i can create something


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
Integration meaning Account linking and withdraws ?  just likt the casino properties ?

**Comment by robgpeak** [comment]
Yeah.  How the calls between our side and their side are made, what sort of
connections and protocols, how our data is housed...  shit like that.

**Comment by robgpeak** [comment]
@cgladue just wanted to put this back at the top of your inbox

**Comment by robgpeak** [comment]
Technically that would work, but do you think there is any sort of online technical schematic maker to make it look slick and professional with cooler diagrams?

**Comment by cgladue** [comment]
lol cooler diagrams...  um i will look around, but i am not unaccustomed to seeing drawings like this from software vendors   

give me a little bit to see, other then visio (which i dont have) ill see if i can find something.

**Comment by cgladue** [comment]
How about this one?
![Complinks Overview](https://user-images.githubusercontent.com/7914133/54477704-87512800-47e0-11e9-84cb-0aef5420b452.png)

**Comment by robgpeak** [comment]
much better :)

**Comment by robgpeak** [comment]
Can you just name the group of servers on the left as "Client's Loyalty Program Servers" or "Systems"

**Comment by cgladue** [comment]
![Complinks Overview](https://user-images.githubusercontent.com/7914133/54477831-e5323f80-47e1-11e9-93eb-7c3549644b02.png)

**Comment by robgpeak** [comment]
Thanks.
