### ISSUE TITLE
"Activated" in campaigns?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#228]
@cgladue What constitutes "Activating" a campaign?  Is it the act of clicking on the link in the first place, or then actually starting a shopping trip?

For example, if you look at the two images below, I just sent an email to customers about activating a campaign, and in Intercom it shows 6 people have clicked on it, but in our back end it only shows one "Activated" and that is me.  I DID start a shopping trip, so that's why I was thinking that might be the criteria. 

Please do me a favor and click on the link in the Earn Double Points email I sent a little while ago from Rewards Everywhere and see if it tracks you in our back end as another Activated campaign...

<img width="1039" alt="Screen Shot 2019-03-14 at 12 50 46 PM" src="https://user-images.githubusercontent.com/28393235/54376326-3531ca80-4659-11e9-91d1-a2d2d615a6ce.png">

<img width="1084" alt="Screen Shot 2019-03-14 at 12 51 01 PM" src="https://user-images.githubusercontent.com/28393235/54376344-3fec5f80-4659-11e9-85d7-a6a5db5657a7.png">

**Comment by cgladue** [comment]
@robgpeak "Activated" means that they clicked the link and a "ComissionBonus" record was written on our side to award them once they earn a comission, a trip is NOT required to count as an activation ...

from the database: 
![image](https://user-images.githubusercontent.com/7914133/54475340-75fb2200-47c6-11e9-8e2e-872df038be96.png)

most people activated on 3/14  and this campaign shows 10 people activated currently.

**Comment by robgpeak** [comment]
Why is there a discrepancy in the number of clicks we are showing and Intercom is showing?  Right now we show 10 and Intercom shows 28 clicks.

<img width="1271" alt="Screen Shot 2019-03-16 at 11 14 05 AM" src="https://user-images.githubusercontent.com/28393235/54477263-a77ee800-47dc-11e9-88e3-7f61e1b3a335.png">

**Comment by robgpeak** [comment]
@cgladue any idea why there is a difference in these numbers?  Now we are showing 13 and Intercom is showing 31.

**Comment by cgladue** [comment]
is it 31 unique people  in intercom or just 31 opens of the message ?


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
It's actually clicks

**Comment by robgpeak** [comment]
@cgladue So I just had a guy, one of our best customers and most avid users tell me that he clicked on the link in the email to activate the double points bonus campaign on 3/14/19 (which I can see he did in intercom), but it does NOT show up as activated on our back end...  His account number is 100224

He is apparently not the only one if we are seeing 35 users who "Clicked" on the link in the email, and only 16 activated the campaign.

<img width="905" alt="Screen Shot 2019-03-27 at 5 38 59 PM" src="https://user-images.githubusercontent.com/28393235/55114217-b789a800-50b7-11e9-9d55-ec69a4027600.png">

<img width="1026" alt="Screen Shot 2019-03-27 at 5 39 46 PM" src="https://user-images.githubusercontent.com/28393235/55114231-bf494c80-50b7-11e9-8dd3-895db832ee3b.png">
