### ISSUE TITLE
drilling into individual customer data

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#23]
@cgladue I think we should have all the account numbers link to the menu for each individual players back end.
I mocked something up below, and I am not sure it is the best way to go, but it is sort of the idea I am 
going for.  Actually, maybe for simplicity we just make the account number clickable and link to the 
person’s dashboard, so the customer service agent can see exactly what the customers is seeing. 

![uploads/0a7e2724-f9d2-4c93-942e-0867c35bfb88/Screen Shot 2018-02-28 at 12.21.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0a7e2724-f9d2-4c93-942e-0867c35bfb88%2FScreen+Shot+2018-02-28+at+12.21.20+PM.png)

**Comment by cgladue** [comment]
we cannot "See what they are seeing" since theres no way to login as that user ... but if you tell me what youd like to see on a screen i can put a screen together that shows the same data  (just wont be the exact same format)

**Comment by robgpeak** [comment]
I am not sure I understand why we can't see the same data they are seeing.  Meaning, at some point, somewhere in the database there is a differentiator between user 100086 and 100087 (and all the other individual users), so how is it that we cannot see that data in the same sort of format that they see it in.

**Comment by cgladue** [comment]
You can.  I just said you cannot log in as them and see exactly the same screen they see.   I could make a separate screen and show it to admins but it won’t be the same url.

**Comment by robgpeak** [comment]
So you mean if a CS rep clicked on a customers account number, it would pop
open a new tab, but show all the user's data that the user would see,
that's fine.

**Comment by cgladue** [comment]
Dosnt have to be a new tab, just wont be the same exact page url that the user is looking at...

so the CS rep wuld have access to only this page that shows users data ?  do you have a list of the fields you want them to see on that page ?

**Comment by robgpeak** [comment]
I don't mind what the URL is, or whether it's in a new tab, (although a new tab would be a better UX for the cs rep).

I want the cs rep (and Super User of course) to have access to ALL the data (fields) the customer sees.  Dashboard, Manage Account, Rewards, Shopping Trips, Points History.

**Comment by cgladue** [comment]
Is it your intention to have a third part handle the CSR Duties ?  just trying to understand your intentions

**Comment by robgpeak** [comment]
Not at the moment.  Right now we will be handling it all internally.  Having said that, I get where you're going.  So thinking about it, and Internal CSR should be able to see and edit anything that the customer can see and edit, but maybe an External CSR should only be able to see everything EXCEPT the Manage Account section, and if they needed to have something done with that section, they would have to escalate the issue to an Internal CSR or higher...

**Comment by cgladue** [comment]
For internal CSR functionality why wouldnt you just use the admin dashboard then ?  do you plan on hiring people that only do CSR related dutues other then you and morgan ?

**Comment by robgpeak** [comment]
I am talking about linking the account number from the admin dashboard to see that data for each user.  It is currently NOT visible, unless I'm missing something.  And yes we are planning on hiring people as CSR other than Morgan and I.

**Comment by cgladue** [comment]
i just need to know what data your referring to, because i think its almost all available,

balance history:
![image](https://user-images.githubusercontent.com/7914133/36947974-9d261748-1fa1-11e8-8dd1-a1efe8aa3a1d.png)

point balances and patron email/name/details:
![image](https://user-images.githubusercontent.com/7914133/36947979-a94beda4-1fa1-11e8-94ab-30f43e47e2c3.png)

So basically what you need is to be able to edit email address on the customer because as far as i can tell thats all thats not editable already by admins.  maybe a way to manually link a patron's xclub rewards card for them ?  would that be something the CSRs would do for the patron ?  but other then that i dont really see anything else that missing unless its me thats missing something ?

obviously ill transition it to the newer design so things are a lot more thoughtfully placed and acessible, but i think 99% is there already

**Comment by robgpeak** [comment]
I smell a screen cast coming... :)   https://screencast.com/t/slKQtwLOoF

**Comment by robgpeak** [comment]
@cgladue As a follow up to the screen cast, in a nutshell, I want to be able to see a holistic view of each individual customer on one screen.  All the shopping trips they've made, the purchases, what they purchased, how much they received in points, how many times they transferred points, how many points they transferred...  everything in one place.  This is critical to providing great customer service.

**Comment by cgladue** [comment]
Sure I get it already in the works.  Have no power tho today.

**Comment by robgpeak** [comment]
No power, that sucks.

**Comment by cgladue** [comment]
all set in new design

**Comment by robgpeak** [comment]
I love it!  Really awesome job.  I like the layout and functionality...
