### ISSUE TITLE
Drag and drop and delete (make inactive) store index boxes

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#231]
@cgladue remember in the past there used to be a feature that would allow me to make changes on the front end of the site when I was logged in as administrator. That's functionality is not there anymore correct?

The reason I was thinking that is because for demonstration purposes only to potential customers it would be cool to have that same functionality that you have in rearranging the advertisers in the featured categories list from one to 10 let's say we're you can drag and drop the logos in that section.

If it's possible I would like to see if you could set that up as a demo where by looking at the front end I could grab let say on the homepage Walmart index store and switch it with Home Depot just buy dragging and dropping. Again I think it'll be great for demonstration purposes as I'm starting to talk to more people about it so I can easily show them how they can rearrange and delete advertisers visually from the front end. Of course the delete function wouldn't really delete it would just mark them as inactive. So if someone pressed it and dragged it there would be a pop-up that would say delete but it would just Market is inactive

**Comment by cgladue** [comment]
i dont think i removed that its not there ?

**Comment by robgpeak** [comment]
I don't see it when I'm logged in do you?

As for the other part if my questions, is it possible to get that sort of
functionality?
