### ISSUE TITLE
Linking a campaign bonus to one specific shopping trip

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#232]
@cgladue I just looked in my points history and see that I had one order at walmart that was broken up into two separate transactions and in turn I received two different 100 bonuses, but should have only gotten one.  (account 100086)

<img width="891" alt="Screen Shot 2019-03-29 at 3 35 06 PM" src="https://user-images.githubusercontent.com/28393235/55258231-a6b47000-5238-11e9-9e3f-62bf5e000e31.png">

**Comment by cgladue** [comment]
ok, i will rectify


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@robgpeak i just fixed the issue, then deleted the data from our system and re-ran the comission process and it awarded the expected results.

**Comment by robgpeak** [comment]
Thanks
