### ISSUE TITLE
CrowdRise integration APIs

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#233]
@cgladue First have a look at https://www.crowdrise.com/americanheart and https://www.crowdrise.com/BGCA to get an idea of how their platform works.

Next take a look at https://drive.google.com/open?id=1Wyq-oJZwPGPxsH4r0heZRAiYDvQesvC- so you can see what I showed them.

Then see if you can put together a flow chart of how the integration would look based on what we talked about on the phone.

**Comment by robgpeak** [comment]
@cgladue Any progress on this?

**Comment by cgladue** [comment]
Yea almost done with it hoping for tomorrow sometime.

**Comment by cgladue** [comment]
ok so after looking at this i think the followign calls would be a good start:

1. API Call to log-in a user (and create account if they dont already have one)  single sign on from Crowdrise

2. Api Call to get a list of a users "Referral" links 

3. Api Call to let crowdrise query the status of the users shopping/point balance ?

4. Api call to notify crowdrise that a transfer has been initiated ?

Is the user starting the shopping for a cause on our site or theirs ?  if theirs then we would need a API call to notify us that they created a new cause so we can create the "Referral" Link

**Comment by robgpeak** [comment]
All the shopping trips would take place (initiate) on our site.  There are some additional legal hurdles in general as it relates to fundraising that need to be addressed first, and I am looking into them.  But thanks, I think this is a good start.

**Comment by cgladue** [comment]
the trips would be originated from our site, but would they need to create the donation page on the crowdrise side (which would then create a return to crowd rise a shopping "referral" link, that is our link that when used would start a trip and credit the original user ?

**Comment by robgpeak** [comment]
the way I am thinking about it is very similar to what we do with the
casinos. Meaning crowdrise would be telling us who the customer is through
a single sign-on functionality, the customer would shop the way they
normally do through our platform, and we would let crowdrise know when
someone had earned cashback that would then be donated to the specific
charity.

in all honesty let's put this one on the back burner for now until I get
the legal aspects sorted out.

**Comment by robgpeak** [comment]
They decided not to integrate at this time.
