### ISSUE TITLE
Stew Leonards gifts

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#236]
@cgladue  Stew Leonards Gifts is marked as inactive and not joined in the back end, but it is still showing up in the Featured Deals section (see the home page).  If an advertiser become inactive, they should be automatically removed from the featured deals section.

**Comment by robgpeak** [comment]
@morganpeak please see why Stew Leonard Gifts is no longer active.  Did they move to a different network?  See what you can find out in CJ as to why they are not "not joined"...

**Comment by cgladue** [comment]
@robgpeak issue resolved on the frontend
