### ISSUE TITLE
Change at CJ

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#237]
@cgladue I just logged into CJ and saw this image...  Not sure what it means.

This is the link to the technical documents page https://developers.cj.com/docs/data-imports/product-feeds

<img width="738" alt="Screen Shot 2019-04-10 at 3 17 36 PM" src="https://user-images.githubusercontent.com/28393235/55907158-f6cdf380-5ba3-11e9-8f9d-cc2ac4ae2fdc.png">

**Comment by cgladue** [comment]
@robgpeak thank you i reviewed it and we dont use it so we are safe.
