### ISSUE TITLE
who is starting all these trips to tickmaster?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#238]
@cgladue I was just looking at something for another reason, and I came across something that looked strange.  It seems like there has been a shitload of trips started to ticketmaster, but that does NOT seem likely.  Please have a look and see if you can find out if it is someone using a bot on the site...

<img width="1161" alt="Screen Shot 2019-04-11 at 3 27 13 PM" src="https://user-images.githubusercontent.com/28393235/55987025-a1aae400-5c6e-11e9-9b1d-dcde2bb31f38.png">

**Comment by cgladue** [comment]
That is a great question... 

This was the API trying to create a trip when there is no trip reported by the advertiser... it has to create a trip to tie the comission to, for some reason it kept creating a new one every time .. not sure why but i cleaned up the ones out there that was the case for and see if it does it again;
