### ISSUE TITLE
Bonus game opt in/out

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#239]
@cgladue as for the functionality of the opt-in/out by the individual user, I figured it should have its own GitHub issue.  There are some references in #229 as to how it should function...

**Comment by robgpeak** [comment]
<img width="1076" alt="55635457-b713a000-578e-11e9-9522-9646885a78b1" src="https://user-images.githubusercontent.com/28393235/56458198-8e280900-6351-11e9-82e8-623ddf0f28d3.png">

**Comment by ChrisASearles** [comment]
Just committed this.

@cgladue while testing this I came across a bug, if you remove the last name and hit save it throws a nullreferenceexception back to the client.

**Comment by cgladue** [comment]
fixed

**Comment by robgpeak** [comment]
Not fixed for me...

https://youtu.be/UYSkwRfF27I

**Comment by cgladue** [comment]
@robgpeak that is for #249 this oneis just on the manage my account page

**Comment by robgpeak** [comment]
Understood
