### ISSUE TITLE
Setting another permission level

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#24]
@cgladue I think we need another permissions level in the back end.  "Customer Care Agent".

This authenticated user would be able to see all the end user back end data that we mentioned in #23.  That would be it for now, but we will probably add other functionality and view-ability in the future.

**Comment by robgpeak** [comment]
@cgladue I see that there is the ability to edit a user and set their role as "Customer Service" but I take it this is not operational yet?  Meaning, I changed the role on one of my accounts, but I tried to get to the admindashboard, and it would not take me there.

**Comment by robgpeak** [comment]
Oh, I thought it would have been the same admin dashboard, with just limited options in the navigation menu based on permission settings.

**Comment by cgladue** [comment]
it can be if you want, just thought you might think it strange they go to
/admindahboard when they arent admin



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I just thought it would be easier from an administration standpoint on your end to have one page to manage, and then you limit the visibility and functionality based on someone's role.

**Comment by cgladue** [comment]
all set in new design

**Comment by robgpeak** [comment]
@cgladue To be sure we are on the same page, I am guessing there is now one back end section for everyone (/dashboard), and the visibility of the various data is based on someone's log in credentials?
  If that is the case, we need to limit the visibility to data for customer service reps when they log into the dashboard so they can only see the info that is in the Customer Service section.  The same thing for the Partner's admin.

**Comment by cgladue** [comment]
That is correct the partners only see the section called partners the CSR‘s only see customer service section and Admin will see everything as well as in the user view page the permissions and account activation enable disable only admin‘s will see that

**Comment by robgpeak** [comment]
On the same subject I found a screencast:)  
https://screencast.com/t/cs5mGWMX50

Three things:
1. I logged in as a CSR and I was still able to see everything in the left hand navigation, not just the CSR section stuff.  You'll see that in the screencast.

2. CSR All User section should have clickable link on the users account numbers to drill into the customer's details just like the admin All Users section does.  The CSR is going to be able to see that data anyway, and it just makes it easier.

3. To be able to notate and/or track who made any change to any user's account information the same way you do now in the comments section.  Meaning, if a CSR comes in and adds points to someone's account, or makes any other change to the data, we can see who did it.

**Comment by cgladue** [comment]
guess i jumped the gun on #1, i didnt uncomment that code yet because im
still testing since i dont have a csr only login...

ill uncomment it shortly with the other two items go in.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Any progress with this Chad?  I wanted to log in as a partner to test and see what they see, and also as customer service to see what they see.

**Comment by cgladue** [comment]
Yea you can check it now...

**Comment by robgpeak** [comment]
I am trying to log in with the account x5@peakmarketing.com which has the role of partner admin but it will not log me in to either shop.complinks.co/dashboard or Xclub.complinks.co/dashboard  would either of those be right?

**Comment by cgladue** [comment]
it is registered with xclub so it should only let you login on
xclub.complinks.co

Whats the password ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
poiuy09876 is the pw

When I try to go to xclub.complinks.co/dashboard it automatically redirects and comes back with this message:
<img width="1107" alt="screen shot 2018-03-14 at 10 32 39 am" src="https://user-images.githubusercontent.com/28393235/37421341-712bc43a-278f-11e8-813d-434b5f53024f.png">

**Comment by cgladue** [comment]
ok try again, there was a misspelling in the URL its partner not
partners... you can just go to /dashboard and it will redirect to the right
place.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Awesome. Working perfectly.  Should we move that other stuff into another issue? Meaning the stuff about, "To be able to notate and/or track who made any change to any user's account information the same way you do now in the comments section. Meaning, if a CSR comes in and adds points to someone's account, or makes any other change to the data, we can see who did it."

Actually, I will start a new issue with that and close this one
