### ISSUE TITLE
points earned missing from user transaction data

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#240]
@cgladue For whatever reason I am only noticing this now, but the "points earned" column in the report https://xclub.complinks.co/dashboard/partner/purchases is, (and has seemingly always been), just "0's"

Please see if you can correct that and have the pending points that they would have earned for the corresponding transaction show up in there.

**Comment by cgladue** [comment]
hmm, really ?  how did we miss that .. ok ill look

**Comment by cgladue** [comment]
@robgpeak does it look correct now ?

**Comment by robgpeak** [comment]
Looks good now.
