### ISSUE TITLE
Selling Gift cards to earn points

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#241]
@cgladue
Barry had forwarded me your conversation that outlines your thoughts on how integration could work, and he asked if I could take a look and provide my feedback. Assuming I understand correctly, here's how I would propose we move forward, which should give us the functionality you're looking for... with the least amount of development effort on our end.

----

1) We create an API endpoint on dlyted.com, that is essentially a product feed. It will contain a list of our active gift cards, and what commission amounts each brand offers. We'll have to identify which specific fields of data you'd need. You would use this API endpoint to pull the list of products to show to your customers. This list can change from week to week (as we add/remove brand offerings) so you'd want to pull the list of products frequently -- you could even pull in realtime if you wish.

2) When you display the offerings to your customers, the links you use to send the customers to dlyted.com will be an "affiliate link", that will contain query string parameters so we know the customers came from your site, and what their CompLinks user ID is. The URLs will look something like...
https://www.dlyted.com/?dtc=105&dtid=123456

...where dtc=105 is the piece that tells our side this is a CompLinks referral, and the dtid=123456 is the CompLinks user ID, so you know which user to match the sales up with on your end. We're using dtc and dtid variables as this is part of our link tracking system that we already have in place.

You can add these affiliate tracking values to any Dlyted URL. For example, you can send a customer to a brand specific page:
https://www.dlyted.com/gift-cards/amazon.com/?dtc=105&dtid=123456

3) When your customer reaches Dlyted.com, we'll save their tracking parameters to a browser cookie, so if they sign up that day (or even later that month), when we create the user account, we'll flag their account as a CompLinks customer, so we know to include their sales in our reporting to you. Our tracking cookies last 1 year.

4) When customer makes a purchase, they will do so via the Dlyted.com site (same as any Dlyted customer), they will enter their credit card details, and we'll delivered the gift cards to the customer as usual. They will have a fully functional dlyted.com account, same as any customer. Only difference is that we'll have that customer (and their orders) flagged as a CompLinks customer.

5) [Optional] At the time of purchase, we can hit an API/webhook endpoint on your site, that would contain details about the sale (total amount, date/time, user ID, commission amount, activation status, etc). The status field will be important here... as our orders do go through various states as the gift cards are purchased and activated. For example, once an order is placed, it goes into "Processing" status. The order doesn't become "Complete" until the gift card is successfully activated (through our 3rd party partners) and the claim codes are delivered to the customer. It's also possible that an order will go "On Hold" if it's flagged by our spam/fraud checks. Orders that go On Hold need to be manually approved by our fraud team. We could potentially turn off our fraud checks if we detect it's a CompLinks customer. 

The possible statuses are: Processing, On Hold, Complete, Cancelled. So any time an order is placed, or its status is updated, we can hit this API/webhook endpoint to update your end on the status. 

We may break an order up into single "transactions". For example, if the customer purchases 3 different gift cards on the same order... I think we would hit your endpoint 3 different times (since each of the 3 gift cards are activated independently of one another... and can have different statuses). 

6) We will also set up an API endpoint that contains a full list of transactions and statuses, so you can query this endpoint at any point to get a status update for any particular transaction. You could pass in transaction ID to look up a specific transaction/statuses... or you can just pass in a date range to get all the recent transactions. You can use this endpoint to get a list of commissions owed to you, and the status of each commission (whether it was paid or not, etc). We'll have to identify the specific fields you'll need to see here. If you didn't want to create the webhook I mention in #5 (above), you could just hit this endpoint on our server to get updates for each order (ie, query it every hour to discover if new transactions are available).

7) We'll create a dashboard on our end (in our administration site) that Barry can use to see a full list of commissions. New commissions will be pending payment for 30 days (or whatever time period is appropriate). Barry will have a tool/report available to tell him how much he owes CompLinks, and he can mark all outstanding commissions as paid once he manually sends you payment. I'm assuming a manual payment (via cheque or wire transfer) would suffice here? If volume becomes high, we could look at automating payment at that time.

8) [Optional] If required, we can create a dashboard view for CompLinks as well. Ie, we'll give you a login to dlyted.com, that you can use to view all commissions and payment history. You could get all this information from the API endpoint I mention in #6 (above) but this dashboard might be an easier way for you to view status.

9) [Optional] If required, we can add some additional CompLinks information to user's Dlyted account. Ie, when they are viewing their "My Account" page on dlyted.com, if they are a CompLinks customer, we could display additional information (points earned, complinks User ID, etc). We would need to identify what details to show, and how we would gather that information.

----

I believe that will give you the functionality you need. Can you confirm this sounds ok -- or let me know if I missed any requirements?

If this sounds good, next steps would be to determine the commission/payment structure (ie, percentages to reward to user vs CompLinks) and then to identify what fields to include in each of the API endpoints I mentioned. At that point, I could begin development on our end.

Let me know how it looks, or if you have any questions. If you need to jump on a call to discuss, let me know and I can give you my availabilities for later this week.

Cheers,
Brad.
Hi Brad, I am cc'ing Chad on our end who will be doing the API stuff between Dlyted and CompLinks.  He and I will discuss internally and get back to you with the best way forward to accomplish what we are setting in out to achieve.

Thanks,

Rob

**Sent from my phone
Hide quoted text

On Mon, May 6, 2019, 11:57 AM <bpineau@gmail.com wrote:
Hi Rob,

Barry had forwarded me your conversation that outlines your thoughts on how integration could work, and he asked if I could take a look and provide my feedback. Assuming I understand correctly, here's how I would propose we move forward, which should give us the functionality you're looking for... with the least amount of development effort on our end.

----

1) We create an API endpoint on dlyted.com, that is essentially a product feed. It will contain a list of our active gift cards, and what commission amounts each brand offers. We'll have to identify which specific fields of data you'd need. You would use this API endpoint to pull the list of products to show to your customers. This list can change from week to week (as we add/remove brand offerings) so you'd want to pull the list of products frequently -- you could even pull in realtime if you wish.

2) When you display the offerings to your customers, the links you use to send the customers to dlyted.com will be an "affiliate link", that will contain query string parameters so we know the customers came from your site, and what their CompLinks user ID is. The URLs will look something like...
https://www.dlyted.com/?dtc=105&dtid=123456

...where dtc=105 is the piece that tells our side this is a CompLinks referral, and the dtid=123456 is the CompLinks user ID, so you know which user to match the sales up with on your end. We're using dtc and dtid variables as this is part of our link tracking system that we already have in place.

You can add these affiliate tracking values to any Dlyted URL. For example, you can send a customer to a brand specific page:
https://www.dlyted.com/gift-cards/amazon.com/?dtc=105&dtid=123456

3) When your customer reaches Dlyted.com, we'll save their tracking parameters to a browser cookie, so if they sign up that day (or even later that month), when we create the user account, we'll flag their account as a CompLinks customer, so we know to include their sales in our reporting to you. Our tracking cookies last 1 year.

4) When customer makes a purchase, they will do so via the Dlyted.com site (same as any Dlyted customer), they will enter their credit card details, and we'll delivered the gift cards to the customer as usual. They will have a fully functional dlyted.com account, same as any customer. Only difference is that we'll have that customer (and their orders) flagged as a CompLinks customer.

5) [Optional] At the time of purchase, we can hit an API/webhook endpoint on your site, that would contain details about the sale (total amount, date/time, user ID, commission amount, activation status, etc). The status field will be important here... as our orders do go through various states as the gift cards are purchased and activated. For example, once an order is placed, it goes into "Processing" status. The order doesn't become "Complete" until the gift card is successfully activated (through our 3rd party partners) and the claim codes are delivered to the customer. It's also possible that an order will go "On Hold" if it's flagged by our spam/fraud checks. Orders that go On Hold need to be manually approved by our fraud team. We could potentially turn off our fraud checks if we detect it's a CompLinks customer. 

The possible statuses are: Processing, On Hold, Complete, Cancelled. So any time an order is placed, or its status is updated, we can hit this API/webhook endpoint to update your end on the status. 

We may break an order up into single "transactions". For example, if the customer purchases 3 different gift cards on the same order... I think we would hit your endpoint 3 different times (since each of the 3 gift cards are activated independently of one another... and can have different statuses). 

6) We will also set up an API endpoint that contains a full list of transactions and statuses, so you can query this endpoint at any point to get a status update for any particular transaction. You could pass in transaction ID to look up a specific transaction/statuses... or you can just pass in a date range to get all the recent transactions. You can use this endpoint to get a list of commissions owed to you, and the status of each commission (whether it was paid or not, etc). We'll have to identify the specific fields you'll need to see here. If you didn't want to create the webhook I mention in #5 (above), you could just hit this endpoint on our server to get updates for each order (ie, query it every hour to discover if new transactions are available).

7) We'll create a dashboard on our end (in our administration site) that Barry can use to see a full list of commissions. New commissions will be pending payment for 30 days (or whatever time period is appropriate). Barry will have a tool/report available to tell him how much he owes CompLinks, and he can mark all outstanding commissions as paid once he manually sends you payment. I'm assuming a manual payment (via cheque or wire transfer) would suffice here? If volume becomes high, we could look at automating payment at that time.

8) [Optional] If required, we can create a dashboard view for CompLinks as well. Ie, we'll give you a login to dlyted.com, that you can use to view all commissions and payment history. You could get all this information from the API endpoint I mention in #6 (above) but this dashboard might be an easier way for you to view status.

9) [Optional] If required, we can add some additional CompLinks information to user's Dlyted account. Ie, when they are viewing their "My Account" page on dlyted.com, if they are a CompLinks customer, we could display additional information (points earned, complinks User ID, etc). We would need to identify what details to show, and how we would gather that information.

----

I believe that will give you the functionality you need. Can you confirm this sounds ok -- or let me know if I missed any requirements?

If this sounds good, next steps would be to determine the commission/payment structure (ie, percentages to reward to user vs CompLinks) and then to identify what fields to include in each of the API endpoints I mentioned. At that point, I could begin development on our end.

Let me know how it looks, or if you have any questions. If you need to jump on a call to discuss, let me know and I can give you my availabilities for later this week.

Cheers,
Brad.

**Comment by robgpeak** [comment]
@cgladue I know this reads like a novel, but what are your initial thoughts?

**Comment by cgladue** [comment]
@robgpeak i dont forsee any issues, we would want them to post to us when the order status updates like they offered and the link should work fine to sent people to them with minimal changes ... like instead of a user id we would send in the trip id (which links to the user)

**Comment by robgpeak** [comment]
In reading Brad's email more closely, he is thinking that a customer is going to have to sign up for a Dlyted account and make the purchases from their site (in its current form), and that's no good, so I am suggesting we get on a call to discuss how we would like to do it.

In a nutshell, I am thinking that we build another site similar to what we have, but instead of pulling the data from cj, ls and impact, it pulls from them, but the transaction of purchasing the gift card "seemingly" happens on our site, but the payment box would be in a modal that is going to Dlyted and processing the payment...

I think it needs to be explained verbally.

**Comment by cgladue** [comment]
ok, i read that but i thought that you had agreed to that model ... the payment could perhaps be an iframe within our site ...
i can talk later if you want  or let me know whent hey are available.

**Comment by robgpeak** [comment]
Let's see what they say.
