### ISSUE TITLE
Extra long locking period at Hotels.com

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#242]
@cgladue Have a look at 
https://shop.complinks.co/dashboard/users/view/100422#tab-history and see all the transactions he's made and look at the locking periods.  They see really long.

Also, as we discussed, see if you can find out what the transactions were actually for?  Meaning the hotels booked...

**Comment by cgladue** [comment]
i checked and they look to be legit sales, i checked CJ backend too and they are there too...

![image](https://user-images.githubusercontent.com/7914133/57739444-99850080-7681-11e9-9f00-9395843234a7.png)

**Comment by cgladue** [comment]
maybe he books travel for other people or something, or travels a lot for work or something

**Comment by robgpeak** [comment]
and those locking periods that far out into the future or legit also?

**Comment by cgladue** [comment]
@robgpeak yea... thats whats coming from CJ... unless theres something messed up on CJ side

**Comment by cgladue** [comment]
`<commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473056129</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:22:11-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536084086</order-id>
            <original>true</original>
            <original-action-id>2150606589</original-action-id>
            <posting-date>2019-05-06T17:01:51-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>8.09</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>202.28</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473056551</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:25:11-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536164131</order-id>
            <original>true</original>
            <original-action-id>2150607387</original-action-id>
            <posting-date>2019-05-06T17:30:08-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>17.76</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>443.98</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473057428</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:28:11-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536221471</order-id>
            <original>true</original>
            <original-action-id>2150608270</original-action-id>
            <posting-date>2019-05-06T17:30:14-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>9.65</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>241.20</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473059147</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:30:20-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536283222</order-id>
            <original>true</original>
            <original-action-id>2150608948</original-action-id>
            <posting-date>2019-05-06T17:30:50-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>6.41</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>160.20</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473059753</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:32:11-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>8122962144944</order-id>
            <original>true</original>
            <original-action-id>2150609494</original-action-id>
            <posting-date>2019-05-06T17:30:54-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>10.24</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>255.98</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473060276</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:34:10-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536380016</order-id>
            <original>true</original>
            <original-action-id>2150610091</original-action-id>
            <posting-date>2019-05-06T17:30:59-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>9.65</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>241.20</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473063971</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:37:19-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536439197</order-id>
            <original>true</original>
            <original-action-id>2150614815</original-action-id>
            <posting-date>2019-05-06T17:31:39-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>8.50</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>212.50</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473064835</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:40:11-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536504482</order-id>
            <original>true</original>
            <original-action-id>2150615669</original-action-id>
            <posting-date>2019-05-06T17:31:58-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>9.65</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>241.20</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>
        <commission>
            <action-status>new</action-status>
            <action-type>sale</action-type>
            <aid>10780389</aid>
            <commission-id>2473065556</commission-id>
            <country>US</country>
            <event-date>2019-05-06T16:42:26-0700</event-date>
            <locking-date>2020-12-26</locking-date>
            <order-id>158536564546</order-id>
            <original>true</original>
            <original-action-id>2150616324</original-action-id>
            <posting-date>2019-05-06T17:32:04-0700</posting-date>
            <website-id>8235261</website-id>
            <action-tracker-id>406471</action-tracker-id>
            <action-tracker-name>Hotels.com NA Pending Booking Action</action-tracker-name>
            <cid>1702763</cid>
            <advertiser-name>Hotels.com</advertiser-name>
            <commission-amount>15.68</commission-amount>
            <order-discount>0.00</order-discount>
            <sid>6404</sid>
            <sale-amount>391.98</sale-amount>
            <is-cross-device>false</is-cross-device>
        </commission>`
