### ISSUE TITLE
A specific list of Xclub members

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#244]
@cgladue Can you produce a csv file with all the xclub members who started a shopping trip between April 1, 2019 and May 31, 2019

Need to select a winner for a drawing for two Righteous Brothers tickets.

**Comment by robgpeak** [comment]
@cgladue Is this something I can do on my own in the back end?  I could not figure out how?

**Comment by cgladue** [comment]
not easily no, im doing this now...

**Comment by cgladue** [comment]
[complinks.zip](https://github.com/robgpeak/CompLinks-xclub/files/3250302/complinks.zip)

**Comment by cgladue** [comment]
@robgpeak here ya go

**Comment by cgladue** [comment]
this does not take into consideration people with multiple trips, it only counts a max of 1

**Comment by cgladue** [comment]
```
SELECT DISTINCT 
	u.accountNumber,
	u.lastname,
	u.firstname,
	u.email 
FROM ShoppingTrips st
INNER JOIN AspNetUsers u ON st.userId = u.Id
WHERE 
	st.tripdate BETWEEN '2019-04-01' AND '2019-05-31' AND
	u.testAccount = false
ORDER BY u.accountNumber
```

**Comment by robgpeak** [comment]
We need ANYONE that started a trip in that period, even it was multiple
trips, and/or NOT their first trip.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea that is what i gave you,  i meant that even if they started 50 trips they only appear once in the results (SELECT DISTINCT) you arent giving them 1 entry for every trip they start right ?

**Comment by robgpeak** [comment]
Yeah.  Gotcha. We're good.  Thanks.

>
