### ISSUE TITLE
Major issue trips not starting

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#245]
@cgladue Just saw this when I tried to start a trip on both xclub and shop to any merchant.  Tried incognito as well.

<img width="1086" alt="Screen Shot 2019-06-07 at 7 20 50 AM" src="https://user-images.githubusercontent.com/28393235/59100796-1d36b380-88f5-11e9-858f-8fea565bb6c7.png">

**Comment by cgladue** [comment]
ugh ok one sec



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@robgpeak i deployed some survey changes last night before bed it was related to that it should be corrected now.
