### ISSUE TITLE
missing commissions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#246]
@cgladue It see like there are a lot of transactions missing commissions, and it seems strange.  https://shop.complinks.co/dashboard/admin/profitability

Please have a look and let me know.

**Comment by cgladue** [comment]
i dont think there is an issue here, they could be people who used another coupon and therefore dont get bachback or bought something that does not quality .. but ill pull the API data ...

**Comment by cgladue** [comment]
```
{
    "etransaction_id":"3EC26063E7E6527B49E5CFD31BE65C9E",
    "advertiser_id":2149,
    "sid":3371414,
    "order_id":"4331985769104",
    "offer_id":"653363",
    "sku_number":"W037000433576",
    "sale_amount":5.97,
    "quantity":1,
    "commissions":0,
    "process_date":"Wed Jun 12 2019 18:18:42 GMT+0000 (UTC)",
    "transaction_date":"Tue Jun 11 2019 22:55:00 GMT+0000 (UTC)",
    "transaction_type":"batch",
    "product_name":"40000:44000:44003:44106:44224:Cascade Complete Gel Dishwasher Detergent, Citrus Breeze, 75 oz",
    "u1":"6667",
    "currency":"USD",
    "is_event":"N"
  },
  {
    "etransaction_id":"74915AA4AF4DE99E7C99F8985401A877",
    "advertiser_id":2149,
    "sid":3371414,
    "order_id":"4331985769104",
    "offer_id":"653363",
    "sku_number":"W021000774364",
    "sale_amount":4.5,
    "quantity":1,
    "commissions":0,
    "process_date":"Wed Jun 12 2019 18:18:42 GMT+0000 (UTC)",
    "transaction_date":"Tue Jun 11 2019 22:55:00 GMT+0000 (UTC)",
    "transaction_type":"batch",
    "product_name":"40000:42000:42003:42106:42240:Kraft Original Flavor Macaroni & Cheese Dinner, 5 - 7.25 oz Boxes",
    "u1":"6667",
    "currency":"USD",
    "is_event":"N"
  },
  {
    "etransaction_id":"F3C7D741C002083898D41E08F4F22596",
    "advertiser_id":2149,
    "sid":3371414,
    "order_id":"4331985769104",
    "offer_id":"653363",
    "sku_number":"W078742300092",
    "sale_amount":6.92,
    "quantity":1,
    "commissions":0,
    "process_date":"Wed Jun 12 2019 18:18:42 GMT+0000 (UTC)",
    "transaction_date":"Tue Jun 11 2019 22:55:00 GMT+0000 (UTC)",
    "transaction_type":"batch",
    "product_name":"40000:44000:1044040:44006:44260:Great Value Economy Paper Lunch Plates, 8 5/8\", 300 Count",
    "u1":"6667",
    "currency":"USD",
    "is_event":"N"
  },
```

**Comment by cgladue** [comment]
Yea its coming right from linkshare with 0 as the comission ...

**Comment by robgpeak** [comment]
@morganpeak please look into these transactions in LS and CJ to see why we are not getting commissions for so many sales.

**Comment by cgladue** [comment]
i bet these purchases were done through walmart grocery vs just walmart.com order...
![image](https://user-images.githubusercontent.com/7914133/59530448-94e67e80-8eb1-11e9-88b1-7c6d0d22f4e3.png)

**Comment by robgpeak** [comment]
That might be new.  I've made purchases through Walmart grocery after
landing on the regular Walmart page by way of a shopping trip on
Xclub.complinks.co and I received cash back.

**Comment by robgpeak** [comment]
Hey @cgladue as a follow up to this, and sort of the same issue, I just looked in the back end of CJ reporting and it is showing that we have had three commission transactions, but they are not showing on our side.

Here is the link to the report (screenshot below)

https://members.cj.com/member/4337795/publisher/navigate_reports.cj#?tab=performance&criteria=%7B%22filters%22%3A%5B%5D%2C%22columnSorts%22%3A%5B%5D%2C%22reportGroupId%22%3A%22performance%22%2C%22reportId%22%3A%22advertiser%22%2C%22reportName%22%3A%22Advertiser%22%2C%22trendPeriod%22%3A%22DoD%22%2C%22startDate%22%3A%222019-06-01T04%3A00%3A00.000Z%22%2C%22endDate%22%3A%222019-06-20T12%3A25%3A27.241Z%22%2C%22presetPeriod%22%3A%22ThisMonth%22%7D

<img width="1251" alt="Screen Shot 2019-06-20 at 8 30 03 AM" src="https://user-images.githubusercontent.com/28393235/59849564-f6856d80-9335-11e9-9a00-4c213f31467e.png">

**Comment by cgladue** [comment]
You are correct rob, CJ changed the name of one of the fields, i have corrected it and the comissions are now showing up...
