### ISSUE TITLE
Using GiftCards.com (CJ) for Rewards in PCH.complinks.co

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#247]
@cgladue I spoke with the guys from PCH today and there has been a slight change in plans. The original idea was to let people earn tokens into their sweepstakes just by clicking on a shop now button without having to make a purchase. Now we want to make d PCH shops more like the X Club platform in that the customers will shop and earn points just like they normally would. The only difference is on the Redemption side they don't have a way for the customers to redeem, so we are going to use giftcards.com as the rewards method.

Meaning instead of someone transferring their available points 2 a card at the casino the only thing they can do with them would be to use those points to purchase a gift card on our site.

I have not looked into the giftcards.com affiliate program that in depth, but I'm wondering if we can through an API show all the different cards that someone could purchase right within our reward section. Please check it out and see if that's possible.

https://members.cj.com/member/4337795/publisher/advertisers/findAdvertisers.cj#{%22pageNumber%22:1,%22publisherId%22:4859760,%22pageSize%22:%2250%22,%22advertiserIds%22:%224575680%22,%22geographicSource%22:%22%22,%22sortColumn%22:%22advertiserName%22,%22sortDescending%22:false}

**Comment by cgladue** [comment]
ok so they would use their points to purchase a giftcard from giftcards.com ?  and giftcards.com would furfill the order or we would furfill it ?

**Comment by robgpeak** [comment]
Not sure.  I guess I was first thinking that most people would buy eGift
cards, but I suppose you're right with regard to fulfilment of a physical
card... We should probably let gift cards.com fulfill the orders.

**Comment by cgladue** [comment]
@robgpeak i cant seem to find any documentation about their API but i cant imagine they dont have that ... can we schedule a call with someone over there to discuss ?  the link you provided dosnt take me anywhere hate CJ and their links...

**Comment by robgpeak** [comment]
I will try to get ahold of someone there.  Basically the link was just to
the program terms for gift cards.com on CJ.

**Comment by robgpeak** [comment]
@cgladue I just signed up for Gyft, (which I think does the same thing whereby we can list their gift card on our site for sale, but I am not sure).  They seem to have a lot of documentation (https://business.gyft.com/developers/docs/) but I can't really tell if it will do what we want.  I wanted to se if you could have a look.

**Comment by cgladue** [comment]
it looks like it will do what we want (theres a API to buy and return a giftcard and list available giftcards) the only thing is you would have to pre-fund the account to cover all purchases that may be made, so youd have to keep that topped off to make sure users could redeem for giftcards .. are you OK with that ?

**Comment by robgpeak** [comment]
That seems a little onerous... I reach out to their support department, and
I will wait to see what they say.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
did you get a chance to talk to them ?

**Comment by robgpeak** [comment]
No one got back to me.
