### ISSUE TITLE
Nothing showing on backend dashboard page for all partners

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#248]
@cgladue https://shop.complinks.co/dashboard/admin/profitability is blank when all partners is selected, which is the default.

**Comment by cgladue** [comment]
This was related to the survey project and has now been fixed.

**Comment by robgpeak** [comment]
Ok.  And today is the 4th and there have been no transactions at all for the month...? Can you just check into that to make sure nothing else broke causing sales data to not be showing up...

**Comment by cgladue** [comment]
i have checked and there was one that showed up today at noon but nothing
before that other then my surveys


Chad Gladue
*DevNull Technology, LLC*
