### ISSUE TITLE
Adding Terms & Conditions and Privacy Policy pages to the CMS

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#25]
@cgladue The same way you made the How it works and FAQ pages easily editable from the admindashboard, please see if you can add that same functionality to the T&C page and Privacy Policy page.  

I guess it makes most sense to have them individually editable by the chosen subdoain with the dropdown menu.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/37866093-0efa456e-2f5c-11e8-9aba-bb0f90444a65.png)

**Comment by robgpeak** [comment]
The privacy policy worked, but when I try to navigate to the Terms and conditions edit page for xclub or any other sub domain, it reverts back to the privacy policy page.  give it a try on your end.

**Comment by cgladue** [comment]
um no i can get to and edit the t&c ..  can you show me one of your
infamous screencasts ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
https://screencast.com/t/EODxnny8N

**Comment by cgladue** [comment]
ok copy paste error, its all set now.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
cool
