### ISSUE TITLE
Seems strange these is only one transaction for the month

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#250]
@cgladue please have a look at https://xclub.complinks.co/dashboard/admin/profitability and see if maybe something is broken in the back end.  Seems odd that we are 8 days into the month and only have one shopping transaction.

**Comment by robgpeak** [comment]
Anything here Chad?  Something is not right.

**Comment by cgladue** [comment]
i looked rob and there is no data in the API, i checked CJ backend and there are no sales there

i checked the trip start logic (which hasnt changed) and it redirects to the proper advertiser and the URL looks fine ...

i really dont see anything that looks amiss

**Comment by robgpeak** [comment]
What about the back end of link share and impact.  It just doesn't seem
right

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
linkshare is $0 in sales also ... but i see inpressions and clicks so i know people are clicking and seeing things.

**Comment by cgladue** [comment]
ill check impact

**Comment by cgladue** [comment]
impact shows the only sale $20 at home depot

**Comment by cgladue** [comment]
@robgpeak i just saw another transaction show up today .. so it seems like the process is ok ...
