### ISSUE TITLE
Customers aren't receiving points for Walmart or Petco purchases

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#251]
@cgladue I have had a customer who has made documented trips to both walmart and petco within the last month or two but have not received credit for their purchases. Would you be able to look into this and see why this may be happening? One particular customer is Barbara Manzo #100789

**Comment by cgladue** [comment]
they arent showing up in the network backends either are they ?

**Comment by cgladue** [comment]
if they dont even show up in linkshare or impact or CJ then i think we need to raise a concern with the networks and see whats going on ?  can we run reports on their backends to see the total traffic being sent to them to make sure they at least recognize the traffic ?

**Comment by cgladue** [comment]
i see purchases for walmart as recently as 7/27... not sure why barb didnt get her points but i dont see that there is a problem, do you ?
