### ISSUE TITLE
Profit summary is blank again

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#252]
@cgladue I looked about 2 hours ago at https://shop.complinks.co/dashboard/admin/profitability showing all partners, and the data was full, now when I look it's all zeros.

![Screen Shot 2019-07-29 at 7 23 30 PM](https://user-images.githubusercontent.com/28393235/62089368-a784ff00-b236-11e9-9723-1881eb8b7bca.png)

**Comment by robgpeak** [comment]
If I remember correctly, it has something to do with the surveys again, becasue I see now that I have 29.4 points pending for completing a survey, and that happened at about the same time as this went blank, and I think that happened last time you completed a survey.

**Comment by cgladue** [comment]
ok let me see, it might not like something thats being set for the survey
since ites a little different then a purchase hold on.


Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
It was related to the survey, when the survey came in it had a blank date field .. i set the date field and now the stats are working fine again.
