### ISSUE TITLE
Survey page menu is askew

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#253]
@cgladue I am thinking this might be an angular issue, but I thought I would bring it to your attention anyway.

I was just about to make a video demo of the platform, and when I click into Surveys on shop.complinks.co the menu items of Surveys and everything to the right of it seem to become "top" justified instead of "center" like they were originally.

<img width="1166" alt="Screen Shot 2019-07-29 at 9 35 47 PM" src="https://user-images.githubusercontent.com/28393235/62093952-474b8880-b249-11e9-8b64-54b6ff2a3b04.png">

**Comment by cgladue** [comment]
yea i saw that i was assuming that chris would fix it i dont know why its
doing that :(


Chad Gladue
*DevNull Technology, LLC*
