### ISSUE TITLE
stats not pushing to Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#254]
@cgladue I am not sure if it had something to do with the surveys or something, but I just noticed one particular incident where a user https://shop.complinks.co/dashboard/users/view?id=101838 made a shopping trip and a purchase, but it is NOT showing up in his attributes in Intercom.

It's showing trips and pending points balance as 0

<img width="1170" alt="Screen Shot 2019-07-30 at 3 18 48 PM" src="https://user-images.githubusercontent.com/28393235/62158453-6ac01300-b2dd-11e9-8339-ba3704ab493d.png">

**Comment by cgladue** [comment]
i checked the intercom backend and we were set to use v1.0 of their API, they were up to v1.3 o i updated to the latest, can you see if that makes a difference?

**Comment by robgpeak** [comment]
Would be instantly that the data would show up, because it's not there.  It shows that he has points in our back end, but not in Intercom

<img width="632" alt="Screen Shot 2019-07-30 at 10 17 40 PM" src="https://user-images.githubusercontent.com/28393235/62178800-53eae200-b318-11e9-998b-b9b4f754e88e.png">


and

![Screen Shot 2019-07-30 at 10 21 17 PM](https://user-images.githubusercontent.com/28393235/62178856-7ed53600-b318-11e9-8442-1f1f5d5d8a50.png)

**Comment by cgladue** [comment]
i will have to run a conversion program to go through and resync all users
and their balances, just curious if the new trip reporting was working
again


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
"...just curious if the new trip reporting was working again..."

Do you mean, is Intercom receiving the indication that a new shopping trip
has taken place and is increasing the number of trips a person has taken
accordingly?

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yes

**Comment by robgpeak** [comment]
I just tested it on my account 100086 and it worked immediately. So that's
a good thing, but it still not showing the trip taken and points earned for
user 101838
<https://t.sidekickopen05.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynN4Wzv3dRbPVxW56dCqf42YxNv102?t=https%3A%2F%2Fapp.intercom.io%2Fa%2Fapps%2Fd8m2yyar%2Fusers%2Fsegments%2Fall%3AeyJwcmVkaWNhdGVzIjpbeyJjb21wYXJpc29uIjoiZXEiLCJ2YWx1ZSI6IjEwMTgzOCIsImF0dHJpYnV0ZSI6InVzZXJfaWQiLCJ0eXBlIjoic3RyaW5nIn0seyJ0eXBlIjoicm9sZSIsImF0dHJpYnV0ZSI6InJvbGUiLCJjb21wYXJpc29uIjoiZXEiLCJ2YWx1ZSI6InVzZXJfcm9sZSJ9XX0%3D&si=7000000001824863&pi=a70b0a10-10f8-4103-ee4d-ebd181831381>.
Maybe it's becasue it was on the 28th, and the surveys stuff messed
something up?

>

**Comment by cgladue** [comment]
no, like i said i have to go back and re-sync all users and their stats in intercom to bring everyone up to date i just wanted to make sure it was reporting correctly now.
