### ISSUE TITLE
trouble saving new comment in back end

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#255]
@cgladue I am trying to save a message but it wont save.  I get an error message.
![Screen Shot 2019-07-30 at 7 15 17 PM](https://user-images.githubusercontent.com/28393235/62171886-8ab3fe80-b2fe-11e9-8604-020bf10c8897.png)

**Comment by cgladue** [comment]
ok looking now one moment

**Comment by cgladue** [comment]
this is all set rob
