### ISSUE TITLE
checking transactions from CJ

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#258]
@cgladue seems strange that the month is half over and we have not had on transaction from CJ.  Please have a look and see if something is not working properly.

**Comment by cgladue** [comment]
i checked and the API is functioning, there are two purchases this month (both from yesterday) and it agrees with the CJ Dashboard as well:

![image](https://user-images.githubusercontent.com/7914133/63118681-59793680-bf6c-11e9-8c8f-bce065ba9655.png)
