### ISSUE TITLE
SMS integration into Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#259]
@cgladue I just spoke to an SMS integration developer to discuss being able to send SMS message to customers and retain a record of it in Intercom, but to also be able to send a text message that uses some of the attributes that we push to Intercom like points balance, number of trips taken, etc.

So a text message might look like, "You've earned xxx points so far and you're only yyy points away from a bonus, click here for more details" OR, "Congratulations on making your 10th shopping trip, click here for a bonus..."

The idea would be to use an SMS service that would of course let people opt out of receiving SMS messages, but to be able to track the conversations in Intercom.

<img width="823" alt="Screen Shot 2019-08-15 at 1 38 07 PM" src="https://user-images.githubusercontent.com/28393235/63114524-11a1e180-bf63-11e9-9f42-347439abf087.png">

​If you look at the details of the toky app on the  page https://app.intercom.io/a/apps/d8m2yyar/appstore?app_package_code=toky&search=sms you ​can see how it would integrate.

I don't know if you have detailed documentation of how you integrated our customer's attributes into Intercom, but if you have something I can show this developer, that would be helpful.

**Comment by cgladue** [comment]
i have done extensive work with twilio and use text and voice at work all the time with them, i wrote a CRM system that makes IP phone calls and two way text messages for our entire 100 person casino sales and host staff... if intercom can work with twilio then its a no brainer

**Comment by cgladue** [comment]
there really isnt any documentation, we just use the Intercom Events API to stream the events as they occur and intercom saves them

**Comment by cgladue** [comment]
@robgpeak i dont see any specifics on the integration other then high level.. i assume they would be able to just work with all the data that intercom has from us and we wouldnt need to integrate with toky at all right ?

**Comment by robgpeak** [comment]
Awesome-sauce!

https://zapier.com/apps/intercom/integrations/twilio

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
it looks like zappier already handles all the twilio communication, would you even need to do anything other then signup for a twilio account ?

**Comment by robgpeak** [comment]
Either way, whether we use Twilio or toky it doesn't matter much to me buy
the idea is that we can see the thread of the messages send via text within
the intercom platform, as that really is our CRM.

**Comment by cgladue** [comment]
are you looking at expanding to a phone # they can call to talk to someone ?  or keeping it email and chat support

**Comment by robgpeak** [comment]
I really want to be able to use SMS as a marketing and communications
channel.  We could allow customers to call in if they have an issue.  I
would have no problem with that.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
Closing this as i have added phone# and unsubscribe_from_sms attributes to the user in Intercom, we will do the SMS from within Rewards Everywhere instead.

**Comment by robgpeak** [comment]
ok
