### ISSUE TITLE
The Click URL field on the promotions page in the admin dashboard

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#26]
@cgladue I wanted to see about adding some functionality to the "Click URL field on the page (example) https://shop.complinks.co/admindashboard/partners/editpromotion/16 whereby the text that I enter in that field would display in a pop up overlay.  Actually, It's easier if I just make one of your favorite screen casts...  https://screencast.com/t/1cOCVmUi

So similar to the way the overlay pops up when you click on the terms and conditions in the already existing overlay of the sign up form, I would like to have the click URL in the promotion section have the same functionality. Also we would need to have the tiny mice text editor sort of thing in there.

**Comment by cgladue** [comment]
the overlays are something chris did in angular, i tried to duplicate but i dont know angular so i cannot do it...  i could make something with the same functionality but not he same look

**Comment by robgpeak** [comment]
If I need to get Chris involved again just to do some last-minute stuff for
the balance of this month, I think that would be worth it. What do you
think?

**Comment by ChrisASearles** [comment]
Hey guys, just going through this stuff to see what needs to be done. Took a look at the page and the screencast and it looks like the field to store the copy you want showing up here hasn't been added yet. @cgladue do you want to let me know once that data is available for us to pull?

**Comment by cgladue** [comment]
i believe "clickUrl" is the url that i added for this...

![image](https://user-images.githubusercontent.com/7914133/37262089-5acd133e-2577-11e8-87b8-215c37ca91fb.png)

**Comment by robgpeak** [comment]
@cgladue Based on your new layout, I think this might work as a layout for the page to update the promos and including the "Main Description" and the Click URL Description.  If they could be html editable, that would be good too.


![uploads/267dcca6-7496-439a-a34f-202e21c3da0f/Screen Shot 2018-03-13 at 11.10.50 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F267dcca6-7496-439a-a34f-202e21c3da0f%2FScreen+Shot+2018-03-13+at+11.10.50+AM.png)

**Comment by ChrisASearles** [comment]
I just committed all the changes and framework for this to function on the front-end with the data that's available at the moment. @cgladue see @robgpeak 's last comment, looks like we need that "Click URL Description" field coming down on the front end and you can just replace the `@promo.description` with the new field in the two spaces on Promotions.cshtml where the modal markup shows up:

`<md-dialog aria-label="Promotion Details" flex-gt-xs="70" flex-gt-sm="50" flex-gt-md="40">
                                        <md-toolbar>
                                            <div class="md-toolbar-tools">
                                                <h2>Promotion Details</h2>
                                                <span flex></span>
                                                <md-button class="md-icon-button" ng-click="closeDialog()">
                                                    <md-icon aria-label="Close details window">close</md-icon>
                                                </md-button>
                                            </div>
                                        </md-toolbar>
                                        <md-dialog-content layout-padding>
                                            <h2>@promo.title</h2>
                                            <p>
                                                @promo.description
                                            </p>
                                        </md-dialog-content>
                                    </md-dialog>`

**Comment by cgladue** [comment]
@robgpeak what else is missinghere, im confused whats missing from hoe its woking as of right now

**Comment by cgladue** [comment]
ok so i am adding a new field for Modal Title and changing the link field to a textarea and naming it Modal Body Or Modal Content or something right is that what we decided?

**Comment by robgpeak** [comment]
Shit, I sort of forgot the way Chris described it, but it made sense when he said it.

I think he said, in the mock up image I put in this thread, where it say "Click URL", you would change the title of that to "Button Text", I can enter "More Details" or "Terms & Conditions" in that field and that is what would show up on the button itself.  And if it was blank, there would be no button visible.

Then there would be a dialog box, or I guess what you call a Modal (maybe call it "Botton Pop Up Content" that I would be able to edit the content.  If you can make it a text area like this (below) that would be awesome.

<img width="585" alt="screen shot 2018-03-22 at 10 20 56 pm" src="https://user-images.githubusercontent.com/28393235/37808142-62a4d686-2e1f-11e8-8023-66af58f0e904.png">

**Comment by ChrisASearles** [comment]
what he said ;-)

Three inputs: Dialog Button Text, Dialog Title, Dialog Text (rich text editor)

**Comment by cgladue** [comment]
Tiny mice 🐁

**Comment by robgpeak** [comment]
Are you mocking me :)

**Comment by cgladue** [comment]
Wouldnt think of it...

**Comment by cgladue** [comment]
🐁🐁🐁🐁🐁

The tiny Mice have been working feaverishly on their wheels, and have turned out the functionality you asked for rob, take a look...  

🐁🐁🐁🐁🐁

**Comment by robgpeak** [comment]
So close. Put another piece of cheese in the cage for those mice and get them back on the wheel.  Everything works great, except the copy that shows up in the actual live modal (pop up) is the copy from the "Description" instead of the "Modal Description".  The other thing is, the copy that does show up in the Modal is showing the HTML mark up...  See the `<p> and </p>` in the image below.  And yes, of course I check it from my phone.

Lastly, what the F is a modal?  Let's call them (Dialog Button Text, Dialog Title, Dialog Text)

--

![screenshot_2018-03-24-08-46-53](https://user-images.githubusercontent.com/28393235/37864080-f6cea62c-2f3f-11e8-98da-f4cf7dc71fbb.png)

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/37864135-fb87ad52-2f40-11e8-8b23-8a2247e203e9.png)

**Comment by robgpeak** [comment]
So in English it's a dialog box:)

**Comment by cgladue** [comment]
No, its a MODAL dialog box ... a dialog box is not subordinate to the applications main window, meaning you can have a dialog box open and still do things in the application... a modal dialog box is the topmost window and has to be dismissed before the user can interact with the application again...

**Comment by cgladue** [comment]
Either way, check it out now ...

**Comment by robgpeak** [comment]
As long as you and the 🐁🐁🐁🐁 what a modal is we're good. Perfect working excellent now.  Thanks.

**Comment by cgladue** [comment]
FYI i Fed up the content for the Parxgrill promotion :( sorry !

**Comment by robgpeak** [comment]
No worries, I'll fix it
