### ISSUE TITLE
Rename the domain to rewardseverywhere.co

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#262]
@cgladue @morganpeak I wanted to have some dialog with you both about changing the domain from xxx.complinks.co to xxx.rewardseverywhere.co

Please put some of your thought on this shared document https://docs.google.com/document/d/1aJDjN2IO6IC6D2Oe_YAAuF3ilYgn5jpmomI9gAhMSgE/edit?usp=sharing 

Let's use different colors on the document so it's easier to tell who said what...  (Rob - Black) (Morgan - Blue) (Chad - Red)

and I would like to have a phone call with the three of us on Monday afternoon/evening (when you are on your way home Chad.  Just let us know here what time works for you and I will send out a calendar invite.

**Comment by robgpeak** [comment]
Ok Chad, we want to move ahead with this process of a name change.  Please put together the list of things we need to do in the proper order to accomplish this, and assign the necessary tasks needed to yourself, myself and Addison to get it done.

**Comment by cgladue** [comment]
did you already purchase the domain ?  if so can you add it to cloudflare and i can stand up a copy of the website n it for the meantime and for testing with addison

**Comment by robgpeak** [comment]
I'd do have the domain it is in my GoDaddy account and I just changed the DNS to cloudflare

**Comment by robgpeak** [comment]
If you need full access to my GoDaddy account to do that other thing for SSL for Peak Gaming Group, the user name is "peakli" and I will text you the password

**Comment by robgpeak** [comment]
@cgladue After everything is said and done, will xclub.complinks.co stop working all together, or can we leave them both working in parallel to be sure we don't miss anything?  Then we can monitor google analytics for a while, and after we see there is no more traffic going to shop.complinks.co we can retire it... yes?

**Comment by cgladue** [comment]
yea you can leave it up for as long as you need to, but i wont be able to make changes like the menu and anything else that gets changed fromt his point onwards.

**Comment by cgladue** [comment]
it will be a time capsule frozen in time.

**Comment by robgpeak** [comment]
but I just made a change to the FAQ page https://xclub.rewardseverywhere.co/dashboard/property/faq/12 and it showed up on both https://xclub.complinks.co/faq and https://xclub.rewardseverywhere.co/faq which is good.

So what I think you're saying is the structure elements like the menu won't change, but the content is interchangeable. If so, I get it.

**Comment by cgladue** [comment]
yea, database driven content will be fine to update, but the structure or features wont.  anything that needs code to be deployed

**Comment by robgpeak** [comment]
OK, understood.  So you got my message in a different issue about the menu items from Promotions and all to the right are higher than Categories and All stores on https://xclub.rewardseverywhere.co/  That means it's a code thing that has to be fixed, not content.

**Comment by cgladue** [comment]
@robgpeak i think everything is moved over, see if you can see any issues and if not then ill close this

**Comment by robgpeak** [comment]
I spoke with Addison yesterday and he will need to do some tweaking to the
extension because it's hard coded to CompLinks.co

Other than that, everything seems to be working fine now.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak i think this is complete now

**Comment by robgpeak** [comment]
I think you're right
