### ISSUE TITLE
Leading zeros in someone's xclub account number

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#27]
@cgladue I just had a call with Parx, and they were saying something about their xclub account numbers having leading zeros in them, and they are NOT needed when someone logs in.  At least that's what I think she was talking about.  There was no one on the call from their tech side, but I wanted to at least bring it to your attention when you talk to their tech side.

Basically, I wanted to see if you can verify with them the exact format that they need the account number in, and we can validate or verify it is in the proper format when someone enters it before we send it to Parx.

To be honest I'm a little confused because I just looked at some examples of their xClub card online and I don't see any leading zeros in their account numbers. Anyway just check with their guys and see what they say.

**Comment by cgladue** [comment]
ok, as it stands right now it just sends whatever the user enters into the
textbox across to them unformatted, if they put the 0s or not...




Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
OK, for now we will leave it as it is and let their side manage the formatting of the textbox data they receive.  We can address it later if it becomes an issue.
