### ISSUE TITLE
Update Google Analytics with new domain name

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#271]
Update google/analytics with new site Domain once go live.

**Comment by robgpeak** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-100214211-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-100214211-3');
</script>

**Comment by cgladue** [comment]
Should be switched over now.
