### ISSUE TITLE
Redesign of the site

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#274]
@cgladue Based on the very positive feedback we've always and still receive on the current site, we would like to keep the overall layout and design as close to what we have now, but use the new infrastructure from this site http://codeboxr.net/themedemo/couponz/html/index.html

Ultimately we are still looking to have the main navigation be similar to the mockups in https://miro.com/app/board/o9J_k0oF_1U=/

So I think the best thing to do would be to start with what they have currently at the couponz codedeboxr template, and make some adjustments and customizations to get it as closely aligned with the layout and design we currently have.  Of course if you think there are some cool features in the couponz template that we can use to enhance the UI/UX, by all means, add them in there.

As you know I am a big fan of the modal, and as I mentioned on the phone, the number ONE thing for me is the speed at which the site renders the page and information.  It has to be fast, so we need to keep that in mind with **everything** we do for the redesign.  The number TWO thing is, it MUST look and respond flawlessly on mobile.

**Comment by cgladue** [comment]
u sure you dont like this one better ? hehe

https://friday-theme.firebaseapp.com/store_single_01.html

**Comment by robgpeak** [comment]
Why is that one easier to work with?

The reason I didn't choose that one was because of the layout.  It doesn't
seem conducive to the layout I like in terms of having four or five "store
tiles" going across in the grid view...  Plus the menu did not seem as nice
as the one that I first selected.

Of you want to message around with both templates side by side, just buy
both and add the cost of them to your invoice for the month.

 I think I may have asked you this once before but do you have someone that
you work with who does graphic design for websites that could help you
achieve what we're looking for with the site?

**Comment by cgladue** [comment]
hmm, my wife does graphics and videos for her job, unless its something really specific she may be able to resize/manipulate things and adjust them to fit, what are you looking for specifically ?

**Comment by cgladue** [comment]
also i think we could manipulate this layout to matcht eh "Store Listing" that you are talking about ...

https://friday-theme.firebaseapp.com/stores_01.html

**Comment by cgladue** [comment]
you want it to be similar to this page right ?  

https://shop.rewardseverywhere.co/category/index/11

**Comment by robgpeak** [comment]
I just meant from the point of retooling the template into a layout that
works for us, not necessarily just resizing images.

**Comment by robgpeak** [comment]
Yes on the category type of layout.  Again the idea is to make the overall layout look as close to the current layout we have in the site, and just taking advantage some of the new features the new template offers.  I.e. menus, modals, speed of rendering pages.. etc.

**Comment by cgladue** [comment]
rob, i have started redesigning the site (on the backend) take a look at https://shop.rewardseverywhere.co/ and let me know if the speed seems faster for you or not.

**Comment by robgpeak** [comment]
Fuckin' A!!!  Now THAT'S what I'm talking about!!!  I love it

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
One thing to note, it works MUCH faster when I am not logged in, but when I log in, it is slower at rendering pages...

**Comment by robgpeak** [comment]
I am guessing you know now that the site https://shop.rewardseverywhere.co/ is currently not working.

One other thing you can do to make the site faster is take out the OneSignal snippet of code from ALL the subdomains.  It is not really working the way I initially thought it would, and is actually redundant to Intercom which we use all the time.

**Comment by cgladue** [comment]
yea i am making a change it should be back up shortly and OK on the OneSignal

**Comment by robgpeak** [comment]
Actually, I just removed the OneSignal Key from the property dashboard, so
we should be all set there.

**Comment by cgladue** [comment]
@robgpeak what reasons if any other then the extension are there to keep complinks.co online for users ?  i am starting to run into cases where its getting difficult to manuver around that site and keep things in sync

**Comment by robgpeak** [comment]
no other reason other than extension and then notifying customers of the
new domain and that they would have to log in using their same credentials.

So what do we need to tell Addison to do?

**Comment by cgladue** [comment]
just to change the URL of his API to rewardeverywhere.co ... im not sure what else he needs to adjust, shouldnt take a long tiem i wouldnt think.

**Comment by robgpeak** [comment]
OK, I will tell him to do it now and let us know when it's done.

**Comment by robgpeak** [comment]
oops, closed it by accident.  @cgladue Let me know if you have some sort of working prototype of the site redesign.  Again, the primary objective is just to have better control over the menu and in essence to give you access to change anything you need to in the front end by yourself.

**Comment by cgladue** [comment]
Yep, will do, i have redesigned the server infrastructure to be faster and more scalable.  now thats complete and the domain name change is complete i can focus on this.

**Comment by robgpeak** [comment]
👍

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak @morganpeak 

can you please add the following to your hosts file (C:\Windows\System32\drivers\etc\hosts)
**18.223.205.3	shop.rewardseverywhere.co**

then close all browser windows and go to:  
http://shop.complinks.co 

right now its only the front page i want you to look at dont click any links yet they are all broken currently.

**Comment by robgpeak** [comment]
We both work on a Mac. Any idea what would be the compatible thing to do.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
standby

**Comment by cgladue** [comment]
How to Edit the Hosts File on macOS (Mac OS X)
Select the Go pull-down menu.
Then select Go to Folder from the menu.
In the box, enter /private/etc/hosts into the box.
Press Return.
A new Finder window will open and your Mac's hosts file will be selected, click and drag it out of the Finder window and drop it on your desktop.

**Comment by robgpeak** [comment]
Do you have a minute for a skype call where I can share my screen with you?
Thanks,

Rob

---

Rob Gallo
President
Peak Marketing
robg@peakmarketing.com
mobile: +1 631 682 5107
skype: robg888
bio: https://www.linkedin.com/in/peakmarketing

http://www.PeakMarketing.com <http://www.peakmarketing.com>

**Comment by cgladue** [comment]
if you cant do that then i can share my screen or something for you guys just let me know, i will have to step away for a little bit to do some yard work in a little bit

**Comment by robgpeak** [comment]
call me on skype it should only take 3 minutes

Thanks,

Rob

---

Rob Gallo
President
Peak Marketing
robg@peakmarketing.com
mobile: +1 631 682 5107
skype: robg888
bio: https://www.linkedin.com/in/peakmarketing

http://www.PeakMarketing.com <http://www.peakmarketing.com>

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/65822382-de649a80-e210-11e9-9082-4930aaba77cb.png)

**Comment by cgladue** [comment]
Made some of the changes you mentioned, does it look more like you here hoping ?

**Comment by robgpeak** [comment]
👍

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
do you still have concerns thus-far ?

**Comment by robgpeak** [comment]
Not at the moment.  I think you're right that it is the right template to
use so we have room to add new modules and features as they come up.

That said, I think it might still be worth having a creative web designer
who has experience in these types of sites, to give us an estimate.  I
would be able to tell from their portfolio the type of finished product
they develop.

Meaning, I think it would be worth a discussion with someone that has more
of a creative eye.  They would also be able to create all the graphics and
imagery we'll need for the site as well.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
So thinking about it, from an infrastructure and layout of what we already
have, I think you should continue to put it all together, and then when we
need imagery or any other bells and whistles, we can bring in a creative
eye.

**Comment by cgladue** [comment]
ok, i dont think we will need much changes (i changed the Partner logo from white to the blue myself) and my wife can do some stuff if images need adjusting and things for the time being to bring us to parity on the site as it exists today.  like you said any future additions if we need images then either she can do it or if its more complicated you can ask a 3rd party to

**Comment by robgpeak** [comment]
Ok sounds good.  Have her get creative with the images.  We used
www.pexels.com for a lot of the header images (photos)

As far as illustrations (graphics like on the How it works page) we just
want a consistent theme, so like when we want to add something new like
travel or games or surveys sections, we could use the same type of themed
illustrations.

I would also want to be able to put them (and other different but new
images) into an html email template for certain types of promotions.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
i assume you want to use Modals as much as possible including for login and registration ?

**Comment by robgpeak** [comment]
Yes sir.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak @morganpeak 

deployed Version 2019.09.29.1 to the test server today, with this update:

- Autocomplete box searches advertisers (i think you will REALLY like it) 

- You can login/logout using your shop.rewardseverywhere.co credentials (no modal yet)

- Hero is visible on small screens

**Comment by robgpeak** [comment]
I do like the autocomplete search.  It works really well.

I was able to log in.  Cool

Hero looks good on small screen.

Very nice job!

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
Closing this thread, opening a separate issue for each area of the new site to review and test and/or develop
