### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#278]

**Comment by robgpeak** [comment]
looks good

**Comment by robgpeak** [comment]
@cgladue For some reason, (maybe it was because of an update you did), the FAQ, Promotions, How It Works, Terms and Conditions, and Privacy Policy pages are not working any longer?

**Comment by cgladue** [comment]
it was because i added the site as a seperate partner and never created them for the new property 

should be all set, i know the heading is not lined up right thats fixed already too

**Comment by robgpeak** [comment]
OK.  Looks better.  The heading on the FAQ page reads Terms and Conditions.

Also the terms and conditions, and privacy links in the footer are also broken links.


<img width="438" alt="Screen Shot 2019-11-05 at 9 55 13 AM" src="https://user-images.githubusercontent.com/28393235/68218526-7db84280-ffb2-11e9-8edc-00e86a1f2b56.png">

**Comment by cgladue** [comment]
ok this is also fixed for the same reason

**Comment by cgladue** [comment]
the link to privacy policy will be fixed once i deploy

**Comment by cgladue** [comment]
should be fixed now too .. site has been deployed
