### ISSUE TITLE
Terms And Conditions Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#279]

**Comment by robgpeak** [comment]
Looks good.  Will this be updatable through the back end like the current site?

**Comment by cgladue** [comment]
Yes, nothing has changed on the backend config other then the "Style" box for partners will go away and instead there will be three new fields named primary color code, secondary color code and button color code, which will control the highlights and colors used on the site.

**Comment by robgpeak** [comment]
👍
