### ISSUE TITLE
Adding verbiage to authenticated ./rewards page.

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#28]
@cgladue Under the Transfer button, I would like to add the text "By clicking the Transfer button you agree that this process is irreversible, and the points transferred will become subject to the Terms & Conditions set forth by the {Rewards Program Name} program."

Then I would like the Term & Conditions to be a hyperlink that is controlled by the admindashboard/partner edit overlay, and it would pop open in a new tab...

See below for an example...

![uploads/0ab36d48-0ae3-4fcc-a71a-6bb1311e97d5/Screen Shot 2018-03-01 at 3.18.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0ab36d48-0ae3-4fcc-a71a-6bb1311e97d5%2FScreen+Shot+2018-03-01+at+3.18.08+PM.png)

**Comment by cgladue** [comment]
Its all added but because of angular the text links are being removed for some reason, only chris can fix it ... so assign this to hime when you can.

**Comment by robgpeak** [comment]
Not sure if this is a different issue, but I see the new text from the front end, (and it looks fine so far minus the link), but just for kicks I clicked the transfer button on my account 100086 and it make two separate transfers for 1000 each at 9:25am and should have only made one.  (I did it from my phone.  Not sure if that matters, but I figured u would tell you)

**Comment by cgladue** [comment]
yea it does matter, from the desktop it only does it once,.. this may be an issue for chris to fix since it has to do with whats going on with angular and stuff but ill take a look

**Comment by robgpeak** [comment]
@cgladue as a follow up to this original issue, the verbiage should only be visible if the person has enough available points to make a transfer.  Right now it is showing up even if someone does not have enough points, and it does not make sense.

**Comment by ChrisASearles** [comment]
I just pushed up some updates to this to hide it when not enough points are available and change the T&C link color, the link has been functioning properly though, the problem at the moment is the link value being passed for the xclub program is coming through as null.

**Comment by robgpeak** [comment]
sweet!
