### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#281]
Remaining Items

1. "View All" Button
2. "All Stores" Button
4. "View All Stores" in SHOP Menu Item

**Comment by robgpeak** [comment]
@cgladue I still have the host set the same way we did it during our skype call, but it is not connecting
<img width="685" alt="Screen Shot 2019-10-02 at 12 05 31 PM" src="https://user-images.githubusercontent.com/28393235/66061238-11f33d80-e50d-11e9-9450-3bda9d70d377.png">

**Comment by robgpeak** [comment]
Here are traceroute results to it side by side with xclub.rewardseverywhere.co just to show you the configuration
<img width="1206" alt="Screen Shot 2019-10-02 at 12 07 54 PM" src="https://user-images.githubusercontent.com/28393235/66061414-68f91280-e50d-11e9-8c0a-20bcb8785c8c.png">

**Comment by cgladue** [comment]
i bet your browser is trying https

manually type http://

**Comment by robgpeak** [comment]
that did not work, neither did incognito.

**Comment by robgpeak** [comment]
OK working now.

A couple of things:

1. Please make the cursor "left justified" instead of center in the search box.
<img width="862" alt="Screen Shot 2019-10-02 at 3 01 22 PM" src="https://user-images.githubusercontent.com/28393235/66073788-c600c280-e525-11e9-95cb-41e9bd2d0c12.png">

2. Change the Lorem Ipsum Paragraph below footer logo to read...
There's nothing like getting cash back on everything you buy, and with Rewards Everywhere, you'll points with every purchase you make through this site that you can exchange for {Rewards Program Name}.

**Comment by robgpeak** [comment]
I would also add the magnifying glass icon in the search bar as well

**Comment by cgladue** [comment]
ok

**Comment by robgpeak** [comment]
One other thing, but I am going to start a different issue for it...

**Comment by cgladue** [comment]
@robgpeak i changed the paragraph and added the search icon

**Comment by robgpeak** [comment]
Cool.  I can't look at it at the moment.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
How is the overall site redesign going @cgladue Are there any outstanding issues I need to look at?  I would like to get this done and live so we can add the travel section in there.

**Comment by cgladue** [comment]
nothing yet, got sidetracked for a bit witht he ipad display issue and the hotelpower issue but back on now

**Comment by cgladue** [comment]
@robgpeak i was thinking, for the stores to the right of the hero, would you prefer that they be dynamic and always the top 6 stores sorted by # of trips ?

**Comment by robgpeak** [comment]
Dynamic by the number of trips is a great idea.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Get as creative as you can with other great ideas and features to enhance
the UX...

**Comment by cgladue** [comment]
@robgpeak should be good to check everything
