### ISSUE TITLE
Making the header and navigation smaller in height

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#283]
Hey @cgladue I would like to make the header and the nav bar smaller in their pixel height, and have that carry over to the mobile experience.  The header and nav as they are now take up too much real estate on both desktop, and particularly mobile.

Please have a look https://www.loom.com/share/523d74f44877409eb25233fc483e4d09

I would also like the primary background color of the header to be the color blue like it is in the live shop.rewardseverywhere.co site, and the Rewards Everywhere logo would be white.

This would hold true for the parx site when we do it.  Meaning it would be black, and their logo would be white.

In both instances, I think the navigation menu would be white (or close to it) as well, with a shadow line underneath like the current live site if possible.

**Comment by cgladue** [comment]
@robgpeak can you check this out on mobile (havent done desktop yet) and excep the logo color and the menu bar color what do you think

**Comment by robgpeak** [comment]
I can't get to the site shop.rewardseverywhere.co on my laptop... And on my
phone it is the real live site not the new one you're working on.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
Hmm.  Must be your stupid mac ;)

Ill have to give you another option.  Because this obviously doesn't work well.  The site is fine for me.  And you can simulate a mobile device in chrome with F12.  Give me a little while and ill find an alternative.

**Comment by cgladue** [comment]
ok, try removing the hosts file entry and just go to https://shop.rewardseverywhere.co

**Comment by robgpeak** [comment]
Looks good.  Went from my phone and it looks really good as well.  Only
thing missing is the login "head and shoulders" silhouette on the mobile
view, and on the desktop view the header background color is still white?

**Comment by cgladue** [comment]
login is in the hamburger menu, because the menu bar looks busy with another item in it IMO

**Comment by robgpeak** [comment]
I disagree.  Granted the Parx Casino Xclub Rewards Everywhere logo is too big, I like the header containing everything including the login head and shoulders icon .  I would still leave the option in the hamburger menu as well.

Also we should make the hero image smaller in vertical height so it fits in to the mobile version a little better where you can still see some of the brands to choose from like you can in the current site.
![Screenshot_2019-10-06-11-59-46](https://user-images.githubusercontent.com/28393235/66271909-78d86580-e831-11e9-8be7-e89227cb52e5.png)
![Screenshot_2019-10-06-11-59-52](https://user-images.githubusercontent.com/28393235/66271913-7d9d1980-e831-11e9-95fa-da616255b12c.png)

**Comment by cgladue** [comment]
@robgpeak 

ok lets use this as the test site going forward:
https://test.rewardseverywhere.co

what you think ?  getting closer ?

**Comment by robgpeak** [comment]
Much closer. Looks good.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak  ok great, also i just pushed change for the desktop version to be smaller (ends up being same size as the old site) if you can take a look and signoff on that woud be awesome

**Comment by robgpeak** [comment]
You made the navigation blue in the desktop instead of the header.  We wanted to make the header, (the very top section that has the logo, search bar and login section) the primary site color, in this case blue, for xclub, black.  Other than that, it looks great!

**Comment by cgladue** [comment]
@robgpeak oh, mah bad i misunderstood, ok is it ok now ?

**Comment by robgpeak** [comment]
Looks good on desktop, but now the header is not there in mobile.
![Screenshot_2019-10-06-20-11-14](https://user-images.githubusercontent.com/28393235/66278306-cb3b7580-e875-11e9-828a-393e119c8579.png)

**Comment by cgladue** [comment]
yea i just noticed that its there the background is just white fromt he change .. ill fix it

**Comment by cgladue** [comment]
ok, try it now

**Comment by robgpeak** [comment]
Looks great.  Can you please check on the iPad.  I don't have mine with me.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
iPad Looks OK too
