### ISSUE TITLE
"View All Stores" Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#284]

**Comment by cgladue** [comment]
https://test.rewardseverywhere.co/stores/all

**Comment by robgpeak** [comment]
Looks good but again I am on my phone so just make sure that functionally
it does what it's supposed to do and that's fine

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak whenever you are settled take a look

**Comment by robgpeak** [comment]
Looks good.  I am sure it will load faster once it is live on AWS

**Comment by cgladue** [comment]
yea, the test server/database is slower (cheaper)  plus there are database indexes that will be added that will affect the speed too.
