### ISSUE TITLE
Start Trip Page (Games Disabled)

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#286]

**Comment by cgladue** [comment]
https://test.rewardseverywhere.co test out the "Shop Now" Buttons and the interstitial

**Comment by robgpeak** [comment]
It is not letting me sign into my account on my laptop, but when I click a shop now button on my phone, it immediately went and opened a new browser tab and took me to the store, but no interstitial.

**Comment by robgpeak** [comment]
Strange.  Now it IS working fine on my phone with the interstitial. (No games though, and I would assume that would be another different issue you will create when you start working on that part). but it is still telling me it is a bad user name/password for my login on my laptop.
https://www.loom.com/share/e0b419eadc364163a7078e3cf29a8a13

**Comment by robgpeak** [comment]
I found the main link in the macy's page goes directly to the macy's site without going to the interstitial page...  https://www.loom.com/share/8fd649afdc3e41ad98fb03d59ac97b07

**Comment by cgladue** [comment]
i know why the login isnt working, because i setup "test" as a partner so you never registered for a user account on there ... so why dont you do that now and try it again, i think i fixed the main shop now button on the advertiser too.

**Comment by robgpeak** [comment]
Sorry for the delay in getting back to you.  So you're saying I need to
register a new account on test?  But on my phone it is still working with
my original email and password.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea not sure why, it may be because its a copy of shop. and it knows that somehow

**Comment by robgpeak** [comment]
OK, just registered and saw it.  looks good.
