### ISSUE TITLE
strange message in email link

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#287]
@cgladue @morganpeak I just both of you a test email for an email we want to send out, and when I got the test message myself and clicked on the Boston Proper link just to see if it worked, I got the message below.  Please let me know if you got the same?
<img width="950" alt="Screen Shot 2019-10-11 at 12 47 47 PM" src="https://user-images.githubusercontent.com/28393235/66669696-0945ea00-ec26-11e9-96fb-d2588058611a.png">

**Comment by robgpeak** [comment]
@cgladue After some digging in Intercom I found this (image below).  I am not sure if you can get to this link and see the same thing I am, but if not, let me know if there is anything I can do to fix it.

https://app.intercom.io/a/apps/d8m2yyar/settings/identity-verification/web

I clicked on the link for missing user hashes and it shows an identity verification secret number, but I did not want to paste it here...  Let me know if you need it and I can text it or email it to you if you don't already have it. 

<img width="1102" alt="Screen Shot 2019-10-11 at 2 32 11 PM" src="https://user-images.githubusercontent.com/28393235/66675871-3e593900-ec34-11e9-923e-f7a67e98c230.png">

**Comment by morganpeak** [comment]
Did you try it again? I changed the default link because when I went to check it out it looked weird. I still never received the test email

**Comment by robgpeak** [comment]
@morganpeak I just sent you another test email

**Comment by cgladue** [comment]
Hmm thats odd ok on it

**Comment by cgladue** [comment]
I didnt get any warning when doing it from my phone.

**Comment by robgpeak** [comment]
It could have been just some fluky thing on my side. What about the information inside intercom? Do I need to do anything there

**Comment by cgladue** [comment]
I am actually in rochester NY for the night looking at colleges with my daughter.  Cornell tomorrow then driving home so i will try to look now and if i cant see anything look in more detail tomorrow night if thats ok

**Comment by robgpeak** [comment]
Ok no problem

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok so i think this is something thats alwasy been there and is optional setup, its not required and we havent ever set it up to this point ...
