### ISSUE TITLE
Missing transactions 

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#288]
@cgladue If you look at https://xclub.rewardseverywhere.co/dashboard/admin/profitability for the current month, and then https://xclub.rewardseverywhere.co/dashboard/partner/purchases for the current month, you'll see there are some missing transactions in the profitability section.

**Comment by cgladue** [comment]
issue is on new database there was a date field that used to default to today but now its defaulting to 0001-01-01 so i will correct manually and fix int he code for next deploy

**Comment by cgladue** [comment]
it show show correct now.
