### ISSUE TITLE
Hotel power not working

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#289]
@cgladue please look into hotel power as an affiliate.  It is still on our site but when you click on a shop now button it says it's a bad link

https://xclub.rewardseverywhere.co/stores/index/6890

**Comment by cgladue** [comment]
i think this is a case where it does not get reported by linkshare anymore in the API, it just dissappears from the API totally... so i didnt know i need to deactivate it, testing some workarounds now.

**Comment by robgpeak** [comment]
ok
