### ISSUE TITLE
Entry fields missing from admindashboard/partners edit screen

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#29]
@cgladue I just realized we are missing some data entry fields in the new format of the partner edit screen.  The Hero images for both authenticated and unauthenticated are the only ones I can remember off hand.

While you're in there monkeying around, maybe you should add a field in there that would let us upload a file to use as the subdomain's .ico

![uploads/029530ad-dadf-4a40-8880-0b43f0b7485b/Screen Shot 2018-03-01 at 3.30.35 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F029530ad-dadf-4a40-8880-0b43f0b7485b%2FScreen+Shot+2018-03-01+at+3.30.35+PM.png)

**Comment by cgladue** [comment]
All Set
