### ISSUE TITLE
Balloon background on ipad

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#290]
@cgladue please have a look at the background of the Xclub.rewardseverywhere.co/travel on the ipad and see if you can see why it's behaving that way.  It is taking up the whole screen, and in fact the rest of the page does not load when you scroll down.
![1571161827839-1458115746](https://user-images.githubusercontent.com/28393235/66856230-a318da00-ef39-11e9-9ec2-922fc307dcce.jpg)

**Comment by cgladue** [comment]
yea i started looking at this not sure why on the ipad it does this but on iphone and desktop it does not :-( grr

**Comment by cgladue** [comment]
@robgpeak think its better now, weird behavior only on an ipad it seems

**Comment by robgpeak** [comment]
👍
