### ISSUE TITLE
WorldWinner games integration

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#291]
@cgladue I wanted to start a thread about the integration of WorldWinner games on the rewards everywhere site.

It is not some much an integration as it is a pure affiliate model like we have with all the stores we have.  I am going to forward you the email thread conversation that I had with them so hopefully it makes more sense. 

Even after you read it, I think it would be helpful for you and I to speak on the phone just to clarify everything.

**Comment by robgpeak** [comment]
@cgladue Here is the **games page** mockup as well as a zip file with the twelve images to use on the page.

Compete in your favorite games to win real money, and earn points!

![Games Page Mockup](https://user-images.githubusercontent.com/28393235/68149832-9241ff80-ff0c-11e9-81ff-ed731ccb0ff3.jpg)
[WorldWinner_Images_Including_Points.zip](https://github.com/robgpeak/CompLinks-xclub/files/3805616/WorldWinner_Images_Including_Points.zip)

**Comment by cgladue** [comment]
got it, page and content added, will let you know when i deploy

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/68219418-f10e8400-ffb3-11e9-99a3-9ffbfb05bfb8.png)

**Comment by cgladue** [comment]
this is live on test site now:

https://test.rewardseverywhere.co/games

**Comment by robgpeak** [comment]
All's we need are the working links from them and we'll be all set, but I am going to close this as an issue in the meantime.
