### ISSUE TITLE
Rewards Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#294]

**Comment by cgladue** [comment]
https://test.rewardseverywhere.co/myrewards

**Comment by robgpeak** [comment]
So you know I am packing up my car and we are driving down to Florida today
and tomorrow so I won't be able to really look at this on a regular basis
unless we stop. I did notice the rewards page slider is not working on
mobile so please check that

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok thanks no rush whenever you can and i will look at that now.

 safe travels.

**Comment by cgladue** [comment]
@robgpeak ok take a look when you are settled

**Comment by robgpeak** [comment]
Shit, when I tried to test the forgot password link I logged out, not I can't log back in (I'm still using my phone to test everything).  This is what happens when I try to log in.
![Screenshot_2019-10-27-22-36-26](https://user-images.githubusercontent.com/28393235/67647903-48ed2100-f90a-11e9-997d-8889b02c9b43.png)

**Comment by cgladue** [comment]
hmm can you reproduce this ?  i tried and it doesnt give me any error from my phone or my PC

**Comment by robgpeak** [comment]
I now have 0 points in my robg@peakmarketing.com account, so the slider for
the points does not show up.  Can you put a bunch of points in my account
so I can try.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok all set

**Comment by robgpeak** [comment]
Points are in there on my dashboard but when I go to the reward section
they're not in there

https://youtu.be/SV4fIiGxREE

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
it may be stuck in cache, can you logout, close browser window and then log back in ?

**Comment by robgpeak** [comment]
Yeah it was.  It shows up now, but not sliding properly.

https://youtu.be/Tg0utd_pAUo

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
hmm, i do not get that behavior on my iphone.  i will have to test with an old android device i have later tonight ...  ugh

**Comment by robgpeak** [comment]
On other thing on that rewards page, it is should pending points and available points, but should be showing available and lifetime like it does on the live site.

**Comment by cgladue** [comment]
corrected the point balances ... i tested my android phone and it worked as i expected it to work i cant reproduce the issue you are having i may find a different "Slider" to use since this one seems a little buggy ...

**Comment by robgpeak** [comment]
I know you corrected the points balance in this might have been a separate
issue but it still shows pending points an available points instead of
available points in lifetime points in the rewards page

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
its uploading now, the site hasnt been updated yet

**Comment by cgladue** [comment]
Point totals should be updates and now displaying the right thing, still working on slider.

**Comment by robgpeak** [comment]
On my rewards page it's showing pending points and available points. But
it's supposed to be showing available points and lifetime points like it
does on the current site. I checked it in incognito window as well.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
i read your last update wrong, ill change it back i thought thats the way you wanted it mah bad

**Comment by cgladue** [comment]
ok fixed
