### ISSUE TITLE
Shopping Trips Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#295]

**Comment by robgpeak** [comment]
I'm not sure what I'm supposed to be looking for?

**Comment by cgladue** [comment]
sorry i clicked the assign button too quick its deploying now.

**Comment by cgladue** [comment]
ok, now its deployed

https://test.rewardseverywhere.co/trips

**Comment by cgladue** [comment]
actually i am going to pull these back to tweak the mobile view a little more... sorry

**Comment by robgpeak** [comment]
👍
