### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#296]
https://test.rewardseverywhere.co/account/dashboard

**Comment by robgpeak** [comment]
looks good, but the table with the data needs to be able to scroll sideways in order to see all the columns.  I like the columns WAY better than the old (current) boxed method of seeing the recent shopping trip data

**Comment by robgpeak** [comment]
On the mobile that is...  Meaning the sideways scroll needs to be available on the mobile view.

**Comment by cgladue** [comment]
updated
