### ISSUE TITLE
Point history Page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#297]
https://test.rewardseverywhere.co/pointshistory

**Comment by cgladue** [comment]
actually i am going to pull these back to tweak the mobile view a little more... sorry

**Comment by robgpeak** [comment]
Understood.  Again, I would much rather sideways scroll to any other
method.  I know it is not standard UI/UX, but believe me it will be fine.

**Comment by cgladue** [comment]
ok, lets try it again

**Comment by robgpeak** [comment]
Awesome
