### ISSUE TITLE
Game Interstitial

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#298]

**Comment by cgladue** [comment]
@robgpeak check out test, right now i have scratch game only configured but everything should be working.

if you are OK with it then ill get the other two games done

**Comment by robgpeak** [comment]
I'm trying to test it but I am not able to interstitials and I can't seem to turn it on in the profile.  I check the box and saved it, but it would not save. See the error message.

My account number is 101950

![Screenshot_2019-11-20-21-00-35](https://user-images.githubusercontent.com/28393235/69294145-ff29ea80-0bd8-11ea-89f0-52da7a3ad9a4.png)

**Comment by cgladue** [comment]
i think its fixed, it will be about 20 minutes till its done deploying ill let you know then

**Comment by cgladue** [comment]
@robgpeak ok try it now

**Comment by robgpeak** [comment]
We're going to need to make the game show up above the fold so we're going to have to tighten up the text at the top yeah
![Screenshot_2019-11-20-21-54-18](https://user-images.githubusercontent.com/28393235/69300220-8c247200-0be0-11ea-901c-0c14b167aba2.png)

**Comment by cgladue** [comment]
would you like to get rid of the text and just put the game there then ?  because they aint both gonna fit i dont think

**Comment by cgladue** [comment]
unless you want to signifigantly reduce the font size perhaps

**Comment by robgpeak** [comment]
Yeah try to make the text much smaller maybe 10 or 12pt font, and remove as
much white space as possible with it looking too crammed.

**Comment by cgladue** [comment]
k

**Comment by cgladue** [comment]
is this enough "above the fold" ?
![image](https://user-images.githubusercontent.com/7914133/69388142-ff3bf000-0c95-11ea-8fdc-9c4ef4349c24.png)

**Comment by robgpeak** [comment]
No, not for me.
![Screenshot_2019-11-21-19-40-22](https://user-images.githubusercontent.com/28393235/69388482-f39cf900-0c96-11ea-915d-1bb0ed872e22.png)

**Comment by cgladue** [comment]
i havent uploaded it anywhere yet ;)

**Comment by cgladue** [comment]
hold on ill put it on the server

**Comment by cgladue** [comment]
ok try it again

**Comment by robgpeak** [comment]
Oh.  Can you tighten up the line space in between the lines Nice Chad earn
2 points per dollar spent on this trip? similar to the line space between
feeling lucky and play even more points. Actually the font size can come
down a little bit also on the top portion.

>

**Comment by cgladue** [comment]
ok one moment

**Comment by cgladue** [comment]
how about that ?

**Comment by robgpeak** [comment]
Yeah, I can live with that.

Next issue still within the Game Interstitial would be to make sure that the functionality when someone wins "0 points" it still shows the shop now button.  It currently does not.

<img width="831" alt="Screen Shot 2019-11-21 at 7 48 29 PM" src="https://user-images.githubusercontent.com/28393235/69388890-65297700-0c98-11ea-8049-81a313078b8d.png">

**Comment by cgladue** [comment]
ok i set it to always pick 0 points, try it again

**Comment by cgladue** [comment]
i deleted your old games played so you can just go back in again user same user

**Comment by robgpeak** [comment]
cool.  works well.

>

**Comment by cgladue** [comment]
ok ill get the other 2 games looking the same and let you know

**Comment by cgladue** [comment]
@robgpeak take a look at the wheel and the slots 

wheel is more likely to show then the slots currently 

on test

**Comment by robgpeak** [comment]
They both work fine, however the shop now button on the interstitial launched a new tab, and we don't want that to happen.  So the main shop now button on the regular site should launch a new tab as it does, but the interstitial tab (with or without the game) should the the tab that the advertiser's site shows up in.

**Comment by cgladue** [comment]
Ah ok

**Comment by cgladue** [comment]
@robgpeak all set
