### ISSUE TITLE
Campaigns: Refresher course on the 50 points for a click in an email

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#30]
@cgladue I wanted to see if you could remind me how it works when I want to place a link in an email.  

Is it possible to use the GUID as a parameter in the URL string to both track the click for the rewards purposes, AND send the user to the specific page.

So for example links might look like this:

Macys: https://xclub.complinks.co/stores/index/6789?GUID=CtinMvOVD8GPqCrGWAEYttyhlfZCMvzJ

and 

Walgreens: https://xclub.complinks.co/stores/index/5292?GUID=CtinMvOVD8GPqCrGWAEYttyhlfZCMvzJ

or something like that...

Meaning, I would not want to just send them to the front page if they click on a specific advertiser.

**Comment by cgladue** [comment]
umm thats not possible right now but totally doable pretty easily

**Comment by robgpeak** [comment]
So what does that mean, doable pretty easily...?  When could you get it done?

**Comment by cgladue** [comment]
this week



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Ok cool.

**Comment by cgladue** [comment]
ok rob you can now use 1 of two types of links... a link that takes you to the front page of the site at: https://shop.complinks.co/campaign/clicktrack/4MxoyNmb3lLCyEkoKDmKq2lT4NWBm1iI

or a link to a specific store at: https://shop.complinks.co/stores/index/5694?guid=4MxoyNmb3lLCyEkoKDmKq2lT4NWBm1iI

**Comment by robgpeak** [comment]
Excellent
