### ISSUE TITLE
Change Password Fields

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#302]

**Comment by cgladue** [comment]
https://test.rewardseverywhere.co/account/myprofile

**Comment by robgpeak** [comment]
Not exactly what I'm looking for here but I did test the forgot your password link and it worked so I guess you can close this one

**Comment by cgladue** [comment]
just double checking my checks basically ... make sure i didnt overlook anything

**Comment by robgpeak** [comment]
Looks good.  I did not test functionality however.  Did you?

**Comment by cgladue** [comment]
yes i did
