### ISSUE TITLE
Getting "points /$1 spent" all in one line

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#303]
@cgladue have a look at the screenshot and see how it wraps the text to the next line, and then you can't see the "shop 'store' deals" as it gets hidden under the shop now button.

I just noticed at the bottom of the homepage all of the featured deals none of them have "up to" on them so it fits all on one line and looks much better. I'm not sure how we can manage that if it is an up to but we can either make the text smaller or just eliminate the up to and deal with the ramifications after the fact. Meaning if someone only gets two points when they expect to get for we would just augment the difference. At The Limited volumes that we're doing now I don't think it makes that much of a difference. Anyway let me know
![2019-10-28 10 10 17](https://user-images.githubusercontent.com/28393235/67687221-605df580-f96e-11e9-887e-af3fc7bb8c42.png)

**Comment by robgpeak** [comment]
@cgladue any thoughts on this?

**Comment by cgladue** [comment]
yea working on it i think we can make it a single line ....

**Comment by cgladue** [comment]
Font size will now change when there is > 19 characters in that line.

**Comment by robgpeak** [comment]
That looks much better, have a look at this screenshot though.  Why would the one at the bottom right with 0.2 points/$1 spent be on two lines?

Also, wtf, only 0.2 points means theya re only paying us 0.4...?  That seems weak.

![2019-11-03 15 29 47](https://user-images.githubusercontent.com/28393235/68091546-1b92fc80-fe4f-11e9-836e-68eb6ad191f6.png)

**Comment by robgpeak** [comment]
I just looked it up on CJ, and yeah, they're only paying 0.5%. Oh well.

**Comment by cgladue** [comment]
found the reason, changed it and uploading now...

**Comment by cgladue** [comment]
@robgpeak ok try now.

**Comment by robgpeak** [comment]
Perfect
