### ISSUE TITLE
Travel page issues

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#305]
@cgladue please have a look

https://youtu.be/522-TcDHxAU

**Comment by robgpeak** [comment]
@cgladue some things are showing up a little squirrely on the mobile version all the travel page. Have a look.

https://youtu.be/-DXRaCyeKhs

**Comment by cgladue** [comment]
hmm, in the place you created the widget for amazon, is there a option to create a mobile friendly one or a smaller / narrower one ?  the widget itself does not like being shown on a small screen i am guessing there is a way to create a mobile version of the widget on amazon and give me the code like you did before ?

**Comment by robgpeak** [comment]
Try this, or a variant that works on our site...

<div id="amzn-assoc-ad-956a334c-867a-447d-a104-d938a49ef4b3"></div><script
async src="//
z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=956a334c-867a-447d-a104-d938a49ef4b3
"></script>



Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
i made some changes and used the new widget what do you think ?

**Comment by robgpeak** [comment]
The new widget looks good but have a look at the way bottom of the page and
see that it looks like it cuts off without scrolling all the way to the end
for some reason

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
hmm, thats weird, what about now ?  its tough because its a scrollable page within a scrollable page ...

**Comment by robgpeak** [comment]
Much better on the scrolling issue, but now the Amazon ads are not
"luggage" related like they were originally.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok i had to mix and match part of the old code you gave me and the new code ... see if luggage shows up now ?  it does for me

**Comment by robgpeak** [comment]
Nope.  Still the same thing for me...  I did it in an incognito window as well.
![Photo on 11-4-19 at 9 47 AM](https://user-images.githubusercontent.com/28393235/68129881-5dbc4c80-fee8-11e9-95ab-7392fa598c2f.jpg)

**Comment by cgladue** [comment]
hmmm, is there a way to specify a search for this widget ?  because the old one had a bunch of parameters you gave me and this one was only two lines with no parameters...  

its an issue with the widget we need to tweak it on amazon i think

**Comment by robgpeak** [comment]
I am going to text you the password, but here is the link you can go to to see the "luggage" ad and the code for it. https://affiliate-program.amazon.com/home/ads/adcode/saved?ac-ms-src=ac-nav

Then you can go to https://affiliate-program.amazon.com/home/ads/adcode/recommendation?ac-ms-src=ac-nav to create other ones.

The login email is info@rewardseverywhere.co
Password: I will text you now.

**Comment by cgladue** [comment]
ahh i see what happened, you created a "Reccomended Ad" which uses your browsing history and page content to suggest products, i am creating a "Search" ad now for Luggage

**Comment by robgpeak** [comment]
Ah.  Ok

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
Rob after bashing my head against the wall the HTML site that we converted is just not playing nice with these widgets ...

i spend like 30 minutes to start making it native in the site (no iFrame, 100% integrated into RewardsEverywhere) here is a start, what do you think ?  think we can make it look nice enough to meet your taste ?

![image](https://user-images.githubusercontent.com/7914133/68143299-2907bf80-feff-11e9-941f-e7c885526a18.png)

**Comment by robgpeak** [comment]
if if it just one row of 4 boxes across, that would be way better.
Otherwise, if it HAS to be 2 rows (8 boxes), we will be better off pitting
it much further down the page, if not at the bottom.

>

**Comment by cgladue** [comment]
no, you can change to only 1 row...

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/68143893-6caef900-ff00-11e9-9cc9-cc2f5c778c1a.png)

**Comment by robgpeak** [comment]
Yeah, that would be fine.  Let's see how it looks on mobile.

**Comment by cgladue** [comment]
its now live on the test site if you want to take a look

**Comment by cgladue** [comment]
https://test.rewardseverywhere.co/travel
