### ISSUE TITLE
Hero Slider Specs

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#306]
@cgladue I wanted to see if you could get me the specs for the images in the slider section of the home page on the test site so I can start monkeying around with different images and text overlays.

**Comment by cgladue** [comment]
ill get you this tonight, also ill update the backend to let you enter the color codes instead of that stupid parter styling text

**Comment by robgpeak** [comment]
cool

**Comment by cgladue** [comment]
the native size is 850x400px, but on the site its limited to 650x450px and scales down from there

**Comment by robgpeak** [comment]
So is there a way I can log into the new back end and change the hero
images and the copy that appears over them?

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea, you can goto https://test.rewardseverywhere.cp/dashboard and do that just like you would today

**Comment by robgpeak** [comment]
getting an error when I try to save a new color with RGB numbers but only
sometimes. Have a look

https://youtu.be/sH61vvElrrU

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
found the reason, there was too many characters and it wouldnt fit in that field in the DB, i made the column int he DB wide enough to support three numbers of 3 chars

uploading now.

**Comment by cgladue** [comment]
ok try now

**Comment by robgpeak** [comment]
Working

**Comment by robgpeak** [comment]
Hey @cgladue in looking at the template of the site that you used as a base for the new test.rewardseverywhere.co, the home page has a slider (scrolling through multiple images with different text and links on them), can we do something like that and control the content from the back end?  https://www.loom.com/share/c637f0e76c474a58a2c33203c62592f0

**Comment by cgladue** [comment]
yea we can do that i just used 1 image since thats whatt he site had originally, can we add this after get the site live and functioning the same as the one thats there now ?

**Comment by robgpeak** [comment]
Yeah, whenever you want to implement it.  I just wanted to be able to
monkey around with it in test mode before it goes live.

>

**Comment by cgladue** [comment]
@robgpeak actually i threw it in there now...

there is another option under the actions button on the property list called "Property Hero Images" select that like you would for promos, faqs etc and monkey around.

also the partner modal has travel, games switches so you can turn those on and off, just remember if you make changes to partner settings you have to close all browser windows and go back and visit since its cached per session.

**Comment by robgpeak** [comment]
@cgladue the hero image is not responsive.

![Screenshot_2019-11-13-08-36-14](https://user-images.githubusercontent.com/28393235/68768992-8da6d680-05f1-11ea-84c4-a7bc04b2fac0.png)
