### ISSUE TITLE
Navigation menu adjustments

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#307]
@cgladue Please remove "Home" from the navigation bar.  The main site logo should just link back to the home page.  It currently does NOT in the mobile view, but it should.

Then we need to add just to the right of "Shop", "Travel" (linking of course to the travel page. Then to the right of Travel in the nav, "Games".  In the games page, I will get you the images to include that will link to the WorldWinner site.

As for the rest of the navigation, it would continue to the right with all the other items that are already there.  Promotions, How it works, etc.

**Comment by cgladue** [comment]
just need the content for "Games"
