### ISSUE TITLE
Shopping trip 7413

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#308]
@cgladue I made a purchase at target.com for $14.99 the other day and I picked up the order already but it's not showing up on our end see if you can tell if they tracked the order

**Comment by cgladue** [comment]
i do see the purchase, and it shows $0 comission from Target ...

order ID 9261148523469
date: 2019-11-02 14:12:30.000

**Comment by robgpeak** [comment]
Ok Target just sucks:)

**Comment by robgpeak** [comment]
I just looked in https://shop.rewardseverywhere.co/dashboard/admin/profitability and I see for some reason the Target shopping trip that I made on test.rewardseverywhere.co (trip id 7413) was credited to a different user (image below)

The other issue is, it looks like the shopping trip IDs you're using on test have already been used?  Meaning 7413 is an older trip that was already used.  (image at the bottom)

<img width="571" alt="Screen Shot 2019-11-04 at 12 37 23 PM" src="https://user-images.githubusercontent.com/28393235/68143997-a41da580-ff00-11e9-822b-2ee706564d00.png">

<img width="1193" alt="Screen Shot 2019-11-04 at 12 40 20 PM" src="https://user-images.githubusercontent.com/28393235/68144155-08406980-ff01-11e9-849d-9058a8033bbd.png">

**Comment by cgladue** [comment]
ooooo you made that trip on test ... uhh yea we cant make actual shopping trips from the test site because it will do just this, there is no test CJ, LS or IR API so anything bought (test or live) will come through the live API from the networks.

**Comment by robgpeak** [comment]
understood
