### ISSUE TITLE
Internal page layout consistency - reducing the space under the nav bar

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#309]
Can you please take all the new internal pages that you just did, (which look great by the way, and in fact I like the alphabetizing of the All Stores section at the bottom of each category), and make them all have the same distance between the bottom of the nav bar and the area that reads Featured Stores in 'Automotive' on the page https://test.rewardseverywhere.co/category/10 as an example.

Meaning, I would ALL pages to have the same distance from the... Ah, fuck it, here's a video 😀 https://www.loom.com/share/b0a58db12d28408a8e0ccbac7f59f365

**Comment by cgladue** [comment]
Sure can do. Makes sense

**Comment by cgladue** [comment]
@robgpeak how about now ?

**Comment by robgpeak** [comment]
Just sitting down for a charity poker event.  I will be offline for a while.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
No rush im heading to boston for a haircut so good luck in the event 👌

**Comment by robgpeak** [comment]
Had a chance to look. Looks great.
