### ISSUE TITLE
Campaign points are not showing in Available, but ARE in lifetime balance total

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#31]
@cgladue the points that get credited to someones account from a campaign DO show up in the lifetime points balance, but not in the Available points balance, and they should.

**Comment by cgladue** [comment]
hmm, ok



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
ok, i believe this is all set now too.

**Comment by robgpeak** [comment]
Nope.  Just tested it on a brand new account that I just set up to test the new guid tracking from the email (which works great), but the 50 points I got went into lifetime instead of available.

<img width="902" alt="screen shot 2018-03-04 at 10 12 13 am" src="https://user-images.githubusercontent.com/28393235/36947036-8e512c10-1f94-11e8-8d0e-c632c1bb200a.png">

**Comment by cgladue** [comment]
How About now ?

**Comment by robgpeak** [comment]
working properly now!
