### ISSUE TITLE
new signups not getting 100 points

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#311]
@cgladue It looks like since Sept 21, new customers who sign up at NOT getting the 100 points automatically.

Please have a look
https://www.loom.com/share/e9903534bee840788b34de2d90285eaa

**Comment by robgpeak** [comment]
I jsut tried from firefox after deleting all my cookies, and you can see the whole process here.  Please see if you can get this fixed ASAP.  Let me know if I can do anything to help.

Different video
https://www.loom.com/share/17e495836eb845ebbae6991bb479cc22

**Comment by cgladue** [comment]
can you try this again ?

i think it was the URL that mailchimp was supposed to post the data to was *.complinks.co so it was failing :|

**Comment by cgladue** [comment]
you will still get the error on registration im working that now.

**Comment by robgpeak** [comment]
let me know when you have that sorted out I'll do both at the same time
meaning I'll just register one time and make sure it works all the way
through

**Comment by cgladue** [comment]
@robgpeak ok try it now, i cant test the 100 points thing but i assume it will work now. and i believe the error to be gone, it was leftover from CINT grr

**Comment by robgpeak** [comment]
Excellent. working as expected.  thanks
