### ISSUE TITLE
points redemptions pending

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#312]
@cgladue I never saw this before.  There looks like there are three transfers of points to this guys xclub account that are all pending... and then there is a "complete" button that looks clickable.

Please let me know what you make of it.
<img width="1186" alt="Screen Shot 2019-11-07 at 3 41 36 PM" src="https://user-images.githubusercontent.com/28393235/68426322-e6035180-0175-11ea-9f61-300085ca138c.png">

**Comment by cgladue** [comment]
This usually means that the transfers didnt complete successfully.... let me email parx and make sure they have updated the firewall rules like i requested a while back ...

**Comment by cgladue** [comment]
ok i just emailed them, ill let you know what they say .

**Comment by robgpeak** [comment]
do you think maybe it's because it's coming from rewardseverywhere.co
instead of complinks.co

>

**Comment by cgladue** [comment]
shouldnt, they do it by IP they shouldnt know the difference.

**Comment by robgpeak** [comment]
no response from them yet?

**Comment by cgladue** [comment]
they responded saying the network admin was out of the office i asked them to let me know when hes back and is able to take a look

**Comment by cgladue** [comment]
i changed the name of the "Complete" button to "Retry"

![image](https://user-images.githubusercontent.com/7914133/68995399-7a973f00-085b-11ea-83f1-7514cfad6567.png)

Clicking this button will retry to send the redemption to the partner, all i did was go and click each button and it was successful this time, must of been a temporary hiccup on that day i guess  but they are all set now, just sent al three through

**Comment by robgpeak** [comment]
ok
