### ISSUE TITLE
Final Site Walkthrough

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#313]
i have gone through all the functions and i think they are working and look at least the same as currently they do, can you do the same and, when you are comfortable, we can schedule a date to launch the new site that is 100% without angular

**Comment by robgpeak** [comment]
I think the site looks great!  Morgan really likes it too.  We are ready to launch ASAP.

A couple of things we need to keep in mind:

1. I will have to get approval from Parx to release the Games section to their users.  I don't think it will be a problem, but I just want to get their sign off.  I am going to send them the link to the test.rewardseverywhere.co site (once of course GSN/World Winner gets their shit together with tracking).

2. We are no longer using Groove at all, so I don't know if there is any API call still happening between us and them, but if there is we can eliminate it.

3. I see the Hero image slider is rotating pictures (👍) but it is not editable in the current back end.  I know you mentioned it would be adjustable once the site was live, so let me know what that might look like so I can play around with it.

I think that's it for now.

**Comment by cgladue** [comment]
ok, i will remove groove fields on the partner admin modal as well as in the sites code.
should i add a field like we did for surveys that says "Earn points for playing games" or something ?  do you see any properties that would NOT want it enabled for them only ?

**Comment by cgladue** [comment]
also can i remove the surveys enabled field as well ?  since surveys are not happening anytime soon ?

**Comment by robgpeak** [comment]
I would leave ALL the modules as options for each individual sub domain,
including surveys.  I will revisit the pollfish option.  Again, keeping in
mind that at the moment, this is a more of a selling feature to
prospective clients that and actual revenue generator.

Meaning, if in the back end if xclub is "Travel=true" "Games=false"
"Surveys=false", on the front end all their users would see in the
navigation of the site is "Travel", but if we changed the Games to = true,
then that too would also show up in the navigation and be accessible.

>

**Comment by cgladue** [comment]
ok so ill add a switch for travel as well then

**Comment by robgpeak** [comment]
yes, because if we were to find a client that was in the travel industry
who wanted to use the platform, we would want to turn off travel for that
subdomain.

>

**Comment by cgladue** [comment]
gotcha

**Comment by cgladue** [comment]
is oneSignal also no longer used ?

**Comment by robgpeak** [comment]
yeah, at the moment we are no longer using them.  Unless they can have a
'persistent' messaging/notification system, it is just not making sense.
Meaning, it only sends a notification IF the person is online and on your
website.  So the short answer is no, we are not using them at the moment.

>

**Comment by cgladue** [comment]
> A couple of things we need to keep in mind:
> 
> I will have to get approval from Parx to release the Games section to their users. I don't think it will be a problem, but I just want to get their sign off. I am going to send them the link to the test.rewardseverywhere.co site (once of course GSN/World Winner gets their shit together with tracking).
> 
> We are no longer using Groove at all, so I don't know if there is any API call still happening between us and them, but if there is we can eliminate it.
> 
> I see the Hero image slider is rotating pictures (👍) but it is not editable in the current back end. I know you mentioned it would be adjustable once the site was live, so let me know what that might look like so I can play around with it.

#1....  i added games_enabled and travel_enabled switches in the partner admin, i will default them to off and you can turn it on when you want to.

#2.... i commented out the second slide for the hero, i will finish up the ability to add multiple hero slides and release that after the site is live, and you can play on test

#3..... One Signal and Groove fields have been removed, as well as Partner StyleInfo, now its is just the three color codes

**Comment by cgladue** [comment]
let me know when you would be OK with taking the site down for 30 minutes to an hour max to update the database and deploy the new site ... im not sure what time is best

**Comment by robgpeak** [comment]
I think it's Tuesday afternoon at 10 minutes after 11 would probably be the
perfect time. I can't see too many people using the program at the moment
so if you want to let it right now pull the trigger.

**Comment by robgpeak** [comment]
I'm assuming you know about this...
<img width="555" alt="Screen Shot 2019-11-12 at 2 05 20 PM" src="https://user-images.githubusercontent.com/28393235/68701815-96e26580-0555-11ea-9b2e-f1d437f2a3b1.png">

**Comment by cgladue** [comment]
where is this happening ?

**Comment by robgpeak** [comment]
in an incognito window at test.rewardseverywhere.co
