### ISSUE TITLE
Intercom instead of MailChimp

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#314]
@cgladue I have what may seem like a stupid question, but I wanted to ask anyway.  Is it possible to use Intercom instead of Mailchimp to develop the initial email list?  Meaning, as it stands now when someone fills out the form to register on our site, it populates the list and uses the optin process from mailchimp, but we really don't use mailchimp, we use Intercom for all outgoing messages.

So the question is, can we eliminate mailchimp and have Intercom capture the initial email address and then send a message to the customer asking them to confirm their email so we can credit their account the 100 points.

**Comment by cgladue** [comment]
hmm, can you create a mail template in intercom ?

i think at the time intercom didnt offer email sending services that is whyyou choose mailchimp .. does intercom offer that now ?

**Comment by robgpeak** [comment]
Yes it does allow template emails.  Let me create one and see how it goes then we can test it out.

**Comment by robgpeak** [comment]
Actually I just had to ask the Intercom people if this was even possible.  I will let you know.

**Comment by robgpeak** [comment]
Here is their response:  Let me know if you think this is something we can test.  It's all greek to me.

In essence we would like to eliminate the need for MailChimp completely and use Intercom from the very beginning of the email/registration process.  This way we only have to administer one list.

--

Hey Rob 

Actually not at all! This is possible but it would require you to create some custom code.

You can create a new incoming message (it will appear in your inbox) from a form by using our API. You also create the user at the same time if they don't exist. The below Ruby example allows you to do this, but the same logic is applicable to any other language and it can be set up both for users and leads.

 def send_contact_form_to_intercom(email, name, message)  
begin    
  user = Intercom::User.find(:email => email)
rescue Intercom::ResourceNotFound    
  user = Intercom::User.create(:email => email, :name => name)  
end  
Intercom::Message.create({    
  :from => {      
    :type => 'user',      
    :email => email    
  },    
:body => ("VIA THE CONTACT FORM:\n\n" + message) }
)
end
PS. Have you checked out our Operator > Qualification feature?
This can ask questions to your Leads after they message in, meaning you get the conversation first and can then qualify to never lose that message if they choose not to give details.

Once you grab those user details you'll be able to set up some on-going messages to confirm the email address of those users:

Ongoing and One-off messages: what’s the difference?
Set a message live that'll send to the right people automatically over time. Or, send a message to your customers in real time.

Jack Jenkins

Let me know if you have any other questions around this

**Comment by cgladue** [comment]
i just emailed you two examples of an email intercom can send ...

so it looks like we could easily do this all in intercom and get rid of mailchimp

i guess id just need an HTML file with the email template you want to use and i can integrate it into intercom.

**Comment by cgladue** [comment]
"Personal" Style
![image](https://user-images.githubusercontent.com/7914133/68994425-c690b680-0850-11ea-9540-01c14ba02f90.png)

"Plain" Style
![image](https://user-images.githubusercontent.com/7914133/68994427-d4463c00-0850-11ea-968d-1fe22ba9e357.png)

**Comment by robgpeak** [comment]
In doing some testing, the first issue is that a lot of the first email from Intercom go into someone's "Promotions" folder, but that does not happen with Mailchimp.  Let me explore some other possibilities.
