### ISSUE TITLE
Hero images not saving

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#315]
@cgladue I am trying to make the necessary adjustments to the hero images for both xclub and shop, but it won't let me.

<img width="1158" alt="Screen Shot 2019-11-12 at 3 47 45 PM" src="https://user-images.githubusercontent.com/28393235/68709703-39a1e080-0564-11ea-989a-cde5c725f098.png">
<img width="1170" alt="Screen Shot 2019-11-12 at 3 49 25 PM" src="https://user-images.githubusercontent.com/28393235/68709704-39a1e080-0564-11ea-9282-f144275a1816.png">

**Comment by cgladue** [comment]
yea im working on this not sure why it dosnt let you on the live server but
it does on the test one...

**Comment by cgladue** [comment]
ok can you try now ?

**Comment by robgpeak** [comment]
worked now on xclub, will test shop now as well

**Comment by robgpeak** [comment]
The learn more button does NOT link to how it works page on either the authenticated or unauthenticated

**Comment by cgladue** [comment]
on the hero ?

**Comment by robgpeak** [comment]
yes

**Comment by cgladue** [comment]
opne moment

**Comment by cgladue** [comment]
ok how abotut now

**Comment by robgpeak** [comment]
working now
