### ISSUE TITLE
Changing the primary color not working on shop

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#316]
@cgladue I changed the primary colors on shop but it is not showing up on the front end.  Is there a delay in this process?  If so there shouldn't be.

I used a hexidecimal number, is that OK?

**Comment by cgladue** [comment]
yes, remember that you need to close all windows or open it in incognito to see since its cached for your current session.

**Comment by cgladue** [comment]
i looked and it looks like the correct blue color.

**Comment by cgladue** [comment]
this blue?

![image](https://user-images.githubusercontent.com/7914133/68711613-f6497100-0567-11ea-90cc-5a7d8d5086eb.png)

**Comment by robgpeak** [comment]
ok, we're good then
