### ISSUE TITLE
size of the xclub logo is small

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#317]
@cgladue please have a look at the size of the xclub logo on your side.  It looked fine before, but now it is much smaller.

<img width="570" alt="Screen Shot 2019-11-12 at 4 25 05 PM" src="https://user-images.githubusercontent.com/28393235/68712186-2ba28e80-0569-11ea-86fb-3611afdb07dc.png">

**Comment by cgladue** [comment]
how about now ?  

![image](https://user-images.githubusercontent.com/7914133/68723732-76330380-0587-11ea-9794-b7d9dc9c6f3f.png)


new size to make the logos is 275px by 60px

**Comment by robgpeak** [comment]
That's a better size, but it needs to be left justified, and about 10px from the left margin


<img width="769" alt="Screen Shot 2019-11-13 at 8 10 43 AM" src="https://user-images.githubusercontent.com/28393235/68766685-4d455980-05ed-11ea-9e91-6c9d22eef1c7.png">
