### ISSUE TITLE
IMPORTANT!  Extension stopped working since new site is live

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#318]
@cgladue before I contact Addison, do you know why the browser extension would not be working since the new site launch?

I have a presentation today at 1:00 with Penn National.  Would love to have it working before then!

**Comment by cgladue** [comment]
ugh no i dont understand why it would ... there should be no changes to that stuff

**Comment by cgladue** [comment]
ask addison and ill take a look now while waiting for a response.
