### ISSUE TITLE
Dialog discription in a promotion modal is showing up empty

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#319]
@cgladue Ive tried several different time but I can't get it to work.  Actually has something to do with it being the **second** active promotion because I deactivated it and then the more details from the third promotion which moved up to the second position was then not visible.

**Comment by cgladue** [comment]
this should be fixed, the text color was white.

**Comment by cgladue** [comment]
but the text was there

**Comment by cgladue** [comment]
@robgpeak fyi
