### ISSUE TITLE
On Mobile Devices, Transferring points is doubled

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#32]
Does not happen on desktop

**Comment by ChrisASearles** [comment]
Hey @cgladue can you provide some more info. I just did the following and I'm seeing what looks correct:

1. Logged into shop.complinks.co
2. Went to https://shop.complinks.co/myrewards
3. Slid the slider up to redeem approximately half of my available points
4. Clicked transfer button
5. Verified in "Points Exchanged" section on same page and "Points History" page that the appropriate number of points were exchanged.

Tested on Chrome 64 on Windows emulating a Galaxy S5 and in Chrome on a Galaxy S8+.

**Comment by cgladue** [comment]
I have no power so I can’t give you details.  But it appears to me that there is two requests being sent for some reason like two forms being submit at the same time or something.  Since it works from desktop but not mobile that’s strange.

**Comment by robgpeak** [comment]
I just tested it again, and the same thing happened when I did it from my phone on both my shop and xclub accounts.  It made two transfers each time, simultaneously.

I am using my galaxy note 4 on Chrome 63

You can see the double postings in the back end as well..


![uploads/3d2973f0-c382-409b-8cb0-3e86b9488ee7/Screen Shot 2018-03-09 at 6.14.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3d2973f0-c382-409b-8cb0-3e86b9488ee7%2FScreen+Shot+2018-03-09+at+6.14.08+PM.png)

**Comment by robgpeak** [comment]
OK, more information...  I just tried on my wife's iPhone in Safari and the first time I did it on my account xclub_test1@peakmarketing.com when my account was NOT linked, the transfer only went through once, but then when I linked it to 1425648 - ZIP 19020 and tried to transfer 1000 again, it went through twice.


![uploads/0b21dff8-f023-4601-8d82-db39d853c504/Screen Shot 2018-03-09 at 6.32.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0b21dff8-f023-4601-8d82-db39d853c504%2FScreen+Shot+2018-03-09+at+6.32.22+PM.png)

To add another wrinkle to it @cgladue When I did it from my phone on xclub, my account was linked to 1423818 - ZIP 19020 and I am noticing that they are still pending, but the ones I did on the account linked to 1425648 were completed immediately.  I just wanted to bring this to your attention, and I guess if need be you can start a separate issue.

**Comment by ChrisASearles** [comment]
Hey @cgladue I have confirmed on both desktop and mobile the correct total is being submitted and only being submitted once. Based on the info @robgpeak provided above it seems as though this issue is isolated to specific conditions on the back-end.

**Comment by cgladue** [comment]
rob can you try this again and see what it does ?

**Comment by robgpeak** [comment]
It appears to transferring the correct amount, and only one time, but it is taking about 20 to 30 seconds to refresh the page (both on mobile and laptop) to tell me that the transfer was successful.  Should we start a separate issue for that?

**Comment by cgladue** [comment]
it shows as successful ?  or stays pending ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
i have a request in to the parx guys to update the IP thats allowed through
their firewall, but they havent updated it yet so untill them linking and
transferring will fail.  thats why its taking that long, it needs to
timeout first



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
It shows successful

**Comment by robgpeak** [comment]
It does finally show successful

**Comment by cgladue** [comment]
is it this one? because i dont see any completed transfer .. they are still
pending...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Oh, sorry.  Yes they are still pending.  But I meant that I a notification that it my points were successfully transferred....  
<img width="463" alt="screen shot 2018-03-22 at 9 48 59 am" src="https://user-images.githubusercontent.com/28393235/37774372-63c3abbe-2db6-11e8-8f50-ff6461292394.png">


as an FYI, it is taking just as long on shop.complinks.co to process.  It comes back as successful (like above, but still pending), but again, 20-30 seconds
