### ISSUE TITLE
move the logo to the left

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#320]
@cgladue That's a better size, but it needs to be left justified, and about 10px from the left margin

<img width="769" alt="Screen Shot 2019-11-13 at 8 10 43 AM" src="https://user-images.githubusercontent.com/28393235/68812976-6c220b00-0642-11ea-9091-f691344711e5.png">

**Comment by cgladue** [comment]
how about now ?  the design of the site dosnt allow it all the way to the left, the "content area" technically starts where the first menu item is ...  it could probbally be changed if you are really against it id have to check

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/68994037-26389300-084c-11ea-905e-aeb91db6158d.png)

**Comment by robgpeak** [comment]
OK, that's fine where it is
