### ISSUE TITLE
Hero Images sizes and responsiveness

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#321]
@cgladue the hero images do not seem to be 850x400 within the container they are in. 

Please have a look at https://www.loom.com/share/2502a1f8401f4feeb279ab4a7efa6dd7

and here was the image of what it looked like on my phone...
https://user-images.githubusercontent.com/28393235/68768992-8da6d680-05f1-11ea-84c4-a7bc04b2fac0.png

**Comment by cgladue** [comment]
What about something like this ...

https://www.jssor.com/cgladue*

username is my email password is **Chadgladue2**

you can design the slider including all sorts of transitions animations etc, then download a html file which i can grab the HTML out of and put on the site ... its a little less efficient as id like but it allows you to design the slide and export it so i can add it to the site.  whatta ya think ?  

there are demos here:  https://www.jssor.com/demos/

**Comment by cgladue** [comment]
another option is to just remove the text like you said, the image is already responsive its the text overlay thats making things difficult

**Comment by robgpeak** [comment]
let me mess around with the jssor thing a little

>

**Comment by robgpeak** [comment]
it does not look like there is the option to have a call to action button
in the jssor solution.  Meaning click here to learn more... like we do now
in our current hero slider option.

>

**Comment by cgladue** [comment]
we could make the entire slide a clickable link tho if that worked

**Comment by robgpeak** [comment]
I figured it out.  We can use html text to make links clickable.  One
thing, will we be able to get rid of the little "J" at the top right of the
screen?

[image: Screen Shot 2019-11-14 at 6.34.08 PM.png]

>

**Comment by robgpeak** [comment]
<img width="248" alt="Screen Shot 2019-11-14 at 6 34 08 PM" src="https://user-images.githubusercontent.com/28393235/68905019-b2906c00-070d-11ea-9b42-a2ad682faad8.png">

**Comment by cgladue** [comment]
if you "buy" it ($15 a year) i think that goes away but we COULD remove it withoutpaying if you wanted to dont know if thats technically allowed

**Comment by robgpeak** [comment]
ok, whatever.  let me play around with it a bit

**Comment by cgladue** [comment]
i found another one that looks interesting ... still looking at it tho http://www.masterslider.com/visual-builder/

**Comment by robgpeak** [comment]
Please have a look at some concerns https://www.loom.com/share/ce47e0b045114df19a40522222a0fe27

**Comment by cgladue** [comment]
ok ill do the other stuff for now, should i just remove the text all together on mobile for now and just leave the image till we sort out the positioning of the text over the image ?

**Comment by robgpeak** [comment]
yeah I suppose.  But leave the text on shop, so when I so a graphics guy,
he'll know what I'm talking about.  So just take the text down for xclub

>

**Comment by cgladue** [comment]
i think we can get it nailed down i understand what you are looking for more exactly now so while you are finding someone i can do the other things

**Comment by robgpeak** [comment]
In the mean time, there is a Layer Slider that I am somewhat familar with, and I just created one that might do the trick and I exported it to a .json file and the images folder (I will attach it as a zip here), and I emailed the company that makes it and they said we would have to buy their json version for $15, which I don't mind doing, but I just want to make sure it will work on our site.

This is a video of how it should look: https://www.loom.com/share/93f97ee2cde34ff1b9ac21a20e076eaf

Like I said, in either case I will get a professional graphic designer to make it look way prettier.

https://layerslider.kreaturamedia.com/pricing/jquery/

[LayerSlider_Export_2019-11-15_at_02.04.37.zip](https://github.com/robgpeak/CompLinks-xclub/files/3849516/LayerSlider_Export_2019-11-15_at_02.04.37.zip)

**Comment by cgladue** [comment]
the layerslider dosnt work with the JSON version it appears and work with the online designer and .json file 

in the meantime i made it the way the old site did it at low size, see below is this ok ?

![image](https://user-images.githubusercontent.com/7914133/68982658-e1721500-07d5-11ea-80a5-ac516f4e2a09.png)

**Comment by robgpeak** [comment]
Yeah that looks great.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Looks good size-wise but right now it just says earn more earn more earn
more four times I'm on the road and I want to see if you can make it say
earn more comp dollars for shopping online 365 days a year. Or something
like that like it used to

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
This is really strange because I just logged into the back end and saw that
you made the adjustments to the copy of what should be overlaying on hero
images but it's not working I checked it in Union Cognito I don't know if
it's still coming from cash but I'm banging my fucking head against the
wall I don't understand why it's still showing her and more and more and
more four times I can't take a picture of an incognito window because of
security reasons apparently but it's still showing like that for me so it's
a cashing issue apparently

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
could be cache for sure, this is what it looks like to me:

![image](https://user-images.githubusercontent.com/7914133/68986412-2fdede00-07ed-11ea-9d04-242eb74ec79f.png)

**Comment by robgpeak** [comment]
Ok
