### ISSUE TITLE
Travel section for unauthenticated users

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#322]
@cgladue As of right now, if travel is "enabled" for a subdomain and an unauthenticated user visits, they get an error message.

I want to change that to show the information that looks like this below.

Then once they do login/register, it would take them to the proper travel page.

![travel_unauthenticated](https://user-images.githubusercontent.com/28393235/68860430-82b67980-06b7-11ea-88e2-2cb8a1e337ac.jpg)

**Comment by robgpeak** [comment]
@cgladue let's test it out on the shop subdomain first.

**Comment by cgladue** [comment]
its not easy to do just on shop but i can do it on test

**Comment by robgpeak** [comment]
We need to have it show on the xclub site so people that have not
registered yet have an opportunity to at least see the option of being able
to book traveler points but again somehow it just needs to tell them that
in order for them to see it or make it function they need to be logged in
or register. So maybe we could do it with some sort of modal somehow when
they first click it's a little pop up that tells them they need to be
registered in order to see the page so it won't actually let them interact
with it and book travel

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
yea i have a modal there now, its uploading to test as we speak, ill let you know when you can see it there...

**Comment by cgladue** [comment]
ok its there now you can check it out

**Comment by robgpeak** [comment]
I just tried in an incognito window and it did not work on test.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
what did it do ?  because it works for me

**Comment by robgpeak** [comment]
It did not do anything, but I am on my phone.  Meaning I was able to see
and navigate throughout the travel site with no problem even though I was
not logged in

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
So to clarify, I did not see a pop-up modal telling me I could not book
travel unless I am logged in.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
you must have gone directly to /travel and not used the navigation link right ?

**Comment by robgpeak** [comment]
Yes.  I guess that was the issue.  But why would that be?

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
figures ;) haha thats the one thing i didnt put in i was excited to show you the modal ... if you use the site nav you should see a modal.  i had since updated the direct link too, Its uploading now to redirect you to login page when access it directly and not logged in

**Comment by cgladue** [comment]
because its two totally different things especially since i cant show a modal on a direct navigation vs clicking a link where i can show a modal to make it look better

**Comment by robgpeak** [comment]
OK.  So will this same functioanlity work now if I enable travel for xclub?

**Comment by cgladue** [comment]
Yes its for all subdomains

**Comment by robgpeak** [comment]
Cool.  One last change and we can close this issue.

Please change the message on the modal that pops up saying you need to be logged in to see this content to:

"The deep discounts on travel of up to 60% off are for members only, so you must be logged in to view this content."

**Comment by cgladue** [comment]
ok its updated, just waiting for the next deploy

**Comment by cgladue** [comment]
@robgpeak  all set

**Comment by robgpeak** [comment]
👍
