### ISSUE TITLE
The save button to change order of advertisers in category not working

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#323]
@cgladue when I am on any page to change the order of the advertisers that appear in the category features section at the top, the save button does not work.

https://shop.rewardseverywhere.co/dashboard/advertisers/reordercategories/151

I CAN drag and drop to reorder them, but it's not saving.

**Comment by cgladue** [comment]
i tried it and it is working for me ...  did you miss the blue save button ?  i did in the beginning too since its been so long.

![image](https://user-images.githubusercontent.com/7914133/68984334-788e9b00-07dd-11ea-9e75-b20300420dfb.png)

**Comment by robgpeak** [comment]
I definitely did click the save button I saw it but I'm not sure why it
didn't work. If it's working now that's fine I can't test it cuz I'm on my
phone it doesn't work that well. I will try when I get to where I'm going
in desktop mode on my phone just to double-check

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Maybe I need to stop smoking crack.  It's working now.
