### ISSUE TITLE
campaign links not working/registering

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#324]
@cgladue I just created a new campaign, but when I went to test it nothing happened.

https://www.loom.com/share/cb316d9588b2466383ff7921dba4d067

**Comment by cgladue** [comment]
hmm, thats odd, i tried it on test and it worked for me ...

![image](https://user-images.githubusercontent.com/7914133/68982978-fef3ae80-07d6-11ea-9c83-4022045c1d47.png)


let me try on live

**Comment by cgladue** [comment]
and i just tried that same one you did on shop and it worked ok too, why didnt it work on xclub i wonder ???  im still looking

**Comment by cgladue** [comment]
ok i just made a slight change that may be why can you try it again ?

**Comment by robgpeak** [comment]
I just tried again from my phone with this link and it did NOT work...

https://xclub.complinks.co/campaign/clicktrack/d5f50d0add4b4d15aea2d4edd134f5cb

Please try from your phone.

What's the story with all the caching issues since the new site has been in place?

**Comment by cgladue** [comment]
they arent issues, its how the site is designed, it stores your user account and details on the partner in session memory.

that session memory stays active till you close the all your browser tabs, usually a user wouldnt even tell a difference except we keep adjusting stuff and testing so we see it

**Comment by cgladue** [comment]
AHA! i finally figured it out !!!

you are still using xclub.**complinks.co**

you need to use **rewardseverywhere.co**

https://xclub.rewardseverywhere.co/campaign/clicktrack/d5f50d0add4b4d15aea2d4edd134f5cb

man i was banging my head against the wall on that one.

**Comment by robgpeak** [comment]
oops.  Sorry about that
