### ISSUE TITLE
broken links in the registration screen

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#326]
@cgladue please have a look https://www.loom.com/share/6645184c2bad4ab3baaf2b760459d2ad

They should link to target="_blank" so it opens a new tab, and make sure the privacy and terms links go to the corresponding pages

**Comment by cgladue** [comment]
shit, good catch .. fixed and deployed now.

**Comment by robgpeak** [comment]
Cool.  Just thinking out loud here, is it possible to have those links actually pop up a modal in front of the registration modal?  I think it would make for a better UX

**Comment by cgladue** [comment]
um, maybe... let me try it

**Comment by cgladue** [comment]
on mobile tho that text will be REALLY long, and the lines will probably wrap and im not sure how readable it will be because the modal would be smaller then the site ...

**Comment by cgladue** [comment]
well i guess its the same either way

**Comment by robgpeak** [comment]
no one reads it anyway, but it will be a better UX for sure if it is in a closable modal instead of another tab

**Comment by cgladue** [comment]
ok take a look now on live

**Comment by robgpeak** [comment]
F'ing beautiful!!!!  I love it
