### ISSUE TITLE
the entire site refreshing on every click

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#327]
@cgladue just wondering why this happens?  https://www.loom.com/share/38d5d4c8117e47c7a47eee1c7294066e

**Comment by cgladue** [comment]
thats how its always worked, you may not have seen it before because this site uses a "preloader" which will load assets then display them att at once instead of loading one by one ... which is the loading indicator you see pop up.

the old site acted the same way just no preloader so you may not have noticed it.

![image](https://user-images.githubusercontent.com/7914133/68997899-78dc7400-0879-11ea-85dd-c3a1975a9d84.png)

**Comment by robgpeak** [comment]
Here's a few better example of what I mean.  It's not the preloader per se...

https://www.loom.com/share/99511c287a0844f4943df54e293e8e92

**Comment by cgladue** [comment]
the entire page is actually being reloaded, you just cant see it (and i can prove it ;))

Right click On one of the menu items on github and inspect element, double click the text for the name of that menu item and change it to something else like below
![image](https://user-images.githubusercontent.com/7914133/68998160-8fd09580-087c-11ea-92f8-98b7bdac5091.png)

then click on one of the other menu items and if it changes back to the original text the whole page is being reloaded.
![image](https://user-images.githubusercontent.com/7914133/68998163-9eb74800-087c-11ea-993a-29b324af43c9.png)

**Comment by cgladue** [comment]
it just happens so damn fast because there is literally nothing on the page ... hardly any images hardly any text

**Comment by cgladue** [comment]
if you want i can disable the preloader and see how it acts

**Comment by robgpeak** [comment]
please try that.  The preloader is making it have that fade in fade out reaction, and that is what's causing the site to do what it's doing.

**Comment by cgladue** [comment]
one moment uploading to test

**Comment by cgladue** [comment]
ok how about now ?  on test

**Comment by robgpeak** [comment]
1000 time better!

**Comment by robgpeak** [comment]
That said, none of the pages on that test site are scrollable

**Comment by cgladue** [comment]
Goddamn it i do see that hmm friggin preloader ok ill keep digging

**Comment by cgladue** [comment]
i found it, try it now

**Comment by robgpeak** [comment]
perfect!

**Comment by robgpeak** [comment]
let's set it live on all the sub domains

**Comment by cgladue** [comment]
already done
