### ISSUE TITLE
fix type-o in footer

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#328]
@cgladue 

In the footer of the sites it reads:
There's nothing like getting cash back on everything you buy, and with Rewards Everywhere, **you'll points** with every purchase you make through this site that you can exchange for Parx Casino® Comp Dollars.

and we need to add the word **earn** between ...you'll & points that I made bold in the original above just to show you where.

**Comment by cgladue** [comment]
got it, ill fix tonight

**Comment by cgladue** [comment]
all set
