### ISSUE TITLE
Orphan transaction

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#329]
@cgladue It looks like the shopping trip 7695 is someone's, but I don't know who.

https://xclub.rewardseverywhere.co/dashboard/users/view/100105?tab=tab-purchases

**Comment by cgladue** [comment]
they dont have a trip id recorded, so i cant do anything untill someone complains i guess

![image](https://user-images.githubusercontent.com/7914133/69159218-8da54b80-0ab5-11ea-9161-b9a630a243b1.png)
