### ISSUE TITLE
Interstitial games not working

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#330]
@cgladue I just enabled the Bonus Games on Shop, but they don't work.  I am going to disable them in the mean time.

**Comment by cgladue** [comment]
yea it wasnt part of the initial rollout, we were going to go back and do them after the site went live

so thats what im working on today

**Comment by cgladue** [comment]
Related to #298 

@robgpeak check out test, right now i have scratch game only configured but everything should be working.

if you are OK with it then ill get the other two games done

**Comment by cgladue** [comment]
@robgpeak all set its been pushed to live, you can enable games for xclub if you want i didnt want to do it i figured id leave it for you
