### ISSUE TITLE
name change on the rewards page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#331]
@cgladue please have a look at the 10 "Comp Rewards" on the right hand side of the slider, but it should be "Comp Dollars"...

<img width="1266" alt="Screen Shot 2019-11-20 at 9 53 06 AM" src="https://user-images.githubusercontent.com/28393235/69250247-54381300-0b7d-11ea-909a-1bf4e4332179.png">

**Comment by cgladue** [comment]
i have it now showing the partner "Rewards Program name" field which for Parx would be "Parx Casino® Comp Dollars"

ok?
