### ISSUE TITLE
changing the default link

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#332]
@cgladue I am trying to change the default link for the Shop Now button for Home depot, but I can't seem to get it to work right.

https://www.loom.com/share/289f1a6da2f24646bed1c9b80da49769

**Comment by cgladue** [comment]
@robgpeak try it again, i think its correct now

**Comment by robgpeak** [comment]
I don't think so.
https://www.loom.com/share/b8847205024a4ae99eb8cc2c1bf1597b

**Comment by cgladue** [comment]
you are testing on shop, i didnt change anything live yet, you need to try it on test

**Comment by cgladue** [comment]
i went in and set HD to patio link

**Comment by robgpeak** [comment]
I was testing on "test" and it did go to the patio link.  I thought it would go to the home page.

**Comment by cgladue** [comment]
it depends on whatever link you use i was just playing around and used the patio link and "Set to main link"

if you know of a link that goes to main page then u can set it to that

**Comment by robgpeak** [comment]
I would have thought it would have been this one... 180580

<img width="1041" alt="Screen Shot 2019-11-21 at 10 10 28 PM" src="https://user-images.githubusercontent.com/28393235/69395088-ca3a9800-0cab-11ea-9cef-f51675ecaeb0.png">

**Comment by cgladue** [comment]
i just went to that link and "make default link"  and it looks like it goes to the homepage as expected.

**Comment by robgpeak** [comment]
OK, it is working now.  But let me try to change it to anther link and see if it takes...

**Comment by cgladue** [comment]
i did make a fix so you werent loosing your mind it was not working as it should originally

**Comment by robgpeak** [comment]
But it is still not working for me.  Meaning I can see the change you made to the default link and it shows up properly, but if I make the change it does not work.

https://www.loom.com/share/6749f0fc300d470fbc1f52b4bb6b0a62

**Comment by robgpeak** [comment]
I even just tried it again after closing down the back end and starting from scratch.

https://www.loom.com/share/0c6df73f29df4fca84ce88486751ae30

**Comment by cgladue** [comment]
you are chaning it on shop.rewardseverywhere.co which is changing it on LIVE

you need to do it on test.rewardseverywhere.co which is NOT the same database

**Comment by cgladue** [comment]
you are changing it on one database and trying to view it on another which is why its not working .

test.rewardseverywhere.co is a totally seperate system.

**Comment by robgpeak** [comment]
Oops.  Gotcha.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
if you say its good then ill upload the changes it to the live system too

**Comment by robgpeak** [comment]
Yeah, it is good to go.  Sorry for the confusion.

>

**Comment by cgladue** [comment]
No need to apologize 🤣
