### ISSUE TITLE
Petco page is showing up blank

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#333]
@cgladue Please have a look and see if you can fix it.

<img width="1087" alt="Screen Shot 2019-11-25 at 4 46 23 PM" src="https://user-images.githubusercontent.com/28393235/69580790-4b8f7480-0fa3-11ea-9e3c-030e2f24ccfa.png">
<img width="1000" alt="Screen Shot 2019-11-25 at 4 46 44 PM" src="https://user-images.githubusercontent.com/28393235/69580791-4b8f7480-0fa3-11ea-8d8e-d1d85ca47c1f.png">

**Comment by cgladue** [comment]
i think i know why its doing this, did petco pretty recently switch from CJ to IR ?

**Comment by robgpeak** [comment]
let me ask @morganpeak Please read the thread and reply and let Chad know when Petco switched to IR

**Comment by morganpeak** [comment]
It says in IR that they switched in September

**Comment by morganpeak** [comment]
@cgladue I didn't do anything different with petco than I usually do with all of the advertisers so it's weird. Other impact advertisers are coming up fine on the site so maybe something is up with Petco. Could you look into it to see if maybe something isn't pulling right from their Impact profile?

**Comment by cgladue** [comment]
Yea im looking now.

**Comment by cgladue** [comment]
Should be working now, i had to create a process that updates a file on the server daily to keep a master list of advertisers up to date ... i thought that the file would be up to date enough for a little bit till i could do this but i guess it changes pretty often so it didnt last as long as i thought it would, you can check it out now.
