### ISSUE TITLE
Using a Hero Image Slider

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#339]
@cgladue I think we are going to have to open up this issue again.  The current solution for the hero image section is not working that well and we need something better.

Please have a look at http://www.menucool.com/responsive-slider and see if some of the demos would fit the bill for what we're looking for.  Please download it and set it up (in demo mode) on test so we can play around with it and see how it works before we buy it.

I also like the fact that you can have it load different images based on the size of someone's screen.

If you look in the FAQ toward the bottom right of the page you'll see "Use different pixel images for different devices"
and the answer is:

If you want different sized devices to load different pixel images, you can add multiple vesions of slide images. For example:

<li>
    <a class="ns-img" href="img/1.jpg" data-screen="450-max"></a>
    <a class="ns-img" href="img/1-small.jpg" data-screen="0-449"></a>
</li>
Then if the device screen is less than 450 pixel wide, the slider will only load the image 1-small.jpg.

Note: This feature can only be tested with real devices as the size specified here is the device size, not the browser size.

You can also load videos, in the slider which is pretty cool.

The only thing I don't know is if it has a GUI to build the sliders.  That would be REALLY cool.

**Comment by cgladue** [comment]
i downloaded it and it works good, the captions (text) however seem to behave the same you still need to do quite a bit of adjustment to make it look right on both screen sizes... but if you were to say put the text as part of the image then it would be a lot better

**Comment by cgladue** [comment]
actually as long as you can standardize a position for the text, then its not that bad, only thing is i dont think we will be able to do the white background under the text so may need to choose the background image more strictly.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/70394612-be95e380-19c4-11ea-9217-8a83cb26b6c6.png)

![image](https://user-images.githubusercontent.com/7914133/70394623-c9507880-19c4-11ea-9d12-5c14682b0ce1.png)

**Comment by cgladue** [comment]
and the reason it dosnt go all the way down is the image size is not being stretched anymore, so the new images would need to be 850*450

**Comment by robgpeak** [comment]
I was thinking we would Eliminate the overlay text completely and just have
the text within the image itself and then have two separate images based on
the screen size.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Does it have a graphical user interface?  How would I make changes?

**Comment by cgladue** [comment]
no GUI, we would have to modify the dashboard to set the parameters you want

**Comment by robgpeak** [comment]
I am not sure what screen resolution you are working with, but when I look at the images you have on test.rewardseverywhere.co the maximum "container" size I can make that area that shows the hero image (slider) is 650*450

**Comment by robgpeak** [comment]
@cgladue please double check on the size of the image you have in the slider, and then compare it to what is showing up on the front end when you look at the site.  For me when I look at it on the front end from a cookie and data cleaned private firefox browser, it looks like it is about 650*450

**Comment by cgladue** [comment]
the image is actually 850x400
https://s3.us-east-2.amazonaws.com/complinks/partners/10-hero_shop_unauthenticated.jpg

to make it exactly the right size for larger screens (it will be scaled down on smaller screens i believe) it should be exactly 650x450

**Comment by cgladue** [comment]
the slidr on test.rewardseverywhere.co is not he new slider, i was just saying that the new slider takkes the image exactly as it is and does not stretch it so its showing up as only 400px height since thats it actual size...   does that make sense if i am explaining it right

**Comment by robgpeak** [comment]
I can see that the raw image is 850*400, but when the "container" that it
is currently sitting in is reduced, the raw image does NOT scale down, it
actually just (seemingly) trims the sides of the image to fit into the
container.

https://www.loom.com/share/3c1668308249401180013bc8c7a8f65d

So the container that it sits in right now is NOT proportioned to
accommodate a raw image file of 850*400.  This means the easiest thing to
do will be to have the designer make the raw images 650*450 and 300*230 for
mobile and we'll call it a day.

>

**Comment by cgladue** [comment]
let me publish the test site so you can see, like i said the test site thats live isnt the latest version so you cant see the new slider thats the old one still .. 

hang on let me deploy it (takes like 20 minutes to deploy)

**Comment by robgpeak** [comment]
Ok.  But even before you deploy it I could tell you that it will not be 850
wide inside that container because that container can't be 850 wide no
matter how wide someone screen is so whatever the ultimate native size of
that container becomes after you deploy it that will be the size of the raw
images I have the graphic designer produce.  Again it's no real problem
what size it ends up being as long as the native images fit well inside the
container and then reduce proportionately based on the screen size like
they do on mypoints.com

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
right... its the 400 part thats the problem i think, it needs to be 450  i agree witht he 850 vs 650 part it should be 650  but its not as noticable as the height .. i will make a test image thats 650x450 after i get back from my birthday dinner and see how it looks, i deployed to test and you can see the trial version watermark messes up the positioning

**Comment by robgpeak** [comment]
I think we might end up going with the layer slider version for $29 as they
have other features as well.

Happy birthday!

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Questions:

1. Can you make the slider container any size you want to accommodate that space on the home page?

2. Is the height of the individual store boxes on the right hand side of the hero image slider adjustable?

3. Not really a question but a statement.  I just bought the other Layer Slider I was telling you about.  It is MUCH better in it's functionality, and we will have a lot more flexibility to do not only the slider, but things like popups, exit detection, bottom layer bars... https://layerslider.kreaturamedia.com/popups/

Here is the link to the zip file for the plugin...  https://drive.google.com/file/d/17BRNsCFly-UJfpB1KY6EPuFbLuqv6unr/view?usp=sharing

Please let me know after you get that one up and running on test and I will double check the sizes of the images and get the designer working on making the graphics.

**Comment by robgpeak** [comment]
Oh, and here is the License Key that I bought: E4790F25-E37E-KF35-MC12-98C4F18D248C

**Comment by robgpeak** [comment]
As a test for the Layer Slider, here is one that I created in the visual editor of my WP version, but they are saying it should work on the JQuery version.

[LayerSlider_Export_2019-12-11_at_13.48.05.zip](https://github.com/robgpeak/CompLinks-xclub/files/3950624/LayerSlider_Export_2019-12-11_at_13.48.05.zip)

**Comment by cgladue** [comment]
do you have any instruction on how to load it in to the jQuery version ?
because i have no idea how to load this file

**Comment by robgpeak** [comment]
https://layerslider.kreaturamedia.com/documentation/ might have some
reference.

>

**Comment by cgladue** [comment]
it seems to me that this is only concentrated on the wordpress version, is
there a support email i can email to ask ?

**Comment by robgpeak** [comment]
just cc'd you on the thread that I've been having with their support person.

>

**Comment by robgpeak** [comment]
@cgladue Here is the link to the zip file for the Layer Slider plugin that I downloaded...(below)  The documentation should be in there according to their support department and the license key is E4790F25-E37E-KF35-MC12-98C4F18D248C

 https://drive.google.com/file/d/17BRNsCFly-UJfpB1KY6EPuFbLuqv6unr/view?usp=sharing

**Comment by cgladue** [comment]
@robgpeak take a look

https://test.rewardseverywhere.co/

**Comment by robgpeak** [comment]
Please put these three images in the slider with NO call out text above them and I want to see how they look on laptop and mobile.  Also, do you think the shop now buttons (realistically the overall image) should link to the store index page on our site, or start a shopping trip to the particular merchant immediately.

I think maybe because it says "Shop Now" they should start a trip immediately
![Slider_Macys](https://user-images.githubusercontent.com/28393235/71094587-37d9c700-2179-11ea-8aa2-06dbbc2da43a.jpg)
![Slider_Petco](https://user-images.githubusercontent.com/28393235/71094589-38725d80-2179-11ea-8a75-374de798be24.jpg)
![Slider_Walmart](https://user-images.githubusercontent.com/28393235/71094590-38725d80-2179-11ea-90a3-c83ce30f7f0e.jpg)


.  Otherwise I can have her make them read, "See Deal" and then they can lead to the store index on our site...

**Comment by cgladue** [comment]
ok, so its ok if the entire slide is clickable ?

**Comment by cgladue** [comment]
as if they clicked the button

**Comment by robgpeak** [comment]
Yes

**Comment by cgladue** [comment]
ok perfect 

what about the concept of authenticated vs unauthenticated images ?  do you still want to use those or same images regardless of logged in or not ?

**Comment by robgpeak** [comment]
Yes, let's use all the same images whether they are logged in or not.

So we want to keep the authenticated and unauthenticated separate meaning
we want to be able to in the future but for now they should all default to
be invisible for both authenticated and unauthenticated. Unless we go in
and manually change an authenticated in the back end

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
please replace the current petco image with this new one with a different promo line.  We dod not earn commission when someone signs up for automatic delivery...
![Slider_Petco](https://user-images.githubusercontent.com/28393235/71107327-e0deec80-218e-11ea-8f69-719d98c4e3e2.jpg)

Let me know when it's live that I can see it on the test site

**Comment by cgladue** [comment]
@robgpeak check it out ...  

https://test.rewardseverywhere.co/

i had to remove the button on the image and make it an actual link, the slider does not let you make the whole slide a link, only layers within the slide.

also on the backend, in the partner hero section there is now two new fields for Authenticated button URL and unauthenticated button URL... if there is anythign in those fields then the button will appear, if not then it will not be on the slide.

**Comment by cgladue** [comment]
aha!

take a look now ?

**Comment by robgpeak** [comment]
Coolio.  Please click on the Petco one and see if it works.  It's coming
back with a bad link.  Petco move to Impact...?  It looks like it is still
using a cj link.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Once that is fixed (Petco link), let's put it up on xclub and shop

**Comment by cgladue** [comment]
its actually just because its the test system, so the links arent kept up to date .. in live it will be fine..

**Comment by robgpeak** [comment]
Ok

**Comment by cgladue** [comment]
@robgpeak ok xclub and shop should have the slider now.

**Comment by robgpeak** [comment]
Cool

**Comment by robgpeak** [comment]
@cgladue please see if you can remove the dots and the play and pause buttons from the slider.  We can keep the left and right arrows and also remove the circle timing indicator at the top right of the image slider.

![2019-12-23 08 26 42](https://user-images.githubusercontent.com/28393235/71360472-050b4680-255e-11ea-97e4-64dc545d6cce.png)
