### ISSUE TITLE
New Feature: Missing Point Lookup

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#340]
https://test.rewardseverywhere.co/stores/missingpoints

take a look when you can rob:

try with this data

Order Number:  16333629276698
Amount: 48.38
PETCO

**Comment by cgladue** [comment]
this page will search for any comissions that were attributed to the Complinks System account and if the Advertiser, order ID, and order amount matches, will reassign all the comissions for that order to the user that is currently signed in

**Comment by robgpeak** [comment]
the message says that it's going to credit my account so does that mean
the actual customer needs to visit that page and put in that information in
order for it to credit their account?  If that is the case I'm not sure I
like that idea to give someone access to that. It seems better if we were
to do it on our own in the back end and then credit a specific account once
we find the order that was missing

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
Yea.  Thats how ebates does it tho.

**Comment by robgpeak** [comment]
Ok.  So let me know when it's live on Xclub and I will have someone test it
out next time there is an orphan transaction.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak ok its there and ready

**Comment by cgladue** [comment]
If you lookup user 100105 thats the system user that all unknown comissions post to:
https://xclub.rewardseverywhere.co/dashboard/users/view/100105

**Comment by robgpeak** [comment]
If we have the order number, maybe it would be helpful to display it in another column on the page https://xclub.rewardseverywhere.co/dashboard/users/view/100105

I just tried to claim a transaction with the order id I received from Walmart but it didn't work. https://youtu.be/SPbpg8oGuhU

It could be because of the format of the order id Walmart sent me and it does not match the format we have it in.

Either way I think it would be helpful to have the order ID listed on that 100105 page this way it would be easy for our customer service to help a customer that we know made the order

**Comment by cgladue** [comment]
what was the order id you got from walmart ?

**Comment by robgpeak** [comment]
Yes.  Here is a screenshot of the email I received.
![Screenshot_2019-12-08-08-59-40](https://user-images.githubusercontent.com/28393235/70390463-482fbc00-1999-11ea-8cac-1143d472fc5e.png)

**Comment by cgladue** [comment]
ah its because the hyphen in the number but they report it without the hyphen....

i changed it to remove the hyphen if you enter it try it again:
https://xclub.rewardseverywhere.co/stores/missingpoints

![image](https://user-images.githubusercontent.com/7914133/70390727-947bfb80-199b-11ea-9490-7291cacab111.png)

**Comment by robgpeak** [comment]
Cool.  That worked. One last thing, you know how sometimes when you 
 Information into a field and you know you're going to put numbers in there and the keyboard automatically shows up looking like a number keyboard? We could do that in the bottom field where someone is going to put in the price that would be cool

**Comment by cgladue** [comment]
i tried but the numeric keyboard does not have a decimal option so i dont think its going to work since you need to enter dollars and cents

**Comment by robgpeak** [comment]
Ok no problem

**Comment by cgladue** [comment]
ok i did find a way to default it to at least show numbers by default on the keyboard (but not the actual numeric keyboard) so at least thats one less keystroke to switch to the numeric keyboard.

**Comment by robgpeak** [comment]
Awesome.

Thanks,

Rob

**Sent from my phone
