### ISSUE TITLE
Getting bonus games live

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#341]
@cgladue  We need to give people some sort of way to see the amount of bonus that they're potentially going to receive if that trip ends in a purchase. I'm thinking probably on the dashboard another column that shows the trip sale amount and the points earned and the other column would say "Pending Bonus"

So if someone spins a wheel and is going to get 20% bonus of chips, the Pending Bonus for that trip would show "20%".  If they are supposed to get 100 extra points, display "100 points".  If the bonus was 0% or they did not play the bonus game, leave it blank.

Then make the column header that reads Pending Bonus be clickable and have it pop open a modal that is similar to the More Details modal on the promotions page, and the content would read:

Header: Feeling Lucky Bonus Games

Main body: From time to time we introduce fun games which give you opportunities to win extra bonuses for the shopping trips you take from the site when you make a purchase from that specific shopping trip.

You can always turn the games on or off from the Games tab on the page https://xclub.rewardseverywhere.co/account/myprofile

![2019-12-10 23 32 33](https://user-images.githubusercontent.com/28393235/70594628-2445c380-1baf-11ea-9746-32cab73d2048.png)

**Comment by cgladue** [comment]
i should have this done tonight ill let you know when its viewable for you

**Comment by robgpeak** [comment]
Cool

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok check it out:

https://test.rewardseverywhere.co/trips

**Comment by robgpeak** [comment]
Awesome.  Can we test everything all together.  Meaning, we want to click
on a shop now button, have it play a game and make sure it tracks and shows
the pending bonus.

Then we want to put it live on xclub

**Comment by cgladue** [comment]
i guess the only way would be to activate it on shop only, and test that way since theres no test API for purchase data

**Comment by robgpeak** [comment]
well if you think it's going to work out of the gate you can put it live
on xclub I'm fine with that too

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
I am just about to make an actual purchase from Walmart through the platform and I would like to test the games and tracking of the whole thing so if you put it live on xclub let me know and I will make my purchase now

**Comment by cgladue** [comment]
sorry i cant till i get home tonight did you already make the purchase ?

**Comment by robgpeak** [comment]
No, I'll wait.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok you should be able to test the purchase now on shop

**Comment by robgpeak** [comment]
OK just placed an order through Walmart with shopping trip 8030 and had a
scratch off win for 100 extra points.  they did show up in the pending
bonus column, so that's good.  The item should be delivered by the 31st, so
well see if the points all get credited automatically.

Can you also put the pending bonus column on the users Dashboard page as
well.  Also include the links on the header to the modal explain the
pending bonus like you have in the shopping trips page.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
@cgladue I wanted to follow up with you in my last message...

Can you also put the pending bonus column on the users Dashboard page https://xclub.rewardseverywhere.co/account/dashboard  as
well.  Also include the links on the header to the modal explain the
pending bonus like you have in the shopping trips page.  Thanks

**Comment by robgpeak** [comment]
@cgladue  please have a look at my last message I want to get this sorted out to have it live on xclub as soon as possible

**Comment by cgladue** [comment]
sorry i missed this update from you ... its all set now

**Comment by robgpeak** [comment]
Excellent.  One more quick thing.  In the Points Hostory, lets' limit to one decimal point for the bonus amount issued...

<img width="957" alt="Screen Shot 2019-12-31 at 9 38 37 AM" src="https://user-images.githubusercontent.com/28393235/71624675-bee36200-2bb1-11ea-93cf-a834c1c50578.png">

**Comment by robgpeak** [comment]
Then once that is done, let's put it live on xclub.

**Comment by cgladue** [comment]
ok, i think its set now to round to 1 decimal, can you check ?

**Comment by cgladue** [comment]
and its live too

**Comment by robgpeak** [comment]
The decimal point thing is working but when I try to see a game interstitial from clicking the shop now button on X club didn't work nothing showed up

**Comment by cgladue** [comment]
when you enable games (or change any partner setting) you have to close all browser tabs and then go back in for the new subdomain settings to take effect.  Did you try that ?

**Comment by cgladue** [comment]
looks like you assumed i set the bonus games setting on the partner setup to enabled, i didnt want to change anything and thought it best to leave it up to you to decide when to do that

**Comment by robgpeak** [comment]
Gotcha

Thanks,

Rob

**Sent from my phone
