### ISSUE TITLE
Campaign not showing I activated it or earned the points

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#342]
@cgladue I was just testing an email (below), and the link to the campaign works in that it takes me to the xclub site, but it does not track the campaign in that I don't receive the message in the green dialog box saying my account was just credited the points, nor does it show up in my transaction history.

 Hi {first name} ​​,

We sincerely appreciate you being a member of Rewards Everywhere in order to earn extra Xclub Comp Dollars, and as a token of our appreciation, here is a link to receive 500 points for free.

https://xclub.complinks.co/campaign/clicktrack/b1513de5b692403f9fd9667b3c944bb8

Thanks again, and Happy Holiday (Shopping, Saving & Points Earning) Season!

Morgan H.
CompLinks
xclub@complinks.co

**Comment by cgladue** [comment]
you are using .complinks.co again ... switch the URL to .rewardseverywhere.co and try it

**Comment by cgladue** [comment]
https://xclub.rewardseverywhere.co/campaign/clicktrack/b1513de5b692403f9fd9667b3c944bb8

**Comment by robgpeak** [comment]
Oops.  Shit... Sorry about that

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
no problemo, i think i will take a look and try to make the redirect carry the whole URL through so it works either way

**Comment by cgladue** [comment]
ok try it again now, it should carry through anything you enter to the new domain now.

https://xclub.complinks.co/campaign/clicktrack/b1513de5b692403f9fd9667b3c944bb8

**Comment by robgpeak** [comment]
yes it did work.  Thanks again.
