### ISSUE TITLE
travel site issues

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#344]
@cgladue I just got off the phone with Amazon customer support and they are saying they CANNOT get to http://travel.rewardseverywhere.co and that is the reason they closed the account.

I am appealing it, but I am still not sure why they are saying they can't get to the site.  I know in cloudflare it is refreshing to whitelabel.travelpayouts.com and maybe that is posing some sort of problem...

Anyway, I will see what happens when they write back as I've escalated the issue with them.

In the meantime, do you know how we can put an image in the background of the page http://travel.rewardseverywhere.co which is located here? https://www.travelpayouts.com/programs/100/tools/whitelabel

**Comment by cgladue** [comment]
there is no reason they should be getting site unavailable ... why not point them to shop.rewardseverywhere.co/travel ?  is that against their TOS ?

**Comment by cgladue** [comment]
we may be able to put an image there .. do you have an image that you want to use ?

**Comment by robgpeak** [comment]
That would be against their terms and conditions because it is an incentive
driven site.

As for the image of the background I would like to use the balloons if we
could

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
how is this:

http://flight.rewardseverywhere.co/

**Comment by cgladue** [comment]
added the following to the Color Scheme CSS:

![image](https://user-images.githubusercontent.com/7914133/71628044-fe1aae80-2bc3-11ea-929a-14a7e600c4f1.png)

**Comment by cgladue** [comment]
body {
	background-image: url(https://shop.rewardseverywhere.co/assets/images/aer.jpg);
}

body .TPWL-template-header {
	background: unset !important;    
}

**Comment by cgladue** [comment]
hmm, only that its not tall enough to fit the page i see now

**Comment by cgladue** [comment]
if we had a taller background (like 2000px) it would fit to the bottom of the page

**Comment by robgpeak** [comment]
That would be fine, but is there any way we can make it (the entire image)
show up as the background, not the way it is getting cut off now where you
can only see a sliver of the balloon.

Also, we don't want it to repeat, and it should only show up at the top of
the page as the background image.  Check it in both your computer and phone.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Let me find a different image

**Comment by cgladue** [comment]
ok i removed the repeat and set to 100%

**Comment by robgpeak** [comment]
Perfect.  Now can you please put it on travel.rewardseverywhere.co

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
its on all three now.

**Comment by robgpeak** [comment]
Cool.  Thanks
