### ISSUE TITLE
video on how it works

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#345]
@cgladue please see if you can get the youtube video that is on the page https://xclub.rewardseverywhere.co/how-it-works to show up as a normal size you tube video container.

Meaning, if you go there and click on the video to watch it, the video is really small and it looks silly.

**Comment by cgladue** [comment]
ok...

**Comment by cgladue** [comment]
@robgpeak how does it look now ?

**Comment by robgpeak** [comment]
That's fine.  One quick fix, change the link to the video 

FROM: https://www.youtube.com/embed/WV3QA7kpCU0?controls=0

TO: https://www.youtube-nocookie.com/embed/WV3QA7kpCU0?rel=0&amp;showinfo=0

This is so it does NOT show random related videos at the end but it shows our "CompLinks" related videos.

**Comment by cgladue** [comment]
@robgpeak ok should be changed now
