### ISSUE TITLE
Bonus Games Points Adjustments look off

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#347]
@cgladue please have a look at this video.  https://youtu.be/p3ksrhoFZbY

There seems to be some issue with the issuance of bonus game points.

Also for reference at the end of the video regarding the idea of tooltips.  https://jqueryui.com/tooltip/

**Comment by cgladue** [comment]
still looking into this

**Comment by cgladue** [comment]
i think i may have found why .. and possibly fixed it, but it seems that 11.50 was 50% of the 23 points you earned on the other purchase, it was picking up the hayneedle trip and using that on a different trip comission ... i added logic to make sure if its a game bonus that the advertiser and tripid match what the bonus was for ... it would be fixed from this point onward so keep an eye out and i will as well.

**Comment by robgpeak** [comment]
Okay cool. And did I leave a note about adding the shopping trip IDs to the descriptions in the points history?

![2020-01-11 08 38 25](https://user-images.githubusercontent.com/28393235/72205150-db9f5580-344d-11ea-96c0-ec97374a7569.jpg)

**Comment by cgladue** [comment]
yep im working on that

**Comment by cgladue** [comment]
@robgpeak this is deploying to test now, ill let you know when its ready to be verified.

**Comment by cgladue** [comment]
@robgpeak ok can you take a look ?

**Comment by robgpeak** [comment]
I see the trip I'd in the transaction history in test. so it seems to be
working.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok ill copy live then

**Comment by cgladue** [comment]
should be live

**Comment by robgpeak** [comment]
It tag some of them with the trip ID but not all of them.  Why would that be?

Also, those erroneous bonuses are still in my points history, but they should be removed.
![Screenshot_2020-01-13-08-18-17](https://user-images.githubusercontent.com/28393235/72259102-a32e8180-35dd-11ea-9ded-26ff625ee232.png)

**Comment by cgladue** [comment]
which ones are in error ?  i cannot tell just from looking at them let me know and ill remove them 

i dont have any data on my user to test with so can you try it again on live and show me what it looks like ?

**Comment by robgpeak** [comment]
Please have a look https://www.loom.com/share/973f59c00cdc40eeb2a374b70ecb3c3e and this is for reference https://xclub.rewardseverywhere.co/dashboard/users/view?id=100086 and perhaps you can think of an elegant way to include this bonus information more cleanly in our back end.

**Comment by cgladue** [comment]
there is not much i can do about all the bonus(s) in the past they are kinda messed up, can we check them going forward ?  and if thats straightened out then i can go back and manually fix them but i just want to make sure they are correct going forward from 1/10 at 10pm onward ?

**Comment by cgladue** [comment]
here is someone who made a purchase after 1/10 and the bonus looks correct:

https://xclub.rewardseverywhere.co/dashboard/users/view?id=100224

**Comment by robgpeak** [comment]
OK that's fine, we'll just keep an eye on it.

Thanks,

Rob

**Sent from my phone
