### ISSUE TITLE
site description missing

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#348]
@cgladue I've been noticing that when I post a link to our sites on Linkedin and other social media, it shows that it is missing a description. "brief description here"

Please see if you can add the description somewhere in the site so it shows up.  Not sure if it's a meta tag or something.

Description for shop:
Earn free cash back for all your online shopping in the form of points that you can use in your favorite loyalty program.

Description for xclub:
Earn free Xclub Comp Dollars for all your online shopping!

<img width="313" alt="Screen Shot 2020-01-18 at 12 54 31 PM" src="https://user-images.githubusercontent.com/28393235/72668289-4a9f2000-39f3-11ea-8b42-78c5d8b764f1.png">
<img width="314" alt="Screen Shot 2020-01-18 at 12 57 46 PM" src="https://user-images.githubusercontent.com/28393235/72668290-4a9f2000-39f3-11ea-8a1c-e0def0bef73b.png">

**Comment by cgladue** [comment]
ok gimme a minute to try to see where that should be put in the code.

**Comment by cgladue** [comment]
ok found it, working on adding two new fields to the backend under the partner admin 

1. Metadata Description
2. Metadata Keywords

**Comment by robgpeak** [comment]
Cool.

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak can you go to partner admin now and set the description and keywords (Comma Seperated for keywords) and try again ?

**Comment by robgpeak** [comment]
Done.  Thanks
