### ISSUE TITLE
Walmart orphan transaction

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#349]
@cgladue in looking at https://xclub.rewardseverywhere.co/dashboard/admin/profitability you will see the transaction from Walmart for $603.99 from today was credited to account 0 but it should have been mine from trip id 8158 that I initiated on the 19th at 10:59am.

 not sure why all of a sudden it wouldn't be tracking that trip please look into it let me know

**Comment by cgladue** [comment]
i looked at this rob and it came across missing the subId ... can you describe how you started the trip ?  mobile/desktop, which link game or no game etc ?

**Comment by robgpeak** [comment]
from my laptop, but honestly I don't remember which specific link on our site I clicked on, but I looking in my history, and here was the redirection link from us to them...

https://xclub.rewardseverywhere.co/trip/start?aid=13861&lid=0&url=%2f%2fgoto.walmart.com%2fc%2f406688%2f612734%2f9383%3fsourceid%3dimp_000011112222333344%26veh%3daff

**Comment by cgladue** [comment]
Ok. That helps.  Lid=0 means the main shop now button for the advertiser.   The link looks exactly like it should.  Nothing appears out of normal for this trip vs others

**Comment by robgpeak** [comment]
So I tried to "claim" this transaction through that new page you built but it didn't work.

![Screenshot_2020-01-25-09-04-55](https://user-images.githubusercontent.com/28393235/73122361-ff849000-3f51-11ea-8cd3-82d9d5c439e4.png)

**Comment by cgladue** [comment]
can you look now ?  i think i had a bug in there that was hanging up the posting of the transaction

**Comment by robgpeak** [comment]
I see it now.

Thanks,

Rob

**Sent from my phone
