### ISSUE TITLE
Double all the points someone earned last month

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#350]
@cgladue I did not set it up through a campaign, (but I will the next time) and had a promotion that told everyone they would earn double points for all the points they earned in January.

I wanted to see if you can calculate all the points each person who did earn from shopping last month, and double the amount they earned.  Considering the amount is relatively small, you can issue the points as available.  Please let me know when it's done, and if you could, please post a list and amount of points that were doubled her in this thread.

In the future, I am thinking about how to best set up a campaign so when a customer click on the campaign, it would double all the points they earn for the month (or whatever percentage we predetermine) and it would automatically double them as they are earned during that month so the customer can see it in real time (they would still be pending until the actual points that spurred the doubling become available by the merchant)

This would be in addition to any bonus game points they might have earned for that particular trip, but those bonus points earned would not double.

**Comment by cgladue** [comment]
ok yea we can do both of these .. 

as for the second request they would visit a link to double their points earned up to that point and then they would have to go back each time to double any points earned since the last doubling ?

or just visit it once on say March 1 to activate the doubling for all of march ?

**Comment by robgpeak** [comment]
I'm not really sure what you're saying about the second point but the way I
thought about it was inside the campaign when I set it up it would be
starting date and ending date, allow multiple wins and since it is a Double
points bonus, the trip bonus percentage would be 100.

Have a quick look
https://www.loom.com/share/9c9c920bf5ab416890ebd2879fc80127

It might actually just work as it is.  Let me know what you think?

>

**Comment by robgpeak** [comment]
As for the first part, let me know when their accounts have been credited and we will email them to let them know.

**Comment by cgladue** [comment]
i believe this is the complete list of transactions (purchases only, not game bonus, campaigns, or email opt in bonuses) for the month of january ... would you concur ?

![image](https://user-images.githubusercontent.com/7914133/73988750-a7666a00-4911-11ea-907c-ca3244c53a59.png)


if you do then i will double them

**Comment by robgpeak** [comment]
I think there is more transactions than that.

Have a look at
https://xclub.rewardseverywhere.co/dashboard/admin/profitability with the
dates changed to last month.

**Comment by cgladue** [comment]
you are right there were some balances that were adjusted outside of january so they didnt show up, i corrected the query and now this should match the listing you showed:

![image](https://user-images.githubusercontent.com/7914133/73991329-cbc64480-4919-11ea-851b-ec8ab6ccc05b.png)

**Comment by robgpeak** [comment]
Yeah that looks right.  You can make the double points credit.  That said,
please do me one more favor and look into account 100301 and DON'T double
her points, primarily because I don't want her to see a note in her points
history that shows she got 0 points doubled.

Thanks,

Rob

*Sent from my phone

**Comment by cgladue** [comment]
i wouldnt double any that are 0 points anyways   i could just double the non-zero points if you wanted or leave her out totally ?

**Comment by robgpeak** [comment]
Yeah you can leave her out totally.

Thanks,

Rob

*Sent from my phone

**Comment by cgladue** [comment]
ok, all adjustments have been added.

**Comment by robgpeak** [comment]
ok thanks.  and on the other point, do you think the way I laid out the
campaign in the set up from the video I sent you would work the way I'm
thinking about it?

>

**Comment by cgladue** [comment]
yea i think thats what its supposed to do, as you described

**Comment by cgladue** [comment]
i looked at the code and i believe thats what it will do

**Comment by cgladue** [comment]
i think this can be closed now.
