### ISSUE TITLE
Walmart Trip and Transactions not being recorded

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#351]
@cgladue users keep having issues with Walmart where both the trips and transactions are not being recorded and it’s been verified that they’re going through the proper steps to start a trip, etc.

**Comment by cgladue** [comment]
ok, do we know account numbers, and dates of anyone thats affected by any chance ?

we are going to have to bring it up with the network since nothing changed on our side

**Comment by morganpeak** [comment]
One account number that we know was affected is: 100789 (Barbara Manzo) Her trip was Jan 20th 2020 - Order total $122.51 before tax, Walmart Order# 2912056-359535

**Comment by cgladue** [comment]
ok, so i looked both in impact backend dashboard and the API and neither one have any record of that transaction ... not sure what @robgpeak and you want to do next ?

**Comment by robgpeak** [comment]
@cgladue do you at least see that Barbara Manzo did take trip 8162 to Walmart on our end?

**Comment by cgladue** [comment]
Yes January 20th at 5:40pm EST

**Comment by robgpeak** [comment]
That's strange.  Can you communicate with Impact's tech and see what might have been the problem?

@morganpeak please send a message to Walmart and ask them why the order number 2912056-359535 was not attibuted to our affiliate account?

**Comment by cgladue** [comment]
Ok

**Comment by cgladue** [comment]
https://help.impactradius.com/hc/en-us/requests/159985

Request has been opened

**Comment by cgladue** [comment]
Danielle Aristizabal (Impact)Feb 24, 14:02 PSTHello Chad, Thank you for reaching out to Impact Support! Unfortunately, the customer clicked on another partner's link prior to placing their order. This means were not the conversion winner for this order. Please let us know if you have any questions. Yours, | Danielle Aristizabal (Impact)Feb 24, 14:02 PSTHello Chad, Thank you for reaching out to Impact Support! Unfortunately, the customer clicked on another partner's link prior to placing their order. This means were not the conversion winner for this order. Please let us know if you have any questions. Yours,
-- | --
Danielle Aristizabal (Impact)Feb 24, 14:02 PSTHello Chad, Thank you for reaching out to Impact Support! Unfortunately, the customer clicked on another partner's link prior to placing their order. This means were not the conversion winner for this order. Please let us know if you have any questions. Yours,
