### ISSUE TITLE
allowing a clickable link in the promotions description

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#352]
Hey @cgladue I am trying to see if there is a way to add a link in the promotion description.  It is currently not possible.

https://www.loom.com/share/7dd0836022774ea6a914baae8656f7e3

**Comment by robgpeak** [comment]
@cgladue I never heard back from you and I wanted to put this promotion live today (March 1st.)  Please look into it and see if you can fix it.  Thanks.

**Comment by cgladue** [comment]
oh shit sorry this got burried in my inbox, i am looking at it now

**Comment by cgladue** [comment]
i should be able to get this to you before this afternoon

**Comment by robgpeak** [comment]
ok cool

>

**Comment by cgladue** [comment]
@robgpeak ok i think it is corrected now, i also update tiny mice to v 5.2.0 from v4.8.0 so the icons look a little different.  but there aparently was a bug in bootstrap and tinymice that caused what you reported.

**Comment by robgpeak** [comment]
Thanks
