### ISSUE TITLE
IMPORTANT** There seems to be a big issue with the most recent campaign

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#354]
@cgladue It looks like there might be a decimal place missing in the 100% bonus for the campaign  45.  I just got a 10000% bonus.  please change that ASAP and adjust anyone else that might become affected by it.

https://www.loom.com/share/781abb6016fc4d9599fc54659eef7e04

https://xclub.rewardseverywhere.co/dashboard/users/view?id=100086

**Comment by cgladue** [comment]
i fixed it, sorry somewhere i had you enter 0-100% but never calculated the decimal value of that (.01 to 1 when awarding points so the award was 100 times instead of 1 times extra points sorry :(

you were the only one affected. and the fix should be in place now.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/76151571-831eba00-6084-11ea-8073-9e6fe16ed407.png)

**Comment by robgpeak** [comment]
Ah, I forgot it went from .01 to 1 only becasue when you look at in =in the edit window, it reads (1-100)  Please change it to either read (.01 - 1) or just rearrange the calculation to the be (1-100) so if I was to put in the number 50, it would be a 50% bonus...

<img width="362" alt="Screen Shot 2020-03-07 at 3 33 01 PM" src="https://user-images.githubusercontent.com/28393235/76152050-4608f680-6089-11ea-9913-245f2c619024.png">

**Comment by cgladue** [comment]
ea its supsed to be 0-100 ill fix the calculation
wasnt anything u did it was me
