### ISSUE TITLE
duplicate the FAQs

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#357]
@cgladue could you please do me a favor and duplicate the FAQs from https://shop.rewardseverywhere.co/faq to  https://marcustheatres.rewardseverywhere.co/faq then I can tweak them as necessary.  Thanks

**Comment by cgladue** [comment]
@robgpeak all set

**Comment by robgpeak** [comment]
Thanks

**Comment by robgpeak** [comment]
@cgladue could you please do me a favor and duplicate the FAQs from https://shop.rewardseverywhere.co/faq to https://lyft.rewardseverywhere.co/faq then I can tweak them as necessary. 

Thanks

**Comment by cgladue** [comment]
Sure

**Comment by cgladue** [comment]
all set

**Comment by robgpeak** [comment]
thanks
