### ISSUE TITLE
Games interstitials need to be default ON for new accounts 

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#359]
@cgladue it seems that when a new person registers, (even in xclub), they are NOT seeing the games interstitials by default, and they should be.

I just registered a new account at Marcus Theatres and it was OFF by default.

<img width="626" alt="Screen Shot 2020-03-21 at 5 32 49 PM" src="https://user-images.githubusercontent.com/28393235/77236973-05859e80-6b9a-11ea-80fd-9d18015fd644.png">

**Comment by cgladue** [comment]
next deploy the default setting when someone registers will be enabled.
