### ISSUE TITLE
Rethinking our email set up

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#361]
@cgladue I wanted to see when you might have time for a call one day this week to discuss our email sending setup (Mailchimp, AWS's SES and Intercom)

**Comment by robgpeak** [comment]
@cgladue let me know when you have time to speak?

**Comment by cgladue** [comment]
@robgpeak whenever you can mark up that html email template for the Welcome/Opt In message that would be great.

**Comment by robgpeak** [comment]
And we can set up multiple different HTML emails for each different subdomain?

**Comment by cgladue** [comment]
sure

**Comment by robgpeak** [comment]
OK, here is a sample for Marcus.  You can try it out on test.rewardseverywhere.co to see how it works out.  Can't attache a .html file in here so I zipped it.
[MarcusTheatres_Welcome_email.html.zip](https://github.com/robgpeak/CompLinks-xclub/files/4372669/MarcusTheatres_Welcome_email.html.zip)

As you can see it would have a link that would lead to a "registration_verification" page on the subdomain that we would have to create, but the idea would be on that page we would have something like, "Congratulations, you are all set to start earning rewards..." but was would also say, "In order to secure your account, please enter your mobile number and we will give you an extra 100 points for free immediately..."

**Comment by robgpeak** [comment]
Just logged into my Twilio account and saw great copy for out registration_verification page:

Secure your account with two-factor authentication
Enter a mobile phone you would like to use for SMS verification.

4155552671
Set up later
How does two-factor authentication help me?
Two-factor authentication (2FA) adds an extra layer of security to your account. When you log in, you'll enter your password along with a verification code sent to your device. In some instances you may be prompted to enter a code, like when you’re logging in from an unrecognized device.
Learn more about 2FA

<img width="1100" alt="Screen Shot 2020-03-23 at 10 14 03 PM" src="https://user-images.githubusercontent.com/28393235/77381195-a3709900-6d53-11ea-8c3e-bf2053e9af92.png">

**Comment by robgpeak** [comment]
Just set you up with access to our Twilio account

**Comment by cgladue** [comment]
do  you want to use 2FA on the site ?

or are you saying just tell them its for 2FA but not actually use it for that ?

**Comment by robgpeak** [comment]
We are not going to actually use 2FA, but that was just as an example.  It would be mainly just to say, keep your account safe, we will send you a text message only one time to verify your account...

**Comment by cgladue** [comment]
@robgpeak i think i have this working on https://test.rewardseverywhere.co if you want to take a look.

Currently it is using the email welcome template you created so it says Marcus but that would be updated to the proper properties when it went live so ignore that part.

**Comment by robgpeak** [comment]
NICE!  Works great.  I love it.  

1. Is there an easy way for me to upload the HTML email file myself?

2. Will it automatically update my email opt-in preference in intercom?

3. What do I need to do to get the SMS integration between twilio intercom, and a system to actually compose and send the SMS itself?

**Comment by robgpeak** [comment]
By the way if you want to check it out in action and how it will react in an intercom you can put it on shop. right now if you like and I can test it from there to make sure it shows up inside intercom

**Comment by cgladue** [comment]
for SMS, how do you envision that the SMS would first be sent ?  in intercom ?  you want any message sent in intercom to also send an SMS if the user has a phone and opted in ?

**Comment by robgpeak** [comment]
I'm not sure if it's possible to actually send the message through intercom when it's connected to twilio. But if it is that would be great I would love to do that. We may need another integration with someone that actually does the composition of the message. Like I said I don't think intercom does that, but let me know. As for every message being sent via SMS I wouldn't want that to happen it would be the same way as if someone their email address inside the chat session of intercom then it would automatically forward to their email address but there is an option that the person can choose to have the thread sent to them an email or SMS. I will find the link and send it to you

**Comment by robgpeak** [comment]
https://www.intercom.com/help/en/articles/17930-capture-your-visitors-contact-details

This article really talks about capturing their email address, but I would hope that if we already have it in our db of contact details, it would give the person the option of choosing whether they want to receive a copy of that "chat" via email or SMS.

Again, the primary objective is to be able to see any conversations we've had with the customer via email, chat or SMS all from within Intercom.

**Comment by cgladue** [comment]
i will ask them if it can be done, i know their API is pretty robust, what if any new message you send (not a reply to an existing one) went out via SMS and then the user could reply to that SMS and it would show up in the chat window in intercom, then from that point on they could reply via SMS to you in intercom ?

**Comment by cgladue** [comment]
the link you sent sounds like they have some native SMS but the user has to choose to be notified by SMS it dosnt happen automatically

**Comment by robgpeak** [comment]
> i will ask them if it can be done, i know their API is pretty robust, what if any new message you send (not a reply to an existing one) went out via SMS and Email/In-App and then the user could reply to that SMS and it would show up in the chat window in intercom, then from that point on they could reply via SMS to you in intercom ? or they could just reply like that do today and not use SMS.
> 
> Maybe you can explain your thought flow on how SMS would be used by you guys in intercom in an ideal world ?

In an ideal world I'd be able to use intercom to compose and send the SMS, but like you mentioned if we were able to compose an initial SMS elsewhere and send it based on specific attributes ins that we are gathering from either intercom or our database and then have all subsequent communications go through intercom via SMS that would be fine.I would like to be able to say to people that are x points away from reaching the next bonus via a text message as I think it is way more effective in communicating that.

**Comment by robgpeak** [comment]
> the link you sent sounds like they have some native SMS but the user has to choose to be notified by SMS it dosnt happen automatically

That's fine too. I don't mind giving him the choice, but the idea is if they already have both bits of data in our database, meaning their email address and their text number they can choose which one they would like it to go to if they don't have it they could add it right then and there on the spot

**Comment by cgladue** [comment]
would you be OK with any new message you create and send out through intercom going to SMS and Email/In-App both ?

**Comment by cgladue** [comment]
actually what about this, you could send the initial SMS through Rewards Everywhere, that would create the conversation in Intercom under the user also, and if they replied to the SMS it would update the conversation in intercom too.  would have to check tho if you replied in intercom would it then SMS them back or not.

**Comment by robgpeak** [comment]
No, I think that would be too much on the recipient...  I would mind SMS and In-app. OR Email and In-app, but not SMS and Email

**Comment by robgpeak** [comment]
> actually what about this, you could send the initial SMS through Rewards Everywhere, that would create the conversation in Intercom under the user also, and if they replied to the SMS it would update the conversation in intercom too. would have to check tho if you replied in intercom would it then SMS them back or not.

Yeah that would work

**Comment by cgladue** [comment]
currently, if you reply to a conversation in intercom does it email the user automatically ?

**Comment by robgpeak** [comment]
If someone starts an in-app conversation and we are not available to respond immediately they have the option of entering your email address and when we reply it would automatically go to the their email as well as the in-app little bubble.  So it would be the same thing, if someone sent a message in-app and we were not available to reply right away,the user would have the ability to enter their email address (or hopefully) their SMS number.  That was the link that I sent you.  But my question is, if we are already collecting their email address from the initial email thing that you showed me on test, could we prepopulate that field?

**Comment by cgladue** [comment]
do you have the name of a contact that has given their phone number by any chance ?  i can check.. there is a field in intercom named "phone" if i can just fill in that field with their phone and have it work automatically then that might work for you .. i did read tho that users cannot reply to any SMS all replies have to be done through intercom so they have to click the link in the SMS to reply.

**Comment by robgpeak** [comment]
no one is really entered their phone number cuz we never asked for it but you could put my phone number and account number 1 (in shop.rewardseverywhere.co) the number is 631-682-5107

**Comment by cgladue** [comment]
i cant do anything till the rest goes live since there is only 1 intercom.  so ill have to come back to this

**Comment by robgpeak** [comment]
I'm not sure what that means?  What "rest goes live"?

**Comment by robgpeak** [comment]
As a follow up I know in intercom we only have one account, but we differentiate members by company name so when the message comes in or goes out, it would be specific to the company.  Meaning if I was going to send an email to several people at the same time for Xclub, in the audience segmentation, I would just include a rule that says Comapny Name is equally to Xclub.  This means Marcus people would not get it.

**Comment by cgladue** [comment]
the removal of Mailchimp and replacing it with SES.

**Comment by robgpeak** [comment]
Ok, so what do you need me to do?  Do you want me to create the initial
email sequence for xclub and shop like I did for Marcus?

Thanks,

Rob

*Sent from my phone

**Comment by cgladue** [comment]
The only thing that would change is the logo, colors, footer text and my account link right ?

i might be able to make it auto generate each template based on the property

**Comment by robgpeak** [comment]
Yeah I supposed to cover it. Which also brings up another issue that we should think about in terms of what if a client doesn't want to use the text message feature. We should be able to turn it on and off per subdomain

**Comment by cgladue** [comment]
Turn off the ability to enter a phone# or just the opt-in ?

**Comment by robgpeak** [comment]
The need to opt-in via email would be mandatory for every subdomain but the welcome message then asking for a cell phone number for SMS would be able to be turned on or off based on the subdomain.

**Comment by robgpeak** [comment]
Let me know if you have time today to pick up this conversation.  I am trying to get ready for the presentation to Marcus Theatres, and one of the things is changing from Mailchip to SES for them because if you register now on marcustheatres.rewardseverywhere.co you get this message from our back end because it's not connected to Mailchip, and I really don't want it to be.

<img width="1280" alt="Screen Shot 2020-03-21 at 3 15 15 PM" src="https://user-images.githubusercontent.com/28393235/77557730-7a095780-6e90-11ea-8139-64191490ce83.png">

**Comment by cgladue** [comment]
i am working on this now, but i dont know if i can do the automatic template before your demo, if you want to send me an xclub one for now i can just use that on live site till i can switch to automatic template

**Comment by cgladue** [comment]
When is your demo ?

**Comment by robgpeak** [comment]
Not sure yet, but I wanted to send my contact there the completed site, and
I know as soon as I do he's going to register because he already registered
at shop. Rewards everywhere. Co.

Thanks,

Rob

*Sent from my phone

**Comment by cgladue** [comment]
ok rob i think i have the automatic template done... it will automatically generate the email template based on the property, use their logo, their colors and rewards program name.  also will use hero image #2 if there is more then 1 otherwise the first hero image.

**Comment by cgladue** [comment]
s deploying now to test ill let you know when its done.

**Comment by robgpeak** [comment]
[beefree-lrmia6nqqi (3).zip](https://github.com/robgpeak/CompLinks-xclub/files/4383403/beefree-lrmia6nqqi.3.zip)

**Comment by cgladue** [comment]
ok got it let me know when you have the welcome template

**Comment by robgpeak** [comment]
[Marcus Full Welcome Email.zip](https://github.com/robgpeak/CompLinks-xclub/files/4383548/Marcus.Full.Welcome.Email.zip)

**Comment by robgpeak** [comment]
Please let me know when it's all done so I can test

**Comment by cgladue** [comment]
ok its on test.rewardseverywhere.co now

**Comment by robgpeak** [comment]
Ok, a few things.

1. There are some wierd symbols on the first email.
![Screenshot_20200325-234232_Gmail](https://user-images.githubusercontent.com/28393235/77608242-03517600-6ef3-11ea-97c8-8f838c5f4360.jpg)

2. On the confirmation page, it still show 100 points.
![Screenshot_20200325-234354_Chrome](https://user-images.githubusercontent.com/28393235/77608334-4c092f00-6ef3-11ea-8422-43866cf7365c.jpg)

3. In the welcome email, there is another one of those strange symbols.
![Screenshot_20200325-234452_Gmail](https://user-images.githubusercontent.com/28393235/77608379-693dfd80-6ef3-11ea-9319-6fe4347cdad5.jpg)

**Comment by robgpeak** [comment]
Other than those things, it seems to work great.

**Comment by robgpeak** [comment]
@cgladue One other thing I didn't notice last night was that the email address in morgan's sign off reads: Email-Protected.  Not sure why that would be, but it shouldn't be.

<img width="597" alt="Screen Shot 2020-03-26 at 7 47 43 AM" src="https://user-images.githubusercontent.com/28393235/77643799-60bae680-6f36-11ea-975d-fd11b51b58a4.png">

**Comment by cgladue** [comment]
yea that email protected thing isnt coming from me ... thats something on her computer or email provider

**Comment by robgpeak** [comment]
This is me on my computer, and it is only showing up on the email that is being sent from SES.  If you register right now as a brand new customer on test, have a look at the welcome email you receive and tell me if you see the same thing?

**Comment by cgladue** [comment]
also i do see the same behavior when i registered for an account like you did in intercom, i think its those "ongoing" messages triggering and sending or something

**Comment by cgladue** [comment]
here is my test last night never seen the email protected thing, it looks fine

![image](https://user-images.githubusercontent.com/7914133/77644329-361d5d80-6f37-11ea-866d-8c20f787450f.png)

**Comment by cgladue** [comment]
and those strange characters are coming from your HTML template there are inprintable characters in that HTML that your site creates that are messing me up i cant see them ugh

**Comment by cgladue** [comment]
https://community.cloudflare.com/t/email-protected-is-shown-for-every-email-adress/14078

**Comment by cgladue** [comment]
it may be a setting on cloudflare, one moment ...

**Comment by cgladue** [comment]
ok, try it again that may be what it was

**Comment by robgpeak** [comment]
OK, at least that explains it.  Can you please fix that in cloudflare?

As for the little characters, it's because I had the registered trademark symbol as superscript.

**Comment by cgladue** [comment]
thats one of them, but there are a bunch others that you didnt see because i found and removed them they were all over the place.

**Comment by robgpeak** [comment]
ok cool.

**Comment by cgladue** [comment]
as for being able to edit the emails, i am planning on letting you edit the main "body" of the email and leaving the header and footer static and the same for all emails, see below the highlighted areas you will be able to edit:

![image](https://user-images.githubusercontent.com/7914133/77645136-9c56b000-6f38-11ea-934b-680c50fc1082.png)

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/77645210-bee8c900-6f38-11ea-9cfd-1fb1b58a238e.png)

**Comment by robgpeak** [comment]
OK, but please remember to take out the "My Account" button in the header of the registration confirmation email.  It was already deleted in the most recent html tempate file I sent you yesterday for marcus

**Comment by cgladue** [comment]
yea, i did that was just an old screenshot

**Comment by cgladue** [comment]
This is all set we are now totally seperated from mailchimp

**Comment by robgpeak** [comment]
cool
