### ISSUE TITLE
A change to some text on the home page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#362]
@cgladue Please see if you can change the text in this section highlighted in the image below to read: "Exchange your points for {Rewards Program Name}" son in this instance for Marcus, it would read "Exchange your points for Magical Movie Rewards® Points."  And on shop it would read "Exchange your points for Your Rewards Program Points" (which is the rewards program name.

Thanks.
<img width="1118" alt="Screen Shot 2020-03-21 at 7 53 44 PM" src="https://user-images.githubusercontent.com/28393235/77239218-7b940080-6bae-11ea-99dc-1d580834097e.png">

**Comment by cgladue** [comment]
ok i will work on this and all the other items today and tomorrow

**Comment by cgladue** [comment]
@robgpeak this will take place next deploy

**Comment by robgpeak** [comment]
When would the next deploy be?  I have a presentation with Marcus tomorrow morning at 9am

**Comment by cgladue** [comment]
in just a little bit
