### ISSUE TITLE
Featured Store funtionality

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#363]
@cgladue please have a look and let me know if I am missing something.  I don't recall how this works with the order for the featured stores in the bottom horizontal scrolling store boxes on the home page.  I know for sure it works on the top featured area to the right of the hero images...

https://www.loom.com/share/109d41209b6d4e37aed9c640bdafb766

**Comment by cgladue** [comment]
ok, fixed the features stores, after next deploy whatyou were doing will work, the first 5 will always be in the hero, the 6th and on will be at the bottom scroller by order

**Comment by cgladue** [comment]
as for the featured deals, they are marked as featured by viewing all the advertisers deals and choosing to make it featured, it them pulls them in random order.  

would you like it so it fulls the deals marked featured in order of the advertiser display order ?  meaning :
![image](https://user-images.githubusercontent.com/7914133/77256227-45ed2700-6c43-11ea-983c-005762685805.png)

in this case Samsung's featured deals would show, then Target's then Dicks ?

**Comment by cgladue** [comment]
actually no that wont work because its not tied to the features stores at all.  i can make it display the deals in the order of them expiring like the ones expiring the soonest display first ?

**Comment by robgpeak** [comment]
Yeah that's a good idea

**Comment by cgladue** [comment]
@robgpeak all set with this its live
