### ISSUE TITLE
Fontawesome?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#364]
@cgladue I was tooling around on the site, and this page in particular(https://marcustheatres.rewardseverywhere.co/store/the-home-depot) took a real long time to load, and this is the site that looked like it was trying to fetch...  What is it, do you know?
<img width="474" alt="Screen Shot 2020-03-21 at 8 35 28 PM" src="https://user-images.githubusercontent.com/28393235/77239742-7d60c280-6bb4-11ea-9723-204528b8a55a.png">

**Comment by cgladue** [comment]
Font Awesome is the little icons that the site uses throughout ... it still taking long time to load ?

**Comment by robgpeak** [comment]
Only specifically on the home depot page, not on any of the others.  And
why would't we just have icons stored on our AWS account?

>

**Comment by cgladue** [comment]
the icons are stored on our servers i believe, i will look at this too to make sure

**Comment by cgladue** [comment]
i have downloaded the file and it will be hosted locally on next deploy

**Comment by robgpeak** [comment]
please go to the home depot page on our site and tell me if it takes much loner than all the other pages.  It   Watch this.  https://www.loom.com/share/8920b05013c046848fef4b2b38bd0901

**Comment by cgladue** [comment]
ok, you know what i think it is ... it looks like home depot has a shitton of deals (links) that are active ... would you want to limit the # of links we show ?  if not then i could load the page first then load the deals in the background.

**Comment by robgpeak** [comment]
but why does it look like in the status bar it's getting hung up loading google.com?

**Comment by robgpeak** [comment]
Not really sure what the issue is, but if it is because there are too many offers, then yes, please do limit them to 25 offers max.  No one is looking at any more than that.

**Comment by robgpeak** [comment]
@cgladue can you please limit the number of offers in HD to 25.  I like to use HD for my demonstrations because they pay up to 4% to the end user, and it's a good high commission.  Thanks

**Comment by cgladue** [comment]
yep its ready for next release

**Comment by robgpeak** [comment]
Do you think that release might be ready to push out today?  I am supposed to present to Marcus tomorrow morning, and I use HD as an example because the commission is up to 4% which looks good.

**Comment by cgladue** [comment]
i just changed it without the release .. should work now

**Comment by robgpeak** [comment]
Perfect.  Thanks.
