### ISSUE TITLE
Certain Stores not appearing on front end

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#365]
@cgladue At least two stores, Vons and Safeway, are not showing up in the search on the front end of the website

**Comment by cgladue** [comment]
ok let me recreate the list of stores for the autocomplete box

**Comment by morganpeak** [comment]
@robgpeak

**Comment by robgpeak** [comment]
@cgladue after that, we need to ad the new category that Morgan created "Grocery" to the main Shop menu

**Comment by robgpeak** [comment]
@morganpeak ithink after the category is up and running, we can add Walmart and Target to the Grocery category, and have them all as featured stores in that category so they all show up at the top of the grocery category page

**Comment by cgladue** [comment]
@morganpeak @robgpeak Grocery Category is visible, i will deploy the other changes soon

**Comment by cgladue** [comment]
ok all set guys
