### ISSUE TITLE
https://marcustheatres.rewardseverywhere.co/ dissapeared

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#366]
@cgladue Please try to get to https://marcustheatres.rewardseverywhere.co/ and let me know what you see.  My just says OK at the top left of a white screen.  The same as when you go to https://rewardseverywhere.co/ without a subdomain.

Please fix ASAP.

**Comment by cgladue** [comment]
sorry about that when i deployed the latest changes i forgot it overwrote a change its all set now, and i hope to remember that for next time.
