### ISSUE TITLE
Font Size on Scrolling advertisers at bottom of home

### ISSUE THREAD

**Issue by morganpeak** [robgpeak/CompLinks-xclub#368]
@cgladue Can we make the font where it says “up to x points/$ spent” or “x points/$ spent” small enough so that it all fits on one line? 
I attached two pics to show that the ones that say “up to...” cut off the smaller font on the bottom that says “ Shop all ‘STORE’ deals”
@robgpeak 
![C09237E9-F599-4F4A-B5A1-9F74A1948660](https://user-images.githubusercontent.com/28446563/77485873-ad060980-6e04-11ea-8a1b-cd57b91e5952.png)
![4F33DA4F-0AD9-4B17-B524-D3A5016EFB72](https://user-images.githubusercontent.com/28446563/77485875-ad9ea000-6e04-11ea-97ec-22b1553bc5e8.png)

**Comment by robgpeak** [comment]
Good call.  Thanks Morgan.

**Comment by cgladue** [comment]
ok, yea that shouldnt be doing that i will correct it

**Comment by cgladue** [comment]
@robgpeak @morganpeak ok updated

**Comment by robgpeak** [comment]
awesome
