### ISSUE TITLE
New Registration Signup User Flow

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#369]
@cgladue Here is the whiteboard I was working on with the email flow:  https://miro.com/app/board/o9J_k0oF_1U=/?moveToWidget=3074457346762221173

**Comment by robgpeak** [comment]
I just updated it a bit, and changed it to 50 points for entering their mobile number.  This way the user will not already be at the minimum transfer threshold.

**Comment by robgpeak** [comment]
Is the new registration onboarding process for Xclub using SES now or is it still using Mailchimp?

**Comment by cgladue** [comment]
the live site is using SES only now so that means all partners it cant be half and half

**Comment by robgpeak** [comment]
Ok.  So let me know when I can see and/or edit the  "verification" and "welcome" email messages

**Comment by cgladue** [comment]
yea thats step #2 im working on now ...

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/77799612-8be32a00-704b-11ea-8e82-441f2ee39b71.png)

**Comment by cgladue** [comment]
The site you used to design the template does not masy to reuse, so if possible can you design it in Tiny Mice?  i added a bunch of new toolbar options to allow you to add lots of different things.

**Comment by cgladue** [comment]
ok its there, here is the URL

https://test.rewardseverywhere.co/dashboard/property/templates

**Comment by robgpeak** [comment]
Can you have a quick zoom call to go over this?  Not really sure what to do

**Comment by robgpeak** [comment]
https://zoom.us/j/4031527792

**Comment by cgladue** [comment]
i am here

**Comment by robgpeak** [comment]
Sorry wife made an early dinner.  Im in there now

**Comment by cgladue** [comment]
sorry now its my turn to make dinner ... say around 7 ?

**Comment by robgpeak** [comment]
LOL, can't make 7, then I have a poker tournament tonight at 8

**Comment by robgpeak** [comment]
tomorrow morning perhaps?

**Comment by cgladue** [comment]
ok maybe sooner are you free till 7 ?

**Comment by robgpeak** [comment]
yeah, text me if you have time before 7

**Comment by robgpeak** [comment]
Chad, let's make it tomorrow.  I am actually going to be having a zoom meeting with some of my buddies  starting right now.

**Comment by cgladue** [comment]
yea thats fine, i just got done anyways

**Comment by cgladue** [comment]
@robgpeak there is now a "Copy To" option that you can use to copy a template to another subdomain... if youw ant to play around setting up xclub, and shop on test, i can copy those from the test database to the live database when it goes live so its available right away

**Comment by robgpeak** [comment]
Cool.  Seems to work well.  I think you can put it all live.

**Comment by cgladue** [comment]
youd need to design the look and feel for shop and xclub first .. if you want i can take a stab at it and you can approve or you can do it all up to you

**Comment by robgpeak** [comment]
Yeah I just left for a Sunday drive.  Can you take a stab at it and let me have a look at them.

**Comment by cgladue** [comment]
@robgpeak ok i added xclub take a peek and let me know if you want something changed or you can change it

**Comment by cgladue** [comment]
this is on the test site by the way so test.rewardseverywhere.co

**Comment by robgpeak** [comment]
OK, I tweaked the Xclub welcome email and it's good to go.  A few things: 

1. The My Account Dashboard button moves to the bottom center (Awesome... Thank you), but for some reason the font that I am using in the edit mode (Helvetica) does NOT show up in the preview?  Meaning when I look at it in the edit mode, it is showing up as Helvetica, but in the preview window it's not.

2. The same thing with the new copy that I put in at the row towards the bottom...  To change your email subscription preferences, please visit the "Communications" section of your Account Profile  I have it as Helvetica on edit mode, but when I look at it in preview, it is a different font.

3. With the above being said, can we add the ability to send a test email so I can send a copy to myself to see exactly what it will show up looking like on my computer and phone.

**Comment by cgladue** [comment]
it looks like Helevitica is a Mac Only font, that may be causing some of the issues, can you change it to a generic font that most PCs have like Times New Roman or Georgia ?

**Comment by robgpeak** [comment]
Then what font is the main body of the message using?  It says it's helvetica...

**Comment by robgpeak** [comment]
I would rather use Arial than TNR or Georgia at worst case.

**Comment by cgladue** [comment]
Its a font-family.  So it tried the first, if thats not available it tries the second, etc.. 

it looks like its currently using Ariel

![image](https://user-images.githubusercontent.com/7914133/78038847-52f0d100-733b-11ea-817e-f97461ce4e9b.png)

**Comment by robgpeak** [comment]
SO let's make that the case as well for the button font, and the font in that new section I added, "To change your email subscription preferences, please visit the "Communications" section of your Account Profile." 

Meaning at the moment it is not using Arial but should be.

**Comment by cgladue** [comment]
ok let me see

**Comment by cgladue** [comment]
i just redid the selection to Arial and checked and it is showing Arial now

**Comment by robgpeak** [comment]
cool

**Comment by cgladue** [comment]
UGH google is ignoring the CSS to center the my account dashboard button under the logo... 

is there any other place you would be ok putting it .. i have no idea why it works everywhere else but gmail

**Comment by robgpeak** [comment]
How bad does it look?

Thanks,

Rob

*Sent from my phone

**Comment by cgladue** [comment]
its on a second line and below the logo its just not centered

**Comment by robgpeak** [comment]
Just thinking out loud without looking at it, but what if you put the logo on the left and the button on the right in two separate cells and have them centered in each cell do you think they would stack and remain centered on a small screen

**Comment by cgladue** [comment]
i tried that too, but google dosnt stack them because they are all one ro the cells just get smaller and smaller

**Comment by robgpeak** [comment]
Damn.  Just finishing a late lunch.  I will get in front of my computer in a minute and mess with it.  Do you have the ability to send yourself a test email to see what it looks like without having to register again.

**Comment by cgladue** [comment]
yea that part is done just deploying it now

**Comment by robgpeak** [comment]
ok let me know when it's deployed so I can conduct some tests on the button
placement.

>

**Comment by cgladue** [comment]
ok u can try it now

https://test.rewardseverywhere.co/dashboard/property/templates/12

**Comment by robgpeak** [comment]
It works if I leave it stacked all the time...(below) and the send test email works too.

<img width="546" alt="Screen Shot 2020-03-31 at 4 07 48 PM" src="https://user-images.githubusercontent.com/28393235/78070528-f22cbd00-7369-11ea-9739-97166b03ad47.png">

<img width="562" alt="Screen Shot 2020-03-31 at 4 08 13 PM" src="https://user-images.githubusercontent.com/28393235/78070541-f8229e00-7369-11ea-9409-4dddac598377.png">

**Comment by cgladue** [comment]
oh, ok then

**Comment by robgpeak** [comment]
Still trying to figure out how to make the overall header and body of the message appear wider in the actual email on the computer compared to what I see in the preview window, and what actually shows up in my gmail inbox?  I would think it would have something to do with the table properties, but I can't seem to figure it out.

**Comment by cgladue** [comment]
i had it set to the first and last column are 20% the middle is 60%

you could do 10, 80, 10 perhaps 

select the entire first column right click and choose cell properties and set width to 10% do the same for the other two columns

**Comment by robgpeak** [comment]
10,80,10 is a little better, but there is still something constraining the overall table itself.

**Comment by robgpeak** [comment]
OK, I have the table properties overall at 100% and the cells at 1, 99, 1 and it looks beast on computer and phone.

**Comment by robgpeak** [comment]
Ready when you are for full deployment to main database.  Thanks Chad, looks and works great.

**Comment by cgladue** [comment]
ok, we could make a copy and set to inactive and play around with using just 1 column or no column at all even if thats the case later on too

**Comment by robgpeak** [comment]
yep, that'll work too.

**Comment by cgladue** [comment]
ill leave that alone for now tho and go with what you have

**Comment by cgladue** [comment]
actually can you look at the templates for test.rewardseverywhere.co (which will be copied to marcus after go live) and do whatever you did for xclub ?

**Comment by robgpeak** [comment]
please see if you can replicate and fix... https://www.loom.com/share/8f717646f4a54cc2940c55a452feea94

**Comment by cgladue** [comment]
ok so i was able to replicate and fixed, i highlighted the entire cell with the logo and clicked the Clear Formatting button to clear any formatting that was applied to that "text"

![image](https://user-images.githubusercontent.com/7914133/78081441-89037480-737e-11ea-9c13-e7fea9621d23.png)

**Comment by robgpeak** [comment]
Ok cool.  I am getting ready to play a 7 tournament 😊

**Comment by cgladue** [comment]
this is live now you may want to tweak marcus and shop templates.

**Comment by robgpeak** [comment]
OK, tried removing the formatting and that is not working the way I would have thought.  Please have a look and let me know what you think?

https://www.loom.com/share/07901cc2103b4d29b0d59dc475034060

**Comment by cgladue** [comment]
you can also grab the bottom border of the row and drag to resize it instead of putting a number in

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/78138633-3fa23c00-73f5-11ea-8715-f54c21f0cb69.png)

**Comment by robgpeak** [comment]
wow, much easier.  thanks.

**Comment by robgpeak** [comment]
How do I change the color of the "CLICK TO COMPLETE REGISTRATION" button?

**Comment by cgladue** [comment]
there are 4 pre-defined templates .. go to insert template and you can see them, they are based on the primary and secondary colors for the partner in the url bar ... other then making an image and using that there really is no easy way to make rounded corners and stuff in the editor so i haev to pre-define them

**Comment by cgladue** [comment]
also you can do this on live now so maybe its better to do there up to you

**Comment by robgpeak** [comment]
In testing the button link in the confirmation email on shop, I am getting a 400 page error.  What should the link be?

<img width="778" alt="Screen Shot 2020-04-01 at 9 43 16 AM" src="https://user-images.githubusercontent.com/28393235/78144261-5fd5f900-73fd-11ea-97df-cf0f803ce4c5.png">

**Comment by cgladue** [comment]
thats not from an actual signup right just the test email you generated ?

if so thats as expected, i cannot generate a test verify url unless the user is newly registered so the merge tag cant be replaced with an actual valid link

**Comment by robgpeak** [comment]
understood.  But that URL string in there is correct yes?  https://shop.rewardseverywhere.co/dashboard/property/%%verify_email_link%% 

(where "shop" is replaced by the proper subdomain)

**Comment by cgladue** [comment]
the URL on the button link should just be: 

%%verify_email_link%%

but if you click it it will go to the current url + that value .. just make sure the link is only se to %%verify_email_link%% on the button

**Comment by robgpeak** [comment]
gotcha

**Comment by robgpeak** [comment]
What am I doing wrong.  https://www.loom.com/share/d550bb43cc5845d5aa0d51b52d1c8f4a

**Comment by robgpeak** [comment]
Also, is it normal that the test email for xclub would be sent from shop@rewardseverywhere.co

<img width="546" alt="Screen Shot 2020-04-01 at 10 33 40 AM" src="https://user-images.githubusercontent.com/28393235/78149695-471d1180-7404-11ea-8d2c-3d76726ed148.png">

**Comment by cgladue** [comment]
ok so what i did was i cut the image to my clipboard.  then clicked in the space below where the image used to be (there was a carriage return/new line there) and hit delete/backspace a few times and it removed that empty space, i then pasted the image back in and centered it.

**Comment by cgladue** [comment]
and yes the test will always come from shop

**Comment by robgpeak** [comment]
OK, and OK.  Thanks.

**Comment by cgladue** [comment]
i know some things may be tough to get used to or not work well enough.  i will do my best to adjust anything that causes you heartburn.  maybe using the tables isnt a good way to go, if you want you are able to copy the template from one subdomain to the same subdomain, which basically makes a copy in the same subdomain, then set one to inactive and you can play around.

**Comment by robgpeak** [comment]
The link for the email registration is broken https://www.loom.com/share/48846f91930e4c668baf19b007124758

It is putting additional code in there.

**Comment by robgpeak** [comment]
Are you looking into this now because it is a critical issue.  In fact, we need to make sure that everyone who signed up since this went live does in fact receive the correct email validation link.

**Comment by cgladue** [comment]
ok its all set now i have no friggin idea why it didnt work on live but works on test, i changed the tags to use ## instead of %% since # is a valid character in a URL so the dumb editor dosnt remove it ...

**Comment by cgladue** [comment]
i saw emails going out last night, but i can resend any that arent verified and signed up since it changed just in case

**Comment by robgpeak** [comment]
So what I hear you saying is I should have the link look like this... yes?  ##verify_email_link##

**Comment by cgladue** [comment]
Yes, thats the new format, i changed xclub already but feel free to

**Comment by cgladue** [comment]
and if you click "Available Merge Tags" button you will see the possible tags too if you forget

**Comment by robgpeak** [comment]
I just sent myself a test using the preview functionality, but the CLICK TO COMPLETE REGISTRATION is not clickable.  is that normal in testing?

**Comment by cgladue** [comment]
yea i believe it is because google is stripping it out since its not a real link, but i will make a change and just stuff a url in there anyways so you can see it works ....  one moment

**Comment by cgladue** [comment]
ok try it now, it will always send you to google.com

**Comment by robgpeak** [comment]
OK, but what you're saying is, if I do it live as a real new person registering, it will send them to the proper email registration page that you built, yes?

**Comment by cgladue** [comment]
Yes, there just is no such page when you are testing so i cant send you there since you are already a user and that link only gets created once at time of registration.  so for testing it will just stick google.com in there instead.  but for the real registration it will send them where they need to go

**Comment by robgpeak** [comment]
OK, all seems to be working with this from a technical perspective, so I cam going to close this issue.

**Comment by robgpeak** [comment]
Thank you Chad!
