### ISSUE TITLE
Mobile Home screen icon

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#37]
I've seen it before we're visiting a mobile site it will ask you to create a shortcut on your home screen. I would like to do the same thing for our mobile version for each different subdomain

Here is some info I found.

https://codelabs.developers.google.com/codelabs/add-to-home-screen/#0

https://webdesign.tutsplus.com/articles/quick-tip-give-your-website-an-ios-home-screen-icon--webdesign-10067

Once we get this and the push notifications all sorted, we will have an explainer video made to so end users how to use both, and the benefits of doing so.

**Comment by robgpeak** [comment]
@cgladue I know we had some trouble with this last time, but just for reference, the code that are using on https://mobile.groovehq.com to promote the user to add a link to the home screen is working well.

**Comment by robgpeak** [comment]
Hey @cgladue maybe we can have @ChrisASearles look into this and troubleshoot it to see if he can it to work properly?  If so, please explain to him what happened last time.  I remember it causing some sort of problem with the site, but I forget what it was.

**Comment by cgladue** [comment]
i think the problem it had last time was the site was trying to load from cache (i think thats how it works) and something wasnt right so it failed to load anything ... i know it requires you to setup a service worker and specify what resources are available offline and stuff so im sure i didnt do something quite right with that since i havent done it before

**Comment by robgpeak** [comment]
OK, let's let Chris take a crack at it.

**Comment by ChrisASearles** [comment]
As far as I can tell this should be working but I can't get it to work on my emulators and I don't have a cable for my phone with me here today so I can't debug it there. I'm going to commit what I did so it gets pushed up (it shouldn't affect anything else) and I can look at it live on my phone once Chad publishes it. From there either when I can debug it on my device or if @cgladue and I can figure out what I'm doing wrong to get it working we can try to put our heads together and see if we can get it sorted.

**Comment by robgpeak** [comment]
@cgladue Was this commit that Chris did ever pushed live?   I am not seeing the notification asking to add the shortcut to my home screen on my phone, or my desktop on my computer.

**Comment by robgpeak** [comment]
I just realized looking at my last comment that the functionality of making this also work on the desktop would be a different issue.  I will submit a separate issue for that now.

**Comment by cgladue** [comment]
I believe it was yes.

**Comment by robgpeak** [comment]
@ChrisASearles please let me know if this is working on your side?  I am not receiving a notification when I go to shop.complinks.co to "add a shortcut to my homescreen" on my phone.

**Comment by ChrisASearles** [comment]
No, not working for me. Like i said, never done this before so I might have to dive a little deeper into it to try to figure it out. @cgladue have you done this before? Any ideas?

**Comment by robgpeak** [comment]
I just went to my generic standard browser on my phone the Samsung internet browser and went to shop.complinks.co and it asked me to create a shortcut on my home screen? prior to doing it I cleared my cache so it was a fresh visit but I did the same thing on my Google Chrome on my phone and I did not get a notification to add the complex icon to my home screen??? Just an FYI

**Comment by cgladue** [comment]
@ChrisASearles never did it before
