### ISSUE TITLE
A little help with Intercom

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#370]
@cgladue please have a look at this video and see if you can help with this issue.  Not sure how or why this is happening, but it's not good.

https://youtu.be/zCOIopOgNsM

**Comment by robgpeak** [comment]
So I asked Intercom support about this and sent them this video.  I just wanted to bring you in the loop

https://www.loom.com/share/4e19d0c2e38c45eb96043b3c236de7ba

**Comment by cgladue** [comment]
hmm, ok so after thinking about this some more, is there any way to create a second instance of intercom as a test instance ?  would that cost more money ?  i think there could be a small chance this is related to the test site and its database interfereing with the live site and its database ...  users are different account numbers are different and intercom may be getting confused

**Comment by cgladue** [comment]
found it in their help section if you are ok with it ill set this up ?

> Create a test workspace in Intercom
> Set up a test workspace of Intercom in your development / staging environment to be sure it’s working correctly before putting it live.
> Ruairí Galavan avatar
> Written by Ruairí Galavan
> Updated over a week ago
> You can set up a test workspace of Intercom in your development/staging environment before adding it to production. Lots of our customers like to do this as part of installing Intercom so that they can be sure it’s working correctly before putting it live.
> 
> Note: There is no additional charge for creating a test workspace of Intercom. 
> 
> Why is it helpful?
> It's great for getting familiar with how Intercom works. You'll be able to hit the ground running then when you do put it live :)
> It allows you to sanity check your user data to see that it's doing what it should be.
> Some people like to get comfortable with sending test messages first, before contacting their real customers. Setting up a test workspace can be helpful for this because it lets you test your auto messages to make sure that they are sending as expected.
> You should use the test workspace as an opportunity to test any custom attributes that you're thinking of sending to Intercom.
> What you need to know about test workspaces 
> Test workspaces are completely separate workspaces with separate data, conversations, messages, etc. You can use Test workspaces to send real messages to users. 
> There's no additional costs to creating a test workspace and there are no user limits. 
> Your test workspace's products are inherited from your main workspace (e.g. if your main workspace doesn't have Engage, your test workspace won't either). 
> If you delete a test workspace it will erase all data within it and cannot be undone.
> It's not possible to migrate data (messages, users, articles etc) from a test workspace to your live workspace.
> So, here's how to do it:
> Step 1: 
> 
> Go to your settings.
> 
> 
> Step 2: 
> 
> You'll then be directed to your General Settings screen where you need to tick the box next to 'Test Workspace', and click Save.
> 
> 
> Step 3
> 
> You'll receive a confirmation message at the top of the screen and your test workspace ID (App ID) will be displayed next to the 'Test Workspace' check box that you selected, as shown below.
> 
> 
> Step 4
> 
> Make sure to add the Intercom snippet to your non-prod environment. When you do, your test workspace will inherit the messaging abilities of your production workspace in Intercom but it will have its own workspace id (app ID), to keep data separate. You need to make sure to update your intercomSettings so that the app_id field has the correct value based on the environment that your site/app is running in. If you're using identity verification, you'll need to go into your setup guide to get the new API secret for your test workspace.
> 
> And... you're done!
> To find your test workspace hover over your avatar, then hover over your real workspace and you'll see the test workspace you've created.

**Comment by cgladue** [comment]
ok for me to make this change?

**Comment by robgpeak** [comment]
So how is it working now in separating shop and xclub?  Meaning, in an ideal world, it would be one "Rewards Everywhere" Intercom workspace, with all the different companies/subdomains separated by their different Company Names...

**Comment by cgladue** [comment]
as long as its one database its fine separating it out but we have a separate test DB now that has a completely separate set of data.   but only one instance of intercom for both so the users get mixed up is what i think is the case, we only recently added the test site so its a new problem... and only from now when we are doing testing we are seeing it.

**Comment by cgladue** [comment]
trust me i think it may solve the issue and wont affect anything only test

**Comment by robgpeak** [comment]
OK try it.  Does that mean though we would be able to leave, CompLinks, Xclub and Marcus Theatres in one instance of Intercom and we can segregate the user by Company Name?

**Comment by cgladue** [comment]
yea that wouldnt change

**Comment by cgladue** [comment]
ok do you have a chance to talk on zoom ?  i can show you how it works.

**Comment by robgpeak** [comment]
Give me a few minutes.  By the way the intercom engineer team is looking into it at the same time.

**Comment by cgladue** [comment]
Should be all set now
