### ISSUE TITLE
The T&Cs link for partner's sites

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#371]
Hey @cgladue I thought the link below the Transfer button on the rewards page https://marcustheatres.rewardseverywhere.co/myrewards was supposed to be going to the T&Cs link in the Property list modal...  Wee images below and look at the status bar as to where it actually goes.  Am I missing something.

<img width="473" alt="Screen Shot 2020-03-26 at 9 41 25 AM" src="https://user-images.githubusercontent.com/28393235/77653642-602a4c00-6f46-11ea-951e-86d031b78b6b.png">

<img width="775" alt="Screen Shot 2020-03-26 at 9 41 49 AM" src="https://user-images.githubusercontent.com/28393235/77653657-66202d00-6f46-11ea-9052-2ccdc8391b01.png">

**Comment by cgladue** [comment]
All Set and its live

**Comment by robgpeak** [comment]
@cgladue I tried it again, but the link is still not correct.  Looking at the page https://marcustheatres.rewardseverywhere.co/myrewards the Terms & Conditions link should be going to https://www.marcustheatres.com/movie-rewards/terms-conditions like it says in the Property list edit modal, but it's still going to our T&C's in a modal.  But we want it to go to the partner's site in a new tab.

I thought it may have been that I did not restart my browser, so I re-registered a new account from a cleared cache browser and it brought up a separate issue. #373

**Comment by cgladue** [comment]
should be opening in a new tab right ?

**Comment by robgpeak** [comment]
Yes, working now.  Thanks.

**Comment by robgpeak** [comment]
Thanks Chad
