### ISSUE TITLE
hero image URL target

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#372]
@cgladue In the dialog box that opens up to edit the hero image we need to add a field in there called "URL Target" and if some enters "_blank" in the field, then on the front end when someone clicks that particular hero image it would open a new tab.  If someone wants the link to open in the same window as the page that hosts the hero image, the URL Target field would be "same" OR if left blank it would default to the same (current) tab. 
<img width="821" alt="Screen Shot 2020-03-26 at 11 37 05 AM" src="https://user-images.githubusercontent.com/28393235/77666630-8efcee00-6f57-11ea-9996-0d27e4715352.png">

**Comment by cgladue** [comment]
ok this is now live on the live site along with all the other stuff (Mailchimp is totally disconnected now)
![image](https://user-images.githubusercontent.com/7914133/77681622-00df3280-6f6c-11ea-959e-3c65cc5d3640.png)

**Comment by robgpeak** [comment]
cool
