### ISSUE TITLE
Points not showing up in my dashboard

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#373]
@cgladue Please have a look https://www.loom.com/share/6de5c9b853b44e9c91bda0d8707d43e1

Additionally, On the rewards page, it currently reads, "The minimum amount of points needed to transfer is 100.00, please come back when you have more points." we want it to read "The minimum amount of points needed to transfer is 100, please come back when you have more points."  No ".00" after 100.

**Comment by cgladue** [comment]
The user info is cached on a per-session basis, try closing all your browser tabs and going back in (you dont need to clear tmp files) or use incognito window and tell me if the points are still now showing up ?

**Comment by robgpeak** [comment]
Working now. Thanks
