### ISSUE TITLE
Not showing "0's" to the right of decimal points

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#374]
@cgladue  I wanted to see if whenever there is no value to the right of the decimal point in any number(front end customer dashboard and back end), we leave the number displayed without the decimal and the 0 to the right of it.  For example in the "2000.0" in the image below, it would just be 2000

<img width="1048" alt="Screen Shot 2020-03-30 at 10 50 50 AM" src="https://user-images.githubusercontent.com/28393235/77926796-874d8a00-7274-11ea-91c2-f29166896085.png">

**Comment by cgladue** [comment]
i can, but the sorting will be all messed up if someone wanted to sort on that column and some are .23 and others are no decimal.  the other option is to always make it 2 decimal places like people are used to.

**Comment by robgpeak** [comment]
I think we are talking about two separate things.  If a number is 2000.0 or 2000.00 or 2000, it will not change the order of a sort.  It would still be 2000

Meaning, if you were to look at the three number in the screen shot in this thread, 147.5 would remain in tact, 0.1 would remain as is, and 2000.0 would become 2000, and would not change is true value, nor would it change the order it would show up in in an ascending or descending sort.

**Comment by cgladue** [comment]
not neccessarily true, if some of them have decimals and the others are formatted differently then its no longer a "Numeric" type of data its now text, so it would not sort the usual way that a numeric type would sort, it would have to sort A-Z or Z-A

**Comment by robgpeak** [comment]
Ah, I see what you're saying.  I thought they would all still be numerical, but with a conditional statement that says, "if it is a whole number grater than 1, don't show the decimal point and zeros to the right."

**Comment by cgladue** [comment]
thats the goal, but im not sure i can or not, im just sayin worse case .. but i will try it and let you know

**Comment by cgladue** [comment]
@robgpeak take a look on live i think thats what you wanted

**Comment by robgpeak** [comment]
perfect.  thanks.
