### ISSUE TITLE
Showing the actual points value bonus

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#375]
@cgladue In looking in the https://marcustheatres.rewardseverywhere.co/pointshistory I see the bonus for trip 8494 shows in the "Points" column, 0.1 which indicates that I am to receive 10%, but to a lay person it looks like i am going to receive .1 points.  Is there a way to change that to the actual point value?  So in essence, I should be receiving an additional 14.75 points, which should also show in my total pending balance...

So I understand that until the merchant reports to us that a transaction has taken place, and how much commission is owed, it need to remain the percentage, so during that state, can we display "10%" in that column instead of 0.1?

**Comment by cgladue** [comment]
it can stay that way in the DB, but ill just format it differently on display on that page.

**Comment by robgpeak** [comment]
That's perfect.

**Comment by cgladue** [comment]
hows it look now ?

**Comment by robgpeak** [comment]
Cool
