### ISSUE TITLE
Update on Macy's commissions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#376]
@cgladue @morganpeak a couple of weeks ago Macy's changed their public offer to 0% and then starting yesterday they changed it to 3%. So I just went in and selected the 3% public offer inside linkshare, but I'm wondering how long it takes for that to propagate and show up on our side so I can activate them again?

![Screenshot_20200502-075747_Chrome](https://user-images.githubusercontent.com/28393235/80863574-626d7d80-8c4b-11ea-9fa8-1e92dac4b437.jpg)
![Screenshot_20200502-075947_Chrome](https://user-images.githubusercontent.com/28393235/80863576-67cac800-8c4b-11ea-86d4-fd29b3711a63.jpg)

**Comment by cgladue** [comment]
It looks like the record was updated in our DB at 6pm last night ... i just set the last update time to midnight yesterday to force it to update again on next run, give it a few and i will let you know if it updates to 3% like it should.

**Comment by cgladue** [comment]
it just ran, and macy's is showing 3% now as expected ... generally it takes 12 hours or so from when you make the change till we update our stored copy of the advertiser data but i hurried it along this time

**Comment by robgpeak** [comment]
Thanks Chad
