### ISSUE TITLE
some logos not showing up 

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#377]
hey @cgladue please have a look at https://xclub.rewardseverywhere.co/

**Comment by cgladue** [comment]
hey rob, i dont see any issue with the advertiser logos ?   any one in particular

**Comment by robgpeak** [comment]
Hmmm.  I think I found the culprit ... I installed Ublock Origin extension to block ads.  If I turn it off, all the logos show up the way they should.  Weird.

<img width="1245" alt="Screen Shot 2020-05-04 at 7 31 44 PM" src="https://user-images.githubusercontent.com/28393235/81023337-04ed5280-8e3e-11ea-8794-4e3e6c8409da.png">

**Comment by cgladue** [comment]
can you set *.rewardseverywhere.co as an exception ?

**Comment by cgladue** [comment]
actually, must the images are hosted on aws so you would need to add them probbally..

**Comment by robgpeak** [comment]
Ok thanks.
