### ISSUE TITLE
advertisers now showing up in backend

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#378]
@cgladue please have a look at https://shop.rewardseverywhere.co/dashboard/advertisers and let me know if they show up for you.

**Comment by cgladue** [comment]
yes, they do show up 

![image](https://user-images.githubusercontent.com/7914133/81943939-06e7ac00-95ca-11ea-9c20-60eed150f133.png)

**Comment by robgpeak** [comment]
Damn, it was that ad blocker again 🙂  Sorry about that.
