### ISSUE TITLE
New Property button not working

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#379]
@cgladue For some reason nothing happens when I click the new property button on the page https://shop.rewardseverywhere.co/dashboard/property

**Comment by cgladue** [comment]
Ok let me check into this

**Comment by robgpeak** [comment]
Any ideas on this?

**Comment by cgladue** [comment]
sorry still looking

**Comment by cgladue** [comment]
Sorry it took so long combination of things but i think its ok now if you want to try ?

**Comment by cgladue** [comment]
if you are adding a new partner then ill have to update the server to accept connections on the new subdomain

**Comment by robgpeak** [comment]
Does that mean you'll have to do that first?  I just tried to create a new property for Lyft and it would not work.  Could you please do what you need to do set it up so that lyft.rewardseverywhere.co works.  I guess that would mean cloudflare too.  Thanks.

<img width="563" alt="Screen Shot 2020-06-04 at 1 12 55 PM" src="https://user-images.githubusercontent.com/28393235/83789831-42bfdf80-a665-11ea-92d4-6dca350f4682.png">

**Comment by cgladue** [comment]
hmmok well i manually added it you should be able to edit it now ill look into why it had an issue
