### ISSUE TITLE
Home Depot order?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#382]
Hey @cgladue please see if you can find the order W957561094 anywhere in our system.  I bought two ceiling fans on June 2 and they were delivered on June 12th.  I don't remember the exact shopping trip, but I think it might have been 8696

**Comment by robgpeak** [comment]
@cgladue I had a shopping trip 8799 to Home Depot yesterday where I made a $10 purchase, but still nothing showing up in the reports.  Can you please check that the systems are working correctly.

Home Depot Order Number WJ10021141

It used to show up within an hour...

**Comment by cgladue** [comment]
yea i will look right now hold on

**Comment by cgladue** [comment]
ok so it seems there was a connectivity issue with the VM that runs the engine ... i couldnt log into it so i stopped the started it again and now its fine .. perhaps something happened with the physical hardware it was running on in AWS datacenter usuall a stop and restart moves it to a new hardware thats working ... and i see your purchase and several others now.

**Comment by robgpeak** [comment]
Strange.  I see them now.  Thanks.  I will close this issue now I suppose.
