### ISSUE TITLE
scrolling text (images) inline with other text

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#384]
@cgladue I wanted see if you knew how I could accomplish this...?

https://www.loom.com/share/4c28ae42ece14970b24db14842c88d64

**Comment by robgpeak** [comment]
any luck here @cgladue

**Comment by cgladue** [comment]
i am sure its possible just need to find the right javascript to do it ... still looking

**Comment by cgladue** [comment]
https://elementor.com/blog/introducing-animated-headline/   is this kinda what you want to do ?   im not sure how to put them togeter in wordpress i assume you would know how since you use it more then i do ?

**Comment by cgladue** [comment]
hmm, after watching the video on their site it might be text only effects ...

**Comment by cgladue** [comment]
https://codepen.io/lembitk/pen/wawmWM    i can make this do what you were asking, but its not for wordpress its just HTML  and CSS... not sure what plugin would work on wordpress

**Comment by robgpeak** [comment]
Ok let me look into it.  Thanks.
