### ISSUE TITLE
moving a transaction

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#385]
@cgladue Please have a look at moving a transaction into someone's account.

https://www.loom.com/share/fc5951dff470496a975d42e7e4a88446

**Comment by cgladue** [comment]
ok i am looking now i will let you know sometime tonight rob

**Comment by cgladue** [comment]
i credited it to him, there was no trip ID returned to us so something went weird with his trip that time.  the comission was .6648 on a 66.48 purchase so he should get 33.24 points correct ?

**Comment by robgpeak** [comment]
I suppose that's correct. Maybe you can look at the previous transactions
that he's done of all the same prices.

**Comment by cgladue** [comment]
Yea i did that but it seemed like the comission used to be higher before the pandemic, so i didnt think the totals matched the current.so i calculated it out based on what the commission actually was this time.

**Comment by robgpeak** [comment]
Yeah that's fine.  You can close this issue.

Thanks,

Rob

*Sent from my phone
