### ISSUE TITLE
Walmart moved to Impact

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#386]
@cgladue I got this email from Walmart below.  We are already in their Impact program and I wanted to see if you can make the necessary transition in our back end.  Thanks.

Valued publishers,

Last year, we sent out communication that we are shutting down Walmart program on Rakuten Marketing platform. But, some of you were asking for additional time. Unfortunately, we are at a point where we need to shut it down. Effective immediately, we will start removing publishers from our program in Rakuten marketing platform.

To continue participating in Walmart affiliate program, pls sign-up here: https://affiliates.walmart.com/

Thank you for your continuance support. We look forward to see you in the other platform.

Walmart Affiliate team

**Comment by cgladue** [comment]
are they showing up in the backend in both programs currently ?

**Comment by robgpeak** [comment]
They are both in the back end and the one for impact seems to be working so we're good
