### ISSUE TITLE
Linking the same account

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#39]
@cgladue I was just poking around and I saw that we both linked to the same xclub rewards ID, and I don't think we would want to allow that to happen in the real world...

Additionally, for consistency and continuity throughout the platform, first name and last name should always be separate fields.

![uploads/64e06eaf-1d71-4d83-b473-d45f177fd6c9/Screen Shot 2018-03-08 at 8.39.39 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F64e06eaf-1d71-4d83-b473-d45f177fd6c9%2FScreen+Shot+2018-03-08+at+8.39.39+AM.png)

**Comment by cgladue** [comment]
This is not allowed now...
