### ISSUE TITLE
update verbiage on ./myrewards page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#4]
@cgladue Please change the verbiage on the page when someone does not have enough points to read to include the bottom line below:

You currently have {number of points} Rewards Everywhere points available.
Minimum transfer is 1,000 Rewards Everywhere Points
(1000 Rewards Everywhere = {1000*[Redemption Rate]} {Rewards Program Name})

This is the same line of copy you have on the page when someone does have enough points to make a transfer.

**Comment by robgpeak** [comment]
@cgladue This seems like an easy fix that Parx wanted to see on the page when someone does not have enough points:<br><br>

The first two lines are there already, we just need to add the third and last line<br><br>

<font color="red">You currently have {number of points} Rewards Everywhere points available.</font><br>
<strong>Minimum transfer is 1,000 Rewards Everywhere Points</strong><br>
(1000 Rewards Everywhere = {1000*[Redemption Rate]} {Rewards Program Name})<br><br>

**Comment by cgladue** [comment]
yessir, will add it tonight



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
should be set now
