### ISSUE TITLE
Need to see Store Logos everywhere for consistency

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#40]
@ChrisASearles This one might be a little tricky to explain verbally, so I made a screen cast https://screencast.com/t/qTvBXU2S

In a nutshell, we need to have the store's logo appear with any and all listings that relate to it.  Meaning in the All {Category Name} Stores section at the bottom of each category, in the Feature Stores and Featured Deals (you can see it when you do a search and view the results on the page), regardless of the size of the screen that the person is viewing the site on.  Right now it changes based on screen size, and it shouldn't.

**Comment by ChrisASearles** [comment]
Committed.

**Comment by robgpeak** [comment]
cool
