### ISSUE TITLE
Forgot Password link to the same overlay

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#42]
@ChrisASearles The Forgot Password link in the Sign In overlay redirects to a page by itself (https://shop.complinks.co/account/forgotpassword), and it looks terrible from a UI/UX perspective.  Can we have it pop open in the same overlay as the sign in window, or at least a different overlay in a layer in front of the Sign In overlay.

**Comment by robgpeak** [comment]
@cgladue Does the functionality of the page https://shop.complinks.co/account/forgotpassword even work?  I just tried to reset the password for test2@pekmarketing.com, and I did not receive an email showing me how to reset my password.

**Comment by robgpeak** [comment]
@cgladue @ChrisASearles I have since logged into the account and changed the password manually as an end user would, so please don't change this password in particular, as I am going to use this account to give the CJ and LS Quality Assurance people access to the site to ensure we are in compliance with our links.

**Comment by ChrisASearles** [comment]
New version of the change password page committed.

**Comment by cgladue** [comment]
can you create a matching one for /account/login ?  thats the last one that
needs creating...



Chad Gladue
*DevNull Technology, LLC*

**Comment by ChrisASearles** [comment]
Sure thing, login page committed.

**Comment by cgladue** [comment]
looks good !

**Comment by robgpeak** [comment]
I think this might be another issue to discuss on our call.  From what I see it is not behaving as I envisioned.  Again, I think it might be because it is seen as two different issues.  Anyway, let's discuss.
