### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#43]
@cgladue 
I just got off a skype call with the guy working on the web extension, and I think it would be worth having a quick call to make sure we are all on the same page with the functionality and data.

One very important thing to consider is that we are going to need to have the ability to quickly include or exclude an advertiser from showing up in the extension from our back end.  That would probably mean adding a field to the database that says "DSA";true," instead of just  "isAdvertiser":true,

I can see RB has already begun to remove advertisers from showing up in their extension who I know are against having their brands show up in web extensions, (what Rakuten calls DSA's - Downloadable Software Applications)

Please let me know when you can have a call with the three of us?

**Comment by cgladue** [comment]
The field is there, i will add it to the edit advertiser modal soon.

**Comment by robgpeak** [comment]
Let's close this issue and pick up the conversation in that other repository.
