### ISSUE TITLE
Update to Groove Intergration

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#44]
@ChrisASearles Based on the conversation that we had today about the importance of separate email boxes for each casino client, I would really like to see if the Groove Widget can send the message someone inputs on the site to a specific email address, based on the subdomain they are on.

For example, if the user sends from xclub.complinks.co the email it is sent to is xclub@complinks.co,
shop.complinks.co the email it is sent to is shop@complinks.co,
foxwoods.complinks.co the email it is sent to is foxwoods@complinks.co, etc.

I just asked Groove Support if they have a way to handle it on their end, but I am not sure they will be able to.  They do have rules, and I can set up some rules to move things to certain inboxes, but they do not have a rule that lets me set the "IF" it comes from a certain URL, "Then" move to this inbox...

My suspicion is they might not be able to do it, and if they can't, I would like to see if you can do it on our end.

![uploads/fa2f3f0d-6bbb-4755-bd6d-fa15fca87a7f/Screen Shot 2018-03-09 at 4.03.33 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa2f3f0d-6bbb-4755-bd6d-fa15fca87a7f%2FScreen+Shot+2018-03-09+at+4.03.33+PM.png)

**Comment by cgladue** [comment]
FYI the subdomain is stored in *ViewBag.partner.subdomain* if that helps
chris.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
As a follow-up, here is the email I just had with Groove support...

Hi Rob, 

Hmm, I'm not aware of any limits with the number of widgets you can create. You can have unlimited number of mailboxes and I believe it's the same with the widget as well. 

Cheers,
Lesley

Rob G. [Peak Marketing] on March 9, 2018 at 7:57pm wrote:

How many different widgets can I set up under the same account that have different email addresses to send to?

**Comment by robgpeak** [comment]
Hey Chris, I marked this one as a high priority, as it is very important that we get it sorted properly.  If it is not clear as to what we need to have done, please feel free to call me.

**Comment by robgpeak** [comment]
@ChrisASearles @cgladue I was just in GrooveHG settings, and I created another widget for Xclub Support and it spit our some code that says it should be placed before the </body> tag on the site, but obviously we would only want this on the xclub subdomain pages...  We would leave the current widget that is in place on shop as it is.

I hope this helps and does not hurt:)


<script id="grv-widget">
  /*<![CDATA[*/
  window.groove = window.groove || {}; groove.widget = function(){ groove._widgetQueue.push(Array.prototype.slice.call(arguments)); }; groove._widgetQueue = [];
  groove.widget('setWidgetId', '62449817-c1c4-48c2-6010-2454af6b6338');
  !function(g,r,v){var a,n,c=r.createElement("iframe");(c.frameElement||c).style.cssText="width: 0; height: 0; border: 0",c.title="",c.role="presentation",c.src="javascript:false",r.body.appendChild(c);try{a=c.contentWindow.document}catch(i){n=r.domain;var b=["javascript:document.write('<he","ad><scri","pt>document.domain=","\"",n,"\";</scri","pt></he","ad><bo","dy></bo","dy>')"];c.src=b.join(""),a=c.contentWindow.document}var d="https:"==r.location.protocol?"https://":"http://",s="http://groove-widget-production.s3.amazonaws.com".replace("http://",d);c.className="grv-widget-tag",a.open()._l=function(){n&&(this.domain=n);var t=this.createElement("script");t.type="text/javascript",t.charset="utf-8",t.async=!0,t.src=s+"/loader.js",this.body.appendChild(t)};var p=["<bo",'dy onload="document._l();">'];a.write(p.join("")),a.close()}(window,document)
  /*]]>*/
</script>

**Comment by ChrisASearles** [comment]
Hey @cgladue we're probably going to have to store the widget script with the partner info in the db, there's no identifier here that we can key off of to marry it to the subdomain on the front end. Can you add this field to the database and spit it out on the layout page in place of the current widget?

**Comment by cgladue** [comment]
i dont understand whats special about that widget that needs to be unique for the domain ... theres no identifer in there at all to identify the dmain its on,  it seems like it would be able to detect the domain automatically ?  is there a groove support email that we could get their inptut on @robgpeak .. kinda would suck to have to add another field to the partner record for this widget ...

**Comment by robgpeak** [comment]
Maybe the call will be more than 10 minutes, because I think we need to talk about this so you guys can understand what I am trying to accomplish.  When you see it, you might be able to see an easier or better way.  As for scheduling a meeting where I can share my screen, I am going to send a separate email outside of github.

**Comment by cgladue** [comment]
@robgpeak @ChrisASearles 

this is now complete.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/37866709-bc1b92c2-2f64-11e8-821d-6e0917ad6919.png)

**Comment by robgpeak** [comment]
sweet nuggets
