### ISSUE TITLE
missing data on /admindashboard/rewards/redemptions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#45]
@cgladue The email field is empty in this data set...

![uploads/e6ef26e2-c093-493e-97d5-7abdc957e748/Screen Shot 2018-03-09 at 6.14.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe6ef26e2-c093-493e-97d5-7abdc957e748%2FScreen+Shot+2018-03-09+at+6.14.08+PM.png)

**Comment by cgladue** [comment]
All this should be fixed this weekend I’m going to roll out the new dashboard

**Comment by robgpeak** [comment]
OK

**Comment by cgladue** [comment]
New Dashboard Layout, email is not on this table anymore.
