### ISSUE TITLE
Change a notification message

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#46]
@cgladue I was just setting up and testing a campaign, and when I click in the link and I am NOT logged in, I see the message Invalid User with a red exclamation point, and I would rather it say something like, "Please Log In First."

![screenshot_2018-03-10-11-56-02](https://user-images.githubusercontent.com/28393235/37244731-5029af2c-245b-11e8-863b-abe4df6cd380.png)

**Comment by robgpeak** [comment]
Hi Chad, this particular issue is fixed and I will close it, but just so you know, it creates another issue when I visit the site.  Meaning the messaging is now correct, but it redirects me to a page where on my phone the screen is grayed out and I can't click on anything (on my phone of course)
https://xclub.complinks.co/?login=True&redirect=%2Fstores%2Findex%2F6789%3Fguid%3DB46lCCKcCX3ySfAyQnZUKxPqz2ZYEZKN

**Comment by cgladue** [comment]
This is now Chris issue and is related to the login overlay that you wanted.  For some reason on your phone it didn’t work. But pc and iOS is fine. Once that’s fixed this will be as well.
