### ISSUE TITLE
Campaigns to be sub domain specific

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#47]
@cgladue as I am starting to message around with broadcast messaging with push notifications, I think we need to make campaigns site specific.  Meanibg, we are going to be giving away tickets to see a show at Parx for example, and we might send out a notification with a special incentive that would include a campaign reward, and we would only want Xlcub people to see it.

I also think just from  a back end management perspective, it might be cleaner and easier to manage if we could separate at least certain campaign separately by sub domains.

So a possible solution would be to manually set the campaign as "site specific" or "global".

Either way, considering we only have one partner live now, we can out this in the back burner, but nonetheless it is something to think about.

**Comment by cgladue** [comment]
if i am managing the notification subscriptions then i associate the user to the notification when they register so i can slice it any way you want and send to anyone you want, even if the campaigns are not site specific...

**Comment by robgpeak** [comment]
tbh, I am not really sure what that actually means, but again, I think we can readdress it when we bring on our second client just to make sure the campaigns are separated...  Ah, I just read it again, and now I understand it.  Just like to are managing the email list of people who opt in/out, when someone agrees (subscribes) to receive push notifications, you will know who that person is, and then we can segment the push notification messaging based on who they are and what partner they are with...  Gotcha.

OK, so we can work on the push notification stuff after we button up some of this other stuff.  Very cool. 

I've been messing around with the notifications from OneSignal on the regular complinks page (https://complinks.co) and here is some extensive documentation they have...  https://documentation.onesignal.com/docs/internal-database-crm  as well they have the ability to use geofencing.  https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

Please have a look when you get a chance.

**Comment by cgladue** [comment]
yea thats the geolocation built into most browsers nowadays thats not a
problem, the problem is your not going to be able to get that data when the
browser(phone) is locked or user is in another app.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Location services in a native app work even if the screen is locked, and
you can't get a browser to do that same functionality? I did test having my
browser closed yesterday and I was still able to receive notifications
which is pretty cool

**Comment by cgladue** [comment]
yea you can recieve the notifications when everything is locked because the
browser allows push notifications to work, but access GPS is not allowed
for privacy reasons i assume.

Native apps can run in the background and continually update your location
even when locked tho



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Hmm.  we'll have to try to find a workaround.  If not, we can just geo push
to those that we are able to, and regular push to those that aren't

Either way, if you have your own SSL site that you can install One Signal
on to monkey around with it, you should, it is pretty cool.

**Comment by robgpeak** [comment]
@cgladue what was the URL naming convention to add the guid to both the home page and an internal page.  There used to be an example in the campaign edit window, but it's gone.

**Comment by robgpeak** [comment]
Actually, I just found an old one I was using for testing https://xclub.complinks.co/stores/index/6712?guid=B46lCCKcCX3ySfAyQnZUKxPqz2ZYEZKN but how do I link it to the home page

**Comment by cgladue** [comment]
use /campaign/clicktrack/{guid}

so https://shop.complinks.co/campaign/clicktrack/
B46lCCKcCX3ySfAyQnZUKxPqz2ZYEZKN
<https://xclub.complinks.co/stores/index/6712?guid=B46lCCKcCX3ySfAyQnZUKxPqz2ZYEZKN>



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@cgladue I just tried to get to https://shop.complinks.co/campaign/clicktrack/66efc496d63d4c2d9e97b3d51c141218 and it came back with "Campaign Exception" message...  But if I go to https://shop.complinks.co/stores/index/7207?guid=66efc496d63d4c2d9e97b3d51c141218 it works as expected.

<img width="597" alt="screen shot 2018-04-06 at 3 04 15 pm" src="https://user-images.githubusercontent.com/28393235/38439483-d0de225a-39ab-11e8-85e8-434898c21803.png">

**Comment by robgpeak** [comment]
@cgladue And would being on a different subdomain make a difference?  Meaning, if I go to https://shop.complinks.co/campaign/clicktrack/66efc496d63d4c2d9e97b3d51c141218 it tells me that I've already received the award for this campaign, but if I go to https://xclub.complinks.co/campaign/clicktrack/66efc496d63d4c2d9e97b3d51c141218 I get the campaign exception message again.

**Comment by cgladue** [comment]
That’s very odd.   I don’t think there is anything that checks what subdomain it came from.  I will verify.  I’m sure it something minor.

**Comment by cgladue** [comment]
@robgpeak i think this is resolved ..can you try it again?

**Comment by robgpeak** [comment]
Seems to be working well now.  Thanks.
