### ISSUE TITLE
Expandable FAQs and adding images to the Answers

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#50]
@cgladue Unless this is a relatively easy fix, we may have to make it a back burner thing, but I wanted to see about having the "Questions" on the FAQ pages be clickable, whereby they expand to show the answer to that specific question?

The primary reason is, I would like to use this page to not only answer some of the FAQs with text, but I would also like to be able to include images in some of the answers.

A specific case in point is to "Show" people how to add our email address to their white list in their mail client so we show up in the primary inbox instead of promotions or worse of spam folder (which we already do with our welcome email).  People are going to need to see visuals...

So the answers might get long, verbose and convoluted if they are all visible at the same time.

That would also mean we would need to revisit the "Text Editor" from within the back end issue.

**Comment by robgpeak** [comment]
@cgladue As an update to this, if it is at least possible to make it expandable, I would like to have each question be a bookmark whereby the cs rep could send an email to a customers saying something like, See how to add our email address to your email program as a trusted sender, have a look at shop.complinks.co/faq#How-to-add-CompLinks-a-trusted-sender-to-my-email-client? and it would take them right to that question, and the answer would already be expanded.

If you have a look at the actual RAQs now on shop.complinks.co/faq and scroll to the bottom, you'll see what I mean about needing to have them expandable and collapsable.

**Comment by cgladue** [comment]
if it was on the backend then i would say no problem and ill have it done in a few minutes, but the frontend dosnt run jQuery it runs angular instead which i dont know how to do this is .. so it most likely will need to be something chris does :(

**Comment by ChrisASearles** [comment]
Committed. Note that the title fields for this are accept markup and one of them has malformed HTML that's being spit out to the front-end which is why it looks funky at the moment.

**Comment by cgladue** [comment]
For the buttons on how it works and faq is there any way To use the standard <button> tag in html instead of the angular ones.  Since wysiwyg editor strips out the unknown tags.

**Comment by cgladue** [comment]
Think this part is all set

**Comment by robgpeak** [comment]
The expandable function works.  Very cool.

Is there any way I can put images in there?  Should that be a separate issue?

**Comment by cgladue** [comment]
All set, you can upload images now... 

![image](https://user-images.githubusercontent.com/7914133/37805034-1d384378-2e0e-11e8-8751-e3bfa5ce329c.png)

**Comment by robgpeak** [comment]
The image upload button is not showing up on my side.  I did a shift refresh and even tried a new log in in an incognito window... still nothing

**Comment by cgladue** [comment]
on the FAQ edit screen ?




Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
Oh my bad i dont think i published the changes one sec its uploading now...

**Comment by cgladue** [comment]
ok its there now @robgpeak

**Comment by robgpeak** [comment]
sweet
