### ISSUE TITLE
Calculating the true profitability

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#51]
@cgladue On the /dashboard/admin/profitability page this is showing all purchases even pending, which is fine, but we are going to need a page that will show true profitability when we actually get paid by the networks less what we actually pay to the partner site.  This will be something for you to think about based on the reports that we get from the networks and how/when we actually pay the partner for the points transferred.

**Comment by robgpeak** [comment]
As a follow up to this, again, we are really going to need to think about how to specifically tie a purchase which we finally get paid on back to the original trip/purchase and issuance of "available" points.  Is there a way to do that?

**Comment by cgladue** [comment]
If there was a report that showed what SIDs made up each payment then it should be trackable yea, but i dont see any way to get them so far, looking at CJ i see a report that kinda shows it, but it dosnt say they paid you, just the transaction is closed...
![image](https://user-images.githubusercontent.com/7914133/38003043-a75fbb1e-3203-11e8-9509-dc5e90a24386.png)

**Comment by cgladue** [comment]
this topic is going to be a real headache... LS does have some reprt that may show what you want but when i run it it takes FOREVER to run and then times out and fails ... and im only running for a 30 day peroid so its brutal...

**Comment by robgpeak** [comment]
Well hopefully we don't have to run it once a month anyway so just do the
best you can. And you might as well check impact radius as well
