### ISSUE TITLE
Missing data on /dashboard/accounting/purchases page, AND add link to users

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#53]
@cgladue The columns for the first name and last name are blank.
![uploads/d9a09a78-cbb3-44c5-9aee-6c0bc83e08d7/Screen Shot 2018-03-14 at 10.02.53 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd9a09a78-cbb3-44c5-9aee-6c0bc83e08d7%2FScreen+Shot+2018-03-14+at+10.02.53+AM.png)

Also, while you're in there, please make the member numbers linkable to (i.e. https://shop.complinks.co/dashboard/users/view?id=100086#tab-purchases)

**Comment by cgladue** [comment]
All Set
