### ISSUE TITLE
Implement Auditing for Balance, User tables

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#54]
To be able to notate and/or track who made any change to any user's account information the same way you do now in the comments section. Meaning, if a CSR comes in and adds points to someone's account, or makes any other change to the data, we can see who did it.

**Comment by cgladue** [comment]
they would use the "Comments" tab and enter a new comment wouldnt they ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I meant it from the standpoint of someone changes someone's information on a user's account like the email address or something like that we would want to make a notation internally to see who made the Trent who made the change to the account

**Comment by cgladue** [comment]
so something automatic, not a comment that someone manually enters, right ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Yes that is correct. We want to be able to notate internally who made a change to a user's account data so we can track that sort of stuff including the date and the data that was changed

**Comment by cgladue** [comment]
ok, i will refer to this as auditing going forward.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Ok makes sense.

**Comment by cgladue** [comment]
Would it be too much of a pain if i made the system just automatically add a comment when someone adds a transaction, or do you want to see it seperate ?

**Comment by robgpeak** [comment]
Yeah that should work.  The objective is just to see who made the lat edit/change to a record...  And after the fact, would we be able to see the revision history?

**Comment by robgpeak** [comment]
@cgladue I know we closed this last week, but based on what we just did with implementing the ability to make a change to some piece of the data in the back end manually, I would like to see an audit trail of it.  Which back end user made the change and date and time.
