### ISSUE TITLE
Tidy up the promotions page layout on mobile

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#56]
@ChrisASearles   If you have a look at the layout of the items on the promotions page on your phone, you'll see what I mean. From the top to the bottom it should be title, image, description and then more details button.  And everything should be centered.  Looking at it now, the image is a little off kilter.

![screenshot_2018-03-16-09-24-15](https://user-images.githubusercontent.com/28393235/37526286-ef2696a8-28fc-11e8-9627-dddc6ea90000.png)

**Comment by ChrisASearles** [comment]
Committed

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
awesome
