### ISSUE TITLE
New log in error

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#57]
Hey @cgladue I just realised that I messed up by telling you to delete all the other accounts...  I had set up test2@peakmarketing.com as a test account for cj and linkshare.  I just received an email from LS who said they tried to log in to check our links to make sure our links are in compliance, and they could not log in.  So I just tried to set up another account t with the same credentials, bit this was the message I got back when I tried...
![screenshot_2018-03-16-17-40-06](https://user-images.githubusercontent.com/28393235/37547861-1fcd40a0-2942-11e8-8af0-e0660ea87d17.png)

**Comment by robgpeak** [comment]
Although, I think k it is actually working now.  Meanibg, I was able to log in now using these credentials after reregistering.

**Comment by cgladue** [comment]
ahh, it seems this error is because i tried to add the email to the mailchimp list when it already existed on the list ... ill make sure it dosnt appear again, shouldnt ever be deleting users anyways so this shouldnt be an issue.
