### ISSUE TITLE
Broken links in Activity stream

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#59]
@cgladue seemingly all the links in the activity streams are still linking to ./admindashboard/.. instead of ./dashboard/.. but having said that, I know there is new functionality that has (at least the ones I know like advertiser/edit popping up in sort of a overlay screen, so that is something to consider when you fix the links.

![uploads/718be777-f058-4bd5-ba97-2b2c877406fc/Screen Shot 2018-03-21 at 3.38.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F718be777-f058-4bd5-ba97-2b2c877406fc%2FScreen+Shot+2018-03-21+at+3.38.20+PM.png)

It would really need to go here (below) in this particular instance, but then the New Links ones would need to go to their corresponding overlay:

![uploads/1c38da7e-3b26-42ab-9e50-9487c93f56fc/Screen Shot 2018-03-21 at 3.46.03 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1c38da7e-3b26-42ab-9e50-9487c93f56fc%2FScreen+Shot+2018-03-21+at+3.46.03+PM.png)

If you can't get it to pop open that overlay automatically, which would of course be the best UI/UX, the alternative would be to ../dashboard/advertisers page with the search field pre-populated with the advertiser's name...

While you're under the hood in the back end, I suppose you should look for anything else that might be referencing ./admindashboard/. and fix it.

**Comment by cgladue** [comment]
Yea automatically piping the overlay isn’t really going to be an option so it would be to automatically search or take the overlay and make a standard non modal overlay out of it.

**Comment by robgpeak** [comment]
I figured that would be a problem.  Do the best you can in cleaning it up.
