### ISSUE TITLE
Impact Radius

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#6]
@cgladue I wanted to put Impact Radius on your radar for integration into our back end.  We are up to 25 merchants that have accepted us into their affiliate program, and once we are live and have some traffic, we can apply to Target, which according to Ebates, is a very good producing advertisers.

**Comment by cgladue** [comment]
Again, im closing this in the assumption that we will be using retail benefits.  if that dosnt pan out we can always re-open

**Comment by robgpeak** [comment]
@cgladue Strange that I just looked in the reports on IR and do not see the trip I jut took to Target  https://member.impactradius.com/secure/mediapartner/report/viewReport.report?handle=mp_action_listing_sku_fast
