### ISSUE TITLE
shop redemption taking a long time

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#60]

**Comment by cgladue** [comment]
All Set

**Comment by robgpeak** [comment]
BaBam.  Nice.  Let me know if you need me to push Marc to have him push their tech guys to get their shit together for testing, because the xclub one is still taking a long time.

**Comment by cgladue** [comment]
yea we def need it by go live because it will stop people from linking
accounts also



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
that we requested a new ip to be whitelisted and havent heard back for a
week or two now.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I'm on it.
