### ISSUE TITLE
Adding "Feeling Lucky" screen to interstitial screen

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#63]
Can we add a functionality to the campaigns where buy we have a specific link guid that if someone clicks and makes a shopping trip that ends in a sale we could add a percentage to the points that they would earn. so for example if we had a campaign that said shop at Best Buy today by clicking on this link you learn an additional 10% in points on anything you buy.

In practical terms I think the best thing to do would be to add another column in the campaign section that says "Percent Increase" and if the number was .1 it would be 10% if it was .15 it would be 15% if it was .3 it would be 30% and so on.  so if a campaign was made and the percentage increase was set to .2 and someone clicked on that link which included that GUID, it would add 20% in points to their very next shopping trip at THAT store which results in points being earned.    

In that case we would have to make that particular campaign (in the example above), "store specific", but I am also thinking it would be nice to have the functionality to make it, site wide, meaning any store, but have it be on the very next shopping trip that results in the earning of points.  At first I thought of limiting it to their very next shopping trip started after clicking on the link, but I know a lot of people are going to comparison shop, and that will be a CS nightmare.

I know we talked about something similar in the past with the interstitial between our site and the advertiser's site that would have a slot machine or roulette wheel looking thing, but it would be predetermined what the percentage increase was before they even spun the wheel, so it's along those lines that it would be a campaign behind it...

Then we would have to keep track of the account of it all.  Meaning in the Commissions Earned sections and all the other sections that it effects would need to be clearly mapped out before we could implement something like this...

That's a lot of moving parts, but it will be worth it.  Before you do anything on this, we would have to have a call dedicated to this topic and flesh it out and then actually build a design document for it.  Let's put it on the back burner for now, but we can revisit it...  I just wanted to get the idea out there.

**Comment by cgladue** [comment]
@robgpeak right now this works as you described i believe for all stores, not a single store.

**Comment by robgpeak** [comment]
@cgladue I renamed and reopened this issue because it is related and you might want to reference the initial post to this issue.  

I wanted to see if  we could mock something up that really works by adding the contents and functionality of this page http://www.357am.com/CL/games/slot2.html to the interstitial page https://shop.complinks.co/trip/start?aid=6789&lid=0&url=http%3a%2f%2fclick.linksynergy.com%2ffs-bin%2fclick%3fid%3djLQ8qrFPMSA%26offerid%3d486109.100221719%26type%3d3

First a couple of questions and comments.

1. This is just going to be on "shop" not xclub, so it won't be live in a real world environment, but it is mainly for me to show off at G2E.

2. Would we need Chris for this? I spoke with Shane who created the slot page and he is willing to help with tweaking and polishing the look and feel of it, as well as any functionality needs, but I was not sure if you would be able to do it without Chris.

3. Even if in a test environment we did it specifically from just one specific "Shop Now" button (say the Macy's Shop Now button on the home page, that would be fine.  Meaning there would not have to be extensive programming of all the different percentages, that would be fine.  We can just lock it in at 20% for that trip. 

Please let me know what you think?
