### ISSUE TITLE
need to be able to sideways scroll tables in the back end

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#64]
@cgladue in trying to navigate in the back end, particularly on the /dashboard/advertisers page.  I know I can remove the visibility of some columns and then get to the Actions column, but please see if you can figure out a way to have a sideways scroll so if all of the columns are visible, I can still scroll to the right in order to get to the edit button.

**Comment by cgladue** [comment]
The site dosnt use sideways scrolling, it uses column priority .. basically it removes columns in order of priority untill the data fits on the screen, so i will look again at it and make sure the edit button stays at a high priority

**Comment by cgladue** [comment]
ok i removed the logo fromt he mobile view and substituted the name instead leaves more room for the settings button to appear.

**Comment by robgpeak** [comment]
Awesome fix.  Now that's good UI/UX.
