### ISSUE TITLE
Verbiage for a delayed points transfer confirmation from casino's API

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#65]
If a customer attempts to make a transfer of points to a casino partner whose API is offline, timing out, or not responding... Let's go with something like this below.  Is it possible to put a working link in one of this confirmation messages?  I did NOT put the FAQ in there yet, but I will.  I am assuming you cannot link to a specific FAQ because they are not bookmarks, plus their order can change???

Also, I am a little hesitant to use the word Pending, as we already use it for pending points... The sample FAQ copy I would write is below this image...

![uploads/2981d34e-cd8a-456b-9b04-623dc30c1c4e/Screen Shot 2018-03-22 at 9.05.49 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2981d34e-cd8a-456b-9b04-623dc30c1c4e%2FScreen+Shot+2018-03-22+at+9.05.49+PM.png)

Why is my Transfer Pending?
A. Sometimes computer systems go offline for a minute and lose their connection.  Don't worry, your points are safe, and as soon as our system is able to communicate with the computer set up to receive your points, it will happen automatically.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/37806982-5a704640-2e19-11e8-8506-9cc565ade520.png)

**Comment by cgladue** [comment]
set

**Comment by robgpeak** [comment]
coolio
