### ISSUE TITLE
Password Reset never sends email

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#66]
This is because we stopped sending the email confirmation emails to users and instead mailchimp handles email confirmation, so when it tried to reset the password it said of they didnt confirm email better not send there.

you can test now and it works.

**Comment by robgpeak** [comment]
Can we have the email that sends the new pass link come from the {subdomain}@complinks.co?

If not, at least can it be sent from support@complinks.co instead of info@complinks.co (that email address is more for advertisers and cj, ls, etc.

**Comment by cgladue** [comment]
Hey rob,

Yes its possible but amazon SES requires that any address i add as a sender be able to "Confirm" so it will need to have a mailbox that you can get an email on to confirm the address... is that possible ?

**Comment by cgladue** [comment]
i just added these two, can you confirm them when possible ?
![image](https://user-images.githubusercontent.com/7914133/37864588-87410662-2f47-11e8-9eee-8040b26953d2.png)

**Comment by robgpeak** [comment]
I'm confused.  I thought the email addresses we were going to use were xclub@comlinks.co / foxwoods@complinks.co / etc.  I don't mind the @{sub_domain}.complinks.co, but if we do that it would be support@{sub_domain}.complinks.co but in those instances, is that something you have to change at cloudflare...?

**Comment by robgpeak** [comment]
OK I verified the xclub@complinks.co for Amazon SES.  Please send the verification email again for shop@complinks.co

**Comment by cgladue** [comment]
Done

**Comment by robgpeak** [comment]
Just thinking out loud here, with the reset password sort of open to the public, does that mean someone could put a b******* password in there 1000 times in a row. Meaning we don't seem to validate the password against our database before sending an email, is that correct? Does that leave us open for someone to have bot to continue to put in bogus email addresses and bog down the server or get us classified as spam?

**Comment by robgpeak** [comment]
As a follow up, I just tested it and I guess it does NOT just send a message to any email address that someone outs in there.  That's good.  But the message that some sees in the forgot password confirmation page should read a little differently.

If we do know the email exists in our system and did send the email, they would see the existing message, but add a sentence at the end that reads, "If you do not receive the email within about a minute, please request it again by clicking here."

Please make the link color a different color from the regular black text.  

Doing it the way I described above does not indicate to a potential spammer/bot that we validate the email address being in our database before we send an email to that address.

 The other way is if they put in an email address that is not in our system, the system would reply with a message saying "The email address you entered is not in our system, please double check the email address you entered and try it again by clicking here. If you are still having trouble, please send a message to our support team using the "?" at the bottom right of the screen."

I leave it up to your discretion to determine whether or not we want to tell the customer that they are email address entered does not exist in our database.  I'm not sure what the best practice is to protect ourselves from spammers or Bots
