### ISSUE TITLE
Beautify the reset password page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#67]
@cgladue @ChrisASearles Not sure who would do this, but I just saw this below, and it was pretty ugly.

At the very least, can we get in a page more like the second image at the bottom of this post?

![uploads/fd083abb-4823-4a7d-b1d6-8148d6d8effa/Screen Shot 2018-03-22 at 10.26.36 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffd083abb-4823-4a7d-b1d6-8148d6d8effa%2FScreen+Shot+2018-03-22+at+10.26.36+PM.png)

--

![uploads/e6178870-8729-4f9f-81b9-c957dca60f3c/Screen Shot 2018-03-22 at 10.34.25 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe6178870-8729-4f9f-81b9-c957dca60f3c%2FScreen+Shot+2018-03-22+at+10.34.25+PM.png)

**Comment by ChrisASearles** [comment]
Updated this and both confirmation pages; code has been committed.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Speed is also a very beautiful thing, and for some reason when I click on the reset password button, I waited two minutes... and then I saw these two images.

<img width="1056" alt="screen shot 2018-03-30 at 12 48 13 pm" src="https://user-images.githubusercontent.com/28393235/38145737-d996456e-3418-11e8-92d0-c58f9e0410c8.png">


-- Then this one.

<img width="1131" alt="screen shot 2018-03-30 at 12 48 51 pm" src="https://user-images.githubusercontent.com/28393235/38145742-e06bbf04-3418-11e8-890a-696437709db4.png">

**Comment by robgpeak** [comment]
@cgladue I am assuming you are/were working on something which made this happen?  It also seems to have affected or might be related to #69 in that I was able to change my preference and opt out of the email in the manage my account section for x66@peakmarketing.com (which I waited about 30 seconds, checked mailchimp and saw I was in fact unsubscribed, so that was good), but then when I went back into manage account and tried to opt back in, it timed out...

**Comment by cgladue** [comment]
can you show me a screencast by any chance? i am not doing anything that
should cause anything to "Time Out"



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
https://screencast.com/t/tJfIvEDe
