### ISSUE TITLE
Staying logged in

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#7]
@cgladue it used to work where I would never have to relog in, but that seems to have stopped.  Can you please change it back so an authenticated user remains logged in all the time.

**Comment by robgpeak** [comment]
Oh I did not realize that.  How often do you push out new revisions?  Honestly it seems like in the last month or so it has happened 10+ times at least.  Seems like maybe after 24 hours in most cases...

**Comment by cgladue** [comment]
i wont upload any changes for a couple days ... login now and try back
again tomorrow and see, i cant think of any reason it would logout



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Will do

**Comment by cgladue** [comment]
i just went to shop.complinks.co and i am still logged in from days ago

remember if you login to shop.complinks.co it wont carry over to
xclub.complinks.co or any other partner domain.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Yeah I know.  I will leave it logged in on my phone as I am in now, and see
what happens tomorrow night.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
OK, here is the first instance where it logged me out on my phone.  (not sure if there is a difference on the phone and regular desktop version).  But again, it is definitely asking me to log back in... https://screencast.com/t/aGUN20aw

**Comment by robgpeak** [comment]
The same thing just happened on my Xlcub account. I was logged in over the weekend, and when I went to Xlcub.complinks.co on my phone, I needed to log in again.  Please try it from your phone.  Log in, leave it for at least 24 hours, and then come back to it and see what happens.

**Comment by cgladue** [comment]
it it only something you notice on your phone or the same from your PC too ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I just started another test from my desktop, and I will check it again tomorrow morning and let you know

**Comment by robgpeak** [comment]
Now I'm not sure if this is related, but when I was just in my phone trying to log into my Xlcub account in complinks, I got this message...
![screenshot_2018-02-12-13-49-43](https://user-images.githubusercontent.com/28393235/36113792-048d3926-0ffc-11e8-975d-32ab43b4523c.png)

**Comment by cgladue** [comment]
hmmm, i didnt touch anything .. ok that is strange




Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
That particular message (screen) happens a lot...

**Comment by robgpeak** [comment]
And so you k ow, this is the URL that is returning that message.  https://xclub.complinks.co/Account/Login?ReturnUrl=%2F

**Comment by cgladue** [comment]
i just logged in fine using that URL, when did the error appear, when you
tried logging in or after you entered user info ?  and was it only from
your phone vs desktop or happens to you on both ?  every time or
intermittent ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
And, it happened from the home page, but I just used the hamburger menu and went to and internal page (promotions), and then when I hit the head and shoulders silhouette and saw the log in screen, I click sign in and it logged me in fine.

Then I logged out and logged back in from the home screen and I did NOT have the system error screen, it logged me in just fine.

**Comment by robgpeak** [comment]
It seems to keep me logged in on my desktop, but the same thing happened on my phone this morning I had to relog in

**Comment by cgladue** [comment]
It might have something to do with the fact that your phone moves across several network throughout the day so the IP address that you logged in at the same IP address that your life that you’re trying again later am I don’t know why the work on the phone I can take a look and see I don’t know if it’s a high priority issue that moment

**Comment by robgpeak** [comment]
It could be because I am changing networks, but just as an example, I am logged into Facebook on my mobile browser, and in fact this same session of github from the browser on my phone, and I travel across multiple networks, yet I still remained logged into those sessions without a problem...

Then just now I went to the xclub.complinks.co page which was already opened from the session I had yesterday, and the same thing happened.  It logged me out, and more disturbingly, when I attempted to log back in I was met by this message below...

Additionally, in an attempt to troubleshoot the multiple networks theory, I was just logged into shop.complinks.co while connected to my home network, then I switched to cellular, and I did not have to re log in...  I think it has something to do with time and/or the mobile version of the site.

![screenshot_2018-02-14-10-09-52](https://user-images.githubusercontent.com/28393235/36211959-b5e54e3c-1170-11e8-8121-42a6e48d30d9.png)

**Comment by robgpeak** [comment]
@cgladue just for shits and giggles, I wanted to see if it was isolated to the chrome mobile browser, but it is not.  I logged into Xlcub.complinks.co from my standard Samsung browser last night at 6:31 pm navigated around a bit, went back to the home page, and then just left it site all night.  Got up this morning, and at 9:30am and when I clicked in the silhouette, I told me I had to log back in.  Which I did with no problems.  Meanibg, I did NOT receive the error message that I had shown earlier in this thread.  Are you not able to replicate this behavior?  Please try it on your end.  Maybe it's just my phone.  I highly doubt it, as I have no problems on any other sites.

**Comment by robgpeak** [comment]
@cgladue while it may not be a high priority, it is still happening on my mobile device where it logs me out, and then I get the error message screen when I try to log back in, and it is ugly and annoying.  You did not find anything on a google search about it?  It seems strange that it primarily happens on mobile.  Having said that, I am going to submit a separate issue right now which again is only related to mobile with regard to the rewards page and display of points...

**Comment by cgladue** [comment]
i changed a setting im not too hopeful, but can you give it another try and let me know ?

**Comment by robgpeak** [comment]
Ok I will let you know...

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
So far so good.  Thanks a bunch!
