### ISSUE TITLE
We need one set of T&C and Privacy Policy pages per site

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#72]
Not sure who this would be for, but Chad just created the ability for me to edit the T&C and Privacy policy pages from the back end for each individual sub domain, which is awesome.  But the links in the sign up screen (overlay) are linking to a modal (I just learned what that word meant today from some tiny mice:), that presumable has a static version of both the T&C and privacy pages.

Meaning, I updated the content for both the pages in the back end, and when I click on them from the links in the footer of the site, they show up fine, but the ones from the signup overlay still have the old content.  Can you please change that so it calls to and displays the most recent content.

**Comment by cgladue** [comment]
Not sure how to do this so i think chris will have to

**Comment by ChrisASearles** [comment]
Done, will commit when I have access to the repo again.

**Comment by cgladue** [comment]
You should be able to commit now.

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
cool
