### ISSUE TITLE
The support Link in the head and shoulders menu

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#73]
@cgladue when I clicked on the support auction in the head and shoulders menu when I was logged in I tried to send a message and this is the response that I got. It should have the same functionality as the widget whereby it should go to xclub@complinks.co
![screenshot_2018-03-25-11-29-48](https://user-images.githubusercontent.com/28393235/37876842-97ca4abe-3020-11e8-89b4-5f882c34c1f7.png)

**Comment by cgladue** [comment]
Chris did this, but i have updated it to use the subdomain like the widget is ...

**Comment by robgpeak** [comment]
I just tested it by trying to send a message from the Support link in the menu at 5:35pm, and I saw this message which tells me that it created a ticket and that we will respond shortly, but nothing showed up to xclub@complinks.co in groove.  I sent one from the bottom right question mark widget at 5:41pm, and it came through to xclub@complinks.co in groove immediately.

<img width="1078" alt="screen shot 2018-03-25 at 5 40 15 pm" src="https://user-images.githubusercontent.com/28393235/37880326-669312b2-3054-11e8-8ce1-7f05ce1bf433.png">

**Comment by cgladue** [comment]
can you search for Ticket #4916 and see where it was created at ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
i just searched and found them both ... right where they should be

![image](https://user-images.githubusercontent.com/7914133/37880384-94751fc6-3055-11e8-8a3a-0949356b908b.png)

**Comment by robgpeak** [comment]
I was in the beta version and it was not there, yet when I did a search for 4916 I saw the body of the message, but it was still not visible on the left side menu.  It must have been a groove thing...  Although, actually it's not because it is not even showing up in the regular xclub@complinks.co gmail account that I have set up...

<img width="1158" alt="screen shot 2018-03-25 at 5 55 53 pm" src="https://user-images.githubusercontent.com/28393235/37880439-57bff136-3056-11e8-9f58-b3043886816f.png">

---

Now I see it when I go to the old version of groove like you showed above...  But like I said, still not actually being sent to xclub@complinks.co in the first place (then in the gmail settings I have it forwarding to the appropriate mailbox in groove.)  That is the idea situation if we can do it.  Can we do that with the widget?

**Comment by cgladue** [comment]
the widget is working exactly like you want right ?

the support option should be doing what you are asking, chris created it but from what i can see the email is going to the right address: 
![image](https://user-images.githubusercontent.com/7914133/37880510-94f03862-3057-11e8-93b5-fa81b0783edd.png)

**Comment by robgpeak** [comment]
For some reason it is going directly to groove and not going to the xclub@complinks.co inbox in gmail first, but if I send something via direct email to xclub@comlinks.co it shows up and then forwards to groove as expected.

The tests that you and I both sent today are in Groove, but not in the gmail inbox (which is really the way I want it, as it is our fail safe if groove shits the bed.)
<img width="1241" alt="screen shot 2018-03-25 at 7 11 40 pm" src="https://user-images.githubusercontent.com/28393235/37881119-ed397ba6-3060-11e8-9481-c95ae9c91a9a.png">

**Comment by cgladue** [comment]
im thinking the groove widget is supposed to go directly to groove...  its their product i doubt they would send an email outside of them just for it to come back to them again...

does the head and shoulders options work as expected now or are they both not working as you expected ?

**Comment by cgladue** [comment]
uhhhh...   @ChrisASearles  any idea why its doing this other then if rob double clicked the button by some chance which i doubt, i looked at your code and it appears to only add the ticket once...
