### ISSUE TITLE
Let's not ask for email address from an authenticated user

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#74]
@cgladue is it possible to allow the widget little question mark in the bottom right-hand corner of the screen have the same functionality as the support Link in the head and shoulders menu where buy it does not ask the user for their email address because they are already logged in. Is that possible with a widget?

**Comment by cgladue** [comment]
Not sure since its a groove widget may not be able to change how it functions .. let me see...

**Comment by robgpeak** [comment]
@ChrisASearles How did you set up the support form in the support Link in the head and shoulders menu where by it does not ask the user for their email address because they are already logged in?  Is that possible to do with the question mark widget for Groove?  Meaning, if they are already an authenticated user, instead of asking them for their email address, it would just ask for the subject and message like the other form does.

**Comment by cgladue** [comment]
He used their api instead of the widget so two different things.   I wonder if it’s possible to have angular populate that field for logged in users.  I don’t think it’s possible totally remove it tho.

**Comment by ChrisASearles** [comment]
@robgpeak I can't update the field in their widget. We could build out something that integrates with the API the same way the other form does if you'd prefer. We had just done it that way originally b/c it took about 10 seconds to embed their widget on the page vs building our own.

**Comment by robgpeak** [comment]
How long do you think it would take to build our own?  Would it be the same "?" at the bottom of every page and have the same functionality?

**Comment by ChrisASearles** [comment]
Safe to assume we're closing this in lieu of #114 ?

**Comment by robgpeak** [comment]
Safe assumption
