### ISSUE TITLE
image for target missing, but only on some pages

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#75]
@cgladue Please have a look https://screencast.com/t/a5JVLvpy  Also, it might affect all the IR sites, I have not looked, but please check it out while you are under the hood.

**Comment by cgladue** [comment]
yea this was because IR is the only network who actually gives us the logo for the advertisers so we dont need to store them ourselves, it should be corrected now.

**Comment by robgpeak** [comment]
OK.  Two new issues.

1. The target logo in the store page looks like it is is being constrained in some way, and does not look good.

2. When it shows up in the search, it does not look centered like the other ones do.

<img width="375" alt="screen shot 2018-03-27 at 11 57 37 am" src="https://user-images.githubusercontent.com/28393235/37979423-91a4d3ec-31b6-11e8-8a73-58eee9ff1352.png">

--

<img width="594" alt="screen shot 2018-03-27 at 11 59 29 am" src="https://user-images.githubusercontent.com/28393235/37979437-98536fb4-31b6-11e8-8103-ba794aaf27b8.png">

**Comment by cgladue** [comment]
i think this is a job for a bigger mouse @ChrisASearles

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
Nice
