### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#76]
@ChrisASearles Are/should we be tracking the traffic on xclub differently from shop.complinks.co in google analytics?

**Comment by ChrisASearles** [comment]
Entirely your call. Either way, we don't have to do anything on our end, you can track all data in the same profile and configure it with a filter in GA if you really feel the need to view reports on an individual subdomain basis. I wouldn't bother until you have at least 2 before you see if you have a need for it but here's a quick tutorial on how to set up that filter if you're interested in a read! https://www.verticalrail.com/kb/filter-in-google-analytics-to-track-subdomains/
