### ISSUE TITLE
Date format changed on dashboard/partner/purchases

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#77]
@cgladue It looks like the format that you report the date changed between 2017 and 2018, particularly on the https://shop.complinks.co/dashboard/partner/purchases page. (that's the only place I noticed it, but tbh the only placed I looked at the moment).

If you are on the page and click the date column to sort it, you'll see what I mean.  There are only 41 records, and you can see that they are different and not sorting correctly.

**Comment by cgladue** [comment]
Yea, this is because the two networks report the date completely different, i wasn't able to standardize the dates in any way yet ...

**Comment by cgladue** [comment]
i believe this was fixed a while ago...
