### ISSUE TITLE
Points not showing up in history

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#78]
@cgladue Morgan just signed up for a new account in xclub (account # 100107) so when she clicks on a link of an xclub account number from within groove she can automatically be logged in and see the customer's data.

Having said that, when she signed up, she received 100 points for opting in to the email, and then I showed her about the special campaigns, and she click on the bestbuy one and got 20 points, so when you look at the top right of her screen you can see she has 120 points, but when you look in her points history on both the front end (in her dashboard), AND looking at the points history tab of the user in the admin dashboard, no points or transactions are showing up.

You CAN see them in the 'Available Points' balance in the profile, but like I said, not in the points history...

![uploads/f7b306cc-b0c4-4228-b9f0-8d98b6b7c4c5/Screen Shot 2018-03-29 at 6.38.49 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff7b306cc-b0c4-4228-b9f0-8d98b6b7c4c5%2FScreen+Shot+2018-03-29+at+6.38.49+PM.png)

**Comment by cgladue** [comment]
all set, i added a column for "Modified by" to show who added the points, and it was supposed to default to the system user, but it defaulted to null instead.  i believe its correct now if you can test it again ?
![image](https://user-images.githubusercontent.com/7914133/38118517-29a06f66-3389-11e8-8aef-9eb4d75dc2c4.png)

**Comment by robgpeak** [comment]
Just tried to test but it brought up another issue...

**Comment by cgladue** [comment]
i saw an error occur, i thought i wouldnt have to republish but perhaps i do



Chad Gladue
*DevNull Technology, LLC*
