### ISSUE TITLE
Not able to register a brand new account, but I am...?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#79]
Ok, so I just tried to register a new account on X club and I did and I used an email address X6 at Pete marketing.com which I've never used before but it told me that the address was already registered. So then I tried another one x-44 at Peak marketing.com which also I've never used and it told me I was already registered using that email...

Sign Up
This email address is already registered, please use the 'Sign In' page to access your account, or reset your password if you forgot it.

I couldn't take a screenshot cuz I was on an incognito window anyway they both show up in the database so I was actually able to register with them but when I clicked on the email to subscribe and earn the hundred points it wouldn't work. Meaning the link worked but I didn't earn the hundred points

**Comment by cgladue** [comment]
can you try it one more time rob ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
working now
