### ISSUE TITLE
Impact Radius Advertiser Name changes

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#80]
@cgladue Morgan is saying that she has gone in and changed the names of the IR advertiser names in the past so they match the brand and not the possible parent company or something like that, and some of them have reverted back to the "corporate" name.  Can you please check the API to make sure it does not do that.

**Comment by cgladue** [comment]
Sure, its probbally always updating the name from the api like you said let me remove that field from being overwritten...

**Comment by cgladue** [comment]
@robgpeak this should be done
