### ISSUE TITLE
Change to the footer

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#81]
@cgladue @ChrisASearles Not sure who would do this, but for now, could you please stop the "Stay Connected" section out of the footer.  It always looks bad when they don't link anywhere, and until we have a good enough place for them to link, let's just remove them.

Having said that, I would like to see if we can keep the remaining items in the same spots.  Meaning, I don't want the three remaining sections to be evenly distributed, I would like them to still be where they are if that is possible.  Lastly, please make sure the results look good on mobile as well.  Thanks.

![uploads/b7b87a70-d22e-476f-9fb0-384aefc63d4e/Screen Shot 2018-03-30 at 5.06.06 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb7b87a70-d22e-476f-9fb0-384aefc63d4e%2FScreen+Shot+2018-03-30+at+5.06.06+PM.png)

**Comment by ChrisASearles** [comment]
Committed

**Comment by cgladue** [comment]
@robgpeak published
