### ISSUE TITLE
adding Active dropdown to promo edit page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#82]
@cgladue can you shorten the "Display Order" field, and add an "Active" field to the promo edit page with the dropdown choices of Active and Inactive, with Active being the default setting.  This way I can choose to have them created in the back end, but not have them display on the site until I am ready to have them visible.  Thanks

![uploads/1c1c127f-bf42-4362-a39c-46770e16356c/Screen Shot 2018-04-02 at 8.37.13 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1c1c127f-bf42-4362-a39c-46770e16356c%2FScreen+Shot+2018-04-02+at+8.37.13+AM.png)

**Comment by cgladue** [comment]
@robgpeak all set

**Comment by robgpeak** [comment]
Great. Thanks.
