### ISSUE TITLE
adding more information to Promo Descriptions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#83]
@cgladue @ChrisASearles not sure who would be able to do this but I was looking to be able to add more information to the Promotions Descriptions through either a link or modal button, but I am not sure how to do it.  It is pretty hard to explain exactly, but I can show you what I am looking to accomplish here... https://screencast.com/t/JlpGC5ijYOML

**Comment by cgladue** [comment]
i just changed the max length of the description field to effectivly
unlimited.  thats why you were getting the error, origionally it was
intended to be a short description, but if you start using HTML the length
gets long quick... take a look again



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
that'll work.  Thanks Chad

**Comment by cgladue** [comment]
i do appreciate the use of the word 

> modal

 about 345 times in that screencast, i feel vindicated ;)

**Comment by robgpeak** [comment]
Just want to get maximum use out of the new words I learn.
