### ISSUE TITLE
constraining the size of the logos for the featured deals

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#85]
@ChrisASearles I just noticed this and it looks a little squirly. They are getting stretched. Can you fix it to the way it was where the size of the logo was the max that it could be in a store box.

![uploads/aac42a31-27eb-4235-9fc8-beb5b499ae89/Screen Shot 2018-04-02 at 5.32.55 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faac42a31-27eb-4235-9fc8-beb5b499ae89%2FScreen+Shot+2018-04-02+at+5.32.55+PM.png)

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
@ChrisASearles Any update on this?

**Comment by robgpeak** [comment]
@ChrisASearles I am not sure what this was still happening, but I remedied the situation by resizing the actual Macy's logo...
