### ISSUE TITLE
limiting the size of Impact Radius Advertiser Ads that appear to 250x250

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#88]
@cgladue I am pretty sure this is still in place with the cj and ls ads, but we need to to the same with IR.  Right now it seems to be pulling ALL the ads.  https://shop.complinks.co/stores/index/7213 has 300+ different ads showing.

**Comment by cgladue** [comment]
yea thats why you go to the ads section in the backend and only enable the
ads you want to show...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I know that, but I know you built the system that retrieves the ads from cj and ls to only pull in those ads that are 250x250, and I wanted to see if you could do the same for IR just for consistency and continuity sake.  Then from there we can still go in and enable only the ones we want to show.

**Comment by cgladue** [comment]
i can, but what if down the road you want to show ads on the mobile device?
or someone has an ad you would of liked and its dimensions are 270 x 250
and you wont see that... either way yea i can only show 250x250 (if thats
even a size that they include standard on IR)  just afraid of throwing out
too many potential good ads... up to you tho



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I am 99% sure we are already limiting the sizes of the ads on the other networks, and honestly I am not worried about missing out on good ads.  Let's just do the same for IR.  250x250 is a pretty standard ad image size.  They are really just for visual effect.  And actually the 250x250's show up fine on mobile now.  It's actually the other one like 468x60 and the 88x30's that show up like shit.

**Comment by cgladue** [comment]
@robgpeak all ads have been removed and will be skipped going forward except ads that are exactly 250x250 for all the networks.

**Comment by robgpeak** [comment]
@morganpeak Just an FYI Morg.
