### ISSUE TITLE
limiting visibility of certain advertiser from appearing on certain subdomains

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#89]
@cgladue we need to think about how we could easily eliminate certain advertisers from showing up in certain sub domains. So for example Caesars Entertainment is an Advertiser through impact radius and they are currently showing up on our site. In the agreement we have with Parx day do not want any competitors that offer gambling services to be listed as advertisers in their version of rewards everywhere. so we would need to think about how we could easily manage this.

by the way, i used https://www.google.com/intl/en/chrome/demos/speech.html to dictate this into my computer, then copy and pasted it in this window.

**Comment by robgpeak** [comment]
Any ideas on this one Chad?  I can't see it being that often, but then again, you never know.  It could also come into play when a specific brand is not popular with a particular casino's demographic.  Meaning, for example Macy's is not a popular brand in southern California, and maybe it would make sense in pechanga.complinks.co to NOT show Macy's.

Maybe there could be a "View Exclusions" link in the "Edit" menu of the Property List...

![uploads/20955306-322a-4fcd-90fa-2166ef98c554/Screen Shot 2018-04-05 at 1.15.42 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F20955306-322a-4fcd-90fa-2166ef98c554%2FScreen+Shot+2018-04-05+at+1.15.42+PM.png)

...which would like to a page like ../dashboard/property/promos/12 in the sense that it would have the dropdown menu of the subdomain at the top of the page, but it might be a page called, /dashboard/property/exclusions/12

The name title of the page would be "Excluded Advertiser List".  Then you could have a "Add Exclusion" button that would all us to add an advertiser that would then be excluded from appearing on that subdomain.  We also need to be sure it then would not show up in a search made by an end user on the front end of the site.

Actually, the other way to do it, and it might be easier is to just put the dropdown menu at the top of the Advertiser List page so the advertisers list is editable by each subdomain.  Either way, we just need to make sure the advertisers that are marked as "Inactive" on one subdomain don't show up in a search from the front end.

In either of these two solution ideas, we need to think about what happens if a store that is excluded from a subdomain is in the featured list.  I would assume all the stores in the list below that removed featured store would just move up one spot in the visible order list sort of automatically.

**Comment by robgpeak** [comment]
What do you think @cgladue ?

**Comment by cgladue** [comment]
Yea I think that’s doable.  I’ll get something together soon I am hoping for you.

**Comment by cgladue** [comment]
@robgpeak @morganpeak 

this should now be working and available here:
https://shop.complinks.co/dashboard/property/excludedAdvertisers

**Comment by robgpeak** [comment]
👍
