### ISSUE TITLE
Forgot password email

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#90]
@cgladue Since we are using AWS to send the forgot email, and the AWS mail system already checks to ensure the email is actually in our db before sending the forgot password email, please do two things:

1. Remove all the footer merge field tags and replace them with the actual copy here:

Copyright © 2018 CompLinks LLC, All rights reserved. 
You are receiving this email because you opted in at our Xclub Rewards Everywhere website powered by CompLinks. 

Our mailing address is: 
CompLinks LLC
11924 Forest Hill Blvd. 10A-145
Wellington, FL 33414

2. In addition the link in "Click Here", please show the full URL below that, with a blank line in between the two so it would look like:

Click Here

"Actual URL"

The reason is, when someone click the forgot password link on the site, it tells them to click the link or copy and paste the url...

**Comment by cgladue** [comment]
@robgpeak published
