### ISSUE TITLE
Desktop shortcut icon

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#94]
@ChrisASearles I know we all live in the mobile first world, but the demographic of the users will be older, and much less computer savvy in many cases.  Therefore, I think we should add the functionality to ask people to create a shortcut on their desktop of their computer.

I mean, in reality I watch my wife surf the Internet, and she still creates icons of webpages to her desktop.  I know you and I would never do such a thing, but trust me, a lot of the people who will be using out platform will do stuff like that.

**Comment by cgladue** [comment]
Is it even possible for a website to create a file on the desktop ?

Wouldn’t that need to be something the user does with the “favorites” function ?

**Comment by ChrisASearles** [comment]
There's kind of a hacky way I know of to do it, the results can't be guaranteed to be consistent across browser and OS but it can (kind of) be done. I tested it quickly on all of the browsers installed on my machine and currently it works everywhere but Chrome. A website can't create a shortcut on the device, so it's really a UI design technique. It would take a good amount of effort to do it in a classy way and, as I said, I can't guarantee where it will work, for how long, and what it looks like once it's been created (right now it's just an icon = your default browser with some text I can specify as the text for the link.

Let me know if you think it's worth building out and we can work on something.

**Comment by robgpeak** [comment]
Can you put it on a page that currently only I can see your hacky way? Meaning don't put it up at shop.complinks.co just put it somewhere where I can see how it responds in the different OS and then make a determination from there.

**Comment by robgpeak** [comment]
BTW, are these the "hacky" way's you're talking about?

http://cubiq.org/add-to-home-screen

and

https://youtu.be/XEeJNp-OHyw

**Comment by robgpeak** [comment]
At 5 minutes and 24 seconds of the video I quoted above it shows how to change the message on iOS and I would want it to read like this.  Tap the <strong>%icon</strong> icon to add Rewards Everywhere to the home screen of your <strong>%device</strong>.

**Comment by robgpeak** [comment]
I would set the lifespan to 15000 (15 seconds) and the expire to once a week.

**Comment by ChrisASearles** [comment]
@robgpeak that script is for mobile devices only to add to the home screen, they don't add anything to the desktop (they can't due to the restrictions originally presented).

**Comment by robgpeak** [comment]
OK.  So can we get it to work on mobile only then?
