### ISSUE TITLE
Error message on redirect

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#95]
@cgladue @ChrisASearles I am not sure if this is related to the other redirection issue #92, but I thought I would share it with you...  It happens on every store page on the site.

<img width="1257" alt="screen shot 2018-04-11 at 4 24 18 pm" src="https://user-images.githubusercontent.com/28393235/38641775-00d079b0-3da6-11e8-9904-90cc9c7afee5.png">

**Comment by cgladue** [comment]
Also I never heard back from Chris about the JavaScript Ajax not working.  This may be why ?

**Comment by ChrisASearles** [comment]
Hey @robgpeak the error's I'm seeing in your console there are related to #37 but shouldn't be causing any problems on the website. Are you seeing an issue somewhere or were just concerned about all the red text the tiny mice keep spitting out?

**Comment by ChrisASearles** [comment]
Pushed an update that should eliminate the error, let me know if there's another error I'm missing.

**Comment by robgpeak** [comment]
#37 What does this have to do with 37?  Looks more like something with #92, but what do I know.

Yeah, I was not see any problems on the website, but just concerned about the red text from those damn mice...
