### ISSUE TITLE
Clarification on the Activity Stream

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#96]
@cgladue @morganpeak Morgan and I were just talking about the "New Advertisers" functionality in the activity stream, and it seems like there is a bit of a disconnect.

It seems like it is pulling ALL the new advertisers that are listed on the networks (cj, ls, ir), but they are not really new to us in the sense that we have been joined to their affiliate program.  We see advertisers in there from all over the world that we would never put in our program...

With regard to the advertisers showing up in Relationship Changed, as it stand now, it seems like the only ones that are showing up in relationship changed are the advertiser who have been 'existing advertisers', and have deactivated or reactivated, but not new advertisers whom have just approved us now become "joined"  

So for example, Dicks sporting goods came in under the New Advertisers section, but NOT in the relationship changed from notjoined to joined (because they approved us), and it should have.

Them just showing up in New Advertisers alone is not enough for Morgan to see that we are now joined because as I mentioned, it is showing ALL the advertisers.

I hope this make sense and you don't need a screencast...:)  But please let me know if this makes sense.

**Comment by cgladue** [comment]
@robgpeak @morganpeak this is fixed now, it will be put in place once i push the changes next time.
