### ISSUE TITLE
Add one signal code to xclub.complinks.co

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#98]
@cgladue I set up One Signal for Xclub.  please got to onesignal.com and grab the code to add it to xclub.complinks.co for authenticated users.

**Comment by cgladue** [comment]
the one signal widget will be automatically added once you fill-in the OneSignal Widget ID in the backend ..

![image](https://user-images.githubusercontent.com/7914133/38843994-939c045e-41bf-11e8-8d05-0c2bc889926d.png)

insert it here:

![image](https://user-images.githubusercontent.com/7914133/38844044-c2d25d22-41bf-11e8-833a-fb54bb2277e1.png)

**Comment by cgladue** [comment]
@robgpeak Should be added now.
